### ISSUE TITLE
Transaction.Save throws NotSupportedException

### ISSUE THREAD

**Issue by preslyel** [dotnet/SqlClient#1003]
### Describe the bug

When I'm trying to save savepoint 

`transaction.Save(savePointName);`
I've got a System.NotSupportedException

```
Exception message: "Specified method is not supported."
Stack trace: no inner stack trace
```

### Further technical details
Microsoft.Data.SqlClient version: 4.8.2
.NET target: .NET Core 5.0
SQL Server version: SQL Server 2017
Operating system: Windows 8

**Comment by JRahnama** [comment]
@preslyel have you tried a lower version? 4.8.0 or 4.7.2 to see if the issue comes up?

**Comment by JRahnama** [comment]
Just to confirm you are using `System.Data.SqlClient` 4.8.2 and targeting .Net5.0. Right?
You can also try your code with the latest version of [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0-preview1.21075.2)
I will try a simple repro using the mentioned environment and will update here shortly.

**Comment by JRahnama** [comment]
@preslyel I tried different scenarios and did not have any issue with save command. Here is the list of things I tried:

1- netcore5.0 using System.Data.SqlClient 4.8.2 everything worked fine
2- net48 using System.Data.SqlClient 4.8.2 and everything worked fine.

Is it possible to provide a repro? Something we can start the investigation from that [point?

**Comment by preslyel** [comment]
I've tried to create a simple solution to reproduce it and found an interesting fact. 
I have class
```
 internal abstract class TransactionFactory<T> : IDisposable where T : DbConnection, new()
{
     protected DbTransaction transaction;
     protected T connection;
     // some code
     TransactionFactory(string connectionString)
     {
          connection = new T();
          connection.ConnectionString = connectionString;
          connection.Open();
          transaction = connection.BeginTransaction();
     }

     public void SaveCheckPoint(string savePointName)
     {
          transaction.Save(savePointName);
     }
}
```
When I've tried to write a solution for .Net5 from scratch I've got an error "DbTransaction does not contain a definition for method Save" in System.Data.Common 4.2.2.0. But in my basic solution System.Data.Common 5.0.0.0 and the method are present. P.S.: I've migrated my solution from core 2.1 to 5.0
So, when I change my code to (transaction as SqlTransaction).Save(savePointName); all become work fine...

**Comment by cheenamalhotra** [comment]
You could clarify that difference from System.Data.Common teams in [dotnet/runtime](https://github.com/dotnet/runtime) repository.
We'll close this issue as External.
