### ISSUE TITLE
SqlClient diagnostics Before event should record timestamp

### ISSUE THREAD

**Issue by trstringer** [dotnet/SqlClient#101]
The following [logging of the before event for SqlClient diagnostics](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlClientDiagnosticListenerExtensions.cs#L27-L32) should include a timestamp member.  This would be as simple as adding `Timestamp = Stopwatch.GetTimestamp()` to the anonymous type passed into `DiagnosticListener.Write()`.

Please assign this issue to me, as I will be making the code change and submitting the pull request (I am the author of the code in question).

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
@saurabh500 Need your input for triaging.

**Comment by divega** [comment]
FWIW, I think the conclusion on https://github.com/dotnet/SqlClient/issues/101#issuecomment-289138941 is that the right way to do this is to start using Activity APIs, but that would be better tracked in a new issue.

cc @vancem in case this guidance has changed.

**Comment by David-Engel** [comment]
This was a small change so we went ahead and made it. The change will be in the next preview release of Microsoft.Data.SqlClient. We have another backlog item (not on GitHub) for enhancing the Activity tracing that we will work on in the future.
