### ISSUE TITLE
PlatformNotSupportedException in Xamarin App

### ISSUE THREAD

**Issue by matti157** [dotnet/SqlClient#1030]
I am developing an Android / iOS cross-platform app with Xamarin

The app has a number of DLLs that contain functions, all the DLLs are in .Net Standard 2.1 (but I also tried with 2.0)

In some functions we access the DB and create a SqlCommand object.

On Android it gives me this exception where I instantiate the object:
![image](https://user-images.githubusercontent.com/76459129/114597523-2b904c00-9c91-11eb-83a2-7c4f07dfa95b.png)

How do I resolve?

Thank you

**Comment by JRahnama** [comment]
@matti157 I suggest starting from [FAQ](https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions#10-why-is-there-still-feature-disparity-between-net-framework-targets-and-net-corestandard-targets).

There might be also PCL related issues. If you are trying to have database directly on your device that will cause an issue as well. If the FAQ does not answer your question please consider providing more detail on your application:

1. What driver are you using? Syste.Data.SqlClient or Microsoft.Data.SqlClient and what versions
2. a sample repro would be appreciated as well.

**Comment by matti157** [comment]
Thanks for the quick answer.

The code you see in the image, where SqlCommand is instantiated, is shared with a website made in .Net and placed in a dll referenced both to the website and to the Xamarin app.

Actually on the tablet we connect to Sqlite but only for code uniformity there are the lines in which SqlCommand objects are created that ARE NOT USED BY XAMARIN.

**So in short we instantiate the SqlCommand objects but WE DON'T USE THEM.**

I have tried with both System.Data.SqlClient and Microsoft.Data.SqlClient but I always get the exact same error.

I have read the FAQ but I can't get anything useful out of it, it says I have to take care of the dependencies but I don't understand what it means.

For the example project the question is complicated because it is a big app, I try to make sure to get it.

**Comment by Raystorm7** [comment]
Any news on this? We have the sample problem.
Xamarin 4.8.0.1560 and Android platform. On iOS it works.

**Comment by JRahnama** [comment]
@Raystorm7 Can you provide a repro? a simple way to reproduce the issue?

**Comment by JRahnama** [comment]
@matti157 I was looking deeper into this issue:

Access to a local database, something that is installed on the mobile device, and only the app on the mobile device has access to it, as you have mentioned is possible through [SQLite](https://www.sqlite.org/index.html) , but accessing to a central database which other mobile devices have access is only possible through Webservices and you can access them via Http(s).

The issue that this is not detected on compile time is from  a [known issue with Netstandard at runtime with PlatformNotSupportedException](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-standard-problems). Apparently net5.0 has solved this issue from Netstandard.

There are some suggested workarounds to make calls to SQL Server from inside the application on your mobile device, **which are not recommended** and I did not test them, using dependency service.  For more detail  about this you can look [here](https://stackoverflow.com/questions/37873020/accessing-directly-a-sql-server-database-in-xamarin-forms).


If you still believe this is a `Microsoft.Data.SqlClient` driver issue, please provide us a repro and we will look deeper into the problem.

**Comment by matti157** [comment]
Fixed, we removed all lines of code where SqlCommand was unnecessarily instantiated
