### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by moxixuan** [dotnet/SqlClient#1044]
### Describe the bug
Hi, i hava a sql query the data.
I check my log and find some error in it，
it is not always happen, it happen something.
the data is about 3000 row, and 20 clomun return.

i add polly to retry.
and it may be success after retry

```
Exception message:
Stack trace:
```

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.    at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadByteArray(Span`1 buff, Int32 len, Int32& totalRead)    at Microsoft.Data.SqlClient.TdsParserStateObject.TryReadUInt16(UInt16& value)    at Microsoft.Data.SqlClient.TdsParser.TryGetTokenLength(Byte token, TdsParserStateObject stateObj, Int32& tokenLength)    at Microsoft.Data.SqlClient.TdsParser.TrySkipValue(SqlMetaDataPriv md, Int32 columnOrdinal, TdsParserStateObject stateObj)    at Microsoft.Data.SqlClient.TdsParser.TrySkipRow(_SqlMetaDataSet columns, Int32 startCol, TdsParserStateObject stateObj)    at Microsoft.Data.SqlClient.SqlDataReader.TryCleanPartialRead()    at Microsoft.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader)    at Microsoft.Data.SqlClient.SqlDataReader.Close()    at Microsoft.Data.SqlClient.SqlDataReader.Dispose(Boolean disposing)    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 456    at MeiYiJia.TakeOut.TaskProcessor.Repository.DapperExtensions.<>c__DisplayClass3_0`1.<<QueryAsyncWithRetry>b__0>d.MoveNext() in /src/src/MeiYiJia.TakeOut.TaskProcessor/Repository/DapperExtensions.cs:line 50 --- End of stack trace from previous location ---
--

```c#
var sql = $@"
               select  *
               from    tbGoods g
                       inner join tbPrice p (nolock)
                           on g.Gid = p.Gid
                       inner join tbGood sg (nolock)
                           on p.Gid = sg.Gid
                       inner join tbCategory cg (nolock)
                           on cg.GoodsCode = g.Code
                       inner join tbCategory c (nolock)
                           on c.CategoryId = cg.CategoryId
               where   p.SrcPlatform = 2;

using var db = new SqlConnection(await GetConnection(CompanyCode));
var eLMDtos = await db.QueryAsyncWithRetry<LocalGoodsELMDto>(sql, new
{
    StoreCode,
    CategoryGroupID
}, commandTimeout: 120);

```

### Further technical details

Nuget
Dapper 2.0.78
Microsoft.Data.SqlClient 2.1.2

SQL Server version: (e.g. SQL Server 2018)

.NET Core version is .NET SDK (5.0.102)
docker version
docker://19.3.5

Server=###;;Initial Catalog=###;;Persist Security Info=False;User ID=###;;Password=###;MultipleActiveResultSets=True;Encrypt=False;TrustServerCertificate=False;pooling=true;min pool size=5;max pool size=512;Connection Timeout=30;

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base

RUN ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so
RUN cat /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y libgdiplus
RUN ln -s /usr/lib/libgdiplus.so /lib/x86_64-linux-gnu/libgdiplus.so

WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["src/MeiYiJia.TakeOut.TaskProcessor/MeiYiJia.TakeOut.TaskProcessor.csproj", "src/MeiYiJia.TakeOut.TaskProcessor/"]
WORKDIR "/src/src/MeiYiJia.TakeOut.TaskProcessor"
RUN dotnet build "MeiYiJia.TakeOut.TaskProcessor.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MeiYiJia.TakeOut.TaskProcessor.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MeiYiJia.TakeOut.TaskProcessor.dll"]

**Comment by JRahnama** [comment]
@moxixuan, seems you are running the code on a Linux container on docker, Is that correct? If yes, give us more detail on the platform such as specific name of it and its version and also .NET Core version and docker information as well please. Docker information could be obtained simply by (`$ docker version`)

If possible can you try the query with MARS set to false. ( Taking MultipleActiveResultSets out or equal to false in the connection string will do the job).
If possible a complete repro of your application ,something that shows what all the names and functions are doing, would be appreciated.

**Comment by moxixuan** [comment]
> 
> 
> @moxixuan, seems you are running the code on a Linux container on docker, Is that correct? If yes, give us more detail on the platform such as specific name of it and its version and also .NET Core version and docker information as well please. Docker information could be obtained simply by (`$ docker version`)
> 
> If possible can you try the query with MARS set to false. ( Taking MultipleActiveResultSets out or equal to false in the connection string will do the job).
> If possible a complete repro of your application ,something that shows what all the names and functions are doing, would be appreciated.

yes, i'm  running the code on a Linux container on docker.
.NET Core version is .NET SDK (5.0.102)

docker version
docker://19.3.5

yes, i have try MultipleActiveResultSets  = false ;

that's is other error follow:
A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
Microsoft.Data.SqlClient.SqlException (0x80131904): A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (54): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at Microsoft.Data.SqlClient.SNI.SNINetworkStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---

i can repro it on my mac system. and docker in linux
but can't repro it on my windows systems.

**Comment by moxixuan** [comment]
> 
> 
> @moxixuan, seems you are running the code on a Linux container on docker, Is that correct? If yes, give us more detail on the platform such as specific name of it and its version and also .NET Core version and docker information as well please. Docker information could be obtained simply by (`$ docker version`)
> 
> If possible can you try the query with MARS set to false. ( Taking MultipleActiveResultSets out or equal to false in the connection string will do the job).
> If possible a complete repro of your application ,something that shows what all the names and functions are doing, would be appreciated.

yes, i'm  running the code on a Linux container on docker.

.NET Core version
NET SDK (5.0.102)

docker version
docker://19.3.5

i have try MultipleActiveResultSets  = false ;

it work well, and nolonger meet this error.

thank you  so much O(∩_∩)O~
