### ISSUE TITLE
Visual Studio package suggestion should include Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by danmoseley** [dotnet/SqlClient#1063]
When using a type in *.SqlClient, it will initially be unresolved. If you hit `ctrl+.` in Visual Studio on an unresolved type, it will offer to install a package that it knows about that offers the type, as shown below. Currently, Visual Studio only suggests System.SqlClient. It ought to also offer Microsoft.SqlClient, as that's the recommended path for new code:

![image](https://user-images.githubusercontent.com/6385855/117504874-fd242a80-af37-11eb-8de5-d2e9df7ea003.png)

@sharwell do you know who maintains the suggestion list?

**Comment by roji** [comment]
Microsoft.Data.SqlClient should probably even be the first recommended option...

**Comment by cheenamalhotra** [comment]
Fully support the thought! Any suggestions to where we go from here, and how can we support?
Pinging @sharwell again :)

**Comment by danmoseley** [comment]
I also played some with the VS feature that adds missing "using" statements, and as far as I can see it's doing the "right" thing assuming you've added the M.D.SqlClient reference - so that's good.

I was wondering whether there was a way to do something like this to port (and then you could suggest this in https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md) 

1. Search and remove all the "old" namespaces
2. Replace the package reference
3. Add missing using statements across the solution.

But it seems it would need a VS extension to do #3. Perhaps @sharwell knows otherwise.

**Comment by sharwell** [comment]
I'm not sure how this is maintained. @CyrusNajmabadi do you know?

**Comment by danmoseley** [comment]
Or @jaredpar ?

**Comment by cheenamalhotra** [comment]
FYI, I've opened a new ticket in Visual Studio, if that helps engage right team!
https://developercommunity.visualstudio.com/t/Include-and-suggest-MicrosoftDataSqlCl/1426003?space=8&entry=suggestion

**Comment by danmoseley** [comment]
@jinujoseph do you know who maintains this list?

**Comment by Youssef1313** [comment]
The codefix provider of this feature is at https://github.com/dotnet/roslyn/blob/main/src/Features/Core/Portable/AddPackage/AbstractAddPackageCodeFixProvider.cs

But I'm not sure where the packages it suggests come from. Some debugging should around it should probably help.

**Comment by jinujoseph** [comment]
The package index is generated by Nuget 
This is being discussed internally.

**Comment by JRahnama** [comment]
Closing this issue as external please follow the progress roslyn page [here](https://github.com/dotnet/roslyn/issues/53736)

**Comment by CyrusNajmabadi** [comment]
The issue here is that MS.Data.SqlClient is in the index, but is much lower priority, so it is filtered out compared to System.Data.SqlClient.  We do this because some types show up in tons of packages due to users just including copies of things.  We don't want the user to get spammed with lots of irrelevant hits, so we order based on magnitude of importance.  It looks like MS.Data.SqlClient is orders of magnitude less used than System.Data.SqlClient so it gets filtered out.
