### ISSUE TITLE
Microsoft.Data.SqlClient in Core Web Application Not Working .net 5

### ISSUE THREAD

**Issue by MithunAmalraj** [dotnet/SqlClient#1071]
Hi Team,

Microsoft.Data.SqlClient is not working in .net 5 web application. If the target framework is changed to 3.1 it is working fine. Help me out here please

**Comment by ErikEJ** [comment]
Could you perhaps be a bit more specific? What does "not work" mean?

**Comment by cheenamalhotra** [comment]
Hi @MithunAmalraj 

Please provide specific details with a repro if possible.

**Comment by MithunAmalraj** [comment]
Hi, Sorry, I am new to this forum. Thank you for your time. Below are the details,

**Project Type:** C# ASP NET Core Web Application
**Template:** ASP.NET Core Web App (Model-View-Controller)
**Framework:** .NET 5

In this sample code below, SQL server is called to fetch some data. When debugging is done, data is not loaded in the datatable. While checked with SQL server profiler, request is received at SQL Server. But data is not getting filled.

```
DataTable objresutl = new DataTable();
SqlDataReader myReader;
using (SqlConnection myCon = new SqlConnection(constring))
{
   myCon.Open();
   using (SqlCommand myCommand = new SqlCommand("GetPopularAirport", myCon))
   {
     myCommand.CommandType = CommandType.StoredProcedure;
     myReader = myCommand.ExecuteReader();
     objresutl.Load(myReader);
     myReader.Close();
     myCon.Close();
   }
}
```

**Error in .NET 5 Image**
![net5error](https://user-images.githubusercontent.com/17832187/118145935-c19fc980-b42b-11eb-938b-c222551ad661.png)

**Working Fine when Target Framework is changed to .NET 3.1**
![net31](https://user-images.githubusercontent.com/17832187/118146121-eb58f080-b42b-11eb-9e0d-2c6e9bccb9e3.png)

**Comment by cheenamalhotra** [comment]
@MithunAmalraj 

I tested below code with .NET 5 with [Microsoft.Data.SqlClient v2.1.2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.2) and I don't see any issue in retrieving records.
```cs
        DataTable objresutl = new();
        using SqlConnection myCon = new(connString);
        myCon.Open();
        using SqlCommand myCommand = new("sp_who2", myCon);
        myCommand.CommandType = CommandType.StoredProcedure;
        using SqlDataReader myReader = myCommand.ExecuteReader();
        objresutl.Load(myReader);
```

Please validate your solution setup.

**Comment by MithunAmalraj** [comment]
@cheenamalhotra one last try here I have uploaded the sample repo, https://github.com/MithunAmalraj/SampleAppNet5.
If its still working for you with this app, I will check more at my end.

**Comment by cheenamalhotra** [comment]
Thanks for repro @MithunAmalraj 

The behavior is strange. It's mainly with the DataTable Visualizer component it seems.
1. In Console App (targeting .NET 5.0) there's no issue.
2. In ASP.NET App (.NET 5.0) DataTable Visualizer does not load data, but the "objresult" contains data if you go to "Rows > Results View":
![image](https://user-images.githubusercontent.com/13396919/118295096-53d9b900-b490-11eb-9d26-7e4da988ef47.png)

So I think this is an issue with Visualizer and for that you'd have to reach to Visual Studio team.
I found this discussion thread [DataTable-Visualizer-crashes-again](https://developercommunity2.visualstudio.com/t/DataTable-Visualizer-crashes-again/1373262) which points to an unsolved issue. Please provide them with your repro and that may help them solve it.

**Comment by MithunAmalraj** [comment]
@cheenamalhotra Thanks for your time. I will take this forward with the visual studio team.
