### ISSUE TITLE
[Minor optimisation] Potential for optimisation in WriteToServer (SqlMetaDataPriv.IsNullable)

### ISSUE THREAD

**Issue by thibault-reigner** [dotnet/SqlClient#1076]
Hello,

While working on a project I have observed through DotTrace an opportunity to quickly get some better performance in `WriteToServer` : 
Framework version : Net Framework 4.7.2
Microsoft.Data.SqlClient version : 2.1.2

![image](https://user-images.githubusercontent.com/6624646/118767860-de675180-b8b0-11eb-88b2-8bc02bee1c7e.png)

As one can see, the `HasFlag` method used in `SqlMetaDataPriv.IsNullable` triggers some boxing and extra computation. I guess a solution like the one mentioned here https://medium.com/@arphox/the-boxing-overhead-of-the-enum-hasflag-method-c62a0841c25a
would result in some interesting performance gain as overall the method takes 0.41% of 9.18%, so ~4.5% of the `WriteToServer` method). This proportion could technically be higher since `GetValueFromSourceRow` calls the `IDataReader` supplied by the client code, whose performance could be better than the one from my example above and hence increase the relative proportion of `ConvertValue` and `IsNullable`.

**Comment by JRahnama** [comment]
@thibault-reigner thanks for sharing your idea to this repo. Can you make a PR for the suggested improvement otherwise we will get back to this in future when we have time.

**Comment by cheenamalhotra** [comment]
PR https://github.com/dotnet/SqlClient/pull/1054

**Comment by Wraith2** [comment]
And https://github.com/dotnet/SqlClient/pull/1064 

From what I was told netcore 3.1 should generate masking for the HasFlag extension and that change was made in corefx when the code was only going to be used from netcore. I have seen this turn up on my own traces even under netcore so I'm not sure why it's not generating the same code as it would in sharplab. Manual flags is more compatible and doesn't box so everything will get switched over as soon as we can.
