### ISSUE TITLE
Multiple timeouts while opening connections on Net Core 3.1

### ISSUE THREAD

**Issue by thibault-reigner** [dotnet/SqlClient#1097]
NB : The issue is similar to https://github.com/dotnet/SqlClient/issues/1027 but as no Linux instance is involved I think it can still be relevant to create new one.

### Configuration
I have recently migrated an application running on :
-  Asp.Net core 2.1 
- Net Framework 4.7.2
- Microsoft.Data.SqlClient **2.1.1**
- Windows Server 2019
- SQL Server 2019 (running on a different Windows machine)

to

- Asp.Net Core 3.1
- Net Core 3.1 (runtime 3.1.15)
- Microsoft.Data.SqlClient **2.1.2** and **2.1.1** (we downgraded later for investigation)
- Windows Server 2019
- SQL Server 2019 (running on a different Windows machine)

The connections to SQL Server are not encrypted and the connection string is as follow : 
`Data Source=<SERVER>;Initial Catalog=<DATABASE>;Integrated Security=True;`

### Details of the issue
Since, I am observing that several connections fail to open with any of these two error messages when the activity from users in the UI starts to pick up :
```
  Microsoft.Data.SqlClient.SqlException (0x80131904): Connection Timeout Expired.  The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement.  This could be because the pre-login handshake failed or the server was unable to respond back in time.  The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21027; handshake=0; 
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
 ```
```
  Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - The wait operation timed out.)
 ---> System.ComponentModel.Win32Exception (258): The wait operation timed out.
 ```

A non negligible factor being that we actually have 2 web servers shared the load through a load balancer of incoming requests, but querying the same SQL server.

I am planning to check the result when disabling one of the web servers, hence reducing the cause of the regression to either the update of Microsoft.Data.SqlClient from 2.1.1 to 2.1.2 or the transition to net core 3.1.

Any idea how such issue should be investigated ? I have checked `dotnet-trace` and `dotnet-counters` but struggled to make them collect anything.

Example of stacktrace
```
Connection Timeout Expired. The timeout period elapsed while attempting to consume the pre-login handshake acknowledgement. This could be because the pre-login handshake failed or the server was unable to respond back in time. The duration spent while attempting to connect to this server was - [Pre-Login] initialization=21018; handshake=0;
Microsoft.Data.SqlClient.SqlInternalConnection in OnError in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParser in ThrowExceptionAndWarning in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParserStateObject in ThrowExceptionAndWarning in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParserStateObject in ReadSniError in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParserStateObject in ReadSniSyncOverAsync in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParserStateObject in TryReadNetworkPacket in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParser in ConsumePreLoginHandshake in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.TdsParser in Connect in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.SqlInternalConnectionTds in AttemptOneLogin in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.SqlInternalConnectionTds in LoginNoFailover in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.SqlInternalConnectionTds in OpenLoginEnlist in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.SqlInternalConnectionTds in .ctor in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.SqlClient.SqlConnectionFactory in CreateConnection in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.ProviderBase.DbConnectionFactory in CreatePooledConnection in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.ProviderBase.DbConnectionPool in CreateObject in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.ProviderBase.DbConnectionPool in UserCreateRequest in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.ProviderBase.DbConnectionPool in TryGetConnection in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
Microsoft.Data.ProviderBase.DbConnectionPool in WaitForPendingOpen in C:\Program Files\dotnet\shared\Microsoft.NETCore.App\3.1.15\System.Private.CoreLib.dll
```

**Comment by ErikEJ** [comment]
Are you using EF Core different version?

If so, check the generated SQL for both versions.

**Comment by thibault-reigner** [comment]
We are not using EF Core but SqlClient directly.

**Comment by thibault-reigner** [comment]
The issue persists after a downgrade to 2.1.1, so it seems the behaviour or the client is different depending on whether it is running on net framework or net core.

**Comment by cheenamalhotra** [comment]
Hi @thibault-reigner

If possible, please try to create a repro app to reproduce the issue consistently. That way we can debug and dive into issue that exists.

On Windows, we expect the driver to be fairly consistent on both .NET Framework and .NET Core, so any discrepancies should be identifiable if we can reproduce the issue.

**Comment by thibault-reigner** [comment]
So far we haven't been able to reproduce the issue in a consistent way. So far the main hypothesis is that the `Always On` / `Availability Groups` feature used in the production environment is the cause of the issue, we are currently working on reproducing this on a sandbox environment.

Browsing the documentation, I noticed that there is `MultisubnetFailover` option for the connection string https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnectionstringbuilder.multisubnetfailover?view=dotnet-plat-ext-5.0 which is indicated as being actually relevant regardless if there is one or several subnets, as long as the availability group feature is on https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/sqlclient-support-for-high-availability-disaster-recovery

Yet this statement suggests there is no need to set it to true explicitly from Net Framework 4.6.1
![image](https://user-images.githubusercontent.com/6624646/121295848-4b0ac480-c922-11eb-8af9-faaf098222b0.png)
 
Do you know if this is still relevant for Net Core (3.1) as well ?

**Comment by thibault-reigner** [comment]
The issue seems to be fixed by `MultiSubnetFailover=true`

**Comment by 414004738** [comment]
Hi @cheenamalhotra, can you clarify whether .NET 5 or .NET 6 supports "Transparent Network IP Resolution" or whether setting MultiSubnetFailover=true is still required? It isn't clear to me how to interpret the statement "Setting MultiSubnetFailover to true isn't required with .NET Framework 4.6.1 or later versions" in the documentation here: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/sqlclient-support-for-high-availability-disaster-recovery

**Comment by JRahnama** [comment]
@414004738 TNIR is not supported in Microsoft.Data.SqlClient and you need to add  `MultiSubnetFailover=true` that will prevent the issue #1126 as well.

**Comment by 414004738** [comment]
OK, thanks for the response, @JRahnama. Do you know if TNIR support is planned to be added to Microsoft.Data.SqlClient (similar to the support in "[Microsoft JDBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/jdbc/jdbc-driver-support-for-high-availability-disaster-recovery?view=sql-server-ver15)" and "[Microsoft ODBC Driver for SQL Server](https://docs.microsoft.com/en-us/sql/connect/odbc/using-transparent-network-ip-resolution?view=sql-server-ver15)")?

**Comment by JRahnama** [comment]
@414004738 just to correct my previous comment, it is supported if the driver is being used with .NetFramewrok application. It is not supported in netcore.
