### ISSUE TITLE
Column Encryption (Always Encrypted) support in SqlClient for .NET Core

### ISSUE THREAD

**Issue by ghost** [dotnet/SqlClient#11]
When using a DbContext with a ConnectionString like

```
{
  "ConnectionStrings": {
    "DefaultConnection": "Server=.\\SQLEXPRESS;Database=EFGetStarted.AspNetCore.NewDb;Trusted_Connection=True;Column Encryption Setting=Enabled;MultipleActiveResultSets=true;"
  }
}
```

I get the following error
StackTrace
```
{System.ArgumentException: Keyword not supported: 'column encryption setting'.
   at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 parsetable, String connectionString, Boolean buildChain, Dictionary`2 synonyms)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Dictionary`2 synonyms)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Internal.LazyRef`1.get_Value()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at xBN.Repository.Repositories.EntityBaseRepository`1.Commit() in C:\!Checkouts\git checkouts\xBN\xBN.Service\Repositories\EntityBaseRepository.cs:line 98
   at xBN.API.Controllers.CompanyController.Get(Int32 id) in C:\!Checkouts\git checkouts\xBN\xBN.API\Controllers\CompanyController.cs:line 37
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()}
```

The issue is about adding support for the Column Encryption Setting to the .NET Core ADO.NET SqlClient.

**Comment by lsuarez5280** [comment]
@David-Engel could you recommend the best place to watch for updated Azure Key Vault support? We're using certificate store for the moment but trying to catch all the places that need cert updates is a pain and we'd love to migrate in the near term.

**Comment by kedarchinchvalkar** [comment]
@divega : Good to hear about this feature. 
Currently EntityCore SQL Provider uses System.Data.SqlClient and its internal dependency comes with EntityCoreSqlServer.  Is there any way to override System.Data.SqlClient with the Microsoft.Data.SqlClient?

**Comment by kedarchinchvalkar** [comment]
@divega  How can this change be incorporated into the EFCore.SqlServer? because System.Data.SqlClient is  one of the dependencies of EFCore.SqlServer.

**Comment by lsuarez5280** [comment]
@kedarchinchvalkar There are two relatively small steps:

1. Register your DB context for DI using the overload provided for specifying the abstract `DbConnection`, constructing instead a `Microsoft.Data.SqlClient.SqlConnection`.
2. Replace the `ISqlServerConnection` service with one targeting `Microsoft.Data.SqlClient` for both `SqlConnection` and `SqlConnectionStringBuilder`.

I lifted the code from GitHub for the last Microsoft.EntityFrameworkCore.SqlServer 2.x release for `SqlServerConnection` and updated it with proper targets as follows:

```
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
using Microsoft.EntityFrameworkCore.Storage;
using System.Data.Common;

namespace My.Storage
{
    /// <summary>
    ///     This API supports the Entity Framework Core infrastructure.
    /// </summary>
    public class SqlServerConnection : RelationalConnection, ISqlServerConnection
    {
        private bool? _multipleActiveResultSetsEnabled;

        // Compensate for slow SQL Server database creation
        private const int DefaultMasterConnectionCommandTimeout = 60;

        /// <summary>
        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public SqlServerConnection(RelationalConnectionDependencies dependencies)
            : base(dependencies)
        {
        }

        /// <summary>
        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        protected override DbConnection CreateDbConnection() => new SqlConnection(ConnectionString);

        /// <summary>
        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public virtual ISqlServerConnection CreateMasterConnection()
        {
            var connectionStringBuilder = new SqlConnectionStringBuilder(ConnectionString)
            {
                InitialCatalog = "master"
            };
            connectionStringBuilder.Remove("AttachDBFilename");

            var contextOptions = new DbContextOptionsBuilder()
                .UseSqlServer(
                    connectionStringBuilder.ConnectionString,
                    b => b.CommandTimeout(CommandTimeout ?? DefaultMasterConnectionCommandTimeout))
                .Options;

            return new SqlServerConnection(Dependencies.With(contextOptions));
        }

        /// <summary>
        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
        ///     directly from your code. This API may change or be removed in future releases.
        /// </summary>
        public override bool IsMultipleActiveResultSetsEnabled
            => (bool)(_multipleActiveResultSetsEnabled
                      ?? (_multipleActiveResultSetsEnabled
                          = new SqlConnectionStringBuilder(ConnectionString).MultipleActiveResultSets));

        /// <summary>
        ///     Indicates whether the store connection supports ambient transactions
        /// </summary>
        protected override bool SupportsAmbientTransactions => true;
    }
}
```

Then I updated my service registration for AddDbContext as follows, where `SqlServerConnection` is `using SqlServerConnection = My.Storage.SqlServerConnection`:
```
        public void ConfigureServices(IServiceCollection services)
        {
            services
                .AddDbContext<MyContext>(opts =>
                    opts
                        .UseSqlServer(new SqlConnection(Configuration.GetConnectionString("DefaultConnection")))
                        .ReplaceService<ISqlServerConnection, SqlServerConnection>()) // TODO: Remove after transition to Core 3
```

Works like a charm.

**Comment by David-Engel** [comment]
> @David-Engel could you recommend the best place to watch for updated Azure Key Vault support? We're using certificate store for the moment but trying to catch all the places that need cert updates is a pain and we'd love to migrate in the near term.

@lsuarez5280 I'm not sure. I'll be sure to update this issue if I hear anything, though.

**Comment by divega** [comment]
> @divega How can this change be incorporated into the EFCore.SqlServer? because System.Data.SqlClient is one of the dependencies of EFCore.SqlServer.

@kedarchinchvalkar, EF Core 3.0 will switch to depend directly on Microsoft.Data.SqlClient. This change is coming probably in the next preview.

**Comment by divega** [comment]
@David-Engel should we have a separate issue to track Azure Key Vault support? I am not very familiar with the feature, but it seems we need to follow up internally with the owners of https://www.nuget.org/packages/Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider.

**Comment by David-Engel** [comment]
@divega I've already notified the team that owns the AKV library. Given the priority of AE support in SqlClient on netcore, I'm certainly keeping tabs on their progress. I've filed #111 here for tracking.

**Comment by kedarchinchvalkar** [comment]
> @kedarchinchvalkar There are two relatively small steps:
> 
> 1. Register your DB context for DI using the overload provided for specifying the abstract `DbConnection`, constructing instead a `Microsoft.Data.SqlClient.SqlConnection` (probably optional).
> 2. Replace the `ISqlServerConnection` service with one targeting `Microsoft.Data.SqlClient` for both `SqlConnection` and `SqlConnectionStringBuilder`.
> 
> I lifted the code from GitHub for the last Microsoft.EntityFrameworkCore.SqlServer 2.x release for `SqlServerConnection` and updated it with proper targets as follows:
> 
> ```
> using Microsoft.Data.SqlClient;
> using Microsoft.EntityFrameworkCore;
> using Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal;
> using Microsoft.EntityFrameworkCore.Storage;
> using System.Data.Common;
> 
> namespace My.Storage
> {
>     /// <summary>
>     ///     This API supports the Entity Framework Core infrastructure.
>     /// </summary>
>     public class SqlServerConnection : RelationalConnection, ISqlServerConnection
>     {
>         private bool? _multipleActiveResultSetsEnabled;
> 
>         // Compensate for slow SQL Server database creation
>         private const int DefaultMasterConnectionCommandTimeout = 60;
> 
>         /// <summary>
>         ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
>         ///     directly from your code. This API may change or be removed in future releases.
>         /// </summary>
>         public SqlServerConnection(RelationalConnectionDependencies dependencies)
>             : base(dependencies)
>         {
>         }
> 
>         /// <summary>
>         ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
>         ///     directly from your code. This API may change or be removed in future releases.
>         /// </summary>
>         protected override DbConnection CreateDbConnection() => new SqlConnection(ConnectionString);
> 
>         /// <summary>
>         ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
>         ///     directly from your code. This API may change or be removed in future releases.
>         /// </summary>
>         public virtual ISqlServerConnection CreateMasterConnection()
>         {
>             var connectionStringBuilder = new SqlConnectionStringBuilder(ConnectionString)
>             {
>                 InitialCatalog = "master"
>             };
>             connectionStringBuilder.Remove("AttachDBFilename");
> 
>             var contextOptions = new DbContextOptionsBuilder()
>                 .UseSqlServer(
>                     connectionStringBuilder.ConnectionString,
>                     b => b.CommandTimeout(CommandTimeout ?? DefaultMasterConnectionCommandTimeout))
>                 .Options;
> 
>             return new SqlServerConnection(Dependencies.With(contextOptions));
>         }
> 
>         /// <summary>
>         ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
>         ///     directly from your code. This API may change or be removed in future releases.
>         /// </summary>
>         public override bool IsMultipleActiveResultSetsEnabled
>             => (bool)(_multipleActiveResultSetsEnabled
>                       ?? (_multipleActiveResultSetsEnabled
>                           = new SqlConnectionStringBuilder(ConnectionString).MultipleActiveResultSets));
> 
>         /// <summary>
>         ///     Indicates whether the store connection supports ambient transactions
>         /// </summary>
>         protected override bool SupportsAmbientTransactions => true;
>     }
> }
> ```
> 
> Then I updated my service registration for AddDbContext as follows, where I construct a `Microsoft.Data.SqlClient.SqlConnection` and `SqlServerConnection` is `using SqlServerConnection = My.Storage.SqlServerConnection;`:
> 
> ```
> public void ConfigureServices(IServiceCollection services)
> {
>     services
>         .AddDbContext<MyContext>(opts =>
>             opts
>                 .UseSqlServer(new SqlConnection(Configuration.GetConnectionString("DefaultConnection")))
>                 .ReplaceService<ISqlServerConnection, SqlServerConnection>()) // TODO: Remove after transition to Core 3
> }
> ```
> 
> Works like a charm. I even think the step of constructing the DbConnection may be unnecessary and you can use the raw string value for UseSqlServer(), but haven't tried it. Feel free to experiment.

Its giving an error on UserSqlServer() as,
The call is ambiguous between the following methods or properties: 

'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)' 
and 
'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)'

**Comment by lsuarez5280** [comment]
> Its giving an error on UserSqlServer() as,
> The call is ambiguous between the following methods or properties:
> 'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)'
> and
> 'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)'

@kedarchinchvalkar That sounds like you may have reference problems in your project with multiple SQL Server EF Relational packages imported somehow, but is not related to the code. Those method prototypes are exactly the same.

**Comment by kedarchinchvalkar** [comment]
> > Its giving an error on UserSqlServer() as,
> > The call is ambiguous between the following methods or properties:
> > 'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)'
> > and
> > 'Microsoft.EntityFrameworkCore.SqlServerDbContextOptionsExtensions.UseSqlServer(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder, System.Data.Common.DbConnection, System.Action<Microsoft.EntityFrameworkCore.Infrastructure.SqlServerDbContextOptionsBuilder>)'
> 
> @kedarchinchvalkar That sounds like you may have reference problems in your project with multiple SQL Server EF Relational packages imported somehow, but is not related to the code. Those method prototypes are exactly the same.

Yes, You're right. There was a duplicate reference due to "Microsoft.AspNetCore.All" package. Thank you so much.

Program now builds perfectly. I have applied column encryption on database table columns.
but while reading data I am getting following error,

InvalidCastException: Unable to cast object of type 'System.Byte[]' to type 'System.String'.
Microsoft.Data.SqlClient.SqlBuffer.get_String()
lambda_method(Closure , DbDataReader )
Microsoft.EntityFrameworkCore.Storage.Internal.TypedRelationalValueBufferFactory.Create(DbDataReader dataReader)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.BufferlessMoveNext(DbContext _, bool buffer)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded) in SqlServerExecutionStrategy.cs
-
            TState state,
            Func<DbContext, TState, TResult> operation,
            Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
        {
            try
            {
                return operation(Dependencies.CurrentDbContext.Context, state);
            }
            catch (Exception ex) when (ExecutionStrategy.CallOnWrappedException(ex, SqlServerTransientExceptionDetector.ShouldRetryOn))
            {
                throw new InvalidOperationException(SqlServerStrings.TransientExceptionDetected, ex);
            }
        }
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities<TOut, TIn>(IEnumerable<TOut> results, QueryContext queryContext, IList<EntityTrackingInfo> entityTrackingInfos, IList<Func<TIn, object>> entityAccessors)+MoveNext()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext()
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.Load<TSource>(IQueryable<TSource> source)
Microsoft.EntityFrameworkCore.Internal.EntityFinder<TEntity>.Load(INavigation navigation, InternalEntityEntry entry)
Microsoft.EntityFrameworkCore.Internal.LazyLoader.Load(object entity, string navigationName)
Microsoft.EntityFrameworkCore.Proxies.Internal.LazyLoadingInterceptor.Intercept(IInvocation invocation)
Castle.DynamicProxy.AbstractInvocation.Proceed()
Castle.Proxies.WorkflowProxy.get_FormData()
lambda_method(Closure , Workflow , SurveyViewModel , ResolutionContext )

**Comment by kedarchinchvalkar** [comment]
Any updates on above?

**Comment by lsuarez5280** [comment]
@kedarchinchvalkar I'm gonna guess that you haven't actually added `Column Encryption Setting=Enabled` in your connection string. At this point, I suggest you don't use this issue to continue the conversation. Either seek community support for utilizing the connector or open a new issue so your questions can be addressed there.

**Comment by kedarchinchvalkar** [comment]
> @kedarchinchvalkar I'm gonna guess that you haven't actually added `Column Encryption Setting=Enabled` in your connection string. At this point, I suggest you don't use this issue to continue the conversation. Either seek community support for utilizing the connector or open a new issue so your questions can be addressed there.

@Isuarez5280 : Thank you so much for the suggestion. I will open it as a new issue.

**Comment by kedarchinchvalkar** [comment]
Thank you so much @lsuarez5280 and @divega 
Your solution works like a charm.

**Comment by cheenamalhotra** [comment]
We believe the originally reported issue has been addressed in Microsoft.Data.SqlClient (NetCore), please open new issues for any specific usecase, closing the issue.
