### ISSUE TITLE
Will 3.0 be an LTS release?

### ISSUE THREAD

**Issue by bdschaap** [dotnet/SqlClient#1103]
Will 3.0 be an LTS release?

Thanks!

**Comment by David-Engel** [comment]
> Will 3.0 be an LTS release?

No. Since 2.1 was an LTS release back in November, we are not considering 3.0 for LTS. We may consider the next release for LTS, but that isn't decided yet.

**Comment by bdschaap** [comment]
Thanks.  I believe the move to Azure.Identity better supports our use cases and am eager to begin using it once it's an LTS release.

**Comment by cheenamalhotra** [comment]
Closing as answered.

_P.S. LTS release information is available on [SqlClient driver support lifecycle](https://docs.microsoft.com/sql/connect/ado-net/sqlclient-driver-support-lifecycle)._
