### ISSUE TITLE
Track progress on Azure Key Vault support for .NET Core

### ISSUE THREAD

**Issue by David-Engel** [dotnet/SqlClient#111]
Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider does not yet support .NET Core. Filing this issue to keep track of when the team that owns it releases an update that does support .NET Core.

Reference: https://www.nuget.org/packages/Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider

**Comment by naresh1990** [comment]
Any update on this? or any timeline for this to be included in .NET Core?

**Comment by David-Engel** [comment]
> Any update on this? or any timeline for this to be included in .NET Core?

No update. It's not "in .NET Core". It's an independent library which needs to support .NET Core targets. The team that owns it says it's a high priority on their TODO list but there is no timeline right now.

**Comment by dferretti** [comment]
I was able to get this to work by re-implementing the `SqlColumnEncryptionAzureKeyVaultProvider` by mostly copying the decompiled source of the .NET Framework version. Using dotPeek or ILSpy on the dll inside the https://www.nuget.org/api/v2/package/Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider/2.1.0 nupkg you can see the decompiled source of `SqlColumnEncryptionAzureKeyVaultProvider`, and the only real things that needed changing that I could see were replacing `new SHA256Cng()` with `SHA256.Create()` a few times and replacing `System.Data.SqlClient` with `Microsoft.Data.SqlClient` (and I was lazy and replaced the resource managed strings in Strings.cs with constants).
Then, with this copied class, the only nuget packages you need (which are .net standard) are `Microsoft.Azure.KeyVault` and `Microsoft.IdentityModel.Clients.ActiveDirectory`. From there, I was able to follow this guide https://docs.microsoft.com/en-us/azure/sql-database/sql-database-always-encrypted-azure-key-vault#register-the-azure-key-vault-provider without issue. 

My test application had these package references:
```
<PackageReference Include="Microsoft.Azure.KeyVault" Version="2.3.2" />
<PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19221.1-Preview" />
<PackageReference Include="Microsoft.IdentityModel.Clients.ActiveDirectory" Version="5.2.0" />
```
Also tested and worked (on my machine! through windows and docker) with Microsoft.Azure.KeyVault 3.0.4.

I would post the source of the provider, but I'm not sure if posting modified decompiled source goes against the license.

**Comment by David-Engel** [comment]
Update: The team that owns the AKV provider is going to pass it to us (the SqlClient team) to work on. We will start working on it as soon as we can and hopefully have an updated version out in September/October.

**Comment by beufordy3k** [comment]
> Update: The team that owns the AKV provider is going to pass it to us (the SqlClient team) to work on. We will start working on it as soon as we can and hopefully have an updated version out in September/October.

@David-Engel 
Will this be available as a dev myget feed here? https://dotnet.myget.org/gallery/aspnetcore-dev

Does this have any milestones set yet? Thanks!

**Comment by Tim-Bijnens** [comment]
Any update or timeframe on this? 

We have several new .Net Core projects running on Azure app service that have to use (time consuming and not ideally performing) work arounds to handle the encrypted data via the regular EF Azure KeyVault provider. 

Thank you!

**Comment by ErikEJ** [comment]
@Tim-Bijens Looks like it is planned for 1.1: https://github.com/dotnet/SqlClient/projects/4

**Comment by cperras** [comment]
@cheenamalhotra hi cheena - any eta an when 1.1 might be released and/or a preview version of SqlColumnEncryptionAzureKeyVaultProvider will be available?

we have an open story on this, so we just want to plan next steps. thanks!

**Comment by cheenamalhotra** [comment]
@cperras very soon! Stay tuned :)

**Comment by cheenamalhotra** [comment]
@cperras @Tim-Bijnens @beufordy3k @naresh1990 @dferretti 

We have released the first public preview version of Azure Key Vault Provider today, please download from here: [v1.0.0-preview1](https://www.nuget.org/packages/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider)

Please note that the AKV Provider is targeted for **SqlClient v1.1** hence will work with [v1.1.0-preview1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.0-preview1.19275.1) version of Microsoft.Data.SqlClient.

Please try it out and send us your feedback so we can enhance the library for a stable version.

**Comment by cheenamalhotra** [comment]
[M.D.S AE Azure Key Vault Provider 1.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider/1.0.0) GA version of library has been released today.
Closing issue.

**Comment by chris5287** [comment]
Great news! Has this been retargeted at MDS v1.0.1 or has v1.1.0 been released as well?

**Comment by cheenamalhotra** [comment]
@chris5287 it now targets M.D.S v1.0.19269.1

**Comment by chris5287** [comment]
Would this work with EF Core 3 straight out the box, or is there a change needed in their code base?

**Comment by cheenamalhotra** [comment]
I don't see EF Core 3.0 or 3.0.1 nuget is referencing driver version **1.0.19269.1** yet, but **[3.1.0-preview2](https://github.com/aspnet/EntityFrameworkCore/blob/08f0c381fca1fc977df7216cbe1f6717298dbc6c/eng/Versions.props#L31)** seems to have updated to this version that can be used.

**Comment by ErikEJ** [comment]
You can always reference a newer version explicitly
