### ISSUE TITLE
Upgrade to Azure.Identity 1.5 once it's available

### ISSUE THREAD

**Issue by ericsampson** [dotnet/SqlClient#1117]
### Is your feature request related to a problem? Please describe.
Following up on #730, the currently used Azure.Identity library versions don't handle the situation well when VS/VSCode has with multiple credentials signed in, which is fairly common (guest tenants etc).
This is being [addressed here](https://github.com/Azure/azure-sdk-for-net/pull/21378), which is planned to land in the next version of the library (1.5)

There's also a question if there is work on the Azure SQL Server side to support sending the tenant ID in the challenge header in order to light up this feature. I'm not sure where this should get filed.

### Describe the solution you'd like
Upgrade SqlClient to Azure.Identity once it's available.

### Describe alternatives you've considered
There are workarounds, but it requires setting environment variables on each dev's machine, so is not ideal.

**Comment by johnnypham** [comment]
Hi @ericsampson, thanks for making this. We'll keep an eye out for new releases.

**Comment by ericsampson** [comment]
Thanks Johnny.

It might be good to look at this together with #1106 , because according to the Identity issue I linked to originally, the user might have to specify a `EnableTenantDiscovery` option for the behavior to take effect. So there would have to be a way to pass that information to SqlClient in the connection string, similar to how in #1106 people are wanting to do things like select which token providers are used. Cheers

**Comment by JRahnama** [comment]
Closing this issue as package has been upgraded
