### ISSUE TITLE
Release date for Microsoft.Data.SqlClient?

### ISSUE THREAD

**Issue by vishwajeets7** [dotnet/SqlClient#112]
Noticed in couple forums the question is raised around the release date for Microsoft.Data.SqlClient, thought of opening another thread to received updates on the release date.

**Comment by David-Engel** [comment]
Right now the plan is to have a few preview releases before GA. For GA, our target is to ship on or around the same time that .NET Core 3.0 goes GA, which is scheduled for September.

**Comment by vishwajeets7** [comment]
@David-Engel  Thank you for sharing the updates.
