### ISSUE TITLE
Is there somewhere I could find the release notes of `System.Data.SqlClient`

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/SqlClient#1123]
Could I find the release notes of `System.Data.SqlClient` somewhere

**Comment by JRahnama** [comment]
System.Data.SqlClient is shipped with .Net framework. All related materials could be found [here](https://github.com/dotnet/core/tree/main/release-notes).

**Comment by ErikEJ** [comment]
To be clear, above link is for .NET Core / .NET 5 and later, for .NET Framework 4.8, see https://github.com/microsoft/dotnet/blob/master/releases/net48/dotnet48-changes.md#sql

**Comment by WeihanLi** [comment]
Thanks, @ErikEJ @JRahnama
