### ISSUE TITLE
How did you list the dependencies of Microsoft.Data.SqlClient?

### ISSUE THREAD

**Issue by chucklu** [dotnet/SqlClient#1137]
https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0

.NETFramework 4.6.1

    Azure.Identity (>= 1.3.0)
    Microsoft.Data.SqlClient.SNI (>= 3.0.0)
    Microsoft.Identity.Client (>= 4.22.0)
    Microsoft.IdentityModel.JsonWebTokens (>= 6.8.0)
    Microsoft.IdentityModel.Protocols.OpenIdConnect (>= 6.8.0)
    System.Configuration.ConfigurationManager (>= 4.7.0)
    System.Text.Encodings.Web (>= 4.7.2)

**Comment by chucklu** [comment]
when I check the references of the file
packages\Microsoft.Data.SqlClient.3.0.0\lib\net461\Microsoft.Data.SqlClient.dll
// Microsoft.Data.SqlClient, Version=3.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5
![image](https://user-images.githubusercontent.com/3004057/123229932-5573b380-d509-11eb-817c-0f7fa9f0ca41.png)

**Comment by chucklu** [comment]
Why  didn't you list  Azure.Core as a required dependency? also System.IdentityModel.Tokens.Jwt is not listed.

**Comment by ErikEJ** [comment]
Those are transitive dependencies (ie dependencies of top level dependencies)

**Comment by chucklu** [comment]
@ErikEJ   Thanks, by the way how did you know which dependencies should be listed?  Did you do it manually or use which tool can handle this automatically?

**Comment by ErikEJ** [comment]
https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netfx/src/Microsoft.Data.SqlClient.csproj#L584

**Comment by chucklu** [comment]
@ErikEJ  The csproj file you mentioned is a result file of the package reference, but I am curious about how did you get that result?

**Comment by cheenamalhotra** [comment]
We use specs: https://github.com/dotnet/SqlClient/blob/main/tools/specs/Microsoft.Data.SqlClient.nuspec

**Comment by chucklu** [comment]
@cheenamalhotra The question would be, how did you maintain the file Microsoft.Data.SqlClient.nuspec? Did you write it manually or generate it by another tool?

**Comment by cheenamalhotra** [comment]
We add new dependencies manually, but it can be generated from nuget package created by packing csproj directly using .NET SDK packing support. Our project is a little complex to be packed by itself, so we do manual addition.

**Comment by chucklu** [comment]
Thanks for you information @cheenamalhotra
