### ISSUE TITLE
SQL runtime hosting support

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#114]
What is the scope for using Microsoft.Data.SqlClient with a runtime hosted in SqlServer? desktop framework supports this feature because it contains constrained execution, coreclr does not (and will not prompted by [this](https://github.com/dotnet/coreclr/pull/24755)) support that feature and as such cannot be used as the host runtime in SqlServer.

What direction will this library take? Will it be a direct feature complete replacement for System.Data.SqlClient capable of being used inside SqlServer's hosted runtime or is that a feature that people aren't interested in supporting?

**Comment by David-Engel** [comment]
You can load Microsoft.Data.SqlClient in SqlServer (unsafe mode) but it will not have the same capabilities as System.Data.SqlClient and won't really be that useful. For UDTs, you can continue to use and define them with System.Data.SqlClient in SQL CLR and then read them on the client-side with equivalent classes from Microsoft.Data.SqlClient.

There is not currently any impetus on the M.D.SqlClient team to get it into the hosted runtime.
