### ISSUE TITLE
Kerberos delegation from Linux to Windows

### ISSUE THREAD

**Issue by rkotenko** [dotnet/SqlClient#1150]
I have asked this on StackOverflow but got no good answers.  I have also stepped through SqlClient code with a debugger, but it is pretty complicated so it is very possible I missed it.  I am now spinning my wheels and am left to ask the experts here.  Is kerberos delegation possible with SqlClient?  I have everything set up correctly for Kerberos and delegation between a dedicated account and Sql Server and yet, the user access is not delegated.  Here is my goal and results.  Please tell me if I am missing something:

**Desired Application Flow**

```User via Browser (koten001) -> Apache (Linux) -> Kestrel (Linux) -> Sql Server (Windows - logged in as koten001)```

It's your basic double hop.

The result is that I can see koten001 as authenticated in Kestrel via Kerberos but when I try to access SQL Server via Integrated Security, which ever user has lasted been kinit'd on the Linux box is who is logged in the profiler.  So no delegation is being done.

Is there a way to do this?  To actually use the Kerberos delegation I have set up for Sql Server?  The desired end to this is to be able to use row-level security for our web applications.  However, if we can't, it is not a deal-breaker.  I would just like to know if I should stop bashing my head against the wall on this.  :)

**Comment by cheenamalhotra** [comment]
Hi @rkotenko 

Kerberos authentication is supported from a Linux host client to SQL Server on Windows (if they're in same domain and SPN is configured correctly), and unconstrained delegation is allowed.

However I'm not sure about Constrained delegation support, I will have to dig in. 
But can you confirm if your client / server domains are same and this is not a constrained delegation?

Also, you can validate your setup using another client driver ([sqlcmd](https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/using-integrated-authentication?view=sql-server-ver15)/[mssqljdbc](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15)) to compare behaviors if you continue to face issue.

**Comment by rkotenko** [comment]
Hi @cheenamalhotra,

I definitely have this set up for constrained delegation.  The designated account is only allowed to delegate for MSSQLSvc, not for all services.  I am not sure allowing this account to delegate for everything would fly with our security team.  I can try bringing it up though. The linux and windows domains are not the same either.

When you say "constrained delegation support" are you referring to linux/windows support in general or specifically for SqlClient?  Implying that unconstrained would work? 

If you mean the former, I could find no sources indicating that constrained delegation would not work from Linux to Windows; as long as an account has the rights and the SPNs are set up correctly, it should be ok.  If you meant the latter, after going through the SqlClient code, I could find no obvious mechanisms which would allow me to use a delegation account to vouch for the actual user. So even if unconstrained works, how would I do that?

I will take a look at those other clients in the meantime.  Maybe one of them will lead me towards a solution.

**Comment by cheenamalhotra** [comment]
Linux/Mac/Windows does not matter, as long as they're in the **same domain**, SqlClient can connect.

Constrained delegation is when client and server not in the same domain but an impersonated user credential can be passed from one domain to another via client driver support. This is supported in [JDBC Driver via GSSCredential APIs](https://docs.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver15#constrained-delegation), that I'm aware of but I don't see any such credential option in SqlClient. I'm looking through any other possibility, but I doubt there is one.

**Comment by rkotenko** [comment]
That is what I thought and is very unfortunate.

I am confused on delegation though.  From what I read, constrained delegation is when an account limited to certain services.  Unconstrained is when an account is allowed to delegate for all services.  It does not matter if everything lives in the same domain or not; it just matters about which services an account can delegate for.

But you said unconstrained delegation is allowed.  How?  Unless I am running SqlClient on windows and can users WindowsIdentity to impersonate, I can't see any way to delegate at all if I can't pass along, essentially, two users, when connecting.  If it IS available though, I could try to make the case for implementing and unconstrained designated account.

**Comment by cheenamalhotra** [comment]
I think you might be right. I couldn't find any good documentation on this feature for our driver, so it's tricky to put pieces together. I was following code too, and I don't see any way to pass credential right now. 

But Kerberos on Linux generally works if you can generate a valid ticket and the user is authorized to connect to the target SQL Server on Windows. We have this setup running in test suite, so that should work for you too!

**Comment by rkotenko** [comment]
Yeah, I have Kerberos for Sql Server working, but I wanted a way to have the user logged into Sql Server without needing to create a kerberos ticket for each user on linux.  It would be a nice feature to see added to SqlClient, like it is in JDBC.

In any case, I found a way around it, I think.  I can use a single machine account to log into sql and and set a session context variable to the "real" user.  I can that to check access in my filter predicates. I haven't implemented it yet, but in theory, it should work.

If anyone else see this through their own searching and wants more details, my email is in my profile.

**Comment by cheenamalhotra** [comment]
Closing as queries have been answered.
