### ISSUE TITLE
Reducing dependencies and references

### ISSUE THREAD

**Issue by freica** [dotnet/SqlClient#1153]
I have 29 referenced assemblies on .NET 4.8 - using System.Data.SqlClient I have zero!
Is there a chance to reduce the references?

**Comment by ErikEJ** [comment]
You are implicitly referencing everything in .NET Framework

**Comment by freica** [comment]
Perhaps my statement was not specific enough.
Using Microsoft.Data.SqlClient I have to deploy 29 additional assemblies with my application, against 0 additional assemblies on using System.Data.SqlClient.

**Comment by ErikEJ** [comment]
If you do not need the new features and performance improvements in M.D.S., you can keep using SDS.

Having package dependencies is how modern .net libraries work.

There are thoughts about splitting out the Azure dependencies.

**Comment by freica** [comment]
We want to get ".NET5/6-ready" so we should move to M.D.S.

Having a small footprint is also a "modern feature"

Splitting out the Azure dependencies sounds good for me.

**Comment by ErikEJ** [comment]
Possible duplicate of #1108 ?

**Comment by cheenamalhotra** [comment]
Hi @freica 

As @ErikEJ referenced, we're considering that change as part of #1108, but other dependencies would continue to stay as it is a standard .NET design requirement.

**Comment by freica** [comment]
OK!
