### ISSUE TITLE
Feature Request: App Roles in the Connection String to avoid Pooling Issues

### ISSUE THREAD

**Issue by aersamkull** [dotnet/SqlClient#1157]
### Is your feature request related to a problem? Please describe.
It's a long standing issue with SQL Server App Pooling and App Roles: https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql-server-connection-pooling#application-roles-and-connection-pooling 

### Describe the solution you'd like
If we'd be able to set the app role in the connection string, we had different connection strings for different app roles and therefore not issues with Connection Pooling. In addition it would make using App Roles a bit simplier

### Describe alternatives you've considered
The alternative is not not use app roles or to disable Connection Pooling - or do some hack to make connection strings differ otherwise. I'd like to use app roles in order to make my app more secure. I use Azure Managed Identity, therefore I cannot just switch the user; app roles are the proper solution for my use case. Disable Connection Pooling is not really a good practice I think, it's there because of performance - and I like performance :)

**Comment by cheenamalhotra** [comment]
Hi @aersamkull 

Thanks for your suggestion. I agree that would be a good solution.
We will consider this if it gains significant interest from community or if it's prioritized on special interest.

**Comment by jzabroski** [comment]
@aersamkull a simple workaround for your problem is to update the Application Name per App Role via SqlConnectionStringBuilder before instantiating the SqlConnection with the connection string.  This works because Application Name differences force a new connection pool.  However, be careful with pool sizing, especially if you have many app roles, as you can exhaust TCP/IP connections at the OS level if you're using TCP/IP to connect.

**Comment by aersamkull** [comment]
I see App Roles will not get a lot of love ;) The workaround is ok, however to be really good it would require a way to say "before my first statement do this and that" (OnOpening Event or the like) which would allow turning the app role on - but that's a different topic. 
I'm not sure I share the concern about password security, I think if passwords are chosen decently and saved in a secure location the risk is acceptable - it's something different for user passwords which are never safe. But still, it's not the way to go and I'm fine with closing this issue - there are lot's of more important things to do

**Comment by jzabroski** [comment]
Well, it won't be thread-safe, but you can hook into [DbConnection.StateChange](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbconnection.statechange?view=net-6.0) event. I would just call whatever delegate you subscribe to that event as very clearly ThreadUnsafe by perhaps giving it such a suffix in its delegate method name.

The other option would be to create a simple DbContext that encapsulates something like Dapper, and have that wrapper DbContext do the app role magic.  Ideally you are not using raw SqlConnection objects in your application, as that leaks quite a bit of implementation detail throughout your business logic layer.

**Comment by jzabroski** [comment]
The additional benefit of using impersonation via EXECUTE AS is that you can trivially debug logic based on a mock user context using it. Care should be taken when using NT Authentication, though, as NT Auth-based login tokens do not expire until every session for that Windows SID is expired (read: logged out).  However, the biggest benefit I see is that you can use user name functions to persist audit trail of what (impersonated) user ran the data manipulation language statement.

Background: I have written very robust scripts for managing SQL Server permissions and am extremely picking about how I set-up my security definitions.
