### ISSUE TITLE
Feature: Localized resource support for .NET Core and Standard libraries

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#1158]
Currently localized string resources are only available for .NET Framework targets, and the same design can be leveraged for .NET Core and Standard libraries. There are many scenarios where this can be useful, e.g. PropertyGrid generation (ref: https://github.com/dotnet/SqlClient/issues/1142), culture specific error messages, etc.

**Comment by JRahnama** [comment]
Closing the issue as localization is added to netcore.
