### ISSUE TITLE
SqlException Includes PRINTed Text - Bug?

### ISSUE THREAD

**Issue by bgribaudo** [dotnet/SqlClient#116]
Using SqlClient, if a SQL statement uses `PRINT` to output text then encounters an error, the exception thrown by SqlClient may contain **both** the error returned by SQL Server (expected) _and_ the output from the print `PRINT` statement (not expected). 

For obvious reasons, it makes sense that the exception contains the error. :-) However, the print statement's contents are not an error and do not necessarily have any connection with the error. Including `PRINT`'s output in the exception seems incorrect. 

Is this a bug? 

Instead, shouldn't the application subscribe to the connection's [`InfoMessage`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.infomessage?view=netcore-2.2) ([ref2](https://stackoverflow.com/a/1880507)) event if they want `PRINT` statement output and the exception be limited to just true error message content?

### Code
_Target Framework:_ netcoreapp2.2
_Package Reference:_ System.Data.SqlClient, version 4.6.1
````
using System;
using System.Data.SqlClient;

namespace ErrorExample
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var connection = new SqlConnection("Data Source=.;Initial Catalog=Test;Integrated Security=true")) {
                connection.Open();

                using (var command = connection.CreateCommand())
                {
                    command.CommandText = "PRINT 'hello world!'; THROW 50001, N'Ouch', 1";
                    command.ExecuteNonQuery();
                }
            }
        }
    }
}
````

### Output
```
System.Data.SqlClient.SqlException: 'Ouch
hello world!'
````

### TDS
At the database protocol-level, the PRINT message is returned in an info token separately from the error message, which is returned in an error token:

* `Info Token - ErrNo: 0, State: 1, Class: 0, Message: 'hello world!', Server Name: [server name]\[instance], ProcName: ''`

* `Error Token - ErrNo: 50001, State: 1, Class: 16, Message: 'Ouch', Server Name: [server name]\[instance], ProcName: ''`

So, the tokens returned by the server have the two messages properly segmented between them. The problem is client-side, where the two tokens are being aggregated into a single exception.

**Comment by bgribaudo** [comment]
Thanks, @divega & @roji!

**Comment by karinazhou** [comment]
@bgribaudo  I am able to reproduce this with Microsoft.Data.SqlClient as well. We will investigate more into this. Thank you for reporting it!

**Comment by bgribaudo** [comment]
Thank you, @karinazhou!

**Comment by karinazhou** [comment]
Hi @bgribaudo,

After more investigation in the code, I am afraid that this is by design in the driver since the beginning. When generating SQLException, the driver copies warnings to the end of errors if they are received in the same TDS packet. This is to let the user see both errors and warnings that occurred. If there are multiple warning messages returned at the same time, they will be collected together as well, e.g. environment change warnings.

According to the MSDN description about [SQLException](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception?view=netframework-4.8), it returns a warning or error.  Changing the current logic in the driver will break backward compatibilities so there is no plan to do this in our recent roadmap. 

Thanks,
Karina

**Comment by bgribaudo** [comment]
Hi @karinazhou,

Thank you for checking into this. 

> When generating SQLException, the driver copies warnings to the end of errors if they are received in the same TDS packet.

Interestingly, the driver has a similar behavior if the error is due to a driver (client-side) timeout (e.g. if you set up a command with `CommandTimeout = 20` then execute `PRINT 'hello world'; WAITFOR DELAY '00:00:20'`, the print statement is captured in the `SqlException` that is thrown even though no error or warning was returned from the server-side).

Could documentation be updated to better reflect these behaviors? Mentioning the special handling of information messages on [SqlException](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlexception?view=netcore-2.2) would be helpful. 

Also, this behavior "breaks" the documented behavior of [InfoMessage](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.infomessage?view=netcore-2.2). (A print statement is an informational response from the server, so based on that documentation, it should be rounded to the appropriate event handler. It normally is but **not** in the case of the scenario we're discussing. Would be helpful for this behavior variance to be documented somewhere in the details for that event.)

Thanks,
Ben

**Comment by karinazhou** [comment]
Hi @bgribaudo , 

I tried your CommandTimeout test and I can see the SqlException is also generated with PRINT message attached. While debugging the code, it follows the same logic when creating SqlException. The PRINT message received from the Server as SQLInfo is treated as warning internally. When the actual exception is thrown, the PRINT message is appended as well. 

I agree that the documentation should be updated to include these scenarios. 

Thanks,
Karina

**Comment by bgribaudo** [comment]
Thank you, @karinazhou!
