### ISSUE TITLE
Rotate Always Encrypted column master key

### ISSUE THREAD

**Issue by myunghojung** [dotnet/SqlClient#1162]
Hello,

I'm running a .Net core app using ef core with a linux SQL server container on k8s. I'm trying to enable Always Encrypted on SQL server and also want to automatically rotate the encryption key. Based on my research, it seems that linux container works with Azure Key Vault as key provider.
https://www.nuget.org/packages/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider/

Is there a way to programmatically rotate the column master key?

Thanks,
Myungho

**Comment by johnnypham** [comment]
Hi @myunghojung, yes, column master key rotation can be done programmatically. See [ALTER COLUMN ENCRYPTION KEY](https://docs.microsoft.com/en-us/sql/t-sql/statements/alter-column-encryption-key-transact-sql?view=sql-server-ver15) for more details.

**Comment by myunghojung** [comment]
Hi @johnnypham, thank you for sharing the link. I read up the doc but I still don't quite understand how to rotate column master key with the SQL statement. Do you mean that I should create a new column master key and update existing column encryption keys to be encrypted by the master key? Also, I need to integrate it with EF core.

**Comment by johnnypham** [comment]
You would first create a new column master key with `CREATE COLUMN MASTER KEY`:
```tsql
CREATE COLUMN MASTER KEY MyNewCMK  
WITH (  
    KEY_STORE_PROVIDER_NAME = N'AZURE_KEY_VAULT',  
    KEY_PATH = N'https://myvault.vault.azure.net:443/keys/MyCMK/4c05f1a41b12488f9cba2ea964b6a700');
    ENCLAVE_COMPUTATIONS (SIGNATURE = 0xA80F5B123F5E092FFBD6014FC222...)
  );
```
Each column encryption key object in the database can have two encrypted values, each value being protected by a different CMK. You can add a new encrypted value with `ALTER COLUMN ENCRYPTION KEY`:
```tsql
ALTER COLUMN ENCRYPTION KEY MyCEK  
ADD VALUE  
(  
    COLUMN_MASTER_KEY = MyNewCMK  ,   
    ALGORITHM = 'RSA_OAEP',   
    ENCRYPTED_VALUE = 0x016E00000163007500720072006500...
);  
GO  
```
Then you drop the encrypted value protected by the old CMK:

```tsql
ALTER COLUMN ENCRYPTION KEY MyCEK  
DROP VALUE  
(  
    COLUMN_MASTER_KEY = MyOldCMK  
);  
GO  
```
The new encrypted CEK value and CMK signature should be generated using the corresponding methods of a key store provider, in your case [SqlColumnEncryptionAzureKeyVaultProvider](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.alwaysencrypted.azurekeyvaultprovider.sqlcolumnencryptionazurekeyvaultprovider?view=akvprovider-dotnet-core-3.0).

In EF Core, I suppose you would have to execute the raw SQL.

**Comment by myunghojung** [comment]
@johnnypham Thank you! I'll try.
