### ISSUE TITLE
SqlClient support for Windows on ARM32 for IoT scenarios

### ISSUE THREAD

**Issue by divega** [dotnet/SqlClient#117]
Currently there is no native implementation of SNI for ARM32. 

I am creating this issue to track this because it is one of the platforms supported by .NET Core for IoT scenarios. We don't have data on customer demand to estimate the priority, so this can be in the backlog.

If you try to use SqlClient on this platforms, as shown in https://github.com/dotnet/corefx/issues/33999, you get a TypeInitializationException.

In the future, support could be provided, by either shipping a native implementation or using the managed implementation. At least, SqlClient could ship with a shim that throws PlatformNotSupportedException for a more graceful experience.

**Comment by ViktorHofer** [comment]
We do have an arm based sni.dll:

```
Dump of file sni.dll

PE signature found

File Type: DLL

FILE HEADER VALUES
             1C4 machine (ARM)
```

https://www.nuget.org/packages/System.Data.SqlClient.sni-arm/4.0.0-beta-23225. That said, that package has a win7 specific RID.

**Comment by cheenamalhotra** [comment]
We recently released support for ARM for .NET Core and .NET Standard in Microsoft.Data.SqlClient [v2.0.0-preview4](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.0.0-preview4.20142.4). Closing the issue as addressed.
