### ISSUE TITLE
Unkown exception after upgrading to .Net 5

### ISSUE THREAD

**Issue by kewinbrand** [dotnet/SqlClient#1171]
After upgrading to .NET 5 and consequently updating Microsoft.Data.SqlClient, we started to see strange errors related to the package. The call stack is very  poor and I am not sure how to reproduce it.

```
Exception message:System.AggregateException
A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)

Stack trace: System.NullReferenceException: Object reference not set to an instance of an object.
  ?, in void SNIPacket.ReadFromStreamAsync(Stream stream, SNIAsyncCallback callback)
  ?, in uint SNITCPHandle.ReceiveAsync(ref SNIPacket packet)
  ?, in uint SNIMarsConnection.ReceiveAsync(ref SNIPacket packet)
  ?, in void SNIMarsConnection.HandleReceiveComplete(SNIPacket packet, uint sniErrorCode)
  ?, in void Task.ExecuteWithThreadLocal(ref Task currentTaskSlot, Thread threadPoolThread)
```

### Further technical details
Microsoft.Data.SqlClient version: 2.0.20168.4
.NET target: .NET 5.0.5
SQL Server version: SQL Server 2019
Operating system: Docker, Linux 5.4.17-2011.5.3.el8uek.x86_64 #2 SMP Wed Jul 29 22:09:11 PDT 2020

**Comment by ErikEJ** [comment]
Have you tried version 3?

**Comment by JRahnama** [comment]
Hi @kewinbrand. If the application setup allows, can you try your application with `MARS` set to `false` and also as @ErikEJ mentioned try to update to the [latest version](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0) please?
If the issue persist can you provide a sample repro app as well?

**Comment by kewinbrand** [comment]
Hi,

**Comment by kewinbrand** [comment]
I closed the issue unintentionally.

Will update the packages and report in a few days. Just to show how sporadic the error is
![image](https://user-images.githubusercontent.com/33696153/125954400-29cc3c75-b84a-4052-b388-d81e8044b35f.png)

**Comment by cheenamalhotra** [comment]
Hi @kewinbrand 

The driver version you're using is a non-LTS and is Out of Support. Also this issue had been fixed in v2.1 (ref #692).

Please upgrade to either v2.1 or v3.0.

**Comment by kewinbrand** [comment]
I don't reference the package manually. I see that Microsoft.EntityFrameworkCore.SqlServer uses Microsoft.Data.SqlClient@2.0.1. Should I raise a issue to them?
![image](https://user-images.githubusercontent.com/33696153/125983066-e671f99c-2676-4b92-a905-9899b801e92b.png)

**Comment by ErikEJ** [comment]
Just add an explicit packagereference to the newer version

https://erikej.github.io/efcore/sqlclient/2020/03/22/update_mds.html

**Comment by ErikEJ** [comment]
Sadly EF Core 5 still depends on 2.0.1.

**Comment by cheenamalhotra** [comment]
@kewinbrand do you have any further questions?
I'm hoping referencing to a newer version resolved your issue?

**Comment by kewinbrand** [comment]
@cheenamalhotra the problem has gone away after referencing the package
i still don't believe ef core was released with such problem...

**Comment by ErikEJ** [comment]
@kewinbrand far from all customers use the managed SNI layer, it is only applicable to non- Windows platforms
