### ISSUE TITLE
Unable to set values for SqlRetryLogicOption when using netstandard2.1 or netstandard2.0 via Powershell 7.1.3

### ISSUE THREAD

**Issue by cricketthomas** [dotnet/SqlClient#1180]
### Describe the bug
Unable to set retry logic options when using SqlClient through powershell 7.1.3. I have tried all the libraries and the only one that seems to work is net 4.6.1 which works as expected, however, netstandard2.1 or 2.0 do not work.

```
Exception message:
MethodInvocationException: Exception calling "CreateExponentialRetryProvider" with "1" argument(s): "Object reference not set to an instance of an object."
```

### To reproduce
Download the 3.0.0 assemblies, and load in the netstandard2.1 SqlClient dll.
Try to create the SqlRetryLogicOption, then the SqlConfigurableRetryFactory. You cannot set any of the retry options, which leads to the null reference exception when calling the CreateExponentialRetryProvider() method.

```powershell
Add-Type -LiteralPath .\lib\netstandard21\Microsoft.Data.SqlClient.dll

[System.AppContext]::SetSwitch("Switch.Microsoft.Data.SqlClient.EnableRetryLogic", $true);

$retryOptions = [Microsoft.Data.SqlClient.SqlRetryLogicOption]@{
    NumberOfTries          = 5;
    DeltaTime              = [TimeSpan]::FromSeconds(1)
    MaxTimeInterval        = [TimeSpan]::FromSeconds(20)
    AuthorizedSqlCondition = $null
    TransientErrors  = $null
}


Write-Host $retryOptions

NumberOfTries          :
DeltaTime              :
MinTimeInterval        :
MaxTimeInterval        :
TransientErrors        :
AuthorizedSqlCondition :

# the retryOptions are empty, and cannot be set for some reason.

$retry = [Microsoft.Data.SqlClient.SqlConfigurableRetryFactory]::CreateExponentialRetryProvider($retryOptions)

MethodInvocationException: Exception calling "CreateExponentialRetryProvider" with "1" argument(s): "Object reference not set to an instance of an object."

```

### Expected behavior
Add-Type -LiteralPath .\lib\netstandard21\Microsoft.Data.SqlClient.dll
```powershell
[System.AppContext]::SetSwitch("Switch.Microsoft.Data.SqlClient.EnableRetryLogic", $true);

$retryOptions = [Microsoft.Data.SqlClient.SqlRetryLogicOption]@{
    NumberOfTries          = 5;
    DeltaTime              = [TimeSpan]::FromSeconds(1)
    MaxTimeInterval        = [TimeSpan]::FromSeconds(20)
    AuthorizedSqlCondition = $null
    TransientErrors  = $null
}



Write-Host $retryOptions

NumberOfTries          : 5
DeltaTime              : 00:00:00
MinTimeInterval        : 00:00:00
MaxTimeInterval        : 00:00:00
TransientErrors        :
AuthorizedSqlCondition :


$retry = [Microsoft.Data.SqlClient.SqlConfigurableRetryFactory]::CreateExponentialRetryProvider($retryOptions)

$retry 

Retrying RetryLogic
-------- ----------
         Microsoft.Data.SqlClient.SqlRetryLogic

```

### Further technical details
Microsoft.Data.SqlClient version: 3.0.
.NET target: (netstandard2.1)
Operating system:  Windows 10 (latest)

**Additional context**
This will work fine when using net461 dll, however, it fails with every other version when using pwsh 7.1.3

**Comment by Wraith2** [comment]
Netstandard isn't a platform and you need to have a platform specific assembly to use sqlclient because it needs to know which sni dll native component to use. You must restore against a netcore or netfx target to get a usable assembly.

**Comment by cheenamalhotra** [comment]
@cricketthomas 

Please do not use this DLL as they are fallback DLLs for platforms that cannot resolve runtime DLLs
_(applies to .NET Core and .NET Standard)_
`Add-Type -LiteralPath .\lib\netstandard21\Microsoft.Data.SqlClient.dll`

Official supported DLLs are in **runtimes** folder:
`Add-Type -LiteralPath .\runtimes\win\lib\netstandard2.1\Microsoft.Data.SqlClient.dll`

**Comment by cricketthomas** [comment]
yikes, lesson learned. thank you!
