### ISSUE TITLE
Timeline for Next Current or LTS Release

### ISSUE THREAD

**Issue by bdschaap** [dotnet/SqlClient#1184]
Do you have a timeline for the next Current or LTS release?  The DefaultAzureCredential feature in 3.0 helps support our use cases but I'm concerned about a [March 10, 2022 end of support date](https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver15#microsoftdatasqlclient-release-cadence) without knowing the timeline for the next Current or LTS release so that I'm able to plan for an upgrade.

**Comment by cheenamalhotra** [comment]
Hi @bdschaap 

Our stable (GA) releases are every 6 months, they're marked Current/LTS based on special considerations. But a new version would be available in around 6 months to replace Current releases.

**Comment by JRahnama** [comment]
@bdschaap Hi, feel free to close the issue if your question is answered and there is nothing more to add to this thread.
