### ISSUE TITLE
System.Data.SqlClient | UWP ARM Build

### ISSUE THREAD

**Issue by Kyagos** [dotnet/SqlClient#12]
## Win 10 IoT ARM Build

The .NET Core Foundation Libraries already got Builds for most common platforms and architectures.

Since the release of Windows 10 IoT Preview Version and announced support for Raspberry Pi Products many developers want to use it in a commercial way but the current build does not inherit the full core. The main issue with the current IoT-Build is the missing ability to connect to MS SQL Server and pass your requests. Using an additional WCF Service and communicate over REST-API is not the proper way to transfer Data in a company. 

So my request is to add a build of the .NET CORE on ARM for Windows 10 IoT usage on the github list or at least adding the ability to handle SQL for MS SQL Server.

**tl;dr**
No possibility to connect to MS SQL Server via UWP 
Should be implemented since Raspberry Pi 3 got Win 10 IoT and is rising interest for companies

Please consider:
According to the porting documentation and a missing branch for IoT ARM I am leaving this request/issue on the master page.
There is no other project handling my request

**Comment by cheenamalhotra** [comment]
@Kyagos 

We recently introduced support for ARM platform for .NET Core and .NET Standard in Microsoft.Data.SqlClient [v2.0.0-preview4](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.0.0-preview4.20142.4). I will close the enhancement request as addressed. Please give it a try and feel free to re-open if you have open concerns.
