### ISSUE TITLE
[Synapse SQL Pools] Make SQL Errors 42108 and 42109 retriable for logins

### ISSUE THREAD

**Issue by azaricstefan** [dotnet/SqlClient#1205]
We would like to make these 2 errors retriable for the logins.

- ErrorNumber: 42108 | Message: Can not connect to the SQL pool since it is paused. Please resume the SQL pool and try again.
- ErrorNumber: 42109 | Message: The SQL Pool is warming up. Please try again.

**Comment by JRahnama** [comment]
Hi @azaricstefan, can you elaborate a bit more please? What retry are we talking about? The retry Logic of the driver which was implemented recently?

**Comment by azaricstefan** [comment]
Yes, the one which was recently implemented.
