### ISSUE TITLE
SqlRetryLogicProvider.cs is missing ConfigureAwait(false) on it's awaits

### ISSUE THREAD

**Issue by alexander-webber** [dotnet/SqlClient#1207]
SqlRetryLogicProvider.cs is missing ConfigureAwait(false) on it's awaits which is causing us pains with async deadlocks in web contexts. Is this by design for some reason, if not could you add them, at the moment we have to roll our own, pretty much identical custom retry classes just to work around this issue.

**Comment by roji** [comment]
Note that the compiler now includes a [diagnostic](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007) to check for any await which isn't covered by ConfigureAwait(false) - it's a very good idea to enable this for any library. This is as simple as dropping the following in an .editorconfig into the solution:

```
# CA2007: Consider calling ConfigureAwait on the awaited task
dotnet_diagnostic.CA2007.severity = error
```

**Comment by DavoudEshtehari** [comment]
@alexander-webber I'd appreciate it if you could share a repro app for more investigation and finding other possible issues in the driver.

**Comment by cheenamalhotra** [comment]
Hi @alexander-webber 

PR #1220 shall address this issue.
