### ISSUE TITLE
Possible threading issues in version 3.0 when using Azure Managed Identity auth 

### ISSUE THREAD

**Issue by ccarpediem** [dotnet/SqlClient#1209]
After upgrading our app from Microsoft.Data.SqlClient 2.1.3 to version 3.0, our application simply seems to "freeze" upon opening any sql connection using Azure Managed Identity auth.  This did work in 2.1.3 and the connection does work if we change it to use SQL auth.  When it "freezes" there are no errors/exceptions thrown; it just hangs indefinitely.  The only diagnostic information directly available seems to be from the SQL Server (Azure SQL Managed Instance).  That error is Error: 33155, Severity: 20, State: 1 (A disconnect event was raised when server is waiting for Federated Authentication token.  This could be due to client close or server timeout expired).

I've created a very simple sample app to further diagnose the issue and my findings thus far are:
•	If you set the project to be a console app all works as expected with Managed Identity
•	If you set the project to be a WinForm app running the exact same code, it will experience the "freeze"
•	If you update the WinForm code to use "con.OpenAsync().Wait();" instead of "con.Open();" again all works without the freeze

Is this a known/expected issue?  While changing the connection to use OpenAsync() in a small sample app isn't a big deal, it is a much larger problem for huge legacy application with many modules so hoping this isn't expected behavior going forward.

### To reproduce
[WindowsFormsApp4.zip](https://github.com/dotnet/SqlClient/files/6976716/WindowsFormsApp4.zip)

### Further technical details
Microsoft.Data.SqlClient version: 3.0
Framework 4.7.2
SQL Server version: Azure SQL Managed Instance
SQL Authentication: Azure Managed Identity
Operating system: Windows 2019

<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Azure.Core" version="1.6.0" targetFramework="net472" />
  <package id="Azure.Identity" version="1.3.0" targetFramework="net472" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" targetFramework="net472" />
  <package id="Microsoft.Data.SqlClient" version="3.0.0" targetFramework="net472" />
  <package id="Microsoft.Data.SqlClient.SNI" version="3.0.0" targetFramework="net472" />
  <package id="Microsoft.Identity.Client" version="4.22.0" targetFramework="net472" />
  <package id="Microsoft.Identity.Client.Extensions.Msal" version="2.16.5" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="6.8.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Logging" version="6.8.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocols" version="6.8.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="6.8.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Tokens" version="6.8.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net472" />
  <package id="System.Configuration.ConfigurationManager" version="4.7.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.6.0" targetFramework="net472" />
  <package id="System.IdentityModel.Tokens.Jwt" version="6.8.0" targetFramework="net472" />
  <package id="System.Memory" version="4.5.4" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0" targetFramework="net472" />
  <package id="System.Security.AccessControl" version="4.7.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.ProtectedData" version="4.5.0" targetFramework="net472" />
  <package id="System.Security.Permissions" version="4.7.0" targetFramework="net472" />
  <package id="System.Security.Principal.Windows" version="4.7.0" targetFramework="net472" />
  <package id="System.Text.Encodings.Web" version="4.7.2" targetFramework="net472" />
  <package id="System.Text.Json" version="4.6.0" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.2" targetFramework="net472" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
</packages>

**Comment by cheenamalhotra** [comment]
This is a strange behavior and not expected.
`OpenAsync()` and `Open()` should ideally not have any change in behavior, but we'll test out your repro to confirm that.

Could you also confirm:
- Your client is an Azure VM (as that's the only way you can get token from Managed Identity)
- Is your Azure DB Server configured for Proxy/Redirect connection policy? (You can find that in Azure SQL Server > Firewall settings)
- Does changing that to redirect resolve the issue?

**Comment by ccarpediem** [comment]
- I can confirm that yes my testing is on an Azure VM properly configured for Managed Identity and the Managed Identity is properly configured on the SQL Managed Instance to have rights to login (validated by the fact it does work properly if using OpenAsync().
-The SQL Managed Instance is currently configured to use the Redirect option.
- Changing to Proxy option did not impact the results

**Comment by ccarpediem** [comment]
I've also added a SQLClient EventListener to my sample code (attached as Form1.txt).  The results from running Open() vs OpenAsync() are also attached.  I'm not sure it really help, but figure it cannot hurt.

[OpenAsync_Log.txt](https://github.com/dotnet/SqlClient/files/6977319/OpenAsync_Log.txt)
[Open_Log.txt](https://github.com/dotnet/SqlClient/files/6977320/Open_Log.txt)
[Form1.txt](https://github.com/dotnet/SqlClient/files/6977310/Form1.txt)

**Comment by AnKor1985** [comment]
Judging by the trace that stops on "Generating federated authentication token", I believe this line in SqlInternalConnectionTds.GetFedAuthToken is very likely to cause a deadlock because of the blocking call to .Result:

 _fedAuthToken = authProvider.AcquireTokenAsync(authParamsBuilder).Result.ToSqlFedAuthToken()

By the way, this seems to be the same issue: https://github.com/dotnet/SqlClient/issues/1138

**Comment by ccarpediem** [comment]
Thanks @AnKor1985!  @cheenamalhotra yes I think it may have been a change committed as part to https://github.com/dotnet/SqlClient/pull/1010 which changed how those these are called within SqlInternalConnectionTds as shown below.

![image](https://user-images.githubusercontent.com/9822163/129616848-69b57e05-9e91-4657-9cd9-50134d651963.png)

**Comment by cheenamalhotra** [comment]
Hi @ccarpediem 

Yes I believe that exact change caused issues on Windows Forms. I was investigating it too and just opened PR #1213 with necessary changes, which we'll include in next release and plan to hotfix 3.0.

**Comment by janecosham** [comment]
Hi @cheenamalhotra 

I'm currently working on a release which is switching from System.Data.SqlClient to Microsoft.Data.SqlClient using 3.0. Everything is working fine except I just found this issue with our WinForms tools which will block the release. 
You said this is planned to be in a hotfix - can you share expected timing on this? Is it quite likely to be in the next 2 weeks for example? If it is then we can wait, but if it is not likely to be in the next 2 weeks then that's ok too and we will downgrade to 2.1.3.

Thanks!

**Comment by cheenamalhotra** [comment]
I will be likely in next 2-3 weeks.
Backport PRs are under preparation.
