### ISSUE TITLE
App service down: Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.WriteAsyncCallback(SNIPacket packet, UInt32 sniError)

### ISSUE THREAD

**Issue by deivyd321** [dotnet/SqlClient#1212]
After deployment app service was completely down but after making restart it started working again. Though this startup issue costs a lot and we don't know what may cause the issue.

Here is _2021_08_16_pl0mdlwk00000L_default_docker.log_ the only place we found any relatable logs.

```
  _____                               
  /  _  \ __________ _________   ____  
 /  /_\  \___   /  |  \_  __ \_/ __ \ 
/    |    \/    /|  |  /|  | \/\  ___/ 
\____|__  /_____ \____/ |__|    \___  >
        \/      \/                  \/ 
A P P   S E R V I C E   O N   L I N U X

Documentation: http://aka.ms/webapp-linux
Dotnet quickstart: https://aka.ms/dotnet-qs
ASP .NETCore Version: 5.0.5
Note: Any data outside '/home' is not persisted
Running oryx create-script -appPath /home/site/wwwroot -output /opt/startup/startup.sh -defaultAppFilePath /defaulthome/hostingstart/hostingstart.dll     -bindPort 8080 -userStartupCommand '' 
Cound not find build manifest file at '/home/site/wwwroot/oryx-manifest.toml'
Could not find operation ID in manifest. Generating an operation id...
Build Operation ID: eca99fad-1e03-4eb5-9af4-4d574cec3a49
Writing output script to '/opt/startup/startup.sh'
Trying to find the startup DLL name...
Found the startup D name: Bonanza.Api.dll
Running the command: dotnet "Bonanza.Api.dll"
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.WriteAsyncCallback(SNIPacket packet, UInt32 sniError)
   at Microsoft.Data.SqlClient.SNI.SNIPacket.WriteToStreamAsync(Stream stream, SNIAsyncCallback callback, SNIProviders provider)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
Could not open output /home/logs/dumps/coredump.787653051a83.28.1629112327: 2 No such file or directory
Gathering state for process 28 dotnet
Writing minidump with heap to file /home/logs/dumps/coredump.787653051a83.28.1629112327
/opt/startup/startup.sh: line 12:    28 Aborted                 (core dumped) dotnet "Bonanza.Api.dll"
```

ASP.NET Core 5
App Service Linux
Azure Cache for Redis 6

**Comment by roji** [comment]
This looks like a NullReferenceException within SqlClient, so transferred to this repo. 

@deivyd321 is this something you can trigger/reproduce? Can you submit a minimal code sample with instructions on how to make this happen?

**Comment by ajcvickers** [comment]
Concurrent use of a single SqlConnection?

**Comment by roji** [comment]
Could be, though AFAIK SqlClient is supposed to protect against that and throw, not NRE...

**Comment by ajcvickers** [comment]
@roji 

> Could be, though AFAIK SqlClient is supposed to protect against that and throw, not NRE...

Really? How do they do this without loosing the advantage of not being thread-safe in the first place? Unless it's just a non-thread-safe check, like we do in EF, in which case NREs are certainly possible.

**Comment by roji** [comment]
All I know is that in general when I try to execute a command on a busy connection, it throws a clear message... No idea about the implementation; Npgsql uses a SemaphoreSlim internally to do that (though the implementation is far from air-tight).

**Comment by vonzshik** [comment]
To me, it looks like the exception might be thrown from here:

https://github.com/dotnet/SqlClient/blob/104e9a698cee44c5467bdf2cca457cba88c18a1d/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs#L117

Specifically, `_sessionHandle` can be not null before it's checked for null, but changed to null immediately afterwards.

**Comment by JRahnama** [comment]
@deivyd321 Hi, 

1. Do you have MARS set to true in your connection string?
2. Is it possible to provide a sample repro? A minimal code to reproduce the issue. (This includes all your connection string options, but password or sensitive information )

I have seen a similar pattern in issue #422 which happens on Linux with MARS set to true with more than 22 Parallel calls.  Thread starvation happens and the stream  comes null (The variable `stream` at `WriteToStreamAsync` in SNIPacket class at line 291) and it causes the exception to be thrown. 

Same pattern works fine on Windows.

For work around we have two options:

1.  Increase Thread Pool size, or
2.  If possible set MARS to false.

**Comment by deivyd321** [comment]
@JRahnama Hi,

1. No, my connection string is like: `bonanzasample.redis.cache.windows.net:6380,password={password},ssl=True,abortConnect=False`
2.

What I didn't mention first is that probably this issue is very relatable to `Redis`. I am using [AspNetCoreLimit ](https://github.com/stefanprodan/AspNetCoreRateLimit) nuget package and it happened after deployment.

My web system has two app services with multiple instances. First App Service is for handling user requests, other for domain events and background jobs. The thing is that main app service was still functioning but all requests with rate limiting had this exception:

`No connection is active/available to service this operation: EVAL; It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code. ConnectTimeout, mc: 1/1/0, mgr: 10 of 10 available, clientName: 6e4de34bbe4e, IOCP: (Busy=0,Free=1000,Min=4,Max=1000), WORKER: (Busy=1,Free=32766,Min=4,Max=32767), v: 2.2.4.27433 It was not possible to connect to the redis server(s). Error connecting right now. To allow this multiplexer to continue retrying until it's able to connect, use abortConnect=false in your connection string or AbortOnConnectFail=false; in your code. ConnectTimeout` 

I checked if all configs are correct but didn't find anything wrong. Also I have similar test environment which works fine.

Regarding background jobs App Service it was completely down as mentioned before. I am wondering can't it happen because my redis cache plan is too basic? But then I would be expecting some kind of different exception messages or some Azure recommendations. Also, can't it be related to ssl=true/false configs. I have enabled ssl in redis both in test and prod environments.

Here is code with removed unnecessary parts.
```
public void ConfigureServices(IServiceCollection services)
{
	...

    services.AddDistributedMemoryCache(); 

    services.Configure<ClientRateLimitOptions>(Configuration.GetSection("ClientRateLimiting"));

    var redisOptions = ConfigurationOptions.Parse(Configuration["Redis_Secret"]);
    services.AddSingleton<IConnectionMultiplexer>(provider => ConnectionMultiplexer.Connect(redisOptions));
    services.AddRedisRateLimiting();

    services.Configure<FormOptions>(options =>
    {
        options.MultipartBodyLengthLimit = TenMbInBytes;
    });

    services.AddSingleton<IRateLimitConfiguration, BonanzaRateLimitConfiguration>();
}


public void Configure(IApplicationBuilder app, BonanzaContext context, IServiceProvider serviceProvider)
{
	...
	
    app.UseClientRateLimiting();

    app.UseEndpoints(endpoints =>
    {
        ...
    });
}
```

**Comment by ErikEJ** [comment]
bonanzasample.redis.cache.windows.net:6380,password={password},ssl=True,abortConnect=False is not a SQL Server connection string.

**Comment by cheenamalhotra** [comment]
@deivyd321 

> Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.WriteAsyncCallback(SNIPacket packet, UInt32 sniError)

I think you might be working with an older driver version where we used to have this error, please add package reference to latest driver version[ v2.1.3](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.3) or [v3.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/3.0.0) to get benefit from recent improvements and let us know if that resolves your issue.

**Comment by deivyd321** [comment]
Thanks for replies. The issue was that in Redis resource I have selected option "Connection through private endpoint" but tried to use a simple connection string.
