### ISSUE TITLE
Copy-paste error in GenericTDSServerSession?

### ISSUE THREAD

**Issue by MaceWindu** [dotnet/SqlClient#1217]
### Describe the bug
I've found this piece of code which looks like a copy-paste error:
https://github.com/dotnet/SqlClient/blob/2c2f100d8ab9a1f6ee8c048a260d77e6a738e1e7/src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.Servers/GenericTDSServerSession.cs#L332

```cs
userOptionsOption.NumericRoundAbort = ImplicitTransactions;
```

Looks like it should be
```cs
userOptionsOption.NumericRoundAbort = NumericRoundAbort;
```

**Comment by MaceWindu** [comment]
Actually it is in test folder, so probably not production code?

**Comment by JRahnama** [comment]
@MaceWindu Hi thanks for bringing this up to our attention. We will look into that shortly.
