### ISSUE TITLE
BinSkim fails regarding 'Microsoft.Data.SqlClient.SNI.x64.dll' because of "Pdb is stripped of cv (CodeView) info."

### ISSUE THREAD

**Issue by yangyud-cn** [dotnet/SqlClient#1227]
### Describe the bug

The newer version of [BinSkim](https://github.com/microsoft/binskim) v1.7.5 asks for full debug info in PDB.

It fails on Microsoft.Data.SqlClient ver 3.0.0 with following error.

        {
          "id": "ERR997.ExceptionLoadingPdb",
          "ruleId": "BA2002",
          "physicalLocation": {
            "uri": file:///D:/src/Hilo1/Release/Debug/x64/GenevaAction/Microsoft.Data.SqlClient.SNI.x64.dll
          },
          "message": "'Microsoft.Data.SqlClient.SNI.x64.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded (Pdb is stripped of cv (CodeView) info).",
          "level": "error"
        },

### To reproduce
Get the latest [binskim](https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/), unpack the nuget and run it over an project with "Microsoft.Data.SqlClient" 3.0.0 or later.

Eg, create a .net core 3.1 project with reference to Microsoft.Data.SqlClient, build debug, then
```
cd E:\Temp\microsoft.codeanalysis.binskim.1.9.0-prerelease1\tools\netcoreapp3.1\win-x64
cd <your project>\bin\Debug\netcoreapp3.1
e:BinSkim.exe analyze --config default --insert Hashes --statistics --sarif-output-version OneZeroZero --output E:\Test\binskim\binskim.sarif --trace PdbLoad    --force *
```

### Further technical details
Microsoft.Data.SqlClient version: 3.0.0
.NET target: Core 3.1
SQL Server version: N/A
Operating system: Any Windows

**Additional context**

**Comment by JRahnama** [comment]
@yangyud-cn any update on this issue?

**Comment by cheenamalhotra** [comment]
Closing this issue, as we discussed internally.
