### ISSUE TITLE
Only loading one SNI.dll and not two into build directory

### ISSUE THREAD

**Issue by jalley3** [dotnet/SqlClient#1235]
### Describe the bug
In the README for this repo, it says explicitly: For the .NET Framework driver on Windows, a package reference to Microsoft.Data.SqlClient.SNI loads native Microsoft.Data.SqlClient.SNI.x64.dll and Microsoft.Data.SqlClient.SNI.x86.dll libraries into the client's build directories.

However, on my machine a package reference to that only loads Microsoft.Data.SqlClient.SNI.dll, not one for each bitness. This is causing the following error when I attempt to open a connection:

```
Exception message: DllNotFoundException: Unable to load DLL 'Microsoft.Data.SqlClient.SNI.x64.dll'
Stack trace:
```

### Further technical details
Microsoft.Data.SqlClient version:  2.1.1 
.NET target: Framework 4.6
SQL Server version: SS2017
Operating system: windows 10

**Additional context**

**Comment by cheenamalhotra** [comment]
@jalley3 

Could you please confirm the below mentioned NuGet Package is included in list of your packages as that is what the driver [Microsoft.Data.SqlClient v2.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.1) depends on for .NET Framework:

https://www.fuget.org/packages/Microsoft.Data.SqlClient.SNI/2.1.1

**Comment by jalley3** [comment]
![image](https://user-images.githubusercontent.com/17911817/131399780-d9dd2159-8dcf-4af0-84c2-0538bcba571c.png)

note that i only added the runtime package to help with trouble shooting, it is only with the runtime package that i actually get the  Microsoft.Data.SqlClient.SNI.dll in my build folder (if i rename that file to Microsoft.Data.SqlClient.SNI.x64.dll then everything works as intended but that is not a viable solution)

**Comment by jalley3** [comment]
Note in the above image that it is indeed 2.1.1

**Comment by cheenamalhotra** [comment]
SNI.runtime package applies to .NET Core 2.1+ or .NET Standard 2.0+ only, so you should not use that.
What is your target framework here? Can you provide a repro app to try?

**Comment by jalley3** [comment]
We are using .NET Framework 4.6 ... thanks for the heads up about the runtime package. Without it, I do not get ANY sni dll's in my build directory. 

Im not sure what you would like for me to give to provide a repro app...the code that we are using where it is failing is simple enough:

```
using (var connection = new SqlConnection(databaseFreeconnectionString))
                    {
                        connection.Open();
                        var databases = connection.GetSchema("Databases");
                        return databases.Rows.OfType<DataRow>().Select(i => i[0].ToString());
                    }
```

Note we have using Microsoft.Data.SqlClient; at the top, so i know it is not trying to use System.Data.SqlClient.

**Comment by cheenamalhotra** [comment]
I really just need your application architecture and build scripts (if any) to reproduce application design.

**Comment by jalley3** [comment]
forgive me for being dense, but what do you mean by my application architecture? Its an app where a user enters a connection string and we use that to connect to a database. The driver application is x64. although the build includes several projects that can target any platform. 

I can send app.config/csproj/sln files if that is helpful although id probably rather not post those publicly here.

**Comment by jalley3** [comment]
I was missing the package reference in the executable project and only had it in one of the sub projects. Thank you for your help!

**Comment by cheenamalhotra** [comment]
Sounds good! Feel free to close if there are no further queries :)
