### ISSUE TITLE
Possible optimization in DbDataReader.GetStream

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/SqlClient#124]
Do you think if it is worth using System.Buffers.ArrayPool<byte> instead of always allocating byte[4096] in default implementation of DbDataReader.GetStream() ?

https://github.com/dotnet/corefx/blob/46d9f33d96a1db41a9634b84dd68256db2eeed4f/src/System.Data.Common/src/System/Data/Common/DbDataReader.cs#L147

**Comment by Wraith2** [comment]
Possibly, but I would expect each provider to override it with a performance tuned implementation as SqlClient [does](https://github.com/dotnet/corefx/blob/e0c0765b7867600e5458d0d122cf8f4bbe2484bd/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlDataReader.cs#L1418). In ths SqlClient specific case I've made some optimizations on streams already in https://github.com/dotnet/corefx/pull/35927 and if there are more that can be seen from specific test cases i'll probably add them.

**Comment by TrayanZapryanov** [comment]
Unfortunately neither MySQL or Oracle done it :(.

**Comment by Wraith2** [comment]
Understandable if a bit sad given their owner and platform preferences. You can try https://github.com/mysql-net/MySqlConnector for mysql it isn't first party but it's modern actively developed and the authors are interested in good performance.

**Comment by TrayanZapryanov** [comment]
Thank you.
I will redirect this proposal to MySQL.
