### ISSUE TITLE
.NET 5.0 | Implement the ADO.NET transaction savepoint APIs

### ISSUE THREAD

**Issue by roji** [dotnet/SqlClient#1256]
SqlTransaction already exposes APIs for managing transactions, but matching general ones were introduced into System.Data in .NET 5.0. SqlClient mostly needs to just override these properties and call the existing logic.

**Comment by JRahnama** [comment]
Hi @roji, I don't think we can make this ready for the next release on September 20st, but we will look into this soon.

**Comment by David-Engel** [comment]
This was done as part of #1704
