### ISSUE TITLE
.NET App service encountered authentication error when connected to Azure SQL DB via federation account(sqlclient)

### ISSUE THREAD

**Issue by tianmoumou** [dotnet/SqlClient#1257]
I'm the support engineer from Microsoft.
Here we got some problem using this package: Our application connecting Azure sql server using SqlConnection works fine in local environment, but failed in Azure web app. The contained user account in the DB connection string has enabled federation(ADFS). We have found the problem is caused by the **target relying party**( our account is in China, but the party is in global). 
So it should be some environment checking in sqlclient code to decide the target relying party.
Now our customer can't use this package to deploy to Azure, it's really a problem to them.
Please help to check this issue, thanks!

**Comment by tianmoumou** [comment]
please feel free to contact me in Teams, my alias is wenxitian.

**Comment by yannashi** [comment]
Same issue has been reproduced in my environment, any one could help on this?

**Comment by JRahnama** [comment]
@tianmoumou, we had several similar issues related tot his topic . I am not aware of environment checking in the driver.
Can you give me more details:

1. Are you using Microsoft.Data.SqlClient or System.Data.SqlClient and what version?
2. Can you send a sample of your connection string as well?
3. Were the client able to connect before?

**Comment by tianmoumou** [comment]
Hi, @JRahnama, sorry for the late reply. Problem is still going on. Here is the answer to your questions:
Are you using Microsoft.Data.SqlClient or System.Data.SqlClient and what version? System.Data.SqlClient
Can you send a sample of your connection string as well? 
public static string ConnectionString = "Server=tcp:vincyserver.database.chinacloudapi.cn,1433;Initial Catalog=vincydb;Persist Security Info=False;User ID=XXXXXX;Password=XXXXXX;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication=Active Directory Password";(AAD way to connect sql, and the account is setting under ADFS authentication.)

Were the client able to connect before? In Azure no， never.
What OS /platform are being used? It can be reproduced by us, so OS/platform maybe not related. And the problem is happening in Azure. In local side, it works.

**Comment by JRahnama** [comment]
@tianmoumou Users should be able to use AAD authentication in Microsoft.Data.SqlClient now in Mooncake(China).

**Comment by JRahnama** [comment]
I am closing this as this is confirmed that MDS is working in Mooncake(China).
