### ISSUE TITLE
The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.

### ISSUE THREAD

**Issue by DavidKlempfner** [dotnet/SqlClient#1262]
I'm getting "The incoming tabular data stream (TDS) protocol stream is incorrect. The MARS TDS header contained errors.".

I'm using .NET Core 2.1, with Dapper 1.60.6 which uses System.Data.SqlClient 4.5.1.

https://github.com/dotnet/SqlClient/issues/85#issuecomment-857012939 says:
"Closing as issue has been fixed and backported to all versions." - however this is not true as we are still getting this issue.

When will this be fixed?

**Comment by ErikEJ** [comment]
.NET Core 2.1 is out of support!

**Comment by Wraith2** [comment]
> .NET Core 2.1 is out of support!

Additionally if you wanted someone to investigate the cause of the problem you should provide a way to reproduce it.

**Comment by JRahnama** [comment]
@DavidKlempfner as @ErikEJ has mentioned support for Net Core 2.1 was dropped on August 21st and it wont be receiving any update patches. 

As @Wraith2 mentioned can you provide a simple repro application that we can look at the issue as well?

**Comment by cheenamalhotra** [comment]
> I'm using .NET Core 2.1, with Dapper 1.60.6 which uses System.Data.SqlClient 4.5.1.

Please use v4.8.2+ of [System.Data.SqlClient](https://www.nuget.org/packages/system.Data.SqlClient) to get the fix.

**Comment by JRahnama** [comment]
Closing the issue as it is Backported to `System.Data.SqlClient` in .Net Core.
