### ISSUE TITLE
Multiple Sqlconnections with Same connectionstring enlisting into distributed transaction

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/SqlClient#13]
@leo12chandu commented on [Fri Aug 24 2018](https://github.com/dotnet/core/issues/1892)

# Issue Title
Multiple Sqlconnections with Same connectionstring enlisting into distributed transaction.

# General
When I open 2 SqlConnections as below and enlist each of them in the same committable transaction, it enlists as a distributed transaction. I would've thought if its the same connection string, we don't need to enlist as distributed transaction.

As a side note, distributed transactions are not supported in .NET Core as of 2.1. they seem to throw PlatformNotSupportedException(). Do you have plans of providing something similar to MSDTC in the future that works on linux boxes too? or is there other recommendations for alternatives to MSDTC to run with distributed transactions in .net core?

Code to reproduce:-
```c#
 TransactionOptions options = new TransactionOptions();
            options.IsolationLevel = System.Transactions.IsolationLevel.ReadCommitted;
            options.Timeout = TransactionManager.MaximumTimeout;

            var tran = CommittableTransaction(options);
            using (SqlConnection connection = GetSqlConnection("cn1"))
            {
                connection.Open();
                connection.EnlistTransaction(tran);
            }
            using (SqlConnection connection = GetSqlConnection("cn1"))
            {
                connection.Open();
                connection.EnlistTransaction(tran);
            }
            tran.Commit();
```

**Comment by roji** [comment]
One note: IIRC if you open two connections with an identical connection string, you are not supposed to get promoted to a distributed transaction as long as the connections aren't alive at the same time. In other words, when you close the first connection, SqlClient should be stashing the physical connection  in a special place because it knows that it still has pending changes that are part of an uncommitted transaction (and the physical connection can't be reused for anything else). If another open request comes in for the same conn string it returns that connection.

I'm used to seeing this pattern with TransactionScope and now with an explicit CommittableTransaction above, it may be worth confirming this.

```c#
using (var scope = new TransactionScope())
{
    using (var conn1 = new SqlConnection(...))
    {
        // perform stuff
    }

    using (var conn2 = new SqlConnection(...))
    {
        // perform stuff
    }
    scope.Complete();
}
```

**Comment by pulla2908** [comment]
> I'm facing a problem but I don't know if it's related to this or not!?
> @karelz @keeratsingh , Any ideas?
> 
> ```cs
> static async Task Main(string[] args)
> {
>     using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
>     {
>         await Task.WhenAll(Query(), Query());
> 
>         transaction.Complete();
>     }
> }
> 
> private static async Task Query()
> {
>     using (var c = new SqlConnection(DataContext.ConnectionString))
>     {
>         await c.OpenAsync();
>         /* ... */
>     }
> }
> ```

@ans-ashkan have you been able to solve your issue? I have exactly the same code and same problem. This throws in .NET Core ("This platform does not support distributed transcation") but works with .NET Full Framework.

**Comment by SimonCropp** [comment]
@roji your comment seems to imply this behavior is not by-design? or do i misunderstand you?

**Comment by SimonCropp** [comment]
@roji 

>  If the tasks were executed in serial, a distributed transaction shouldn't be necessary.

and that is the scenario in the issue description.
