### ISSUE TITLE
Why the method don't cast the ToString() automatically?

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/SqlClient#1331]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Why-the-method-dont-cast-the-ToString/1534501)._

---
Why the method don't cast the ToString() automatically?

```
            fcSqlConnectionStringBuilder = new SqlConnectionStringBuilder();
            fcSqlConnectionStringBuilder.DataSource = host;
            fcSqlConnectionStringBuilder.UserID = "sa";
            fcSqlConnectionStringBuilder.Password = "[Redacted]";
            fcSqlConnectionStringBuilder.InitialCatalog = FcDb.FcDefaultDbName;
            fcSqlConnection = new SqlConnection(fcSqlConnectionStringBuilder); <-- Error, need write . ToString()

```

---
#### Feedback Bot on 9/22/2021, 00:02 AM: 

We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.

**Comment by cheenamalhotra** [comment]
As @roji mentioned, this is by design.
