### ISSUE TITLE
System.PlatformNotSupportedException when loading dll at run-time

### ISSUE THREAD

**Issue by bhaeussermann** [dotnet/SqlClient#1347]
### Describe the bug
A .NET 5 project references the `Microsoft.Data.SqlClient` NuGet package. I load the dll of this project at run-time using `AssemblyLoadContext` as follows:

```
var assembly = AssemblyLoadContext.Default.LoadFromAssemblyPath(Path.Combine(pluginFolderPath, "MyLibrary.dll"));
AssemblyLoadContext.Default.Resolving += (context, assemblyName) =>
{
    if (assemblyName.Name == "Microsoft.Data.SqlClient")
    {
        return context.LoadFromAssemblyPath(Path.Combine(pluginFolderPath, "Microsoft.Data.SqlClient.dll"));
    }
    else
    {
        return null;
    }
}
```

and instantiate a class from the MyLibrary assembly to start calling into it.
As soon as a SqlClient class is called (eg. `var connection = new Microsoft.Data.SqlClient.SqlConnection("A")`) from within MyLibrary, the following exception occurs:

```
**System.PlatformNotSupportedException**
Exception message: Strings.PlatformNotSupported_DataSqlClient
Stack trace: 
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at ClassLibrary1.Worker.DoWork() in C:\Projects\AdHoc\TestSqlClientLoader\ClassLibrary1\Worker.cs:line 9
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid1[T0](CallSite site, T0 arg0)
   at ConsoleApp1.Program.Main(String[] args) in C:\Projects\AdHoc\TestSqlClientLoader\ConsoleApp1\Program.cs:line 32
```

### To reproduce
See the attached Visual Studio solution. Run the ConsoleApp1 project to see the error.

### Expected behavior
We can successfully use `Microsoft.Data.SqlClient` from a dynamically-loaded library without having to include it as a dependency of the main application.

### Further technical details
Microsoft.Data.SqlClient version: 3.0.1
.NET target: .NET 5.0
SQL Server version: N/A
Operating system: Windows 10 Enterprise

[TestSqlClientLoader.zip](https://github.com/dotnet/SqlClient/files/7346193/TestSqlClientLoader.zip)

**Comment by JRahnama** [comment]
@bhaeussermann thanks for bringing this up. Have you tried adding below code inside `AssemblyLoadContext.Default.Resolving`
```C#
                IReadOnlyList<RuntimeLibrary> dependencies = DependencyContext.Default.RuntimeLibraries;
                foreach(var lib in dependencies)
                {
                    return context.LoadFromAssemblyName(new AssemblyName(lib.Name));
                }
```

**Comment by cheenamalhotra** [comment]
@bhaeussermann 

Which path are you loading DLLs from?
Please note, the `lib\` folder DLLs are fallback not-supported DLLs for .NET Core and .NET Standard whereas the `runtime` DLLs are the official platform compatible DLLs that one should be able to work with.

**Comment by cheenamalhotra** [comment]
I tried your solution, the "runtime" DLLs are downloaded in "..\TestSqlClientLoader\ClassLibrary1\bin\Debug\net5.0\runtimes\win\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll" folder, please load from that location and try again.

This is what is loaded by .NET Runtime when you run .NET Core app. This applicable DLL depends on your OS and your target framework and is accordingly loaded.
