### ISSUE TITLE
Packaging own nuget package

### ISSUE THREAD

**Issue by fh-dakselrod** [dotnet/SqlClient#1350]
Hi. We would like to create our own package with a minor change to the library.
When I open it in 2019 VS, there's no **Pack** option in the menu. Is there a special way to create a package ?

We're on netfx461

thx

**Comment by fh-dakselrod** [comment]
Will try that.

Out changes are to get rid of SqlConnectionAttestationProtocol class which
we don’t use. But it introduces dependencies which are bad for us. Since we
are on an older version of OWIN. And can’t upgrade without rewriting a lot
of things.

**Comment by cheenamalhotra** [comment]
Acknowledged, let us know if you have any more questions!
