### ISSUE TITLE
Prevent language resource dlls from being output

### ISSUE THREAD

**Issue by ensign-nemo** [dotnet/SqlClient#1368]
Since switching to Microsoft.Data.SqlClient, we now get folders output for the following language codes:

de, es, fr, it, ja, ko, pt-BR, ru, zh-Hans, zh-Hant

Each folder contains a 250kb Microsoft.Data.SqlClient.resources.dll file, totalling 2.5Mb in all.

We don't have any need for these regionalisation/internationalisation resources, and yet they are generated every time. Presumably this list will grow over time as new languages are ported.

How do we prevent these folders from being generated and becoming part of the build product?

**Comment by David-Engel** [comment]
> That will doubtless achieve the same result, but would need maintained as new language packs get added.

That's a pretty rare event.

Implementing satellite packages for languages would add complexity. It also would greatly multiply the number of packages if we want to implement things like #1108. I don't see this being a big enough issue to be worth the effort over something like #1108.

**Comment by JRahnama** [comment]
I am closing the issue as this will never going to happen due to complexity and conflict with other solutions/plans we have for future.

**Comment by SimonCropp** [comment]
the annoying thing for me is that most of these resource files are used to localize exception messages, which just result in making exceptions more difficult to google-bing for. So i get the tax of extra files to ignore/cleanup for a net-negative value

**Comment by JJoe2** [comment]
@SimonCropp - I agree.  If this were an open source project run by one or two volunteers I could understand responses like:
"Once again this could be prioritize if it gets more interest from community"
"Implementing satellite packages for languages would add complexity"

But the project purports to be "the flagship SQL Server driver going forward" and I think it should have a best practice solution for localization.

**Comment by SimonCropp** [comment]
>  If this were an open source project run by one or two volunteers I could understand responses like: "Once again this could be prioritize if it gets more interest from community"

but that was a response from a dev from MS who maintains "the flagship SQL Server driver going forward"

> But the project purports to be "the flagship SQL Server driver going forward" and I think it should have a best practice solution for localization.

"best practice" should be able to evolve over time when it become clear there is a "better practice"

**Comment by JRahnama** [comment]
@SimonCropp, thanks for updating this thread, the fact that you do not need localization does not mean that they should not be there there are so many other users all over the world using the driver. One can **easily** delete those folders. [The cons of having Satellite packages are more than its benefits in our case](https://docs.microsoft.com/en-us/nuget/create-packages/creating-localized-packages#advantages-and-disadvantages-satellite-packages) and it is in contradiction with our future goals with the driver as it was mentioned by @David-Engel . Regarding "best practice" topic, what are the facts and reasoning that put satellite package in "best practice" category for SqlClient driver?

**Comment by dsplaisted** [comment]
I believe that the [SatelliteResourceLanguages](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#satelliteresourcelanguages) property may be what you're looking for.  It allows for an app to filter the language resources that will be included, even if referenced NuGet packages may include more.

**Comment by ensign-nemo** [comment]
> I believe that the [SatelliteResourceLanguages](https://docs.microsoft.com/dotnet/core/project-sdk/msbuild-props#satelliteresourcelanguages) property may be what you're looking for. It allows for an app to filter the language resources that will be included, even if referenced NuGet packages may include more.

Genius - worked for me. Many thanks indeed.

**Comment by ErikEJ** [comment]
@dsplaisted great tip, generally very useful

**Comment by JRahnama** [comment]
@dsplaisted thank you.

**Comment by MrKelpy** [comment]
For those that can't for some reason use the `SatelliteResourceLanguages` solution as mentioned by @dsplaisted, adding the following after build command to your project's `.csproj` file will also work:

```
<Target Name="AfterBuild">
    <ItemGroup>
        <ResourceFiles Include="$(OutputPath)\**\Microsoft.Data.SqlClient.resources.dll"/>
    </ItemGroup>
    <RemoveDir Directories="@(ResourceFiles->'%(RootDir)%(Directory)')" />
</Target>
```

This will delete every directory containing a `Microsoft.Data.SqlClient.resources.dll` file within it. These are the resource files for which the folders are created.

**Comment by dradovic** [comment]
For those who want to enforce English exception messages just for the `SqlClient` package, I suggest using a build target that just removes its resources files:

```xml
  <Target Name="RemoveSqlClientResources" AfterTargets="Build">
    <ItemGroup>
      <ResourceFiles Include="$(OutputPath)\**\Microsoft.Data.SqlClient.resources.dll"/>
    </ItemGroup>
    <Delete Files="@(ResourceFiles)" />
  </Target>
```

(Note that we need to use `AfterTargets="Build"` as just using `"AfterBuild"` [was deprecated](https://stackoverflow.com/a/41476596/331281) so @MrKelpy's build task might not work.)

**Comment by matti157** [comment]
> For those who want to enforce English exception messages just for the `SqlClient` package, I suggest using a build target that just removes its resources files:
> 
>   <Target Name="RemoveSqlClientResources" AfterTargets="Build">
>     <ItemGroup>
>       <ResourceFiles Include="$(OutputPath)\**\Microsoft.Data.SqlClient.resources.dll"/>
>     </ItemGroup>
>     <Delete Files="@(ResourceFiles)" />
>   </Target>
> (Note that we need to use `AfterTargets="Build"` as just using `"AfterBuild"` [was deprecated](https://stackoverflow.com/a/41476596/331281) so [@MrKelpy](https://github.com/MrKelpy)'s build task might not work.)

Not working for me :( I include this snippet in a .net 9 csproj
