### ISSUE TITLE
Any call to SqlClient gives 'Strings.PlatformNotSupported_DataSqlClient'

### ISSUE THREAD

**Issue by hanaana** [dotnet/SqlClient#1385]
Template Blazor WebAssembly App-project .NET 5.0  from VS2019. Added nuget package Microsoft.Data.SqlClient 3.0.1. Any call (e.g. creating SqlConnectionStringBuilder,  SqlConnection) gives an exception: 'Strings.PlatformNotSupported_DataSqlClient'.
Target framework being .NET 5.0, but any CORE target framework does the same??

When calling from .NET Windows Forms App-template works as expected! Is it just some project setup issue??

**Comment by Wraith2** [comment]
You need to nuget restore with a real tfm, not netstandard. The restore process need to know if you're using windows or linux so it can pull the right implementation out of the package because they're different. If you restore with netstandard you'll get the not implemented shim which has not supported exceptions for everything.

**Comment by cheenamalhotra** [comment]
To clarify, this is not netstandard issue.

The Not Supported exception is thrown by DLLs in "lib" directory of NuGet package (all except net461), which is fallback folder for unsupported platforms.

Ideally a .NET application must fetch DLLs from "runtimes" folder applicable to respective platform, when they don't the driver will throw unsupported platform exception.

![image](https://user-images.githubusercontent.com/13396919/141166665-80195b18-f53b-488d-87d5-b2e4e2dd51b5.png)

**Comment by hanaana** [comment]
> You need to nuget restore with a real tfm, not netstandard. The restore process need to know if you're using windows or linux so it can pull the right implementation out of the package because they're different. If you restore with netstandard you'll get the not implemented shim which has not supported exceptions for everything.

Nuget restore makes no difference. What am I missing here? If I manually select Restore Nuget Packages, it restores with netstandard? How can you restore with real tfm then?

**Comment by hanaana** [comment]
Ok, so it is not possible to use .net5.0 as target framework.
