### ISSUE TITLE
SqlTransaction loosing connection on execution of SqlCommand.ExecuteNonQuery() with exception

### ISSUE THREAD

**Issue by IoBes** [dotnet/SqlClient#139]
Tested with .NET 4.7.x and 4.8

In some cases SqlTransaction.Connection property is nulled on exception.
That's why it is not possible to make a call to Commit() or Rollback(), because 
"This SqlTransaction has completed; it is no longer usable." exception is thrown.

To reproduce the issue please use my project

https://github.com/IoBes/NET_SqlTransaction_BUG

or use attached code

[NET_SqlTransaction_BUG-master.zip](https://github.com/dotnet/corefx/files/3372907/NET_SqlTransaction_BUG-master.zip)

**Comment by roji** [comment]
Unless I'm mistaken, transferring requires write access on both repos, and I don't have write on SqlClient...

**Comment by divega** [comment]
@roji I see. Added you.

Cc @David-Engel FYI.

**Comment by roji** [comment]
Thanks @divega, will only use this for issue transfer.

**Comment by cheenamalhotra** [comment]
Hi @IoBes 

I'm able to reproduce the error with **Test 2** and have also tested the exact same steps with MSSQL JDBC Driver and SSMS, which seem to work fine and that confirms this behavior is not expected. We will investigate more into the issue and fix it sometime in future.

**Comment by cheenamalhotra** [comment]
Closing as stale, please open a new issue with repro if problem reoccurs.
