### ISSUE TITLE
SqlConnection.Open() lock forever unde linux (Pi4+Raspbian Buster)

### ISSUE THREAD

**Issue by dobova86** [dotnet/SqlClient#140]
Similar problem to:
https://github.com/dotnet/corefx/issues/30961#issue-339998608

**SqlConnection.Open() will lock forever and never return.** 

This problem happens with 3.0 preview6 (but also with v2.2.x project) on a Rpi4 (2gb) with Buster Linux installed.
No issue on rpi3/3+ with stretch installed, it works fine.
Sql.Data.Client.dll is 3.0.0-preview6-19303 

**Note: connection to Sql Server 2014**

**Comment by peterbae** [comment]
Hi @dobova86,

I'm not sure if this problem is coming from the driver's end, with the Rpi4 and Raspbian Buster being very recent releases. Could you try redirecting this issue to Raspbian team instead?

**Comment by dobova86** [comment]
I will try to inform Raspbian Buster group. 
I've no clue at the moment about the issue, but seems related to some Buster network low-end problem.

**Comment by cheenamalhotra** [comment]
Hi @dobova86 

I will close the issue for now. 
If you need further assistance, please feel free to reopen or create a new issue.

**Comment by dobova86** [comment]
Just for your info, this bug is still present in preview8 on debian buster, but at the moment no more info or solution.
