### ISSUE TITLE
4.0 version of the microsoft sqlclient not working on sites that does not have ssl

### ISSUE THREAD

**Issue by musictopia2** [dotnet/SqlClient#1400]
When I use the 4.0 version of the microsofts sql client, it says it does not trust the authority.  However, 3.0 worked fine.  Is there a way to work without ssl for a website.  Because many businesses if they are hosting locally and want others to access from the same network, they cannot have ssl.

**Comment by Wraith2** [comment]
from the [release notes](https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0.md)

> Changed Encrypt connection string property to be true by default. #1210 Read more

**Comment by JRahnama** [comment]
@musictopia2, as @Wraith2 mentioned, the default value of Connection property Encrypt is changed to true.  Please take a look at them and let us about the outcome.

**Comment by musictopia2** [comment]
am i correct in assuming the actual connection string has to change (especially if a person is using it in wpf or even console app)?  there are many apps out there that does not even use any cloud.  not everybody can even afford to put everything to the cloud.

**Comment by ErikEJ** [comment]
If you are updating the app by depending on SqlClint version 4, you should also be able to update the connection string in use. (Or at least manipulate it before it is actually used)

**Comment by JRahnama** [comment]
@musictopia2 I am closing this issue as it does not seem an actual issue to us. You can simple add `Encrypt=false` to your connection string and continue as it was before. You also can keep Encrypt value to true and add `TrustServerCertificate=true` in connection string. Please feel free to reopen the issue if you think there is a part that we can change and provide a better solution to all users.
