### ISSUE TITLE
Acquiring access token is very slow

### ISSUE THREAD

**Issue by kacperwojtyniak** [dotnet/SqlClient#1403]
Hey,

I wanted to ask if it is normal for `ManagedIdentityCredential.GetToken` to take several seconds?

I am running an ASP.Net on .NET 5, hosted in Azure App Service and I'm using user-assigned managed identity to connect to a SQL Database. My connection string is as follows: `Server=tcp:<sql-server-name>.database.windows.net;Authentication=Active Directory Managed Identity; User Id=<managed-identity-client-id>;Database=<database-name>;`
I am using Microsoft.Data.SqlClient Version=4.0.0
I have not customized the token provider in any way so I just create a new connection like so `new SqlConnection(connectionString);`

The first time I open a connection to the database, I can see in Azure App Insights logs that the `ManagedIdentityCredential.GetToken` method takes several seconds to complete. It can go as high as 5.7 seconds.

I have noticed that the next requests do not cause this method to be invoked at all. I assume the token is cached. However, after some time (probably when the token expires) when the `ManagedIdentityCredential.GetToken` is called again it does not take nearly as much time, it is less than half a second.

First call to my app, where database connection is created
![image](https://user-images.githubusercontent.com/38474178/143232398-a8678d5e-f7da-406d-9351-fc579be5a831.png)

Subsequent call, when the token is refreshed I assume.
![image](https://user-images.githubusercontent.com/38474178/143233007-0689b971-7c75-4718-8d0f-c6a131450a7c.png)

I have two questions.

Is this normal for some calls to `ManagedIdentityCredential.GetToken` to take several seconds?
Is there any way to improve the performance?

**Comment by DavoudEshtehari** [comment]
Your assumption of using cached tokens for the consequent requests is correct. It's not easy to put a certain answer for the SaaS latency here; you can check your SLA. Trying a stand-alone app using the MSAL library to acquire a token could clarify it more.
Also, you can try different [Authentication](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver15) methods which will attempt to use the acquired token: `Active Directory Integrated`, `Active Directory Device Code Flow`, or `Active Directory Default`.

**Comment by kacperwojtyniak** [comment]
Thank you @DavoudEshtehari 
I have tried other auth methods using Managed Identity and the performance is the same. I have tried the same code in a VM and getting the token there is virtually instant. However, when the App Service is in constant use, requests are coming in all the time getting the token is as fast as on VM. This solved all of my concerns. Thank you.

**Comment by JRahnama** [comment]
closing the issue as the question was answered.

Regards,
Javad
