### ISSUE TITLE
Set TrustServerCertificate=True for entire application?

### ISSUE THREAD

**Issue by MojoDK** [dotnet/SqlClient#1406]
Instead of setting TrustServerCertificate=true on every connectionstring, is it possible to set it for the entire application?

I was hoping for some kinda ... "Microsoft.Data.SqlClient.TrustServerCertificate = True".

Thanks.

**Comment by ErikEJ** [comment]
You could do it in a single lokation in your data access layer.

**Comment by MojoDK** [comment]
> You could do it in a single lokation in your data access layer.

Yes, but we have like 40 applications developed over a periode of 20 years and some are not well structed (our mess), so we have many places to change the connectionstring, Would be easier to set it application wide on start up.

**Comment by JRahnama** [comment]
@MojoDK, that needs a bit more of investigation to understand pros and cons of the approach, however you can provide your connection string in an `appsetting.json` file and have a configuration manager to read from that location all over the application.

**Comment by JRahnama** [comment]
@MojoDK this is not something we could do. Driver is not responsible to make this kind of decisions for users. Users need to understand and make that decision deliberately. I am closing this as there is no future plan to add this. As suggested before you can centralize your connection strings in data access layer and manage it from there.
