### ISSUE TITLE
ConnectionString.ConnectRetryCount or Connection.RetryLogicProvider?

### ISSUE THREAD

**Issue by clement911** [dotnet/SqlClient#1409]
I'm  confused about the relationship between ConnectionString.ConnectRetryCount and Connection.RetryLogicProvider?

My understanding is that ConnectRetryCount defaults to 1 (retry once) and RetryLogicProvider defaults to null (do not retry).
Should we use both at the same time or is it redundant to use both (we are using Azure Sql)?

**Comment by DavoudEshtehari** [comment]
The **Configurable Retry Logic** was introduced in v3.0. Using it needs more caution; It doesn't have a conflict with the connection retry mechanism. For better understanding, reading the following articles would help:

- [Configurable retry logic in SqlClient](https://docs.microsoft.com/en-us/sql/connect/ado-net/configurable-retry-logic?view=sql-server-ver15).
- [Retry Pattern](https://docs.microsoft.com/en-us/azure/architecture/patterns/retry)
- [Idle connection resiliency in the OLE DB Driver](https://docs.microsoft.com/en-us/sql/connect/oledb/features/idle-connection-resiliency?view=sql-server-ver15): the general idea behind it is similar to ADO.Net

**Comment by JRahnama** [comment]
@clement911 is your question answered? If yes, please feel free to close the issue.

**Comment by clement911** [comment]
I couldn't find any material regarding the relationship between the two.
For example, if I set ConnectionString.ConnectRetryCount = 3 and the Connection.RetryLogicProvider is setup with SqlRetryLogicOption.NumberOfTries = 3, will it end up trying a total of 3 x 3 = 9 times?

**Comment by DavoudEshtehari** [comment]
A straight answer to your question is **Yes** and **No**. `SqlConnection` uses a separate internal [transient error](https://github.com/dotnet/SqlClient/blob/c56baaabb641de6dd595203f78a2e93b65ac2317/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L245) list to do the retry using the `ConnectionString.ConnectRetryCount` property, while **Configurable Retry Logic** has been introduced with an internal [transient errors](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconfigurableretryfactory?view=sqlclient-dotnet-standard-4.0#remarks) which is customizable. Your assumption would be correct if common transient errors occurred from these two lists.

**Comment by clement911** [comment]
I see.
I appreciate that some of these recent improvements for retrying various things. We are using Sql Azure and transient failures have to be dealt with.
However, I must say that I am still left quite confused as to exactly how to choose a value for the ConnectionString.ConnectRetryCount and the retry logic. Retrying 3 times seems reasonable but retrying 3 x 3 times does not, and digging into the code to figure out exactly which error codes are considered transient is not a great experience.
(On top of that, we use EF Core, which also has its own retry logic).

I trust the code is very solid and this is probably more a documentation issue. It would be great to have a doc page that discusses ConnectRetryCount VS retry logic VS EF core retry logic and best practices around them.

Are there recommended defaults to use, especially when connecting against Sql Azure?

**Comment by DavoudEshtehari** [comment]
Since this is a new feature, there might be some opportunities to enrich documentation. Our focus on documents is on SqlClient, not the dependants, and I believe EF team has a better perspective to take ownership of the suggested document.

> Are there recommended defaults to use, especially when connecting against Sql Azure?

Using **Configurable Retry Logic** needs a profound understanding of the **Retry Pattern**, besides having sufficient knowledge of the production transient failures. If there was any recommendation we'd set it up as a default. And I'd suggest avoiding it without that information.

**Comment by DavoudEshtehari** [comment]
Closing the thread because of inactivity.
