### ISSUE TITLE
Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.3'

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/SqlClient#1413]
### Describe the bug
After upgrading nuget `System.Data.SqlClient` from 4.8.2 to 4.8.3 I get the above error on production. Works fine on local machine running under Visual Studio IIS Express but after **PUBLISHING** a "ReadyToRun" win-x64 app to a folder and then copying to the server - it stops working. 4.8.2 worked fine, it's a regression.

The weird thing is that both 4.8.3 and 4.8.2 publish the same`System.Data.SqlClient.dll` identical file that is 2-something megabytes large. I guess that is the problem - publishing the wrong files. Must be targets are messed up in Nuspec? Or the "ReadyToRun" publishing messes up versioning somehow?

My guess is "ReadyToRun" publishing has some internal caching logic and does not "recompile" the file because it's not detecting any changes after moving from 4.8.2 to 4.8.3

```
Exception message: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Jitbit.Utils.DBUtils.GetNewOpenConnection
   at HelpDesk.BusinessLayer.HDUserPrincipal.InitPropertiesFromDb() in c:\jitbit\helpdeskCore\HelpDesk\BusinessLayer\HDUserPrincipal.cs:line 71
   at HelpDesk.BusinessLayer.HDUserMiddleware.InvokeAsync(HttpContext httpContext) in c:\jitbit\helpdeskCore\HelpDesk\BusinessLayer\HDUserPrincipal.cs:line 196
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

### To reproduce
Publish a `readyToRun` ASP.NET 5 Core app in VS 2019 to a folder and try to run it. Works fine with 4.8.2. Then upgrade Nuget to 4.8.3 and republish - it stops working

**Comment by JRahnama** [comment]
@alex-jitbit I will look into this issue to see if we are able to reproduce it.

**Comment by alex-jitbit** [comment]
@JRahnama it appeared it is indeed a bug in nuget caching. After clearing the `/obj` folder everything worked as expected. So I guess the bug is not with SqlClient, but rather with nuget and "ReadyToRun".

**Comment by Kaur-Parminder** [comment]
@alex-jitbit Can you leave the detailed steps that you followed to resolve the issue. It might help others if they see any issues with Publishing. Was it only deleting /obj folder and rebuilding solution?

**Comment by alex-jitbit** [comment]
@Kaur-Parminder yes, it was.

Again, the reason for this error is because "ReadyToRun" publishing believes that the `System.Data.SqlClient.dll` file has unchanged between 4.8.3 and 4.8.2. Probably because it _really_ hasn't changed, except the metadata (assembly version number etc) but we all know that "ReadyRoRun" looks deeper than just metadata and actually tries to "understand" the assembly code.

It would be great if you forward this issue to ReadyToRun team or Nuget team? Or direct me where to do this, I'll post the issue myself.

**Comment by Kaur-Parminder** [comment]
@alex-jitbit You can report it on repository: https://github.com/dotnet/runtime/issues

**Comment by JRahnama** [comment]
closing this as this is not `SqlClient` issue.
