### ISSUE TITLE
Bad performance when using async variants compared sync variants

### ISSUE THREAD

**Issue by davesmits** [dotnet/SqlClient#1420]
### Describe the bug
I have a scenario where i have a simple table where i have a ID and a long text column. When retrieving a single row by id the performance using the async api's got really bad. THe sync api's seem to work as expected.

### To reproduce
Included a sample project but basically having these two pieces of code to compare. The desription and screenshot is ran from exact the sample included.

The used database is the LocalDB that comes with Visual Studio 2022

[AsyncPerformanceProblems.zip](https://github.com/dotnet/SqlClient/files/7651877/AsyncPerformanceProblems.zip)

```
{
    // Read Sync
    var stopwatchSync = Stopwatch.StartNew();
    var readTextSyncCommand = connection.CreateCommand();
    readTextSyncCommand.CommandText = @"SELECT LongText FROM Example";
    using var readerSync = readTextSyncCommand.ExecuteReader();
    while (readerSync.Read())
    {
        stopwatchSync.Stop();
        Console.WriteLine($"Length: {((string)readerSync[0]).Length}; Took: {stopwatchSync.Elapsed}");
    }
}
```

and

````
{
    // Read ASync
    var stopwatchASync = Stopwatch.StartNew();
    var readTextASyncCommand = connection.CreateCommand();
    readTextASyncCommand.CommandText = @"SELECT LongText FROM Example";
    using var readerASync = await readTextASyncCommand.ExecuteReaderAsync();
    while (await readerASync.ReadAsync())
    {
        stopwatchASync.Stop();
        Console.WriteLine($"Length: {((string)readerASync[0]).Length}; Took: {stopwatchASync.Elapsed}");
    }
}

````

Resulting in this where the 11 minute read is the async version

![slowquery](https://user-images.githubusercontent.com/3148438/144660234-bc54ee14-9831-410b-8099-083a4181c002.png)

### Expected behavior
Expecting the async and sync have a similar performance

**Comment by Wraith2** [comment]
Yup, see https://github.com/dotnet/SqlClient/issues/593

**Comment by JRahnama** [comment]
@davesmits this is a known issue. As @Wraith2 has mentioned. If you agree and feel like issues are coming from same source please close this issue and lets focus and follow on the open one #593 .
