### ISSUE TITLE
SqlConnectionStringBuilder.Encrypt - documentation is not correct

### ISSUE THREAD

**Issue by abelykh0** [dotnet/SqlClient#1421]
### Describe the bug
SqlConnectionStringBuilder.Encrypt is documented to be `false` by default, but it is `true`, see https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.encrypt?view=sqlclient-dotnet-core-4.0

### To reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

```c#
// See https://aka.ms/new-console-template for more information
using Microsoft.Data.SqlClient;
using System.Diagnostics;
SqlConnectionStringBuilder builder = new SqlConnectionStringBuilder("Data Source=server; Initial Catalog=Catalog; User Id=testuser;Password=secret;");
Debug.WriteLine(builder.Encrypt);
```

### Expected behavior
The builder.Encrypt should be `false`. Note: it is `false` if using `System.Data.SqlClient` v 4.8.3 as well as Microsoft.Data.SqlClient v 3.0.1

### Further technical details
Microsoft.Data.SqlClient version: 4.0.0
.NET target: 6.0
SQL Server version: N/A
Operating system: Windows 10

**Additional context**

**Comment by JRahnama** [comment]
@abelykh0 thanks for finding this. We will update the documentation. Issue #1248 was addressed in [preview 2 of version 4](https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0-preview2.md). We will address that breaking change starting from v4 in the documentation.
