### ISSUE TITLE
System.Data.SqlClient crashes with Integrated Security in .NET 6 on Linux

### ISSUE THREAD

**Issue by oxcart83** [dotnet/SqlClient#1429]
### Describe the bug

After migrating from .NET 5 to .NET 6, our program crashes when connecting to SQL server with "Integrated Security=true" on Linux (Ubuntu 20.04) only (it works fine on Windows 10).

No exception is thrown, and the program crashes with a segmentation fault.

### To reproduce

Project file:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net6.0;net5.0</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
  </ItemGroup>
</Project>

``` 

Code:

```c#
using System;
using System.Data.SqlClient;

try
{
    var connection = new SqlConnection("Data Source=SQL_TEST;Integrated Security=true");
    Console.WriteLine("Trying to connect...");
    connection.Open();
    Console.WriteLine("Connection open");
    connection.Dispose();
    Console.WriteLine("Connection closed");
}
catch (Exception ex)
{
    Console.WriteLine(ex.ToString());
}
```

### Expected behavior

The code should connect on both .NET 5 and .NET 6

### Actual behavior

The code works as intended on .NET 5 on Linux:

```
$ dotnet run -f net5.0
Trying to connect...
Connection open
Connection closed
```

But crashes on .NET 6 on Linux:

```
$ dotnet run -f net6.0
Trying to connect...
$ echo $?
139
```

The exit code 139 means it's a segmentation fault (SIGSEGV).

### Further technical details
System.Data.SqlClient version: 4.8.3
.NET target: .NET 6
SQL Server 2019
Operating system: Ubuntu 20.04 LTS

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.100/

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa
```

**Comment by JRahnama** [comment]
@oxcart83 this is a known issue with .net 6 release and Kerberos authentication. Since you are using `System.Data.SqlClient ` the fix will be released with next patch release of net 6. For `Microsoft.Data.SqlClient` we are planning to release it some time around January 14. For more information you can look into #1390

**Comment by JRahnama** [comment]
I am closing this issue as a duplication of #1390. You can follow or comment  the progress on that thread.

Regards,
Javad

**Comment by oxcart83** [comment]
Indeed, thank you :)
