### ISSUE TITLE
Turn Off "Security Warning "The negotiated TLS 1.0..." if Encrypt=false passed in Connection String

### ISSUE THREAD

**Issue by zkost** [dotnet/SqlClient#1434]
### Is your feature request related to a problem? Please describe.
In a development or internal network setting and where "Encrypt=false" in the connection string, a warning is sent to the console that is interfering with other console output produced by our apps. Also this is an unnecessary performance hit to our apps as this message is written to the console every time a new DbContext session/connection is established. 

The specific warning is = Security Warning: The negotiated TLS 1.0 is an insecure protocol and is supported for backward compatibility only. The recommended protocol version is TLS 1.2 and later."

### Describe the solution you'd like
Solution 1: automatically disable this warning message if "Encrypt=false" 
Solution 2: Add another switch in the connection string that turns this warning off when combined with "Encrypt=false"

**Comment by DavoudEshtehari** [comment]
Using "Encrypt=false" means after login the data transmission happens without encryption. But, the login process still could use encryption. I'll add it to the triage board for more discussion.

**Comment by zkost** [comment]
Thanks Davoud, No contest to your response and thank you for adding it to the triage board; 

Additional note - I understand the goal for ensuring conscious security state by the developer in using Microsoft.Data.SqlClient, but If one consciously disables the use of encryption "Ecrypt=false" in scenarios of development or internal network isolation from the outside world as in a sandbox, then is having TdsParserHelperClasses.GetProtocolWarning() drop a warning message on every login in TdsParser.cs#L955, well? Is it necessary? To your point, this error is related to "encrypt login" #L900 of the same source file. Is there a way to set EncryptionOptions.NOT_SUP via the connection string? 

This message is a real issue in our world. Hoping for your direction or workaround to disable the message for use in our sandboxes and still keeping current with the current and future updates of this API.

Thank you
Ben
