### ISSUE TITLE
Retry does not work correctly for SqlCommand.ExecuteReader when CommandBehavior.CloseConnection is used

### ISSUE THREAD

**Issue by sksk571** [dotnet/SqlClient#1454]
### Describe the bug
When CommandBehavior.CloseConnection is passed into SqlCommand.ExecuteReader, the command is not retried and System.InvalidOperationException is thrown.

Exception:
```
Exception message: System.InvalidOperationException: ExecuteReader requires an open and available Connection. The connection's current state is closed.

Stack trace:
   at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(Boolean isAsync, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.<>c__DisplayClass152_0.<RunExecuteReaderWithRetry>b__0()
   at Microsoft.Data.SqlClient.SqlRetryLogicProvider.Execute[TResult](Object sender, Func`1 function)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderWithRetry(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)

```

The connection appears to be closed upon calling ExecuteReader while according to documentation of  [CommandBehavior.CloseConnection](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=net-6.0#fields) it should be closed when the reader is closed.

### To reproduce
```c#
using System.Data;
using Microsoft.Data.SqlClient;

using var connection = new SqlConnection("Data Source=.;Initial Catalog=master;Integrated Security=True;Trust Server Certificate=true;");
connection.Open();
var command = connection.CreateCommand();
command.RetryLogicProvider = SqlConfigurableRetryFactory.CreateFixedRetryProvider(new SqlRetryLogicOption { NumberOfTries = 3, TransientErrors = new[] { 50000 } });
command.CommandText = "RAISERROR('Test error', 16, 1)";

// When CommandBehavior.CloseConnection is removed from the line below, command is retried 3 times as expected.
using var reader = command.ExecuteReader(CommandBehavior.CloseConnection);
```

### Expected behavior
The command is retried according to specified retry options, connection is closed when the reader is closed.

### Further technical details
Microsoft.Data.SqlClient version: 4.0.0
.NET target: .NET 6
SQL Server version: Microsoft SQL Server 2019
Operating system: Windows 10 Enterprise

**Additional context**
[Dapper](https://github.com/DapperLib/Dapper) (popular O/R mapping library) passes CommandBehavior.CloseConnection into SqlCommand.ExecuteReader when query is executed on an initially closed connection. This issue breaks retry logic when Dapper is used, unless connection is explicitly opened before executing query.

**Comment by JRahnama** [comment]
@sksk571 I looked at the code, when the exception happens, in this case error is raised, reader gets closed and since requested,  the connection gets closed consequently. Now the question would be should the documentation get adjusted to this behavior or we can give some control to `RetryLogicProvider` to control the retries and reader and close them accordingly?

I was able tp check if retryProvider in SqlDataReader class is requested and omit the connection closure, but that would be against `CommandBehavior.CloseConnection` purpose and simply makes it useless.

**Comment by JRahnama** [comment]
After looking deeper in the code and patterns we noticed that `CommandBehavior.CloseConnection` is in contradiction with `RetryLogic`. We will update the documentation soon. Thanks for catching this.

**Comment by sksk571** [comment]
@JRahnama I think the problem is caused by the fact that the reader is created and disposed on every retry, which causes connection to be closed between retries. We worked around the issue by creating own SqlRetryLogicProvider that reopens connection before retrying, but it's a bit hacky.
