### ISSUE TITLE
Connection string not working when using localhost ip instead of "localhost"

### ISSUE THREAD

**Issue by JanTrichter** [dotnet/SqlClient#1455]
Hey there,
I had a complicated issue yesterday. I upgraded my EF Core version form 3.x to 5.x in a project (.Net core 3.1). When I did that, the old Connection string which uses the ip address `127.0.0.1` of localhost instead of the string `localhost` for Data Source / server had connection problems.

I asked [this question](https://github.com/dotnet/efcore/issues/27112) first in the EF Core repo and I was redirected to this repo. 

Here is my Connection string that worked for the 3.1.22 version (uses SqlClient version 1.1.3+):
`server=127.0.0.1;user id=user;password=password;database=db;trusted_connection=true;`
_sensitive data has been replaced_

When I try the same connection string in EF Core version 5.0.13 (SqlClient version 2.1.4+) I get the following error:
`Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'`

But it works when I replace the ip address of localhost with the string "localhost" it works in EF Core version 5.0.13 (SqlClient version 2.1.4+):
`server=localhost;user id=user;password=password;database=db;trusted_connection=true;`
or alternatively:
`Data Source=localhost; Initial Catalog=db; Integrated Security=true`
_sensitive data has been replaced_

Where did this breaking change appear? I couldn't find anything about this when I searched for it  yesterday and I fixed it purely by coincidence.

**Comment by JRahnama** [comment]
@JanTrichter there is no breaking change regarding this matter. I have created a sample repro with EFCore 5.0.13 and I was able to get connection either way. I also used Microsoft.Data.SqlClient version 4 and the issue you mentioned did not show up. I only had to change connection string for version 4 to add `Encrypt=false` to address [the breaking change](https://github.com/dotnet/SqlClient/blob/main/release-notes/4.0/4.0.0.md#breaking-changes). Please review my sample repro in this [gist](https://gist.github.com/JRahnama/da5eac3c91397dd6f3613f28c55ddaec) and let me know if it is looking like your application.

Now,

1. `localhost` is not using IP. It uses shared memory. Can you check if `TCP` is enabled on your server by looking at Sql Server Configuration Manager properies?

2. Can you also enforce the TCP protocol usage by adding tcp:127.0.0.1 in your connection string as data source?
3. Other places you can check is to go to `Sql Server Configuration Manager` expand `SQL Server Network Configuration` and click on `Protocols for MSSQLSERVER` or other instances, if your using any, and right click on TCP/IP on right column and  click on property select `property `and go to `IP Addresses` tab. Scroll down till you see IP Address 127.0.0.1 and make sure it is Active?
![image](https://user-images.githubusercontent.com/32077152/148464551-8a6f660d-8c37-49e0-bfa9-e3a99161cbbc.png)
![image](https://user-images.githubusercontent.com/32077152/148464665-2059d351-405b-4db5-8a33-6622dbed759a.png)

**Comment by JanTrichter** [comment]
Couldn't replicate it. I rest my case ^^
