### ISSUE TITLE
Update from 2.1.0 to 2.1.1 does not remove references to Microsoft.Data.SqlClient.SNI.targets

### ISSUE THREAD

**Issue by RichardD2** [dotnet/SqlClient#1456]
### Describe the bug
I have multiple ASP.NET MVC 5 applications which reference `Microsoft.Data.SqlClient`.

After upgrading from 2.1.0 to 2.1.1 via the NuGet package manager, the project file is left with invisible references to the `Microsoft.Data.SqlClient.SNI.targets` file for 2.1.0.

After committing the change and cloning it to a new PC, the project fails to build, complaining that it references a package which does not exist.

### To reproduce
* Create an ASP.NET MVC 5 project;
* Add a reference to `Microsoft.Data.SqlClient` version 2.1.0;
* Use the NuGet package manager to upgrade the reference to 2.1.1;
* Open the project file in a text editor;

### Expected behaviour
All references to 2.1.0 should be removed. Only references to 2.1.1 should remain.

### Actual behaviour
The project file still references 2.1.0:

```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    ...
    <Error Condition="!Exists('..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets'))" />
    <Error Condition="!Exists('..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets'))" />
  </Target>
  
  <Import Project="..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\packages\Microsoft.Data.SqlClient.SNI.2.1.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />
  <Import Project="..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\packages\Microsoft.Data.SqlClient.SNI.2.1.1\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />
```

### Further technical details
Microsoft.Data.SqlClient version: 2.1.x
.NET target: Framework 4.7.2
Operating system: Windows 10

**Comment by JRahnama** [comment]
@RichardD2 I tested that and it looks like it only happens for 2.1.0 to 2.1.1? Am I correct? I am going to do some more testing and see if the driver is faulty for that behavior or Nuget. There might be some issues with .net framework SDK. Cannot say anything before some more testing.

**Comment by RichardD2** [comment]
@JRahnama 2.1.0 to 2.1.1 is the only version I've noticed this problem with. I have another ASP.NET project which was updated from 1.1.3 to 2.1.2 to 3.0.1 which doesn't have these orphaned references.

**Comment by JRahnama** [comment]
Closing this issue as our latest supported version for 2.1 is patch number 4. Please try with 2.1.4 or any newer version. Feel free to open or comment if the issue still exists.
