### ISSUE TITLE
Trying to connect to TLS 1.2 enabled Sql Server from .Net Core client

### ISSUE THREAD

**Issue by m4masood** [dotnet/SqlClient#147]
Hi,

I have got a client (container application) in .net core and trying to connect to TLS 1.2 enabled Sql server.

When the Sql server was not configured the client can talk to database but after enabling TLS 1.2 it started throwing below error:

Error: The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts.
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown 

Can you please assist on this?

Thanks,
Muhammad Masood

**Comment by ErikEJ** [comment]
Version and brand of provider in use? Please

**Comment by David-Engel** [comment]
@divega It should be. I would think TLS 1.2 support was added to SqlClient long ago and would be very surprised if it wasn't working. We have TLS 1.3 support on our near term roadmap. I think this issue would need more environment investigation.

@m4masood Can you try connecting to the server with other methods, like the Microsoft ODBC Driver for SQL Server, and via other clients and applications, when TLS 1.2 is enabled? It's also possible that the container is missing encryption libraries required for TLS 1.2 connections, too. So that will need to be verified.

**Comment by m4masood** [comment]
Hi,

I am using below sql client:
![image](https://user-images.githubusercontent.com/7548298/62669551-59f55880-b9d3-11e9-917f-599416458274.png)

Not sure about encryption libraries for container. 
Can you please provide some sample document / guide that shows how to connect and required libraries for container?

I will check whether I can access the Sql server using ODBC driver.

Below is the error I am getting:
Error: The connection is broken and recovery is not possible.  The client driver attempted to recover the connection one or more times and all attempts failed.  Increase the value of ConnectRetryCount to increase the number of recovery attempts.
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQuery(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at MMasood.Database.ExecuteStoredProcedure(String storedProcedureName, Dictionary`2 inputParams) in


Thanks,
Muhammad Masood

**Comment by karinazhou** [comment]
Hi @m4masood , 

As @David-Engel mentioned, this could be related to some environment settings either on the server-side or on the client-side.  Could you try to do a simple connection to the TLS 1.2 enabled SQL Server to see whether it works? Also, there are several things that can be tested:

* connect through System.Data.SqlClient from the same container you got errors
* connect through Microsoft ODBC Driver 17 from the same container you got errors if possible
* connect through System.Data.SqlClient from another client machine
* connect through Microsoft ODBC Driver 17 from another client machine
   NB: If on Windows, you can simply use ODBC Data Source Administrator to test the connection.

Thanks,
Karina

**Comment by m4masood** [comment]
Hi,
I followed https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-encrypted-connections?view=sql-server-2017 and added CA signed cert to the container and it can talk to database now. But currently server is not forcing for TLS 1.2 (it is enabled) so I am waiting for dba to make this happen in database and see how container will behave after that.
I will update you guys. 

Thanks a lot.

**Comment by m4masood** [comment]
Hi,
It can talk to database server with TLS 1.2 enabled.
Here is part of my Dockerfile:

COPY ./Certificates/db.cer /etc/pki/ca-trust/source/anchors/db.cer
RUN update-ca-trust

Thanks,
Muhammad Masood

**Comment by BackTrak** [comment]
FYI, you still cannot connect to TLS1.2 enforced SQL Server  as of the aspnet:3.1.5-buster (Debian) Microsoft docker image, but the Ubuntu version (3.1.5-Bionic) works fine. Hope this helps someone else out! Seems like fixes are in progress: https://github.com/dotnet/SqlClient/issues/201
