### ISSUE TITLE
`SQL2019-SSEI-Expr.exe` is unable to find the German installer file on the server

### ISSUE THREAD

**Issue by lauxjpn** [dotnet/SqlClient#1470]
(I didn't know where to report this issue, so I am doing it here, even though it is not .NET related.)

When I try to install the SQL Server 2019 Express Edition on a machine, and select `German` after when running the `SQL2019-SSEI-Expr.exe` file, an error appears for the `FullDownloadActivity` that the `SQLEXPRADV_x64_DEU.exe` (German installer file) could not be found on the server.

Selecting `English` instead works as expected and downloads and installs fine.

Looks like the file got moved server-side and the installer wasn't updated (or something similar).

### Further technical details
Installer file version: 15.2002.4709.1
SQL Server version: SQL Server 2019 Express
Operating system: Windows 10

**Comment by JRahnama** [comment]
Hi @lauxjpn, we would recommend to submit your feedback directly from the SQL2019-SSEI-Expr installer (the smiley face in the upper right)

![image](https://user-images.githubusercontent.com/32077152/149386069-8f601a2a-38bd-4d67-b7a1-502dc01cbda3.png)

other options would be listed on  [SQL Server help and feedback](https://docs.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver15)

**Comment by lauxjpn** [comment]
@JRahnama Thanks!
