### ISSUE TITLE
SqlDependency Causing Huge amount of Conversation_Endpoints in SqlServer

### ISSUE THREAD

**Issue by ReinhardAmon** [dotnet/SqlClient#148]
While using SqlDependency in .net Core Sql-Server is creating a new conversation_endpoint STARTED_OUTBOUND every 30 seond.

select state, state_desc, count(*) from sys.conversation_endpoints
where is_system=0
group by state, state_desc

select  lifetime, state_desc, security_timestamp 
from aprosys_dev.sys.conversation_endpoints
where is_system=0
order by lifetime

Is there anything I can do about it?

testet with Sql Server 2008 R2 Express and Sql Server 2016 Express/Standard/Developer

[SqlDependencyTest.zip](https://github.com/dotnet/corefx/files/3481089/SqlDependencyTest.zip)

**Comment by karinazhou** [comment]
Hi @ReinhardAmon ,

I tried your application targeting SQL Server 2017 and I can see the STARTED_OUTBOUND generated gradually. We will investigate this more.

Thanks,
Karina

**Comment by matthiasleitner** [comment]
@karinazhou seeing the same issue, any further insights already?

**Comment by karinazhou** [comment]
@ReinhardAmon  @matthiasleitner 

We just released the new version 1.1.0 for Microsoft.Data.SqlClient which contains a bunch of fixes. I tried the `SqlDependencyTest.zip` with MDS v1.1.0 and I keep the application running for 5 mins. I can see only one STARTED_OUTBOUND conversation_endpoint being created now.

Could you try the latest Microsoft.Data.SqlClient on your side?

**Comment by David-Engel** [comment]
Closing as not repro.
