### ISSUE TITLE
BinSkim errors on Microsoft.Data.SqlClient.SNI.dll

### ISSUE THREAD

**Issue by nhbala** [dotnet/SqlClient#1481]
### Describe the bug
Much like the issue linked [https://github.com/dotnet/SqlClient/issues/598](here), BinSkim is failing with loading Pdb errors when scanning an application that uses Microsoft.Data.SqlClient

```
 C:\__w\1\s\MyAppI\bin\Release\netcoreapp3.1\bin\Microsoft.Data.SqlClient.SNI.x64.dll : error ERR997.ExceptionLoadingPdb : BA2002 : 'Microsoft.Data.SqlClient.SNI.x64.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded.
```

### To reproduce
Create a new empty .NET Core 3.1 project (console app is fine)
Add Microsoft.Data.SqlClient from Nuget
Build the application
Download BinSkim, extract it somewhere and run binskim.exe analyze bin\Debug\netcoreapp3.1\runtimes\win-x64\native\sni.dll (adjusting the path to point at the app's bin folder)

### Expected behavior
BinSkim shouldn't error

### Further technical details
Microsoft.Data.SqlClient version: 4.0.1
.NET target: .Net Core 3.1
SQL Server version: N/A
Operating system: Windows 10

**Additional context**
Is there any workaround for this? I know this issue was initially fixed in ver 2.0 for the Microsoft.Data.SqlClient but then was removed based off the conversations [https://github.com/dotnet/SqlClient/issues/644](here)

**Comment by JRahnama** [comment]
have you tested with previous versions? I just tested with v4.0 and v3.0.1 got the same results. pdbs are published to Microsoft  symbol server. I will check in more detail and will get back to you.

**Comment by nhbala** [comment]
Looks like 4.0 works but 4.0.1 still shows the same behavior?

**Comment by JRahnama** [comment]
@nhbala do you provide --sympath variable as well? As mentioned before pdbs are published on Microsoft Symbol server and 4.0.1 is depending on SNI 4.0 release which its pdbs are already published there. So far I am getting same error message for all versions. I will test more with clearing all caches.

**Comment by JRahnama** [comment]
please include the exact command for the repro as the `dll` in your error message is not the same as the one used in the command.

**Comment by JRahnama** [comment]
@nhbala any update on this?

**Comment by JRahnama** [comment]
@jjaguirre394 pdbs are striped from the packet. You need to provide symbol server path when you run binskim. the correct argument for that is `-sympath <path to symbol server or cache goes here`. Read more [here](https://github.com/Microsoft/binskim#command-line-quick-guide).
