### ISSUE TITLE
EF Core Slow Connection To MSSQL On Ubuntu 18.04

### ISSUE THREAD

**Issue by leecoul** [dotnet/SqlClient#149]

**Comment by cheenamalhotra** [comment]
@leecoul 

Could you also test with a console app targeting Net Core that simply connects to remote SQL Server with Microsoft.Data.SqlClient, ruling out any other dependency.

Just to let you know, we are testing connectivity with remote databases (various versions) in our test lab from Ubuntu 18.04 and have never encountered such issue.

**Comment by cheenamalhotra** [comment]
For the "TimeoutExpired" exceptions, please test with latest preview version [1.0.19221.1-Preview](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19221.1-Preview) and we expect them to go away.

**Comment by leecoul** [comment]
Have tested with a console app using Microsoft.Data.SqlClient version 1.0.19221.1-Preview but that either takes or minute or 2 to connect or sporadically times out with:

Unhandled Exception: System.AggregateException: One or more errors occurred. (Unable to write data to the transport connection: Connection reset by peer.) ---> System.IO.IOException: Unable to write data to the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)

To further rule out any network issues I’m going to test connection to a remote PostgreSQL database. In a couple weeks time our data-mart is going to be upgraded to MS SQL Server 2016 so will be able to test with that.

**Comment by leecoul** [comment]
I've now tested this with MS SQL Server 2016 and I have no problems at all connecting to that. I'm guessing whatever the problem was, it was specific to the 2008 R2 version.
