### ISSUE TITLE
Managed Identity Access Token is refreshed very often

### ISSUE THREAD

**Issue by kevinharing** [dotnet/SqlClient#1495]
### Describe the bug
I recently started using managed identity authentication functionality from SqlClient after using our own access token caching implementation, but I'm seeing a lot of random token refreshes and I'm wondering if this is expected. Below is a screenshot from app insights showing the refresh calls over a period of 24 hours of one app instance.

Before:
![image](https://user-images.githubusercontent.com/1201599/151762808-d7476b0c-4150-43e6-8922-767641dcead1.png)

After:
![image](https://user-images.githubusercontent.com/1201599/151761409-036d7c81-5ca5-46d1-866b-e89b49161cf1.png)

I would expect the token to be cached around 24 hours before a refresh is triggered if the token lifetime is 24 hours. What I am experiencing though is that it refreshes at a seemingly random interval.

This behavior is slowing down a bunch of our requests as you can probably imagine.

One other thing I noticed is calls to the below endpoints when the token is refreshed. We did not see these pop up before the change.

- GET crl3.digicert.com/Omniroot2025.crl
- GET mscrl.microsoft.com/pki/mscorp/crl/Microsoft%20RSA%20TLS%20CA%2001.crl

Currently I'm considering moving back to our own implementation, because this is just plain dumb behavior.

### To reproduce
Just run a application with using the below segment in the connection string.

```
Authentication=Active Directory Managed Identity
```

### Expected behavior
Refresh the token just before the token expires (5 minutes before or something).

### Further technical details
Microsoft.Data.SqlClient version: 4.0.1
.NET target: 6.0.1
SQL Server version: Azure SQL Server
Operating system: aspnet:6.0-bullseye-slim

**Comment by JRahnama** [comment]
@kevinharing, a token should be refreshed in about 10 hours (5-10 minutes before expiration time) and it would be cached to make it easier to use. Is that happening sooner than that time for you? 

Even if a token is acquired manually when it goes to the pool when it is re-used (after 10 hours) server checks credentials and it may throw token the expired exception.

**Comment by kevinharing** [comment]
> @kevinharing, a token should be refreshed in about 10 hours (5-10 minutes before expiration time) and it would be cached to make it easier to use. Is that happening sooner than that time for you?

A token should be refreshed 5-10 minutes before expiration time indeed (not 10 hours specifically as the token lifetime is configurable is AAD). As can be seen on the screenshots, this is happening way more often than once every 10 hours.

> Even if a token is acquired manually when it goes to the pool when it is re-used (after 10 hours) server checks credentials and it may throw token the expired exception.

What do you mean with "server checks credentials"? A token does not contain credentials.

**Comment by JRahnama** [comment]
> What do you mean with "server checks credentials"? A token does not contain credentials.

A better term would be revalidation. We have a very good topic on this matter. I t could be seen at #767

**Comment by scottaddie** [comment]
With the upgrade to `Azure.Identity` v1.8.0, this problem will be solved. When `Authentication=Active Directory Managed Identity` is used, the Azure Identity library's `ManagedIdentityCredential` type is used. As of v1.8.0, that credential type caches and refreshes tokens by default. See https://github.com/Azure/azure-sdk-for-net/blob/b9950ad3a3287c1a121f7c901072a8faddcd6a15/sdk/identity/Azure.Identity/src/Credentials/ManagedIdentityCredential.cs#L87-L89 for more details.

**Comment by ErikEJ** [comment]
@scottaddie Are you recommending an explicit Update today with Managed Identity and the current version of MDS?

**Comment by scottaddie** [comment]
@ErikEJ My recommendation is to use the v5.2.0 release of MDS when that becomes available.

**Comment by ErikEJ** [comment]
@kevinharing Have you tested with 5.2 preview 4 ?

**Comment by kevinharing** [comment]
> @kevinharing Have you tested with 5.2 preview 4 ?

Nope, and to be frank, I currently don’t have time to test this out thoroughly.

**Comment by kf-gonzalez2** [comment]
Hi @zheweiwangMicrosoft  this will be targeted to be addressed by PR #2380

**Comment by PaulVrugt** [comment]
@David-Engel @DavoudEshtehari did this fix make any release?

**Comment by ErikEJ** [comment]
@PaulVrugt It was added to 5.1.6 and 5.2.2 https://github.com/dotnet/SqlClient/pull/2380
