### ISSUE TITLE
Feature Request: Instrument SqlConnection/SqlDatReader with EventSource

### ISSUE THREAD

**Issue by yahorsi** [dotnet/SqlClient#150]
Hi Guys,

Currently SqlClient has built in tracing for the SqlCommand's.
It would be really helpful to have it for the SqlConnection/SqlDataReader as well.
In today's apps in most cases time taken to read data is significantly exceeds time to execute SqlCommand's. But it is currently not possible to track readers explicitly ((

EntityFramework made their own tracing and they expose SqlConnection lifetime events and one SqlDataReader event. But that's EntityFramework, we need it built in to the client.

Thanks

**Comment by cheenamalhotra** [comment]
We'll investigate more on this request in future, adding it to our triage board.

**Comment by cheenamalhotra** [comment]
Hi @yahorsi 

Closing this issue as we're tracking tracing activities with issue #93 .
Discussions are open and we're welcoming suggestions there.
