### ISSUE TITLE
What runtimes is SqlClientDiagnosticListener supported on?

### ISSUE THREAD

**Issue by SimonCropp** [dotnet/SqlClient#1529]
When using a `DiagnosticListener.AllListeners` to subscribe to a `SqlClientDiagnosticListener` it does not work for net48.

Here is a runnable repo (only on windows since it is using localdb): https://github.com/SimonCropp/SqlClientDiagnosticListenerExperiments/

In [the test](https://github.com/SimonCropp/SqlClientDiagnosticListenerExperiments/blob/main/Sample/SqlServerTests.cs) `Subscriber.OnNext` is not called on net48.

Is this expected? if so where is it documented?

this is in the context of the `Microsoft.Data.SqlClient` nuget

**Comment by SimonCropp** [comment]
i decompiled all the microsoft.data.sqlclient.dll `net461`, `netcoreapp3.1`, `netstandard2.0`, 
`netstandard2.1`. the SqlClientDiagnosticListener code does not exist in `net461`. 

Looking at the csproj, it seems listener code is only included in `netcoreapp` and `netstandard`?

https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj#L462-L469

```
 <ItemGroup Condition="'$(OSGroup)' != 'AnyOS' AND '$(TargetGroup)' == 'netstandard'">
    <Compile Include="Microsoft\Data\SqlClient\SqlAuthenticationProviderManager.NetStandard.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlDiagnosticListener.NetStandard.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlDelegatedTransaction.NetStandard.cs" />
    <Compile Include="Microsoft\Data\SqlClient\TdsParser.NetStandard.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SNI\SNIStreams.Task.cs" />    
    <Compile Include="Microsoft\Data\SqlClient\SNI\SslOverTdsStream.NetStandard.cs" />
  </ItemGroup>
```

https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj#L508-L518

```
  <ItemGroup Condition="'$(OSGroup)' != 'AnyOS' AND '$(TargetGroup)' == 'netcoreapp'">
    <Compile Include="Microsoft\Data\ProviderBase\DbConnectionPool.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlAuthenticationProviderManager.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlDiagnosticListener.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlDelegatedTransaction.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\TdsParser.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SNI\SslOverTdsStream.NetCoreApp.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SqlConnectionFactory.AssemblyLoadContext.cs" />    
    <Compile Include="Microsoft\Data\SqlClient\SqlDependencyUtils.AssemblyLoadContext.cs" />
    <Compile Include="Microsoft\Data\SqlClient\SNI\SNIStreams.ValueTask.cs" />
  </ItemGroup>
```

**Comment by JRahnama** [comment]
@SimonCropp I am looking into this and will update you soon.

**Comment by SimonCropp** [comment]
@JRahnama thanks. please let me know if u need more help

**Comment by JRahnama** [comment]
@SimonCropp according to [documentation](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.diagnosticlistener?view=net-6.0) diagnostic listener is only available in netcore and not .Net framework that is why we did not add it to netfx and just for netcore.

**Comment by SimonCropp** [comment]
@JRahnama thats weird given the net461 of https://www.nuget.org/packages/System.Diagnostics.DiagnosticSource/ has ` DiagnosticListener.AllListeners.Subscribe(...);`. u can see that it compiles and runs in my repro on net48. I can even debug into it and see a `System.Net.Http.Desktop` listener come through 

![image](https://user-images.githubusercontent.com/122666/156657784-f6faf164-66bc-4cd3-abca-a0f77425ef7d.png)

**Comment by JRahnama** [comment]
@SimonCropp we are talking internally to see if that is supported on netfx and is not added for netstandard support, Either documentation or nuget needs to be fixed. Meantime we do not support DiagnosticListener on .Net Framework at the moment.

**Comment by JRahnama** [comment]
Closing the issue as adding DiagnosticSource to SqlClient netfx is not on the current plan.

**Comment by SimonCropp** [comment]
@JRahnama thanks for the clarrification
