### ISSUE TITLE
SqlFileStream in System.Data.SqlClient 4.6.1

### ISSUE THREAD

**Issue by reflash** [dotnet/SqlClient#153]
I'm trying to use SqlFileStream class, but unable to do so. 
CS0246	The type or namespace name 'SqlFileStream' could not be found (are you missing a using directive or an assembly reference?)

Running on Windows. Project compiled with netcore 2.1. System.Data.SqlClient version is 4.6.1.

**Comment by cheenamalhotra** [comment]
Hi @reflash 

SqlFileStream was added in .NET Core 3.0 as mentioned in #15 ([comment](https://github.com/dotnet/SqlClient/issues/15#issuecomment-517037124)). It's also available in Microsoft.Data.SqlClient previews, you could test with either of the two and that should solve your problem.

**Comment by reflash** [comment]
Hi @cheenamalhotra 

Thank you! I was not aware SqlFileStream wasn't included in earlier versions of netcore, so using Microsoft.Data.SqlClient preview works for me.
