### ISSUE TITLE
GenerateDependencyFile Property Causes PlatformNotSupportedException

### ISSUE THREAD

**Issue by AceCoderLaura** [dotnet/SqlClient#1531]
### Describe the bug

If you set GenerateDependencyFile to false in your project file (like below) you'll receive a PNSE exception.
`<GenerateDependencyFile>false</GenerateDependencyFile>`

```
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor()
   at ClassLibrary1.Class1.ThrowPNSE() in C:\Users\Laura\RiderProjects\SqlClientPNSE\ClassLibrary1\Class1.cs:line 10
   at Program.<Main>$(String[] args) in C:\Users\Laura\RiderProjects\SqlClientPNSE\WebApplication1\Program.cs:line 3
```

### To reproduce
Run this sample project
[SqlClientPNSE.zip](https://github.com/dotnet/SqlClient/files/8176669/SqlClientPNSE.zip)

### Expected behavior
There should be a warning or error in the build log telling me that setting this property to false will cause this problem or if this is not the intended effect of the property, for the correct assembly to be selected when compiling.

### Further technical details
Microsoft.Data.SqlClient version: I tried all versions of Microsoft.Data.SqlClient as well as System.Data.SqlClient from 2.0.1 to latest.
.NET target: .NET 5 and .NET Standard 2.0
SQL Server version: N/A
Operating system: Windows 10

**Comment by JRahnama** [comment]
The fact that `<GenerateDependencyFile>false</GenerateDependencyFile>` is preventing creation of deps.json makes the driver to fall back on lib folder instead of runtime with actual official libraries for different runtimes conditions. Keep in mind that the actual official dlls are inside runtime folder and lib folder is just for fall back.

> There should be a warning or error in the build log telling me that setting this property to false will cause this problem or if this is not the intended effect of the property, for the correct assembly to be selected when compiling.

As far as I know there is no way to get runtime information on compile time to give a warning. I might be wrong and if you know a good way to do so go ahead and make PR . we will review that and it will get merged if gets approved.

**Comment by AceCoderLaura** [comment]
Do we need to detect the runtime if we already know the wrong dlls will be used, provided that the property is false?
Is there a reason something like this can't be done?
```
<Warning Condition="'$(GenerateDependencyFile)' == 'false'" Text="Microsoft.Data.SqlClient requires a deps.json file to resolve the correct assembly, please set GenerateDependencyFile to true." />
```

**Comment by JRahnama** [comment]
As a multi-target driver these files are required to build your project. There is no way we can detect that property from your project at compile time.

**Comment by AceCoderLaura** [comment]
Well at least this behavior is documented somewhere so other people won't waste time figuring this out.
