### ISSUE TITLE
Visual Studio should not recommend the System.Data.SqlClient for dotnet 6 projects

### ISSUE THREAD

**Issue by KSchlobohm** [dotnet/SqlClient#1557]
### Is your feature request related to a problem? Please describe.
While building new code I would like Visual Studio to help me resolve references. When I build a new dotnet 6 console application that references `SqlConnection` it suggests **System.Data.SqlClient**

### Describe the solution you'd like
I would like Visual Studio to guide me to choosing the **Microsoft.Data.SqlClient** package

### Describe alternatives you've considered
I can manually install the package at this time

### Additional context
I was trying to use the newer managed identity connection string features in my project and received the error "Keyword not supported". It would have been nice if that package returned an error saying it didn't support the new managed identity connection strings. I'm not sure if that's a separate issue I should open but the way I resolved the error was to import the correct package.

**Comment by DavoudEshtehari** [comment]
Hi @KSchlobohm,

This query is already running under #1063 thread. You can join the discussion.
Feel free to reopen this issue if you find that unrelated.
