### ISSUE TITLE
SqlClient is not usable via transitive reference with dotnet-sdk 3.0.100-preview8-013656

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/SqlClient#156]
### Describe the bug
Almost the same repo as #137, but use dotnet-sdk 3.0.100-preview8-013656 and see an new bad behavior. 
(Not sure whether it's an issue of sdk, report it here and wait someone to reroute it).

Tested with MS.SqlClient `1.0.19221.1-Preview`, dotnet-sdk `3.0.100-preview8-013656`, net48(runtime).

2. If you use dotnet-sdk(3.0.0-preview8-28405-07), it will perfer ns2 version of SqlClient instead of net46 as it does in 2.2.400, and `dotnet run` failed with System.IO.FileNotFoundException: Failed to load assembly "System.Configuration.ConfigurationManager, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" (`1.0.19189.1-Preview` also not work for me);
> That not happened for dotnet-sdk 2.2.400, other versions of sdk is not tested.

### To reproduce
Still the same repo https://github.com/anurse/SqlClientNotTransitive , just update the version of SqlClient to `1.0.19221.1-Preview`, and run/publish it with dotnet-sdk `3.0.100-preview8-013656`.

### Expected behavior
2. `dotnet run` in dotnet-sdk 3.0.x should success(or `SqlException` if don't change connStr.) as it does in 2.2.4xx;

### Further technical details
Microsoft.Data.SqlClient version: `1.0.19221.1-Preview`
.NET target: net472
SQL Server version: -
Operating system: Windows10 1903

**Additional context**

**Comment by cheenamalhotra** [comment]
Hi @yyjdelete 

This seems to be working fine until **.NET Core 3.0 Preview 7** but failing with **.Net Core 3.0 Preview 8**. 

cc @divega @danmosemsft

**Comment by cheenamalhotra** [comment]
Hi @yyjdelete 

We were able to fix the issue and the fix will be available in GA release for 1.0.
