### ISSUE TITLE
`sni.dll` is not include in the result of `dotnet publish` for netfx

### ISSUE THREAD

**Issue by yyjdelete** [dotnet/SqlClient#157]
### Describe the bug
`sni.dll` is not include in the result of `dotnet publish` for netfx.
Looks like #137, but finally found it also happen with directly reference.

### To reproduce
Tested with MS.SqlClient 1.0.19221.1-Preview/1.0.19189.1-Preview, dotnet-sdk 3.0.100-preview8-013656/2.2.400, net48(runtime).

1. `dotnet new console`;
2. change TargetFramework to net472;
3. `dotnet add package Microsoft.Data.SqlClient --version 1.0.19221.1-Preview`;
4. `dotnet publish`
See `sni.dll` is included in the build result `bin\Debug\net472\x64\SNI.dll` but not the publish result `bin\Debug\net472\publish`. And SqlClient failed to init with the published program as an result.

### Expected behavior
`sni.dll` should also be included with `dotnet publish` for netfx

### Further technical details
Microsoft.Data.SqlClient version: `1.0.19221.1-Preview`
.NET target: net472
SQL Server version: -
Operating system: Windows10 1903

**Additional context**

**Comment by cheenamalhotra** [comment]
Hi @yyjdelete 

The issue is reproducible, we're looking into the fix. Will update you soon!

**Comment by cheenamalhotra** [comment]
Hi @yyjdelete 

We were able to fix the issue and the fix will be available in GA release for 1.0.
