### ISSUE TITLE
SqlClient Traces on Azure

### ISSUE THREAD

**Issue by pfdsilva** [dotnet/SqlClient#1570]
How do I enable and view SqlClient traces on Azure?
I have a web app hosted on Azure and it uses SqlClient.

**Comment by DavoudEshtehari** [comment]
[Enable event tracing in SqlClient - ADO.NET Provider for SQL Server | Microsoft Docs](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver15)
Generally, you can use either PerfView or Xperf depending on the OS in use. 
In case of accessing the source code, you can implement a custom listener.

**Comment by JRahnama** [comment]
@pfdsilva if your questions is answered and you were able to capture traces on Azure please feel free to close the issue.

**Comment by pfdsilva** [comment]
> [Enable event tracing in SqlClient - ADO.NET Provider for SQL Server | Microsoft Docs](https://docs.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver15) Generally, you can use either PerfView or Xperf depending on the OS in use. In case of accessing the source code, you can implement a custom listener.

How do I use PerfView or Xperf to view SqlClient traces when my web app is hosted on Azure?

**Comment by JRahnama** [comment]
@pfdsilva you can get memory dump from azure diagnostics tools and open the file with `PerfView`.

**Comment by JRahnama** [comment]
Closing the issue due to inactivity.
