### ISSUE TITLE
Microsoft.Data.SqlClient doesn't support DataContext from System.Data.Linq, so it can be used with an AAD auth connection string

### ISSUE THREAD

**Issue by Moeahmad94** [dotnet/SqlClient#1576]
Microsoft.Data.SqlClient doesn't support DataContext from System.Data.Linq. This means that we can't move over from System.Data.SqlClient and so can't use AAD auth connection strings using managed identities and are stuck using passwords, increasing our risk surface.

**Comment by JRahnama** [comment]
@Moeahmad94 can you provide a practical repro to elaborate a bit more on the issue?

**Comment by Moeahmad94** [comment]
Hi @JRahnama, the following is an example I'm trying to use in .Net 6:

`
    public class TestDataContext
    {
        public TestDataContext()
        {
            var connectionString = "Server=tcp:PlaceholderSql.database.windows.net,1433;Initial Catalog=PlaceholderDB;Persist Security Info=False;User ID={your_username};MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication=\"Active Directory Integrated\";"
            DataContext = new DataContext(ConnectionString) { ObjectTrackingEnabled = false };
        }
    }`

The issue here is that the DataContext object is only available in the System.Data.Linq nuget package, which doesn't support the "Authentication" keyword in the connection string so we can't use "Active Directory Integrated" authentication.

**Comment by ErikEJ** [comment]
Have you tried using the constructor that takes a SqlConnection instead of a connection string?

**Comment by Moeahmad94** [comment]
Ah, that did it! Took some finagling of nuget packages to resolve a sql
Auth dependency file not found issue but its working now. Thank you so much
for the help!

Moe

**Comment by JRahnama** [comment]
@ErikEJ thanks for the support.

Closing as resolved.
