### ISSUE TITLE
SqlClient: Allow |DataDirectory| macro in AttachDBFilename

### ISSUE THREAD

**Issue by bricelam** [dotnet/SqlClient#16]
Now that .NET Standard 2.0 includes `AppDomain.GetData`, there shouldn't be anything blocking the implementation to expand the `|DataDirectory|` substitution string in the `AttachDBFilename` value of the connection string.

**Comment by SidShetye** [comment]
We're facing this on some of our demo applications after we made them compatible with the recent EF 6.3 release + .NET Core 3.0.

**Comment by Wraith2** [comment]
@ErikEJ has a PR for this at https://github.com/dotnet/SqlClient/pull/284 which looks reasonable it just needs a bit of a push from the MS side i think

**Comment by ErikEJ** [comment]
Yes, it is awaiting review from @saurabh500

**Comment by cheenamalhotra** [comment]
Closing as #284 has been merged and fix will be available in v1.1.0

**Comment by ErikEJ** [comment]
@bricelam Assume this is too late for 3.1 ?

**Comment by bricelam** [comment]
Yeah, but we already have the code to handle |DataDirectory| during CREATE DATABASE in EF Core 3.0.0, so if you just update SqlClient it should all work.
