### ISSUE TITLE
MAUI Android TypeLoadException for first DB call

### ISSUE THREAD

**Issue by janseris** [dotnet/SqlClient#1600]
Hi,
I have been linked to post here from MAUI so I am posting:

Edit: added updated sample project - tested with official MAUI GA version 24/5/2022:
[MauiApp1.zip](https://github.com/dotnet/SqlClient/files/8765580/MauiApp1.zip)

https://github.com/dotnet/maui/issues/6607

When a database is called (and probably happens because the code is in a different project - Data Access Layer) project,
first DB call always fails with this exception:

System.TypeLoadException Could not load type of field 'Microsoft.Data.SqlClient.SqlQueryMetadataCache:_cache' (2) due to: Could not load file or assembly 'System.Runtime.Caching, Version=[4.0.0.0](http://4.0.0.0/), Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.

Every subsequent call works fine.

Everything works fine on Android Debug and on Windows any configuration.
This exception occurs only with internet connection on because when internet is off, a SqlException is thrown.
Steps to Reproduce

Call DB using EF Core 6 from a `Release` Android MAUI app (potentially the DB call occurs in a different project)

**Comment by roji** [comment]
Moving to the SqlClient reop as it seems to be a trimming-related issue there.

**Comment by janseris** [comment]
> Moving to the SqlClient reop as it seems to be a trimming-related issue there.

Thanks for a quick reply. Can this be avoided when not trimming the app? I think I am not trimming it.

**Comment by roji** [comment]
I am not sure, but it may be that trimming is on in Release but not in Debug, explaining why this is work in the latter but not in the former.

**Comment by janseris** [comment]
@roji actually I have trimming off for Release because if trimming is on, the application crashes.

**Comment by roji** [comment]
OK, it could be a non-trimming issue as well...

**Comment by JRahnama** [comment]
@roji thanks for transferring this.

@janseris we will look back to this soon.

**Comment by Kaur-Parminder** [comment]
@janseris What is the target framework of Data Access Layer Project? How are you invoking DAL?
if you can just provide an app with single DB call, I will have idea of your project setup and I can try to reproduce the issue.

**Comment by janseris** [comment]
@Kaur-Parminder 

I have created a sample app and found the following:

The `System.TypeLoadException Could not load type of field 'Microsoft.Data.SqlClient.SqlQueryMetadataCache` exception occurs no matter if the code is called directly from Data Access Layer or from the current project.

**Comment by Kaur-Parminder** [comment]
@janseris I tried out your Repro. I had to add `clr-namespace:Microsoft.AspNetCore.Components.WebView.Maui;assembly=Microsoft.AspNetCore.Components.WebView.Maui` to MainPage.xaml to get it working. 

I can see the errors as shown in image on subsequent attempts, I am testing on emulator. It is using Android Internet, I can see manifest file already have the Internet permissions. 

`<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.net.conn.CONNECTIVITY_CHANGE" />`

I have also applied Release configurations.

I am interested in learning how it works for you on subsequent attempts. Are you using actual Android device to test or emulator
![err3](https://user-images.githubusercontent.com/88398605/167459527-3ea1704d-f851-41f4-befc-7fbe18a14c17.PNG)
?

**Comment by janseris** [comment]
I am using both emulator and real device. The issue occurs only in Release on both emulator and real device.
The issue is for first DB call. There is no issue for any subsequent DB call. The error you receive is not what I was reporting. The error what you got is that you cannot connect. Either the device is offline or the server is offline or the connection string is wrong. I assume that you have to get a connection string to a real SQL Server. I could not give you connection string to my public server.
Is there anything else you need?
Thank you

**Comment by janseris** [comment]
On Android 8.1 and below I receive the following exception and I am not able to call any DB at all:
![image](https://user-images.githubusercontent.com/64279914/170105089-4d8ad57c-318d-47f8-9dc4-04f8318e0f19.png)

**Comment by VictorCanovasA** [comment]
> @janseris I tried out your Repro. I had to add `clr-namespace:Microsoft.AspNetCore.Components.WebView.Maui;assembly=Microsoft.AspNetCore.Components.WebView.Maui` to MainPage.xaml to get it working.
> 
> I can see the errors as shown in image on subsequent attempts, I am testing on emulator. It is using Android Internet, I can see manifest file already have the Internet permissions.
> 
> `<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" /> <uses-permission android:name="android.permission.INTERNET" /> <uses-permission android:name="android.net.conn.CONNECTIVITY_CHANGE" />`
> 
> I have also applied Release configurations.
> 
> I am interested in learning how it works for you on subsequent attempts. Are you using actual Android device to test or emulator ![err3](https://github.com/assets/88398605/3ea1704d-f851-41f4-befc-7fbe18a14c17) ?

Hello @Kaur-Parminder As in your image below i am getting the error "Microsoft.Data.SqlClient.SqlException
  Message=A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)". 
This is happening on Android Emulator but working on Windows Machine in VS 2022 preview (MAUI App .NET 6)

I have all 3 internet permissions. ¿Do you have any idea where the problem is?. Thanks in advance.

**Comment by janseris** [comment]
This error means that you do not run the SQL server which the connection string is connecting to.

**Comment by janseris** [comment]
This seems to be no longer an issue in a different MAUI app of ours.
