### ISSUE TITLE
Error:  The target principal name is incorrect

### ISSUE THREAD

**Issue by jogibear9988** [dotnet/SqlClient#1621]
### Describe the bug

We have a Net6 Programm wich throws this error (In German: "Der Zielprinzipalname ist falsch").

If we you the same software in an older Version wich works with Net4.8 and System.Data.SqlServer the same connection String could access the Database. 
Also Managementstudio could access the DB.

We use "Integrated Security=true" to access the Database.

We also tried to add: encrypt=false to the connection string.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/364896/169984769-bf85e821-30ae-4d33-afdb-9ed745d62a91.png)

**Comment by jogibear9988** [comment]
Got it fixed via adding: 
Trust Server Certificate = true;
to ConnectionString

see:
https://github.com/dotnet/SqlClient/issues/609#issuecomment-645406981

**Comment by JRahnama** [comment]
@jogibear9988 is server setup to force encryption?

**Comment by jogibear9988** [comment]
@JRahnama Don't know... I only know, it worked with the connection sring in net4.8
And it now works after adding: "Trust Server Certificate=true"
