### ISSUE TITLE
Please, allow relative path in json ConnectionStrings for AttachDbFilename when using update-database command

### ISSUE THREAD

**Issue by BDisp** [dotnet/SqlClient#163]
Although we can use string substitution in json file and replace with the string we want, it would be nice during the update-database command and if a AttachDbFilename start with a UNC like =\\Data\\aspnet-WebAppCoreDB.mdf, the possibility of your program get the path of the current project and successfully attach the DB to the server automatically.
Thanks.

**Comment by David-Engel** [comment]
The connection string is not always in the context of a project. If we instead considered CurrentDirectory, that can change over the course of an application's execution. Applications should simply expand the path when needed and provide the entire thing to SqlClient.

Closing this issue as not planned.
