### ISSUE TITLE
Sql Query Through Visual Studio is Very Slow

### ISSUE THREAD

**Issue by hintsofttech** [dotnet/SqlClient#1633]
Dear Sir/Mam,
We are facing Very Slow Sql-Server-Query Performance 
only when run through Visual Studio 
for even very simple select/insert query.

The same issues not being faced on client's pcs.

even formatted laptop several times and on different ssd.
But still no luck.

please suggest how to fix the problem.

Regards-
Sanjeeb

**Comment by Kaur-Parminder** [comment]
@hintsofttech We had similar issue where VS2022 was slow. Please see #1540 . You might have some features enabled that might be causing. if that does not change things for you. Please provide same 'Hello World' level program that shows slowness comparison between the two and we can investigate it further.

**Comment by JRahnama** [comment]
Closing the issue due to inactivity. Feel free to open a new issue or comment here if the problem still exists.
