### ISSUE TITLE
Cannot unload a collectible AssemblyLoadContext if Microsoft.Data.SqlClient v4.x+ or System.Data.SqlClient is used

### ISSUE THREAD

**Issue by rafalkwol** [dotnet/SqlClient#1635]
I'm trying to create a plugin based solution for my application. I created a prototype to check if all the requirements can be met with AssemblyLoadContext API. Everything seems to work fine until I use Microsoft.Data.SqlClient v4.x+ or System.Data.SqlClient as a plugin dependency.

The sample source code is available at: [~~https://github.com/rafalkwol/NetCorePlugins~~](https://github.com/rafalkwol/NetCorePlugins)

In the example solution I have a host project which is .NET Core 5 console application. Other than that I have two plugin projects with EnableDynamicLoading enabled. Each of those plugins have an additional dependency project which have a simple SQL Server database communication (you may need to replace the connection string for testing purpouses). Plugin1 is using Microsoft.Data.SqlClient and Plugin2 is using System.Data.SqlClient - both in currently newest available versions. Additionaly there is a Shared project which have the interface and models used to communicate with plugins.

In the main application flow I load those plugins in a loop (one by one), call the plugin method to execute it's code, than I unload it and wait until it's fully removed from memory and AppDomain. For AssemblyLoadContext I use this NuGet: [https://www.nuget.org/packages/McMaster.NETCore.Plugins/](https://www.nuget.org/packages/McMaster.NETCore.Plugins/). It makes using AssemblyLoadContext a lot easier and from what I recon it's not the source of the issue here.

The issue I have is that Microsoft.Data.SqlClient v4.x+ stays in memory after unloading the AssemblyLoadContext. The same goes for System.Data.SqlClient 4.8.3. Weirdly enough the same code works if I downgrade Microsoft.Data.SqlClient to v3.1. It seems there was something added to Microsoft.Data.SqlClient in the newer versions which makes the library unable to unload fully. The same issue is encountered with System.Data.SqlClient.

It seems to be similar to the issue #414. I'm guessing some kind of regression might have happened in the new version or I'm just missing something obvious. Any input or idea to solve this would be appreciated.

**Comment by JRahnama** [comment]
Hi @rafalkwol, we will look into this after preview release.

**Comment by Wraith2** [comment]
Using the documentation at https://docs.microsoft.com/en-us/dotnet/standard/assembly/unloadability (as well as the dotnet-sos tool to get the sos.dll i need and then loading manually using `.loadby c:\users\Wraith2\.dotnet\sos\sos.dll`) I've dumped the gc roots and SqlClient doesn't turn up in the list, meaning it isn't causing the rooting behaviour as far as I know.

```
0:012> !dumpheap -type LoaderAllocator
         Address               MT     Size
0000020902f10870 00007ff97fe7dc10       48     
0000020902f108a0 00007ff97fe7dd38       24     

Statistics:
              MT    Count    TotalSize Class Name
00007ff97fe7dd38        1           24 System.Reflection.LoaderAllocatorScout
00007ff97fe7dc10        1           48 System.Reflection.LoaderAllocator
Total 2 objects
0:012> !gcroot -all 0x0000020902f10870
HandleTable:
    00000209014F1368 (strong handle)
    -> 0000020902F0AFA8 System.Runtime.Loader.DefaultAssemblyLoadContext
    -> 0000020902F32C68 System.Func`3[[System.Runtime.Loader.AssemblyLoadContext, System.Private.CoreLib],[System.Reflection.AssemblyName, System.Private.CoreLib],[System.Reflection.Assembly, System.Private.CoreLib]]
    -> 0000020902F10870 System.Reflection.LoaderAllocator

    00000209014F13E8 (strong handle)
    -> 000002091AF01018 System.Object[]
    -> 0000020902F0AFA8 System.Runtime.Loader.DefaultAssemblyLoadContext
    -> 0000020902F32C68 System.Func`3[[System.Runtime.Loader.AssemblyLoadContext, System.Private.CoreLib],[System.Reflection.AssemblyName, System.Private.CoreLib],[System.Reflection.Assembly, System.Private.CoreLib]]
    -> 0000020902F10870 System.Reflection.LoaderAllocator

    00000209014F1DF8 (strong handle)
    -> 0000020902F10678 McMaster.NETCore.Plugins.Loader.ManagedLoadContext
    -> 0000020902F0AFA8 System.Runtime.Loader.DefaultAssemblyLoadContext
    -> 0000020902F32C68 System.Func`3[[System.Runtime.Loader.AssemblyLoadContext, System.Private.CoreLib],[System.Reflection.AssemblyName, System.Private.CoreLib],[System.Reflection.Assembly, System.Private.CoreLib]]
    -> 0000020902F10870 System.Reflection.LoaderAllocator

Found 3 roots.
```

**Comment by rafalkwol** [comment]
It seems there are some handles held by DefaultAssemblyLoadContext, ManagedLoadContext and an array of objects. I'm not sure if it's correct behaviour of AssemblyLoadContext implementation or not. The weird thing is that if I'm not using Microsoft.Data.SqlClient or System.DataSqlClient the issue is not there. Also older version of Microsoft.Data.SqlClient seems to work fine.

From what I gather in the documentation you linked there seem to be another command to analyze thread frames:

`~*e !clrstack`

Maybe there is something on another thread inside SqlClient that is holding the reference?

**Comment by rafalkwol** [comment]
It seems the issue is somewhere in the NuGet as I couldn't seem to figure out the source of the issue. I resolved my problem using a different solution so I'm closing this issue.
