### ISSUE TITLE
Project board not updated

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#1636]
As a contributor and user it is useful to see progress via the project board, but it seems be [neglected](https://github.com/dotnet/SqlClient/projects/9) - ie many merged PRs are not in the Done lane, making it useless. 

Would be nice with an update...

**Comment by JRahnama** [comment]
@ErikEJ thank you, I will look into this today.

**Comment by JRahnama** [comment]
@ErikEJ I am closing this as I think we have updated the board. Let us know if there is something missed in the process.
