### ISSUE TITLE
Configurable command retry logic from appsettings.json

### ISSUE THREAD

**Issue by mcavanagh** [dotnet/SqlClient#1640]
The ability to define retry logic from configuration is described here: https://docs.microsoft.com/en-us/sql/connect/ado-net/configurable-retry-logic-config-file-sqlclient?view=sql-server-ver16#command-section

However, it's using the XML config format.  Is it possible to define the same config rules but with an appsettings.json as found in a typical asp net core app?

I took a best guess at what the json version might look like, and tried this:

```
{
  "SqlConfigurableRetryLogicCommand": {
    "NumberOfTries": 3,
    "DeltaTime": "00:00:03",
    "RetryMethod": "CreateExponentialRetryProvider"
  }
}
```

but no luck.  Am I going about this all wrong, or is there a way to supply the equivalent config from a json appsettings file?

**Comment by JRahnama** [comment]
@mcavanagh we will look into this after the release.

**Comment by JRahnama** [comment]
@mcavanagh I am closing this as this is not in our plan yet. We may come back to this later if more people from community request the feature.

**Comment by gpolcode** [comment]
@JRahnama or @DavoudEshtehari I have a similar issue.
What is the intended way of using the .net cores configuration system and using this retry configuration?

**Comment by DavoudEshtehari** [comment]
A solution for using appsettings.json file would be implementing your own logic through an extension method over the configuration type. Or you can implement any solution that fits your project using the exposed APIs.
