### ISSUE TITLE
Improve error message for entrypt=strict

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#1651]
5.0 preview 3 with encrypt=strict

Getting this now (none of the "possible causes" apply)

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The client was unable to establish a connection because of an error during connection initialization process before login. Possible causes include the following:  the client tried to connect to an unsupported version of SQL Server; the server was too busy to accept new connections; or there was a resource limitation (insufficient memory or maximum allowed connections) on the server. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.
```

**Comment by JRahnama** [comment]
@ErikEJ couple of questions, although you mentioned none of the possible causes apply, just to confirm:

1. You have a SSSL/TLS server certificate installed?
2. Your connection string provides the exact, FQDN, as "Data Source" or you have defined a HostNameInCertificate?

Just keep in mind no matter what, when you select `Encrypt = SqlConnectionEncryptionOption.Strict` in `SqlConnectionStringBuilder` or just `Strict` in `SqlConnection` constructor as a string, `TrustServerCertificate` is useless and is set to false. The certificate has to be validated.

**Comment by ErikEJ** [comment]
Neither. The actual Win32Exception message points me in the right direction.

**Comment by ErikEJ** [comment]
Unimportant
