### ISSUE TITLE
Protocol Version for TDS 8.0 connection

### ISSUE THREAD

**Issue by MasayukiOzawa** [dotnet/SqlClient#1652]
Connect to SQL Server 2022 CTP 2.0 with TDS 8.0 with `Encrypt=Strict` and get the Protocol Version with the following query.
```
select 
ec.connect_time,es.last_request_start_time ,es.session_id, 
(CAST(protocol_version AS BINARY(4))),
es.program_name, es.client_version, ec.protocol_type,ec.protocol_version,
es.client_interface_name,ec.encrypt_option
from sys.dm_exec_sessions as es
inner join sys.dm_exec_connections as ec
	on ec.session_id = es.session_id
order by connect_time desc
```
 When I connect with `Encrypt=Strict`, I expect a TDS 8.0 connection, but the query results in a TDS 7.4 connection.
![image](https://user-images.githubusercontent.com/5971957/174478136-7821b4d8-ecd6-44fa-879a-676310f390fc.png)

Even if `Encrypt=Strict` is specified, the Protocol Version obtained from SQL Server is TDS 7.4, does this mean that you are not able to connect with TDS 8.0?
Or is it a problem with the display of the Protocol Version of SQL Server 2022 CTP 2.0?

environment
- SQL Server: 2022 CTP 2.0 (16.0.600.9)
- SQL Client Version: Microsoft.Data.SqlClient 5.0.0-preview3 22168.1

**Comment by JRahnama** [comment]
@MasayukiOzawa this could be a SQLServer 2022 issue for not showing the actual version number, but let me do more testing and I will get back to you soon.

**Comment by MasayukiOzawa** [comment]
Thanks for the information.
Should I present this question as feedback for SQL Server 2022?

**Comment by David-Engel** [comment]
> Should I present this question as feedback for SQL Server 2022?

No need. The server team is already aware of the issue and plans to address it before RTM.

**Comment by MasayukiOzawa** [comment]
It appears that the server team is already aware of this issue, so we will close it.
Thanks to all who commented.
