### ISSUE TITLE
5.0.0 deployments seems to ship an win-arm runtime folder.

### ISSUE THREAD

**Issue by AraHaan** [dotnet/SqlClient#1653]
### Describe the bug

The bug is that the 5.0.0 deployments seems to ship an win-arm folder. If I remember right I thought the .NET SDK dropped 32 bit ARM support for a total support of only: win-x86, win-x64, and win-arm64.

### To reproduce

Build any project that references the latest SqlClient build.

### Expected behavior
For the win-arm folder to not be created under the ``runtimes`` folder in the project build outputs.

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: 6.0
SQL Server version: SQL Server 2019
Operating system: Windows 11 21H2

**Additional context**
N/A (I think)

**Comment by JRahnama** [comment]
@AraHaan we are currently using netcoreapp3.1 to build the driver when the support for net6 is added we will drop that I think.

**Comment by lcheunglci** [comment]
I believe the changes to drop arm86 was available in the `5.1preview2` release according to the [release notes](https://github.com/dotnet/SqlClient/releases/tag/v5.1.0-preview2) specially from SNI update.

**Comment by JRahnama** [comment]
Closing the issue as it has been fixed.
