### ISSUE TITLE
SqlClient version 4.1.0 connection database SqlServer version 2008 error

### ISSUE THREAD

**Issue by 563256676** [dotnet/SqlClient#1659]
When I use SqlClient version 4.1.0 to connect to the database of SqlServer 2008 version, there is a problem in getting the columns of the table, but the same code to connect to SqlServer 2022 is normal. Does version 4.1.0 not support 2008? It is the lowest What are the supported versions?

**Comment by ErikEJ** [comment]
What error are you seeing?

**Comment by DavoudEshtehari** [comment]
The SQL Server 2008 and earlier versions are out of support. We no longer test those versions.

**Comment by Wraith2** [comment]
> The SQL Server 2008 and earlier versions are out of support. We no longer test those versions.

True, but we also should know if we broke something so a test case would be useful.
