### ISSUE TITLE
Reconsider throwing errors by default when the server uses a self-signed certificate

### ISSUE THREAD

**Issue by airbreather** [dotnet/SqlClient#1669]
In 4.0, there was an intentional breaking change to enable encryption by default on connections.  I wholeheartedly appreciate the intent: I truly believe that all internet traffic should be encrypted in transit by default.

Now, as I understand it, SQL Server instances use self-signed certificates by default unless they are intentionally set up otherwise.  As far as I can tell, whenever **any** SSL/TLS encryption is in use in **any** application, for some reason there seems to be this ingrained assumption that people therefore need to be screamed at if there is a potential for MITM attacks, presumably because that's a problem that SSL/TLS encryption **could** solve, and therefore the user **might** be using SSL/TLS encryption for that reason.

So that brings us to a world today that looks something like:

|`Encrypt`|Does the server actually use a self-signed cert?|`TrustServerCertificate`|Can packet sniffers steal your data?|Is MITM viable?|Do we throw any errors because MITM is viable?|
|-|-|-|-|-|-|
|`False`|*|*|Yes|Yes|No|
|unspecified or `True`|No|*|No|No|No|
|unspecified or `True`|Yes|unspecified or `False`|No|Yes|Yes|
|unspecified or `True`|Yes|`True`|No|Yes|No|

So in other words, in all versions of `Microsoft.Data.SqlClient` prior to 4.x, as well as all versions of `System.Data.SqlClient` dating back to when it was first added to .NET Framework 1.x, without any explicit action taken by someone in charge of creating a `SqlConnection` (or writing the corresponding connection string), an unsophisticated packet sniffer could easily steal your data over the wire, and a sophisticated attacker could even alter the data in transit without you ever knowing anything.

Starting with 4.x, `Microsoft.Data.SqlClient` has changed that so that connections by default are less vulnerable to unsophisticated attacks, and in many cases they are **also** less vulnerable to the sophisticated attack I described above (depending on server configuration), but connections to many servers are still just as vulnerable as they have always been.

To be more explicit, the part of this situation that's weird to me is that 4.x and higher are **more secure in all cases** by default, but then there are **some cases** where 4.x and higher aren't **even more extra secure than that**, and it's the fact that we aren't **even more extra secure** that leads to **more error messages about security** even though we're **more secure than ever**.

As someone who has been developing .NET applications using SQL Server databases for over 10 years, I find it odd that I am required to engage with this topic, especially since all our SQL Server instances are only accessible through either intranet or VPN.  I would understand it a bit more if I were **opting-in** to encryption, as you have no way of knowing my intentions for doing so (do I intend for encryption to be a defense against MITM attacks, or do I just want to thwart unsophisticated packet sniffers?).

Is there a viable path that can get us to a world that looks something like:
|`Encrypt`|Does the server actually use a self-signed cert?|`TrustServerCertificate`|Can packet sniffers steal your data?|Is MITM viable?|Do we throw any errors because MITM is viable?|
|-|-|-|-|-|-|
|`False`|*|*|Yes|Yes|No|
|unspecified or `True`|No|*|No|No|No|
|unspecified or `True`|Yes|**specified** as `False`|No|Yes|Yes|
|**specified** as `True`|Yes|unspecified or `False`|No|Yes|Yes|
|unspecified|Yes|unspecified or `True`|No|Yes|No|

Considering each of those scenarios from the perspective of someone upgrading from `System.Data.SqlClient` or from `Microsoft.Data.SqlClient` pre-4.x, everything that used to work before is going to continue to work going forward (unless my workflow involves using Wireshark to sniff packets entering / leaving my own system, but I certainly don't want to advocate for avoiding [**every** conceivable breaking change](https://xkcd.com/1172)).

Compared to `Microsoft.Data.SqlClient` 4.x and what I've observed from preview of 5.0.0 so far, the only people who will be negatively impacted are those who **implicitly** rely on **both** the encryption **and** the MITM protection offered by encryption.  I honestly can't advocate for this group, but I suspect that people who specifically need the full range of protections offered by TLS will accept that they will have to opt-in to them, as long as they're made aware of it.

Thoughts?

(edit 1: make the new proposed behavior the last row in the table, instead of sandwiching it between two "current behavior" rows)
(edit 2: fix a mistake on one of the rows.  it's when `TrustServerCertificate` is unspecified or **`False`** that should error out)

**Comment by David-Engel** [comment]
If you encrypt without validating the certificate, all you are protecting against is eavesdropping. Unless you trust every device between a client and server, you can't be sure one of them isn't proxying your entire conversation and using its own certificate (which you are blindly trusting) to read your data.

This proposal goes backwards and will not pass a security review.

**Comment by airbreather** [comment]
> If you encrypt without validating the certificate, all you are protecting against is eavesdropping. Unless you trust every device between a client and server, you can't be sure one of them isn't proxying your entire conversation and using its own certificate (which you are blindly trusting) to read your data.

Yes, I believe that I have acknowledged this using different words ("packet sniffing" instead of "eavesdropping", "MITM" instead of "proxying your entire conversation [] to read your data").  At least, I sure **hope** that I have...

As a developer who **strictly** works with SQL Server instances that are **strictly** accessible from within our corporate intranet anyway, I don't have a tangible reason to give encryption much more than a passing consideration.  This has been true for over a decade of my direct experience with my current employer and for (I think) just about as long before I showed up.  We didn't encrypt, because we didn't need to.  To my knowledge, that entire time, every database server instance has been set up without taking any particular extra steps to ensure that someone who wanted to opt-in to using SSL/TLS would be able to fully benefit from it.

Without publicizing things I might not be allowed to divulge, a (somewhat shallow) analysis of our particular risk profile suggests that if an attacker is able to gain enough access to be able to pull off the kinds of attacks that `TrustServerCertificate=False` uniquely protects against, then as far as I'm concerned, they already have an unacceptable degree of control.
- I will concede that I have not given this specific hypothetical situation the same degree of thorough analysis that I would have given it if I were actually tasked with analyzing our exposure to this particular risk.  My analysis feels less than bulletproof, and it's very possible that there is a nonzero (probably still negligible) benefit to `TrustServerCertificate=False` in this situation.

Now, from my own selfish perspective, **I really don't mind** setting `TrustServerCertificate` to `True` on my connection strings.  It is very easy for me, in my current position at my organization, to explain that — while setting this value this way objectively opts-out of something that would have improved security if it were working — this is actually a consequence of the system as a whole being significantly **more** secure than it had been in earlier versions when we had left encryption unspecified, and that if we wanted to go above and beyond to improve our security even further than that, "here's how to do it".  In fact, as a nice little side benefit, this thread is already helping me with that: it gives me a nice little URL I can link to where I've already explained all the considerations that went into why I've already started setting this flag in something that isn't a one-off on my own workstation :smiling_imp:.

So why would I make a bit of a fuss over having to set a flag that does exactly what I want to do?  It's because this is (*I presume, based on my training and experience*) another facet of the same environment where we say things like this:

> This proposal [] will not pass a security review.

In my experience, it seems that there's one surefire way to jettison nuance from any discussion about some software development feature or another, and that's to make it smell like Option A is "more secure" and Option B is "less secure".  If that smell can stick, then Option B is almost invariably dead in the water, regardless of what other non-security considerations there are, as long as Option A isn't absolutely outlandishly unworkable.
- I realize, reading through my comment, that this bit in particular might be misunderstood as a preemptive response to a security review that hasn't even happened yet.  That's not something I want to say here at all.
- I'm referring to the general way in which organizations treat "security".  Your team might conduct a security review of this proposal and decline on some basis or another (and I of course have no specific reason to doubt the process at this point), whereas another organization might see just the parts of the result that they have to engage with and then **because the spotlight is shining on that code now**, they decide that the only permitted way forward is to stop all forward progress until they can get fully trusted certificates onto database servers (for all I know, some might wind up having to set up entirely new infrastructure to publish certificates for this), because "that's better than explicitly turning off security", [regardless of whether or not the increased security protects against any potential threats that they should **actually** take seriously](https://xkcd.com/463).

Back to direct relevance, if the following two were my only available choices, I probably wouldn't type a zillion-word essay:

- Set `TrustServerCertificate` to `True`, or
- Start the process of getting our IT / DBA folks to configure all SQL Server instances to encrypt data using up-to-date certificates signed by our root cert that all our machines trust, where "up-to-date" means that every such certificate almost certainly needs to be renewed frequently on a very short cadence because (again) nuance is gone because the word "security" showed up.
    - *OK, that last bit isn't **completely** fair.  Renewal can absolutely be automated, and any IT organization worth its budget can figure out how to do this without ongoing investment, so the relatively small ongoing benefits of having certificates that expire after a short while are easily worth the ~zero marginal cost of doing so.*

At first glance, these probably look like the only two options that someone in my position would have to choose between, and it's hard to argue that this is a particularly bad place to be in.  However, those aren't the only options.  There are others:
- Hold `Microsoft.Data.SqlClient` back at 3.x because upgrading to 4.x breaks our code ("just like going from .NET Core 2.1 to .NET Core 3.1 did, remember?  .NET isn't perfectly backwards-compatible anymore, we've gone over this, sometimes you have to stay on the old versions of things for a while, and it's great that we can do that on our own terms now... remember how much .NET Framework 4.5 broke our stuff and we had to fix it immediately instead of working on that time-critical feature?").
- Set `Encrypt` to `False`, which may be **easier** to justify than setting `TrustServerCertificate` to `True` because "that's how it always worked before, we just have to opt-in to it now" is a familiar, nuance-free, and **completely accurate** way to describe the situation, whereas "this alternative gets us some of the advantages of the feature without completely opting-out of it" invites a lot more of a nuanced discussion in a context where nuance is often discouraged.
- Switch back to `System.Data.SqlClient` because that library is stable and won't break our stuff when we try to upgrade.
    - From a security standpoint, this is clearly exactly the same as the previous bullet point, because we get the same effect as setting `Encrypt` back to `False`, but it's perfect for getting something past a code reviewer who would otherwise pull the fire alarm if they saw a "make us be less secure" line (nuance, blah blah blah).
    - From a "lazy developer whose just got burned by the faster-moving `Microsoft.Data.SqlClient` library breaking things in the past few years that used to work for decades" perspective, it's comforting that I can go back to the more familiar thing that I've used forever and leave all that "move fast and break things" junk to the kids these days.

Despite the fact that I think these last three options are Bad Ideas™, each of them seems either **easier to implement**, **easier to discover**, or **easier to justify** (to some stakeholders) than either of the two "do it right" options listed above, which smells to me like a failure at achieving "Pit of Success".  As such, I feel a responsibility to at least draw some attention to this situation.

**Comment by JRahnama** [comment]
closing the issue as this goes backwards and will not pass a security review.
