### ISSUE TITLE
Build and project queries

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#167]
I've cloned and followed the build instructions. It's quite chatty at the moment which probably helps with debugging and it almost works. What stops it is that the netcore project has xml comments enabled and is complaining that a lot of items are missing xml comments, 800+ of them. Some of these are new types from netfx and some are old that have been around a while. Is it a project goal to have the documentation complete? If not can we change the build to suppress the xml doc warnings/errors?

The project is split into two totally different branches for netfx and netcore. This is quite different to the corefx version which was built for two targets but had one set of source. Having two complete sets of source will make maintenance and changes more time consuming and error prone. Is this the final configuration for the repository? If so can you give me some detail about why this approach was chosen?

I've checked on a couple of my PR's that were open in corefx for bug fixes and those haven't been pulled into the 1.0 version. Do I need to get back over my PR history in corefx and diff those changes into this project?

Are there plans (however rough) for a release cadence that you can comment on? How often will official builds be made available on nuget?

**Comment by ErikEJ** [comment]
>> Is this the final configuration for the repository? If so can you give me some detail about why this approach was chosen? 

and

>> Are there plans (however rough) for a release cadence that you can comment on? How often will official builds be made available on nuget?

**Comment by Wraith2** [comment]
> For porting activities, yes the remaining PRs were flagged for porting post GA, feel free to port them over here, if you have availability!

It's not just open PRs. For example https://github.com/dotnet/corefx/pull/35549 was merged in march and those changes aren't in this codebase. Will I need to back through all my previous changes and port them over again? How far back do I go?

I've got 10+ branches for performance improvements on the corefx version that I've been holding back to try not to complicate the porting process. Some of those are very complex and I'll now have to reimplement them twice. This additional complexity seems unnecessary at the moment given that the original corefx source build from a single location.

**Comment by Wraith2** [comment]
I thought the intention for this library was to be a single package which contained a unified SQL ADO driver for netfx core and netstandard. Have I misunderstood? is this not the intent?

It looks and reads like we've just got the code for the two totally separate libraries with no attempt to merge them, if that's the case why did it take so long to publish the code?

**Comment by David-Engel** [comment]
> I thought the intention for this library was to be a single package which contained a unified SQL ADO driver for netfx core and netstandard. Have I misunderstood? is this not the intent?
> 
> It looks and reads like we've just got the code for the two totally separate libraries with no attempt to merge them, if that's the case why did it take so long to publish the code?

SDS shipped with .NET Framework and we are not able to add features there anymore. So the main intention is to have a package we can implement new features in, supporting both .NET Framework and .NET Core (the .NET Core implementation also supports .NET Standard). There is still a huge customer base on .NET Framework who would like to get the latest SQL features.

As for why it took so long, there are many reasons. A few of them are the many tentacles SDS had deep into .NET, building up new build and test pipelines, porting features and tests from Framework to MDS, keeping up with PRs from Core, going through iterations of trying to support back-compat features in unique but ultimately discarded ways, changing the namespace, separating the native and managed code on the Framework side, removing closed source code, building new packages supporting the unique needs of SqlClient, migrating from ADAL to MSAL, packaging and indexing symbols, migrating documentation, setting up localization, working out licensing issues, etc. We originally thought we could get it done by May but it turned out to be a lot more work.

**Comment by Wraith2** [comment]
Ok. So on to what next.

Looking at the codebases there's a lot in there that's similar and I think that working towards a unified codebase for the drivers is possible but a long job with a lot of compatibility testing required. Is this something you'd support doing and if so how would you prefer it to be implemented? The goal would be to have all tfm's present all features and for changes in one to be quickly easily and  automatically (where possible) be reflected in the others.

I think start by identifying shared files and moving them to a common location so both projects share them. Once done we'll have files with implementation specific behaviour neatly segregated and we can investigate how to align those implementations or keep them split in the leanest way possible. I usually like the corefx method of doing this by using project conditions and avoid #defines where possible.

**Comment by Wraith2** [comment]
Looking through the codebases some more a few more questions of policy and how we can contribute occur to me.

1. Should everthing be using the current corefx style of formatting (netfx code is using java style bracing.) and if so would you agree to taking a copy of the corefx editorconfig file and putting it hight enough up in the repo to affect everything? Then we could to fairly straight forward automatic format updates which would resolve a lot of differences in trivial files.
2. there are places where sql version specific checks are made and i've found at least one difference so far between core and fx in an isYukon (2005) check. This leads to two questions. Can we get a list of the supported SQL server targets so we can harmoize these checks, and can we rename these symbols from internal codenames to external marketting identifiers?.
3. I (and perhaps others) are looking to see how we contribute to this project in a co-operative way rather than just running off and doing my own thing which might cause conflicts. There's still a lot of performance work i've got mapped out that i'd like to bring into the project but i'd like to know if i can do so for all users and not just the netcore users.

**Comment by ErikEJ** [comment]
re 1: Yes, that would be a good step towards enabling code sharing between the two code bases

re 3: Would improving code sharing not help with this?

**Comment by Wraith2** [comment]
1. Yup, just need to know if that's an agreed way to go. and 3. yes to some extent. The managed implementation doesn't exist in desktop at all in desktop and lags in performance but it's the only true open implementation which is an important consideration or some consumers, all other implementations use a closed source native component.

**Comment by ErikEJ** [comment]
Maybe potential contributors could benefit from a wiki post with all this vital information?

**Comment by Wraith2** [comment]
Oh, and no Always Encrypted support on netstandard?

**Comment by ErikEJ** [comment]
Netstandard ?? Assume you mean .NET Core? And is it not supported now? Or do you mean native versus open source implementation?

**Comment by Wraith2** [comment]
I decided to sync the ref projects so the differences were clearer. the AE classes and members are conditionally included in the netcore build but not in the netstandard build. So if you add M.D.SqlClient to a netstandard TFM project you won't see the AE members and thus be unable to use it. Presumably since you can use AE on netcore unix the implementation is entirely portable so it may just be a mistake.

**Comment by David-Engel** [comment]
1. We have a task to configure coding style and apply it to all the existing code. @cheenamalhotra is working on it.
2. It will be in the documentation that we are working on, but SQL Server version support follows what SQL Server versions are still in support at the time of release. So SQL Server 2012 and up for 1.0. I am not against renaming those symbols. It may be possible to just remove some/most of them.
3. I know you like perf work. The managed SNI layer is the obvious target for improvement and doesn't require working in both netfx and netcore. If it can be brought to perf and stability parity to the native SNI layer, that would be awesome. Anything that can move us towards a fully managed stack across platforms.
My understanding is that netstandard is missing certain encryption dependencies required by AE:
https://github.com/dotnet/SqlClient/blob/master/release-notes/1.0/1.0.19249.1.md#always-encrypted
I have a question out to the AE team about what exactly those dependencies are.

**Comment by cheenamalhotra** [comment]
Listing items here so we can resolve this issue:

- [ ] Configure Coding Style with .editorconfig - Done
- [ ] Roadmap transparency in Repository Docs and GitHub Projects - Done
- [ ] .NET API Reference documentation for Microsoft.Data.SqlClient - In Progress
- [ ] Porting PRs from CoreFx - In Progress
