### ISSUE TITLE
Migrate to NegotiateAuthentication for GSSAPI authentication on .NET 7

### ISSUE THREAD

**Issue by filipnavara** [dotnet/SqlClient#1670]
### Is your feature request related to a problem? Please describe.
Currently SqlClient uses custom interop to call into the System.Net.Security.Native interop on .NET Core / 5 / 6. This is an internal API that is not intended for public consumption. It was previously broken on at least one occasion (https://github.com/dotnet/runtime/commit/e334603d8230873b91fde94210acaca19c710e72).  On .NET 7 a new public `NegotiateAuthentication` API was added (https://github.com/dotnet/runtime/issues/69920, https://github.com/dotnet/runtime/issues/70909) to address the scenarios. Furthermore, the `NegotiateAuthentication` is supported on platforms like Android where the native GSSAPI shim is not available.

### Describe the solution you'd like
Remove any interop dependency on `System.Net.Security.Native` for .NET 7 and newer, migrate to `NegotiateAuthentication` API instead.

**Comment by JRahnama** [comment]
@filipnavara thanks for bringing this up. We would love to do so, but there was no proper solution to address the issue. We have some conversations with related teams. We probably wait till Netcoreapp 3.1 is out of support by the end of this year and Net7 GA is released.

**Comment by filipnavara** [comment]
Presumably fixed by https://github.com/dotnet/SqlClient/pull/2063.
