### ISSUE TITLE
Too Many TimerQueueTime objects retained by DBConnectionPool of sqlClient

### ISSUE THREAD

**Issue by arthurvaverko-kaltura** [dotnet/SqlClient#1674]
We are running an API server that is using Microsoft.Data.SqlClient 4.1.0
The api is async all the way and here is a sample that runs a stored procedure.

```csharp
            using (var con = new SqlConnection(sConn))
            {
                try
                {
                    await con.OpenAsync().ConfigureAwait(false);
                    command.Connection = con;

                    IEnumerable<T> result;
                    
                    var queryParams = new DynamicParameters(m_Parameters);
                    result = await con.QueryAsync<T>(procedureNameWithDbVersionPrefix, queryParams, commandType: CommandType.StoredProcedure).ConfigureAwait(false);


                    await con.CloseAsync().ConfigureAwait(false);
                    return result;
                }
                catch (Exception ex)
                {
                    LogException(ex);
                    return null;
                }
            }
```

.NET target: Core 3.1

over time with a load of 5K requests per second we are seeing our service ramps up to 80% cpu and then keeps rising even though the load is the same .. until process gets to 100% cpu.
in addition memory keep rising and over 15 min it gets to to ~1.2Gb 

then we took a mem dump and this is the result
![image](https://user-images.githubusercontent.com/3643617/179984158-4ed9300a-1adc-4062-86cd-0fef38f9b78d.png)

after inspecting this TimerQueueTimer in perfView we see this ref:
![image](https://user-images.githubusercontent.com/3643617/179984459-ef1146ee-c95e-48ff-a7fb-61619c9b7223.png)

what could cause such a behavior ?

**Comment by ErikEJ** [comment]
What happens if you remove Dapper from your sample code?

**Comment by DavoudEshtehari** [comment]
Closing the issue since it's not a SqlClient issue. 
Feel free to reopen it or keep posting here.
