### ISSUE TITLE
.NET Standard support for ADOMD and Analysis Services

### ISSUE THREAD

**Issue by bencyoung** [dotnet/SqlClient#170]
Are there any plans to implement an equivalant library for ADOMD support and Analysis Services? It's one of the few libraries we don't currently have an alternative for and I'm not found any announcements stating that it will be ported at any time?

**Comment by David-Engel** [comment]
No idea. That would be an entirely different group from us. You could try contacting them via the Contact Owners link on their NuGet:
https://www.nuget.org/packages/Microsoft.AnalysisServices.AdomdClient.retail.amd64/
or via SQL Server feedback:
https://aka.ms/sqlfeedback
