### ISSUE TITLE
i'm confused..

### ISSUE THREAD

**Issue by koolinoor** [dotnet/SqlClient#1732]
is that supposed to be like a new System.Data.SqlClient ? or why does it share the same namespace, 
except have a tons of unnecessary assemblies attached to it?

congrats!

**Comment by taspeotis** [comment]
Not sure the premise of this question is correct - it's a different namespace. This is `Microsoft.Data.SqlClient` which is not shared with `System.Data.SqlClient` by virtue of being different.

[The dependencies](https://www.nuget.org/packages/Microsoft.Data.SqlClient#dependencies-body-tab) are pretty normal for a Microsoft package, pulling in other Microsoft packages.

There's a discussion about this library (`Microsoft.Data.SqlClient`) and its predecessor (`System.Data.SqlClient`) and a successor of sorts [here](https://github.com/dotnet/datalab/issues/6). You can also dig up the blog posts announcing `Microsoft.Data.SqlClient` for more info about its purpose.

**Comment by ErikEJ** [comment]
System.Data.SqlClient also had many dependencies, but they were part of .NET Framework installed on every Windows machine.

**Comment by ErikEJ** [comment]
Please adhere to the code of conduct.

**Comment by roji** [comment]
Seems like this is largely a duplicate of #1108

**Comment by koolinoor** [comment]
You know fuck that! Fuck you, your political correctness, and your cursory fanboys. 
There are about 400M downloads of System.Data.SqlClient.. 400 apps relying on this SLA. 
Now why do you have to take a perfectly functioning, isolated and independent component; 
And mix it up with the rest of your shit-sauce?! 
What about the S in SOLID?
Should have known better, and gone with the Java from the get go. God damn!

**Comment by ajcvickers** [comment]
@koolinoor Your comment has been deleted since it does not adhere to the [code of conduct](https://dotnetfoundation.org/about/code-of-conduct) for this repo.
