### ISSUE TITLE
Inconsistent documentation

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#1736]
The docs for `Host Name In Certificate` seems to not follow the standard version indication pattern used in the connection string docs:

![image](https://user-images.githubusercontent.com/4169187/186090951-ecf112a8-a0f2-42d0-a3a9-e820c50a0ecb.png)

https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-4.1

**Comment by JRahnama** [comment]
@ErikEJ do you mean the section for v5.0 is not added to the documentation?

**Comment by lcheunglci** [comment]
I think @ErikEJ means changing the `Available starting in version 5.0.` in `HostNameInCertificate` to `(Only available in v5.0+)` to keep it consistent with the existing 2 entries for `FailoverPartnerSPN` and `ServerSPN`.

**Comment by ErikEJ** [comment]
@lcheunglci Exactly!

**Comment by JRahnama** [comment]
We did not have those features, HNIC or new Encrypt options, in v4.1. Should that show on that version's documentation at all?

**Comment by ErikEJ** [comment]
@JRahnama maybe not. But seems like a minor point In time issue.

**Comment by JRahnama** [comment]
@ErikEJ thanks for continuous support on the driver.

I am closing this as the PR has been merged, but the documentation will be updated probably on our next release.

**Comment by ErikEJ** [comment]
You are welcome. Always happy to help improve the driver and the UX.
