### ISSUE TITLE
Use better link for AAD auth 

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#1737]
Currently the "Authentication" keyword links to this page: https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnection.connectionstring?view=sqlclient-dotnet-standard-4.1

I think it would be much more helpful with a link to https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16 - but the page above does not even have a link to this helpful page.

This could be adressed in the docs here, or on the first page above. Not sure which is better.

**Comment by JRahnama** [comment]
Thanks @ErikEJ. We will look into this.

**Comment by JRahnama** [comment]
@ErikEJ The Authentication keyword from VS? Where is that Keyword located?

**Comment by ErikEJ** [comment]
Sorry - link is from the ConnectionString docs, the Authentication keyword.

**Comment by JRahnama** [comment]
@ErikEJ thanks for continuous support on the driver. 

I am closing this as the PR has been merged, but the documentation will be updated probably on our next release.
