### ISSUE TITLE
I think this might be a duplicate of #1656

### ISSUE THREAD

**Issue by gshzr** [dotnet/SqlClient#1745]
I think this might be a duplicate of #1656

_Originally posted by @lcheunglci in https://github.com/dotnet/SqlClient/issues/1740#issuecomment-1227454284_

it's not work

**Comment by JRahnama** [comment]
@gshzr  Can you follow the issue on the original one and close this one please?

**Comment by JRahnama** [comment]
Closing as duplicate. Please follow the progress and comments on the main issue.
