### ISSUE TITLE
Microsoft.Data.SqlClient 4.1.0 error - provider: SSL Provider, error: 0 - The target principal name is incorrect

### ISSUE THREAD

**Issue by qizu0302** [dotnet/SqlClient#1753]
I met this 
_SqlError: 'A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The target principal name is incorrect.)'    Source: 'Framework Microsoft SqlClient Data Provider' Number: -2146893022 State: 0 Class: 20 Procedure: '' LineNumber: 0 Server: 'sql'_ 
when I establish a connection from SharePoint to SQL server. SharePoint is using Microsoft.Data.SqlClient lib while SQL Server is still using System.Data.SqlClient.

**I create a self-signed cert on sql server and import it to SharePoint server, set 'Force Encryption' to Yes and 'Trust Server Certificate' to Yes of both SQL Server network configuration and sql native client 11.0 configuration via SSCM.**

Is it possible that sql server version isn't compatible with Microsoft.Data.SqlClient lib version?

**Comment by JRahnama** [comment]
@qizu0302 most probably the certificate is not made correctly. 

1. Subject should be the FQDN of the machine. You can define other or friendly names as extensions.
2. System.Data.SqlClient and Microsoft.Data.SqlClient are client side libraries, so SQL server cannot use either of them. SSMS 18 is using S.D.SqlClient while SSMS 19 has switched to M.D.SqlClient.
3. As a test set the `Force Encryption` to False/No and add `Encrypt=false` to your connection string to see if you are able to get connection.

**Comment by qizu0302** [comment]
Previously SharePoint used S.D.SqlClient, but I'm working on replacing the lib with M.D.SqlClient now, so I need to verify my work. I use sql server 2019 with version 15.0.4223.1 and SSMS 18 in my lab. 

Below is my self-signed cert, sql server's fqdn is 'sql.contoso.local'
![cert](https://user-images.githubusercontent.com/103396968/189010104-a09683b3-0e3e-410c-a732-aebd1d12107d.PNG)

Given the configuration, can the encrypted connection be established successfully?

**Comment by JRahnama** [comment]
@qizu0302 SQL Server 2019 uses TDS protocol to communicate with drivers such as M.D.SqlClient or S.D.SqlClient or JDBC or other drivers. It does not uses client side library. However, SSMS 18 is using S.D.SqlClient on the background to get connection from SQL Server and SSMS 19 is using M.D.SqlClient for that matter. S.D.SqlClient is in servicing mode and is not accepting fixes or adding new features. It only accepts security related fixes, however M.D.SqlClient is active ADO.NET library and continuously improves and adds new features. 

that being said, you need to go to the Details tab and make sure that couple of things are correct:
 A self signed certificate for SSL server authentication looks like below. Keep in mind this is for localhost and you need to change the IP address in the text extension
```powershell
New-SelfSignedCertificate -Subject "CN=<FQDN>" -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation "cert:\LocalMachine\My" -TextExtension @("2.5.29.17={text}DNS=localhost&IPAddress=127.0.0.1&IPAddress=::1") -HashAlgorithm “SHA256” -Type SSLServerAuthentication -Provider “Microsoft RSA SChannel Cryptographic Provider”
```

- subject is same FQDN of the server.
- make sure cert store location is correct.
- make sure correct text extension is selected along with IP addresses.
- make sure Type is `SSLServerAuthentication`
- make sure provider is `Microsoft RSA SChannel Cryptographic Provider`

Then you need to import the certificate and make sure it is the active certificate in the section highlighted inside the below image
![image](https://user-images.githubusercontent.com/32077152/189028017-bb48d8a7-f21f-4154-acea-585cb7c1ffc8.png)

**Comment by qizu0302** [comment]
Appreciate your reply! It seems this kind of cert works now.

**Comment by JRahnama** [comment]
@qizu0302 you are welcome. Keep that in mind that this kind of certificates do not provide any trust value oppose to CA (certificate authority) issued certs. These kind of certificates are good for developers and testing purposes.

I am closing the issue as resolved.
