### ISSUE TITLE
Invalid connection in the pool after a commit timeout

### ISSUE THREAD

**Issue by dmytro-gokun** [dotnet/SqlClient#176]
This is to confirm that fix for #130 does not work in Microsoft.Data.SqlClient 1.0.19239.1 

Today, i've got several instances of the following situation (app running in ServiceFabric against an Azure SQL DB):

1) A Commit times out with the following exception:

`
Microsoft.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---&gt; System.ComponentModel.Win32Exception (258): The wait operation timed out
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action``1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean&amp; dataReady)
   at Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction, Boolean isDelegateControlRequest)
   at Microsoft.Data.SqlClient.SqlInternalTransaction.Commit()
   at Microsoft.Data.SqlClient.SqlTransaction.Commit()
   at INTERNAL CALL STACK
`

2) After that, ANOTHER connection silently fails to read data from the DB.

It does not look like the original bug was fixed.

@cheenamalhotra Can you please take a look at this?

**Comment by cheenamalhotra** [comment]
This problem looks like commit times out on server end, for which the driver is throwing a valid exception - isn't it expected? Future connections will definitely not read data as the data is not committed.

Also please elaborate _"ANOTHER connection silently fails"_. If you're expecting the first connection where commit failed should be re-used to re-allow commit, that will not happen as on server side the transaction has ended. On client side, we doom the connection and make it non-poolable.

>It does not look like the original bug was fixed.

The original bug reported in #130 was the case where same corrupted connection was pooled and reused, and with the fix, we make sure it is marked doomed and future connections from client will not reuse the same corrupted connection. 

Also, once a commit succeeds/fails, that marks end of transaction. If it failed with exception, you need to redo your transaction or avoid commit timeouts at the first place.

**Comment by dmytro-gokun** [comment]
> This problem looks like commit times out on server end ...

That is true. You see, I run this against SQL Azure, which by defualt configured to use mirroring. This means, that each commit should be propagated to backup server(s) before it is considered success. Now, if there are some (transient) network condition which prevent data propagation during the commit, then the commit times out. This is all well and expected. Our code will handle this transient exception and retry the whole operation (transaction) using an appropriate retry strategy. So, no problem with the commit timeout itself. It happens very rarely (may be, a couple times a week), we wait a bit, retry and move on.

> Also please elaborate "ANOTHER connection silently fails".

You may clearly see what i mean by it if you read my code in the original issue. But I will try to explain it in words again here.
So, after a commit times out, some time passes by and the server picks up another unrelated work item to process. As a part of processing a new SQL connection is open.
Now, the first thing the processor does is "SELECT * TABLE WHERE Id = @Id". And this particular select returns 0 records even though the record with Id = @Id is 100% in the database.
This is completely bananas behavior, to be honest. What happens here is that the connection opened by this operation is actually a broken connectin picked up from the pool. One which timed out before. Again, if you read the reproduction code from the previous issue, try executing it, you will see that it's indeed what happens here.
		
> The original bug reported in #130 was the case where same corrupted connection was pooled and reused, and with the fix, we make sure it is marked doomed and future connections from client will not reuse the same corrupted connection.

Well, may be that has happened on different execution path. Fortunatelly, we now have a stack trace which you can examine to see if the connection is evicted from pool or not (it is not).

Well, I hope it is a bit more clear now. Let me know if you need any more info from me.

**Comment by yukiwongky** [comment]
@dmytro-gokun Can you try this package out? [Microsoft.Data.SqlClient.1.1.0-dev.zip](https://github.com/dotnet/SqlClient/files/3820945/Microsoft.Data.SqlClient.1.1.0-dev.zip) 
It contains the fix in PR #299.

**Comment by dmytro-gokun** [comment]
@yukiwongky Well, frankly speaking the only way for me to test this would be to put it to production (since it is really hard to get these timeouts in test env as you probably realize). And i cannot put dev version to production for obvious reasons. Sorry( When 1.1.0 is released, i will update and report back if i see this issue again or not after a month in production (remember, it happens really rarely under specific network conditions in Azure).

**Comment by yukiwongky** [comment]
@dmytro-gokun [Stable release v1.1.0](https://github.com/dotnet/SqlClient/releases/tag/v1.1.0) is out. Please kindly try it out to see if it fixes the problem. I'm going to close this issue. Feel free to reopen if you see the issue persist.

**Comment by dmytro-gokun** [comment]
@yukiwongky I'm already running this release. Have not seen this issue again. I think it is fixed now. Thanks a lot!
