### ISSUE TITLE
SqlCommandBuilder.DeriveParameters to Sql2005 Database

### ISSUE THREAD

**Issue by DanielVinagre** [dotnet/SqlClient#1777]
### Describe the bug
With a connection to a SQL Server 2005 Database, SqlCommandBuilder.DeriveParameters is creating Parameters of SqlDbType.Variant when the parameter is of type Int

### To reproduce
```c#
string connString = @"Server=SQL2005_INSTANCE;Database=DB_NAME;UID=sa;Password=YOUR_PASSWORD;TrustServerCertificate=True;";
Microsoft.Data.SqlClient.SqlConnection conn = new Microsoft.Data.SqlClient.SqlConnection(connString);
conn.Open();

Microsoft.Data.SqlClient.SqlCommand command = new Microsoft.Data.SqlClient.SqlCommand("STORED_PROC_NAME", conn);
command.CommandType = CommandType.StoredProcedure;
Microsoft.Data.SqlClient.SqlCommandBuilder.DeriveParameters(command);
conn.Close();

SqlDbType dbtype = command.Parameters[1].SqlDbType;
```

### Expected behavior
Parameters Type be of the right type according to the procedure

### Further technical details
Microsoft.Data.SqlClient version: 5.0.0
.NET target: (.NET 6)
SQL Server version: (SQL Server 2005)
Operating system: (Windows 8)

**Additional context**
System.Data.SqlClient 4.8.3 has the same problem.

**Comment by lcheunglci** [comment]
Hi @DanielVinagre , the Sql Server version and Operating system specified are both out of support.  The minimum system requirements can be found [here](https://github.com/MicrosoftDocs/sql-docs/blob/live/docs/connect/ado-net/sqlclient-driver-support-lifecycle.md#sql-version-compatibility-with-microsoftdatasqlclient).

**Comment by lcheunglci** [comment]
Please upgrade your system to at least `Windows 8.1` [[eos: Jan 10 2023](https://learn.microsoft.com/en-us/lifecycle/products/windows-81)] or above and `Sql Server 2012` [[eos: Jul 12 2022](https://learn.microsoft.com/en-us/lifecycle/announcements/sql-server-2012-windows-server-2012-2012-r2-end-of-support)]  or above and try your repro steps again as we cannot guarantee that the same functionality would still work on an End of Life version of Sql Server.

**Comment by lcheunglci** [comment]
Closed due to inactivity.
