### ISSUE TITLE
Backwards incompatibility between Microsoft.Data.SqlClient.SqlConnectionStringBuilder and System.Data.SqlClient.SqlConnectionStringBuilder

### ISSUE THREAD

**Issue by captain-seablade** [dotnet/SqlClient#1780]
### Describe the bug
There is a significant discrepancy between the two SqlConnectionStringBuilder types as far as their internal keywords are defined.
The keywords can be found in the internal class DbConnectionStringKeywords.  An example:

https://github.com/dotnet/SqlClient/blob/04db1a40a95726af8567b7596653e20acdd7f19a/src/Microsoft.Data.SqlClient/src/Microsoft/Data/Common/DbConnectionStringCommon.cs#L1039

However, in the .NET Framework version of the System.Data.SqlClient, the same keywords class has it defined differently:

https://referencesource.microsoft.com/System.Data/R/6a6a501b9f709c06.html

This is an example keyword, but there are more keywords where this is an issue.

Here's the code excerpt for both:

## Microsoft.Data.SqlClient
```c#
...
internal const string TrustServerCertificate = "Trust Server Certificate";
...
```

## System.Data.SqlClient
```c#
...
internal const string TrustServerCertificate = "TrustServerCertificate";
...
```

When a connection string is built using the Microsoft.Data.SqlClient.SqlConnectionStringBuilder, it cannot be deconstructed within the System.Data.SqlClient.SqlConnectionStringBuilder as it throws an exception indicating that the keyword is not supported.
### To reproduce

Run the following code in a project that is using Microsoft.Data.SqlClient:

```c#
var csb = new SqlConnectionStringBuilder { TrustServerCertificate = true };
var cs = csb.ConnectionString;
```

Take the connection string from that and then apply it to a different set of code using the System.Data.SqlClient:
```c#
var connectionString = "Trust Server Certificate=True";
var csb = new SqlConnectionStringBuilder(connectionString);
var cs = csb.ConnectionString;
```
The following exception will occur:

System.ArgumentException: 'Keyword not supported: 'trust server certificate'.'

### Expected behavior
I would expect that the keywords would match and thus the connection strings would be interchangeable.

### Further technical details
N/A

**Additional context**
N/A

**Comment by JRahnama** [comment]
@captain-seablade that change was decided and made as a breaking change in earlier stage of M.D.SqlClient in [PR #534](https://github.com/dotnet/SqlClient/pull/534).

**Comment by captain-seablade** [comment]
Ok, thank you.  I attempted a search for anything related to breaking changes regarding this issue and I was unable to find the PR you mentioned or other supporting details.  Thank you for the information.  I'll adjust accordingly and add workarounds.

**Comment by JRahnama** [comment]
Closing as not an issue,
