### ISSUE TITLE
Application Insights telemetry is missing with Microsoft.Data.SQlClient 5.0.0.0  and .Net48

### ISSUE THREAD

**Issue by bijueb** [dotnet/SqlClient#1789]
Hi,

We  recently switched from System.Data.SQLCleint to  Microsoft.Data.SQlClient 5.0.0.0  in  .net48  web application  deployed in Azure VM.    SQL  dependency is not showing up  in Application Insights   after switching to Microsoft.Data.SQlClient .  is there any workaround for this ?  or is it a known issue ?

Thanks!
Biju

**Comment by JRahnama** [comment]
Hi @bijueb we will look into this shortly.

**Comment by lcheunglci** [comment]
Hi @bijueb , thanks for bringing this to our attention.  Unfortunately, we do not know how the telemetry data is collected.  Please open a ticket with Azure Support as they can direct you to the Application Insights team to provide more info.

**Comment by Wraith2** [comment]
We could try asking @mbakalov who has helped us with app insights/open telemetry issues before...

It seems strange that the events would fail since there haven't been any changes around them that i'm aware of.

**Comment by JRahnama** [comment]
@mbakalov did you have a chance to look into this issue?

**Comment by JRahnama** [comment]
Closing this issue as an external. Feel free to comment here or open a new issue.
