### ISSUE TITLE
The certificate chain was issued by an authority that is not trusted.

### ISSUE THREAD

**Issue by dburtsev** [dotnet/SqlClient#1827]
Hello

We got the certificate from database admin. I installed it into Trusted Root Certification Authorities on Windows Server 2022.
Got error: "Client unable to establish connection SSL Provider: The certificate chain was issued by an authority that is not trusted."

Provider=MSOLEDBSQL19;Password="qwe";Persist Security Info=True;User ID=qwe;Data Source=1.1.1.1,1234;Trust Server Certificate=True;

**Comment by cheenamalhotra** [comment]
Hi @dburtsev 

It could be that your hostname in certificate does not match to Data Source since you seem to be providing IP address.

Could you update your DataSource to "hostname" to match what is defined in the certificate instead of the IP address?

**Comment by ErikEJ** [comment]
You are also using the OLEDB driver. This repo is for the .NET SqlClient

**Comment by dburtsev** [comment]
@cheenamalhotra we already test this certificate with JDBC and it is working
@ErikEJ  We have the same error with .NET

**Comment by JRahnama** [comment]
@dburtsev what version of M.D.SqlClient are you using? what platform is the client on please include the version and what platform is the server on? Also, as @cheenamalhotra mentioned please use the actual hostname from certificate instead of the IP address and see if that makes any difference.

**Comment by dburtsev** [comment]
Windows Server 2022, 64 bit.
Microsoft.Data.SqlClient 5.0.1
I can't use the actual hostname from the certificate. "A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible."
I am on AWS and SQL Server is on another cloud. I can connect only by IP.
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.

Note: I can connect to the server without a certificate (trust server certificate) but we must use certificate for client connection.

**Comment by cheenamalhotra** [comment]
Since you're using SqlClient 5.0.1, you can now specify "Host Name in Certificate" connection property to contain the hostName, and use IP/servername as before in Data Source.

I believe that should work for you!

**Comment by dburtsev** [comment]
@cheenamalhotra I add HostNameInCertificate=True to the connection string.
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.)

**Comment by dburtsev** [comment]
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate's CN name does not match the passed value.)

**Comment by dburtsev** [comment]
I remove HostNameInCertificate=True and add Encrypt=Mandatory
It works now
thanks

**Comment by lcheunglci** [comment]
Note `HostNameInCertificate` is not a `boolean` value, but a `string` of the CN/hostname in the server certificate.  Unfortunately, we missed the update to the documentation, so it'll show up in our next release.  By default, `Encrypt` is set to `true`/`Mandatory`, so you shouldn't need to explicitly set it, and there should be a functional test that validates that condition.
