### ISSUE TITLE
The certificate chain was issued by an authority that is not trusted.

### ISSUE THREAD

**Issue by Vikas8881** [dotnet/SqlClient#1836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Today I update the project from core 6 to 7. and after this when i try to execute any API then I get this error 

**Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.**

But in core 6 it's working fine. 

### .NET Version

7

**Comment by lcheunglci** [comment]
Thanks @ErikEJ ,

When upgrading from EF Core 6 to EF Core 7, the dependency of `Microsoft.Data.SqlClient` went from `2.1.2` to `5.0.1` and the Encrypt default value went from `false` to `true` i.e. `mandatory`, so you'll either need to set it to set it explicitly to `Encrypt=false` or `TrustServerCertificate=true` or `HostNameInCertificate=<CN Subject of your certificate>`.

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#encrypt-true

**Comment by Vikas8881** [comment]
> Seems like a SQL issue? What database are you connecting to?

I use MS SQL Server
SQL Server Management Studio						15.0.18424.0
SQL Server Management Objects (SMO)						16.100.47021.0+7eef34a564af48c5b0cf0d617a65fd77f06c3eb1
Microsoft Analysis Services Client Tools						15.0.19750.0
Microsoft Data Access Components (MDAC)						10.0.22621.819
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.22621

**Comment by Vikas8881** [comment]
Thank you Everyone's Issue was Resolved By adding **TrustServerCertificate=True;** in the Connection String in AppSettings
and its work.

**Comment by yogapratama12428** [comment]
it work for me, thanks @Vikas8881

**Comment by SrkPrasadChangala** [comment]
> Thank you Everyone's Issue was Resolved By adding **TrustServerCertificate=True;** in the Connection String in AppSettings and its work.

It worked for me.

**Comment by saman-ar** [comment]
Adding TrustServerCertificate=True to the connection string fixed this issue in entityframework 8.

**Comment by Kiran9684** [comment]
> Thank you Everyone's Issue was Resolved By adding **TrustServerCertificate=True;** in the Connection String in AppSettings and its work.

Worked for me, Thanks @Vikas8881
