### ISSUE TITLE
Microsoft.Data.SqlClient v5.1 GA is in Progress

### ISSUE THREAD

**Issue by lcheunglci** [dotnet/SqlClient#1845]
The SqlClient team is currently in the middle of a GA release for `5.1.0`. We are code freezing any new changes/PRs until the process is complete. _Only_ approved critical bug fixes and tests will be included for it at the moment.  We will resume the review process of your opened PRs in a few weeks (i.e. early/mid-December) for the next preview release.  Thank you for your support and contributions.

**Comment by ErikEJ** [comment]
So when is the planned GA date?

**Comment by DavoudEshtehari** [comment]
We've targeted on Dec 13, coincides with .NET core 3.1 EOL.

**Comment by lcheunglci** [comment]
We are going to delay the 5.1 release to January after the holidays.

**Comment by frones** [comment]
@lcheunglci do you have a specific date for the release? Thanks!

**Comment by lcheunglci** [comment]
Our target date is January 19 2023 as some of us will be on vacation for the holidays and it'll give us enough time to thoroughly test it as we are planning to make the 5.1 release a LTS version.

**Comment by Wraith2** [comment]
A total freeze for 2 months when we're already moving very slowly is disappointing.

**Comment by ErikEJ** [comment]
I think due diligence is in place for a LTS version. 

On a related note, it now looks like Woodstar is finally happening (in a year or so anyway)

**Comment by Wraith2** [comment]
> I think due diligence is in place for a LTS version.

Perhaps. But I have no information about that and what it takes to do that. All I see from the outside is that We're moving from slow to stopped in terms of PR progress and there's no visible result apart from a nuget package, we produce those in the CI. Why does it take 2 months? If we're waiting on long running processes to test the packages then it doesn't require people to watch them, they can be a background task unless there are problems found.

**Comment by lcheunglci** [comment]
The original plan was to release MDS 5.1 a month after the 5.1preview3 release and timing it with the EOS for .NET Core 3.1, which was around this time; however, MDS 3.1 LTS was extended from Jan 2023 to Mar 2025, so the efforts was reprioritized for backporting some of the changes in both MDS and MDS SNI. As with any of the GA release, testing is where majority of the time is spent adding more code coverage to x86. Win arm64 and Sql Server 2022 on Windows 11 was recently in our pipeline and that work is still ongoing to ensure the tests are run against them. In addition, compliance, code analysis and localization/documentation also take time. Thank you for your continued support and patience.  Sorry for the delay.

**Comment by stevendarby** [comment]
> January 19 2023

@lcheunglci is this still the target date? :)

**Comment by lcheunglci** [comment]
Yes, it's officially release today. https://github.com/dotnet/SqlClient/releases/tag/v5.1.0
