### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#185]
Unable to build from source, using VS 2019 with all vsconfig defined pre-requistes installed.

**Unable to find package Microsoft.DotNet.GenAPI. No packages exist with this id in source(s):** 
```
Exception message:
Project "C:\Code\Github\SqlClient\src\Microsoft.Data.SqlClient.sln" (1) is building "C:\Code\Github\SqlClient\src\Micro
soft.Data.SqlClient\tests\tools\TDS\TDS.EndPoint\TDS.EndPoint.csproj" (3) on node 1 (default targets).
_CheckForNETCoreSdkIsPreview:
  You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
C:\Code\Github\SqlClient\src\Microsoft.Data.SqlClient\tests\tools\TDS\TDS.EndPoint\TDS.EndPoint.csproj : error NU1101:
Unable to find package Microsoft.DotNet.GenAPI. No packages exist with this id in source(s): CliFallbackFolder, Microso
ft Visual Studio Offline Packages, nuget.org, Package source
Done Building Project "C:\Code\Github\SqlClient\src\Microsoft.Data.SqlClient\tests\tools\TDS\TDS.EndPoint\TDS.EndPoint.
csproj" (default targets) -- FAILED.
```

### To reproduce
Pull source, run msbuild in the src folder as prescribed.

### Expected behavior
The build complets

### Further technical details

**Additional context**
In addition, the Functional test project reference two unknown packages:
microsoft.xunit.netcore.extensions
Microsoft.dotnet.buildtools.testsuite

- are you mssing documentation of a "secret" package source?

**Comment by ErikEJ** [comment]
Indeed!! 😞 

Adding this fixed the issue - I will create a PR to get the NuGet.config file added 😄 

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="dotnet-core" value="https://dotnetfeed.blob.core.windows.net/dotnet-core/index.json" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>

```

**Comment by ErikEJ** [comment]
PR submitted

**Comment by cheenamalhotra** [comment]
Hi @ErikEJ 

FYI The Nuget Package sources the driver refers for building are defined in [build.proj](https://github.com/dotnet/SqlClient/blob/52a4e8819453d2ef6a1a9deb8cd1782c41672d20/build.proj#L37), however putting them in a separate Nuget.config file is good for developers reference. Thanks for the PR, I will update documentation accordingly.

Also I figured out with latest VS 2019 Enterprise & Community edition, `microsoft.visualstudio.component.typescript.3.4` is not found. Just to confirm if you also saw this while installation, I'm going to remove/replace that package reference.

**Comment by ErikEJ** [comment]
Ah, I misunderstood the build instructions, and ran msbuild from a developer command prompt in the src folder, not in the root folder. Adding NuGet.config to the solution folder will now enable build from the src folder (and VS in particular)
