### ISSUE TITLE
Linux (Ubuntu): Could not load file or assembly 'Microsoft.Data.SqlClient,'. Access is denied.

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/SqlClient#1857]
### Describe the bug

Running a .NET 6 app with `dotnet MyApp.dll` throws this exception:

```
System.IO.FileLoadException: Could not load file or assembly
'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'.
Access is denied.
```

#### Running with `sudo dotnet MyApp.dll` works fine

Changing `chmod 777 Microsoft.Data.SqlClient.dll` does not help.

### Further technical details
Microsoft.Data.SqlClient version: 5.0.1
.NET target: net6
SQL Server: SQL Server 2019 (on external windows machine)
Operating system: Ubuntu 20 (reproducible on WSL2 on Windows)

```
$ dotnet --info

global.json file:
  Not found

Host:
  Version:      6.0.11
  Architecture: x64
  Commit:       943474ca16

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.11 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

**Comment by lcheunglci** [comment]
Thanks @alex-jitbit for bringing this to our attention.  That's strange that it needs to be run with sudo.  Do you have a sample repro project that you can provide to us?

**Comment by alex-jitbit** [comment]
@lcheunglci I tried creating a simple project and.  was unable to replicate this. As it turned out, the program that was causing the error was supllied as a zip file and the zip file had unsufficient permissions to the "runtime" subfolder that has native dependencies for SqlClient. Please disregard, sorry for wasting your time.

**Comment by alex-jitbit** [comment]
P.S. TIL that zip files can have permission data stored for folders inside it....

**Comment by lcheunglci** [comment]
No worries.  I'm glad you sorted it out. Thanks for keeping us posted.
