### ISSUE TITLE
System.Data.SqlClient to Microsoft.DataSqlClient, errors increased. ExecuteReader requires an open and available Connection. The connection's current state is closed.

### ISSUE THREAD

**Issue by wangenbao1001** [dotnet/SqlClient#1858]
I upgraded my app from .net freamework to .net6/standard, so I upgraded System.Data.SqlClient to Microsoft.Data.SqlClient and have changed some code. But I found that the number of errors in the log has increased.
> "xxx requires an open and available Connection. The connection's current state is closed." has never occurred before, but now many.
> "A transport-level error has occurred when receiving results from the serve" has increased.
> ...

My app connects multiple dbs, and the above errors occur randomly in each db.

version
> DB: Azure Sql Server
> Microsoft.Data.SqlClient 5.0.0

Main:
``` c#
using (var conn = SqlHelper.GetSqlConnection(dbTarget.ConnectionString, trackingId: trackingId))
{
    using (var command = SqlHelper.GetSqlCommand(conn, dbCommonCriteria.CommandText, parameters,  dbCommonCriteria.CommandType, rule.RuleMaxExecutionTimeInSeconds))
    {
        try
        {
            using (var reader = SqlHelper.GetSqlDataReader(command))
            {
                var dataTable = new DataTable();
                dataTable.Load(reader);

                if (dataTable.Rows.Count <= 0)
                {
                    string error = string.Format("Criteria query returned zero row. UniqueName:{0}", rule.RuleName);
                    Logger.LogError(null, MethodBase.GetCurrentMethod().DeclaringType?.FullName, MethodBase.GetCurrentMethod().Name, error);

                    if (conn != null)
                    {
                        SqlConnection.ClearPool(conn); // Clear Pool to see if it can help on the cases that db return unexpected zero row;
                    }
                    throw new InvalidOperationException(error);
                }

                UpdateHealthStatus(ResultConverter(dataTable, rule, dbTarget),
                    dbCommonCriteria.ReportDBConnectionString,
                    rule.AlertServices);

                Logger.LogPerf(trackingId, MethodBase.GetCurrentMethod().DeclaringType?.FullName, MethodBase.GetCurrentMethod().Name,
                    $"{rule.RuleName}: Execute DatabaseHealthStatusPlugin, target: { target.GetTargetName()}, TaksType: {rule.ExecuteTaskType}, RuleName: {rule.RuleName}.", "ExecutePlugin", (DateTime.UtcNow - startTime).TotalMilliseconds);
            }
        }
        catch (SqlException e)
        {
            var isGeoSecondary = rule.TargetSection.IsSecondary;
            var isLocalSecondary = !isGeoSecondary && (ApplicationIntent.ReadOnly == rule.TargetSection.Intent);

            // Write call failed with read-only error on primary indicates a failover happened
            if (!isGeoSecondary && !isLocalSecondary)
            {
                var hasReadOnlyError = false;
                foreach (SqlError error in e.Errors)
                {
                    if (error.Number == 3906) // 3906 means "Failed to update database XXX because the database is read-only."
                    {
                        hasReadOnlyError = true;
                    }
                }
                if (hasReadOnlyError && conn != null)
                {
                    SqlConnection.ClearPool(conn); // Clear connection pool if the failover has been detected
                }
            }

            throw;
        }            
    }
```
SqlHelper.cs(diff):
![image](https://user-images.githubusercontent.com/40199478/205458526-a45ff48d-83c5-4345-8e53-dc5e36270175.png)
![image](https://user-images.githubusercontent.com/40199478/205458538-80cb216e-7662-4a7b-b3b5-bf2892472566.png)
![image](https://user-images.githubusercontent.com/40199478/205459632-325bb795-da08-4926-b6b8-a128263caa06.png)

Error Info:
> Exception:System.InvalidOperationException: ExecuteReader requires an open and available Connection. The connection's current state is closed.
>    at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 5932
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 5027
>    at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 5000
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method) in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 2494
>    at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader() in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlCommand.cs:line 2425
>    at Microsoft.Practices.EnterpriseLibrary.TransientFaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
> ...

Could someone help me?

**Comment by lcheunglci** [comment]
Hi @wangenbao1001, we have a guide when porting from System.Data.SqlClient to Microsoft.Data.SqlClient [here](https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md).  I see that in your diff with SqlHelper.cs should get pass the breaking changes with encryption. From the exception that you mentioned, it feels like the connection was closed when you started using the reader and will need more time to investigate as we're currently in a middle of a release. We'll get back to you soon.

**Comment by wangenbao1001** [comment]
Hi @lcheunglci, thanks for your reply.
I also suspect  when command retry, connection closed by network issues or others. so I update the retry logic, But it hasn't been verified yet. 
![image](https://user-images.githubusercontent.com/40199478/205698909-bcfc988c-80fb-4ee8-b12a-3a2ffc9ab597.png)
![image](https://user-images.githubusercontent.com/40199478/205699098-aad78346-9564-4b64-8a76-47090cab8497.png)

And if It is worked for me, I wanna why connection closed. 
Are there related by "A transport-level error has occurred when receiving results from the server" these errors?
> connStringBuilder.Encrypt = true;
> connStringBuilder.TrustServerCertificate = true;

Will these two parameters cause some transport-level errors？

**Comment by lcheunglci** [comment]
I don't think `Encrypt=true` and `TrustServerCertificate=true` would result in the transport-level errors that would close the connection silently.  Instead, I would expect it to throw an error 35 in SSL handshake if there was authentication error if it was not set/configured properly. You could try to test `Encrypt=false` which would be the default behavior before the migration.

**Comment by wangenbao1001** [comment]
I have set ```Encrypt=false``` before, and the number of errors is more than System.Data.SqlClinet, so I try to set ```Encrypt=true```. It doesn't work.
On the whole, the number of errors in multiple databases is more than that before the upgrade.

**Comment by wangenbao1001** [comment]
By the way, Left is ```using System.Data.SqlClient``` and Right is ```using Microsoft.Data.SqlClient```
![image](https://user-images.githubusercontent.com/40199478/205704819-099ae20b-9bbe-416a-95d6-0c8287871e3d.png)

**Comment by lcheunglci** [comment]
For your migration from SDS to MDS, did you also move from an on-premises Sql Server to an Azure Sql Server? Perhaps, there's network idle timeouts in play.  Is it possible `SqlCommand.ExecuteReader()` is using `CommandBehavior.CloseConnection()`?

**Comment by wangenbao1001** [comment]
I don't change the SqlServer when I migration. It has been in Azure Sql Server.
and I don't know the details ```SqlCommand.ExecuteReader()(Microsoft.Data.SqlClient, Version=5.0.0.0)``` using ```CommandBehavior.CloseConnection()```

**Comment by wangenbao1001** [comment]
> Hi @lcheunglci, thanks for your reply. I also suspect when command retry, connection closed by network issues or others. so I update the retry logic, But it hasn't been verified yet. ![image](https://user-images.githubusercontent.com/40199478/205700245-b1bd0128-228f-4d2f-973b-65c77e883598.png) ![image](https://user-images.githubusercontent.com/40199478/205699098-aad78346-9564-4b64-8a76-47090cab8497.png)
> 
> And if It is worked for me, I wanna why connection closed. Are there related by "A transport-level error has occurred when receiving results from the server" these errors?
> 
> > connStringBuilder.Encrypt = true;
> > connStringBuilder.TrustServerCertificate = true;
> 
> Will these two parameters cause some transport-level errors？

This code have resolved ```xxx requires an open and available Connection. The connection's current state is closed.``` this error by retry. It seems that when sql command retry, the connection is already closed.

And ```A transport-level error has occurred when receiving results from the server``` may caused by Azure Sql Server High Cpu or some network fluctuation, and maybe not Application Errors. So If you have some concern, please let me know. And If no some new discuss about why connection closed. Maybe I can close this issue.

**Comment by wangenbao1001** [comment]
Thanks for your help 👍. I will close this issues.
