### ISSUE TITLE
Does Microsoft.Data.SqlClient support using Active Directory Service Principal Authentication with certificates?

### ISSUE THREAD

**Issue by RikaEndo0** [dotnet/SqlClient#1859]
In the document below, the method using a secret is described, but is the method using a certificate also supported?

https://learn.microsoft.com/en-us/sql/connect/ado-net/sql/azure-active-directory-authentication?view=sql-server-ver16#using-active-directory-service-principal-authentication

https://learn.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#option-1-upload-a-certificate

**Comment by lcheunglci** [comment]
Thanks @RikaEndo0 for bring this to our attention. I'll have to look into this and get back to you.

**Comment by lcheunglci** [comment]
The AAD authentication does not support using certificates with service principals.

**Comment by mvarblow** [comment]
Sad. It doesn't look like it would be too difficult to support using a certificate (it is well supported by Azure.Identity) and this would be a more secure approach than using a secret. By not supporting certificate-based authentication you're not providing very good options for securely using a service principal with Azure SQL. We're back to the bad old days when connection strings contained passwords.

**Comment by mvarblow** [comment]
@ErikEJ I understand it's an old issue, but I couldn't help leaving my two cents. :)

Yes, there are ways to do this and have been for a while. My contention is that it should be just as easy to use a certificate as it is to use a secret. Security is not served by making it harder to configure the solution securely, especially when it wouldn't be a big reach to make it easy for people to do it the right way. Microsoft has certainly been doing better in this area than their reputation (largely based on those "bad old days") would suggest but if security is really taken seriously, and I think it is, this seems like one of those places where it should show.
