### ISSUE TITLE
Insufficient information in exception to be able to diagnose problem (.NET 7 connection to SQL Server 2019)

### ISSUE THREAD

**Issue by dwe-alan** [dotnet/SqlClient#1868]
### Describe the bug
While trying to connect to a SQL Server 2019 database using the Microsoft.EntityFrameworkCore.SqlServer version 7.0.0 NuGet package from a .NET 7 Docker container, I got the following exception:

System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity)
at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst)
at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)

When the Microsoft.EntityFrameworkCore.SqlServer package was downgraded to 6.0.11 the connection opened without exception.

When the "trustServerCertificate=true" property was added to the connection string, the connection opened without exception.

However, it is impossible to diagnose the problem based on the exception message above. Please could it be changed so that there is some clue in the message.

Thanks

### Further technical details
.NET target: 7
SQL Server version: 2019
Operating system: Docker container

**Comment by ErikEJ** [comment]
What would have been a better message?

**Comment by dwe-alan** [comment]
Something like host name mismatch, or certificate expired on anything that gives a clue as to the problem. The fact that it stopped working between version 6 and 7 is particularly frustrating as something that was OK in 6 is apparently no longer up to scratch in 7. But I don't know what. We have one lead. A connection in Cairo. You leave tonight....

**Comment by ErikEJ** [comment]
>> omething that was OK in 6 is apparently no longer up to scratch in 7. But I don't know what. 

An easy way to find out is to consult [the breaking changes list](https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#encrypt-true) in the documentation :-)

**Comment by dwe-alan** [comment]
I will do that. However, whether or not I find anything, it is still worth providing a helpful error message.

The days of "Error 94" are long gone.

**Comment by dwe-alan** [comment]
I can confirm that there are no relevant breaking changes in the list provided by Microsoft. This makes it all the more important to provide a helpful error message.

**Comment by ErikEJ** [comment]
I linked directly to the relevant breaking change ..

**Comment by dwe-alan** [comment]
We were using encrypted connections before, so it's not that. The only way to get encrypted connections to work with .NET 7 is to add "trustServerCertificate=true" to the connection string, but that doesn't tell me what the underlying problem was. The connection string worked fine without "trustServerCertificate=true" in .NET 5/6

**Comment by JRahnama** [comment]
@dwe-alan `Microsoft.EntityFrameworkCore.SqlServer` v6.0.0 was using `M.D.SqlClient` v2.1.4 and on version 7.0.0 they have changed to v5.0.1. As @ErikEJ mentioned there are several breaking changes from 2.1.4 to 5.0.1. The most important one, we have changed `Encrypt` from false to true and that causes the issue. For testing purposes, you can either add `TrusetServerCertificate=true` or `Encrypt = False` in your connection string and that will solve the issue.

For the exception I think is self-explanatory. Plus, the exception is thrown by a different library and SqlClient is just getting showing that. There is not much we can do about it.

**Comment by JRahnama** [comment]
Closing the issue as it has been discussed before and breaking changes are documented.

**Comment by dwe-alan** [comment]
I am sorry, but my connection had "Encrypt=true" explicitly set **before** the upgrade. The change of the default value from false to true is **irrelevant**. Again, the issue is that the exception does **not** provide sufficient information to be able to diagnose the problem.

**Comment by ErikEJ** [comment]
"Docker container" does not describe your OS.

What is it exactly? 

There are other breaking changes between 2 and 5.

**Comment by JRahnama** [comment]
Just to confirm, you have a valid SSL certificate, Self-signed certificates are legit as well, which has your FQDN as its subject.

you can also test with creating a self-signed certificate by this command:

`New-SelfSignedCertificate -Subject "CN=<FQDN>" -KeyAlgorithm RSA -KeyLength 2048 -CertStoreLocation "cert:\LocalMachine\My" -TextExtension @("2.5.29.17={text}DNS=localhost&IPAddress=127.0.0.1&IPAddress=::1") -HashAlgorithm “SHA256” -Type SSLServerAuthentication -Provider “Microsoft RSA SChannel Cryptographic Provider”`

make sure you provide the FQDN in the subject field then install the certificate and provide access to its private key. Then try to import this to your SQL server and see if the issue happens again. 

For access permission, when certificate is created right click on it in MMC then select All Tasks and then select Manage private key and then provide enough access to the SQL server instance user.

If you still think this is a driver issue, then provide a simple repro including your connection string properties. The repro needs a step-by-step instruction that leads to reproducing the issue.

**Comment by dwe-alan** [comment]
My issue is with the exception message.

It needs to be helpful. 

**The remote certificate was rejected by the provided RemoteCertificateValidationCallback**

is not helpful

**The hostname does not match the certificate subject***
**The certificate has expired***
**The certificate chain is missing**

or a combination of these would be helpful.

**Comment by ErikEJ** [comment]
You should raise an issue in the .NET CLR repo then; System.Security.Authentication.AuthenticationException
