### ISSUE TITLE
[QUESTION] Approach for adding more tests

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#187]
Hi, I would like to add some tests for SqlParameter, I intend to create tests for all constuctors, and port the mono tests (NUnit => xUnit)- any advice and/or recommendations on how to approach this - or should I just give it a go and we can discuss in PR?

**Comment by cheenamalhotra** [comment]
Hi @ErikEJ 

That would be great! We just wanna ensure tests can be run in parallel executions on same client and Sql Database (as our pipelines run multiple configurations on same machines against same database). Also our pipelines run against Azure DB, so the tests must be written considering compatibility with Azure DB, with high preference. If they cannot be made compatible, you can add conditions to skip as done in other tests.

Guidelines are mentioned in [Readme.md](https://github.com/dotnet/SqlClient#guidelines-for-creating-pull-requests) and I'm also working on adding Contributing guidelines with more clarity for future.

**Comment by ErikEJ** [comment]
Great, I will submit a couple of tests, and we can discuss. The tests I plan to add just now do not require a database connection. (I am starting with some low hanging fruits) 😄

**Comment by ErikEJ** [comment]
Regex for cleaning NUnit tests: , "#\w+:\w+"\);

**Comment by cheenamalhotra** [comment]
Hi @ErikEJ 

Closing the issue as doubts were answered.
Feel free to contribute tests anytime!

**Comment by ErikEJ** [comment]
Thanks, I will add more "soon"

**Comment by ErikEJ** [comment]
Regex:

    , "#\w"\);
