### ISSUE TITLE
SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)

### ISSUE THREAD

**Issue by dinushahasith** [dotnet/SqlClient#1870]
I have deployed a Blazor .NET 7 app to IIS on a server and when I try to access the database I get the following error.

*Win32Exception: No process is on the other end of the pipe.
SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.)*

The app works fine on my development PC inside VS 2022.

I saw this article and tried the below options, but it didn't work.
https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/breaking-changes#encrypt-true

1. If the server has a certificate, but it is not trusted by the client, then TrustServerCertificate=True to allow bypassing the normal trust mechanisms.
2. Explicitly add Encrypt=False to the connection string.

connection string:
"DefaultConnection": "Server=.;Database=******;Integrated Security=SSPI;Encrypt=False"

**Comment by lcheunglci** [comment]
Can you switch your server from `.` to `tcp:localhost`?, this will expose the actual error message instead of ` No process is on the other end of the pipe.` because the stream has been disconnected by the server.

**Comment by dinushahasith** [comment]
ok.. I changed to tcp:localhost. recycled the app pool.

"DefaultConnection": "Server=tcp:localhost;Database=********;Integrated Security=SSPI;Encrypt=False"

still getting the same error. When I try again I get the following error. Getting the same error until I recycle the app pool.

_SqlException: Login failed for user 'sa'._

**stack trace:**

Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
Microsoft.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
Microsoft.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool enlistOK)
Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, string newPassword, SecureString newSecurePassword, bool ignoreSniOpenTimeout, TimeoutTimer timeout, bool withFailover)
Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, string newPassword, SecureString newSecurePassword, bool redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, string newPassword, SecureString newSecurePassword, bool redirectedUserInstance)
Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, object providerInfo, string newPassword, SecureString newSecurePassword, bool redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, bool applyTransientFaultHandling, string accessToken, DbConnectionPool pool)
Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, uint waitForMultipleObjectsTimeout, bool allowCreate, bool onlyOneCheckConnection, DbConnectionOptions userOptions, out DbConnectionInternal connection)
Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(bool errorsExpected, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(bool errorsExpected, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, bool errorsExpected)
Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync<TState, TResult>(TState state, Func<DbContext, TState, CancellationToken, Task<TResult>> operation, Func<DbContext, TState, CancellationToken, Task<ExecutionResult<TResult>>> verifySucceeded, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable<T>+AsyncEnumerator.MoveNextAsync()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync<TSource>(IAsyncEnumerable<TSource> asyncEnumerable, CancellationToken cancellationToken)

**Comment by lcheunglci** [comment]
This is a more useful error and stack trace.  You might want to enable your `sa` account on your Sql Server using [Sql Server Management Studio](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16) or [Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16) and specify the `UID` and `PWD` in the connection string instead of the `Integrated Security = SSPI` or if you need to want to use `Integrated Security` make sure IIS Instance for your Blazor app uses your windows account in your application pool because the default account on application pool might be referenced as a different account i.e. `NT Service\<ApplicationPoolName>` which might not exist on the Sql Server.

**Comment by dinushahasith** [comment]
hi, I tried the sa login as well. still same. App pool is using local system.

_SqlException: Login failed for user 'sa'._

connection string:
"DefaultConnection": "Server=tcp:localhost;Database=*****;User Id=sa;Password=****************;Integrated Security=False;MultipleActiveResultSets=true;TrustServerCertificate=True;Encrypt=False"

screenshot of the error:
[https://ibb.co/6vSnGYN](url)

Im inclined to try .NET 6 to see if it resolves the issue

**Comment by lcheunglci** [comment]
I don't think it's an issue with `.NET7` or `.NET6` nor `SqlClient` but a configuration issue with your **Sql Server sa account** or **IIS's application pool identity**. To check if the `sa` account has access, have you tried connecting to your Sql Server with the `Sql Server Authentication` with `sa` account with [SSMS](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)? If you're unable to login to your `sa` account, you have 2 options.

### Option 1 - Ensure the sa account is enabled:
The `sa` account might be disabled, you may need to use Windows Authentication option in SSMS and manually enable it.
`Databases > Security > Logins > sa > Login Properties > Status`
"Permission to connect to database engine" is set to `Grant`
"Login" is set to `Enabled`

### Option 2 - Explicitly set the IIS Application Pool Identity to a Windows account:
I'm not an expert in IIS as it's out of scope of my expertise, but if you have a windows account added in the logins to have access to your db, you try explicitly specifying your windows credentials in IIS Manager 
`Application Pools > "Your_Blazor_Apps_application_pool_name" > Advanced Settings > Identity > Custom account`
and specify that username and password there.

Also, in your connection string, when you specify the `user id` and `password`, you can exclude `Integrated Security = false` and if you specify `TrustServerCertificate=True`, you don't need to specify `Encrypt=False` and vice versa.

**Comment by dinushahasith** [comment]
have you tried connecting to your Sql Server with the Sql Server Authentication with sa account with [SSMS](https://learn.microsoft.com/en-us/sql/ssms/download-sql-server-management-studio-ssms?view=sql-server-ver16)?

yes. can log in using sa account with SSMS. Option 1 is enabled.

It's strange. I have 2 .net core mvc and API apps that use 2.1 and 3,1 with integrated security and they are working fine. I will check some more.

**Comment by lcheunglci** [comment]
From your observation where the same solution works with .NET Core 2.1 and 3.1, it might be a good idea to try and see if `.NET6` is also working and if you can provide us with a repro sample code, we might be able to do some investigation, but again if it's specially IIS's App Pool Identity, it might be out of my scope of expertise, and we're currently in the middle of release, so we might have to get back to it after the release.

**Comment by dinushahasith** [comment]
sure. I will check. thank you.

**Comment by RafaelxFernandes** [comment]
Any updates? I am facing the same problem

**Comment by JRahnama** [comment]
@RafaelxFernandes This issue does not look like a client driver issue, but more of IIS setup issue. The login fails for the provided user. You need to see what credentials have passed to the server and why server is rejecting them. Maybe server logs could be helpful.

**Comment by dimaggessi** [comment]
I was with the same error message.

change your .csproj
<InvariantGlobalization>false</InvariantGlobalization>

It seems to be InvariantGlobalization sent the incorrect credentials when you try to connect to your SQL Server database.

It solved to me.

**Comment by cheenamalhotra** [comment]
Closing as stale and solutions are discussed above.
