### ISSUE TITLE
SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 25 - Connection string is not valid)

### ISSUE THREAD

**Issue by Folasayo-Samuel** [dotnet/SqlClient#1871]
This error message typically indicates that there was a problem connecting to the SQL Server instance. Here are a few things you can try to troubleshoot the issue:

Make sure the SQL Server instance is running. You can check the status of the SQL Server instance in the SQL Server Configuration Manager.

Check the connection string in your application to ensure it is correct and points to the correct server and instance. Make sure the server name is correct, and that the instance name is correct if you are connecting to a named instance.

Make sure the firewall is not blocking the connection. If you are connecting to a remote SQL Server instance, you might need to add an exception for the SQL Server port (1433 by default) in the firewall.

If you are using a named instance, make sure the SQL Server Browser service is running. The SQL Server Browser service allows clients to connect to a named instance of SQL Server.

If you are using a named instance, make sure that the dynamic port assignment is enabled for the SQL Server instance. This allows the SQL Server instance to use a dynamic port, which can be useful if the firewall rules are changed frequently.

**Comment by lcheunglci** [comment]
Is this an actual issue where you tried all of the above steps and it still doesn't work with your connection string or are you posting the resolution steps here as an FYI of how to deal with the issue if someone runs into the same error.  If it's the latter, and it's not in the documentation, we can look into it; otherwise, if it's the former, please provide the connection string so we can see if we can reproduce it. Thanks!

**Comment by Folasayo-Samuel** [comment]
I posted the resolution steps here as an FYI of how to deal with the issue
if someone runs into the same error.

And, will appreciate more hints on how to get the issue resolved from more
experts based on their experiences.

**Comment by lcheunglci** [comment]
This doesn't appear to be in the [FAQ section](https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions), we can add that in and close this issue. You can continue to discuss here before adding to the FAQ.

**Comment by Folasayo-Samuel** [comment]
Alright bro.

**Comment by Aakash556-AI** [comment]
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)  on mac m2 chip

**Comment by moqueet009** [comment]
![form](https://github.com/user-attachments/assets/b3b7bb26-3f4d-4f26-b8d5-a78f52390cc8)
same issue 
if any one can help highly appreciated
