### ISSUE TITLE
Clarify documentation for `SqlBulkCopy.EnableStreaming`.

### ISSUE THREAD

**Issue by madelson** [dotnet/SqlClient#1873]
### Describe the bug
Today, [the docs for this property](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlbulkcopy.enablestreaming?cid=kerryherger&view=dotnet-plat-ext-7.0) say:

> When EnableStreaming is true, SqlBulkCopy reads from an IDataReader object using SequentialAccess, optimizing memory usage by using the IDataReader streaming capabilities. When it's set to false, the SqlBulkCopy class loads all the data returned by the IDataReader object into memory before sending it to SQL Server or SQL Azure.

To me, this reads as if this this property determines whether or not we can stream rows from the reader or whether we load all rows into memory upfront.

However, looking at the implementation, `EnableStreaming` is quite a bit more narrow and nuanced; as far as I can tell it only affects the handling of MAX-length _columns_ [here](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs#L1213) and null values [here](https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs#L978). 

### Expected behavior
It would be good to replace the current docs with a more detailed explanation of what this property does and what the tradeoffs are. When does it matter, and why would a caller want to set this vs. not?

It seems to me that this will only be really impactful if you are dealing with large binary and text columns, because it can avoid needing to read an entire column value into memory. I'm not sure when it would be a good idea _not_ to have this enabled; perhaps it adds overhead if you have lots of short values in MAX-length columns?

**Comment by JRahnama** [comment]
@madelson we will look into this.

**Comment by lcheunglci** [comment]
Thanks for bringing this to our attention. It looks like you're correct and it only applies MAX-length for the value types and null values for them.  We can update the documentation to reflect this behavior to reflect this detail.

**Comment by madelson** [comment]
Thanks!

**Comment by lcheunglci** [comment]
This has been merged and included in the 5.1.0 GA Release. Thank you!
