### ISSUE TITLE
sql connection exclusive access to db

### ISSUE THREAD

**Issue by JanEggers** [dotnet/SqlClient#189]
im trying to automate db deployment for my app (MS Orleans cluster, has no build in api for that)

sometimes the setup fails because another connection is open and an "alter db" hangs because it needs exclusive access to the db.

my first idea was to put db in single user mode but that sometimes fails because there is another connection open to the db that I just created.

I added  SqlConnection.ClearAllPools(); because I observed that besides I put all sqlconnections in using statements and close them explicit there still have been multiple active connections to the new db (seen in management studio)

Is there an api to disable connection pooling aka make sure that when the connection is disposed it is really closed?

Is the an api to close all connections except the connection i am using to setup the db?

I found this [kill em all](https://www.experts-exchange.com/questions/28984258/kill-all-other-existing-SQL-server-connection-except-the-login-started-by-current-session.html) but it seems hacky.
 
```
public static async Task SetupDatabase<T>(params string[] resources)
        {
            if (!await IsDbSetupRequired())
            {
                return;
            }

            Console.WriteLine("Setup DB");

            var connectionStringBuilder = new SqlConnectionStringBuilder(OrleansConstants.ConnectionString);
            var db = connectionStringBuilder.InitialCatalog;

            connectionStringBuilder.InitialCatalog = "master";

            using (var masterConnection = new SqlConnection(connectionStringBuilder.ToString()))
            {
                masterConnection.Open();

                using (var cmd = masterConnection.CreateCommand())
                {
                    cmd.CommandText = $"IF(db_id(N'{db}') IS NULL) CREATE DATABASE {db}";
                    cmd.ExecuteNonQuery();
                }
            }

            SqlConnection.ClearAllPools();

            using (var connection = new SqlConnection(OrleansConstants.ConnectionString))
            {
                await connection.OpenAsync();

                using (var cmd = connection.CreateCommand())
                {
                    cmd.CommandText = $"ALTER DATABASE {db} SET SINGLE_USER WITH ROLLBACK IMMEDIATE; ";
                    cmd.ExecuteNonQuery();
                }

                try
                {
                    foreach (var step in resources)
                    {
                        using (var stream = typeof(T).Assembly.GetManifestResourceStream(typeof(T).Namespace + "." + step))
                        {
                            using (var cmd = connection.CreateCommand())
                            {
                                cmd.CommandTimeout = 500;
                                cmd.CommandText = new StreamReader(stream).ReadToEnd();
                                cmd.ExecuteNonQuery();
                            }
                        }
                    }
                }
                finally
                {
                    using (var cmd = connection.CreateCommand())
                    {
                        cmd.CommandText = $"ALTER DATABASE {db} SET MULTI_USER;";
                        cmd.ExecuteNonQuery();
                    }
                }
            }
        }
```

**Comment by JanEggers** [comment]
@Wraith2 thx for the pointer to pooling, I overlooked that. 

do you have any input on:

Is the an api to close all connections except the connection i am using to setup the db?

I found this kill em all but it seems hacky.


As there may be another cluster node that does some availability check while one node is trying to setup the db?

**Comment by cheenamalhotra** [comment]
@JanEggers 

Any updates over @Wraith2 's suggestions?

Pooling is enabled by default and disabling it isn't a hack but another driver supported behavior documented on MS Docs: [SqlConnection#Remarks](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection?view=netframework-4.8#remarks). You can disable pooling by setting connection property `Pooling` as `false` or `no`.

Let us know is that resolves your problem with open connections and if you need any other support.

**Comment by JanEggers** [comment]
@cheenamalhotra the pooling option did improve the situation if I just launch one cluster node.
But if I start multiple nodes I still have the problem that one Node tries to setup the db and other nodes interfere with their connections. But I guess that I have to workaround that by creating just one instance during initial deployment and ramp that up once the db is setup.

**Comment by cheenamalhotra** [comment]
Hi @JanEggers I'm not well versed with MS Orleans but wondering if this could be a cluster management issue where nodes are redirecting requests or you're missing some configuration on client side!

If your setup is leaning towards FailOver Cluster group then maybe something you need to configure to make that configuration work. If not done already, you can try playing with SqlConnection properties like MultiSubnetFailover. Please refer documentation if this helps: https://docs.microsoft.com/en-us/sql/sql-server/failover-clusters/windows/sql-server-multi-subnet-clustering-sql-server?view=sql-server-2017
