### ISSUE TITLE
can not connect to sql server 2008 in mac?

### ISSUE THREAD

**Issue by ljzj2** [dotnet/SqlClient#1898]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I can not connect to SQL Server 2008 in mac .
and I can connect it in windows using same code.

I am using asp.net core 7.0 razor pages.
mac version is 11.6.5.

and I can connect to SQL Server 2008 using dbms tools.

### Expected Behavior

connect well.

### Exceptions (if any)

SQL Exception:
A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 2 - Connection was terminated: Connection was terminated)

### .NET Version

7.0.102

**Comment by lcheunglci** [comment]
Hi @ljzj2, as @ErikEJ mentioned Sql Server 2008 has reached [end of support](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-sql-server-2008) and you can see the list of supported versions [here](https://learn.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver16).  We would recommend that you upgrade to a newer supported version and try again.

**Comment by lcheunglci** [comment]
Also, are you using Microsoft.Data.SqlClient or System.Data.SqlClient?

**Comment by ljzj2** [comment]
@ErikEJ @lcheunglci  thank you for your answer. I know SQL Server 2008 has reached end of support. I use it for cheap price some provider still use it. microsoft azure is a little expensive for me student.

**Comment by ljzj2** [comment]
@lcheunglci  I am using asp.net core 7.0 + ef core . not Microsoft.Data.SqlClient or System.Data.SqlClient.

**Comment by ljzj2** [comment]
I use Azure Data Studio in mac and it can connect to SQL Server 2008 

that what I have tried.

**Comment by JRahnama** [comment]
@ljzj2 try with the developer edition of SQL server 2019 (it is free) for testing purposes and see if you are able to get connection. If you are still unable to connect, we can start investigating the issue, otherwise because that version is not supported anymore there is not much we can do.

If the issue persists with SQL server 2019 provide a simple repro application.

**Comment by JRahnama** [comment]
> @lcheunglci I am using asp.net core 7.0 + ef core . not Microsoft.Data.SqlClient or System.Data.SqlClient.

`Microsoft.EntityFrameworkCore.SqlServer` has a dependency to `M.D.SqlClient 5.0.1`

**Comment by ljzj2** [comment]
same code in windows I am able to get connection so I think it is mac issue.

not sql server.

now I close this issue and I give up and I will go to use windows to develop.


and can you tell me what is difference of express edition and developer edition of SQL Server?

**Comment by JRahnama** [comment]
> and can you tell me what is difference of express edition and developer edition of SQL Server?

> SQL Server Developer edition lets developers build any kind of application on top of SQL Server. It includes all the functionality of Enterprise edition, but is licensed for use as a development and test system, not as a production server. SQL Server Developer is an ideal choice for people who build and test applications.

whereas 

> SQL Server Express edition is the entry-level, free database and is ideal for learning and building desktop and small server data-driven applications. It is the best choice for independent software vendors, developers, and hobbyists building client applications. If you need more advanced database features, SQL Server Express can be seamlessly upgraded to other higher end versions of SQL Server. SQL Server Express LocalDB is a lightweight version of Express that has all of its programmability features, runs in user mode and has a fast, zero-configuration installation and a short list of prerequisites.

you can read more on [this article](Microsoft.EntityFrameworkCore.SqlServer).
