### ISSUE TITLE
Wrong version number in latest release? Starts with "3"

### ISSUE THREAD

**Issue by alex-jitbit** [dotnet/SqlClient#1918]
The releases page is a bit confusing https://github.com/dotnet/SqlClient/releases

**Comment by alex-jitbit** [comment]
Probably because it's  a .NET Framework version... Closing this issue.

**Comment by JRahnama** [comment]
@alex-jitbit we addressed a minor tagging issue. Thanks for bringing this up.  Can you check if you concern is addressed?
