### ISSUE TITLE
Upgrade Azure.Identity dependency to version 1.8.0

### ISSUE THREAD

**Issue by scottaddie** [dotnet/SqlClient#1919]
In v1.8.0 of the Azure Identity library for .NET (_Azure.Identity_), token caching was added for the `ManagedIdentityCredential` type. Token lifetime and refreshing is handled automatically. See https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/CHANGELOG.md#180-beta1-2022-10-13. Under the hood, MSAL's in-memory cache is used. This dependency upgrade will help mitigate Azure AD throttling issues that occur from calling it too frequently.

For Java customers, this issue has already been addressed as of the latest stable JDBC driver release. See https://github.com/microsoft/mssql-jdbc/issues/1930.

/cc: @David-Engel

**Comment by ErikEJ** [comment]
@scottaddie So an explicit update to 1.8.0 will also add automagic caching?

**Comment by lcheunglci** [comment]
Thanks @scottaddie for making the suggestion.  I do believe by upgrading this dependency it would also resolve https://github.com/dotnet/SqlClient/issues/1900 and we can consider upgrading it in our next release and I'll bring it up to the team and get back you too soon.

**Comment by scottaddie** [comment]
> @scottaddie So an explicit update to 1.8.0 will also add automagic caching?

That's correct, @ErikEJ. Caching is enabled by default. No app code changes are required to use it.

**Comment by lcheunglci** [comment]
Thanks @scottaddie for the suggestion and Azure Identity 1.8.0 would be included in the 5.2 release.

**Comment by scottaddie** [comment]
@lcheunglci The following issue should also be resolved with this dependency upgrade: https://github.com/dotnet/SqlClient/issues/1495
