### ISSUE TITLE
Upgrade from Framework to Standard

### ISSUE THREAD

**Issue by DanPatten** [dotnet/SqlClient#1923]
Hello,

I am looking to gradually upgrade several projects one at a time from .NET Framework -> .NET Standard 2.0.

However I have several projects referencing Microsoft.SqlServer.Types (using SqlGeography)

How do I upgrade the lowest project first to .NET standard 2.0 while still maintaining existing references. I am confused if I should be using this library or something else.

As a note I am using System.Data.SqlClient everywhere, I could upgrade it.

Thanks!

**Comment by ErikEJ** [comment]
Just use Microsoft.Data.SqlClient 5 with the latest Microsoft.SqlServer.Types package

**Comment by lcheunglci** [comment]
@DanPatten did upgrading to Microsoft.Data.SqlClient 5.x resolve the issue for you?

**Comment by DanPatten** [comment]
I'm going to try that and see if that works, thanks!

**Comment by DanPatten** [comment]
So just to confirm this will work correct?

The Microsoft.SqlServer.Types being on .NET Standard 2.1 is what is confusing me

![Design](https://user-images.githubusercontent.com/10733204/221096097-1a56cd60-cd9e-4c3d-9493-751587a7a768.png)

**Comment by ErikEJ** [comment]
@DanPatten Why? Microsoft.SqlServer.Types targets NET Standard 2.1 & NET Framework 462 ...

**Comment by DanPatten** [comment]
Can a .NET standard 2.0 library reference a 2.1 standard library?

**Comment by DanPatten** [comment]
I tried the above scenario and getting this error:

Warning	NU1701	Package 'Microsoft.SqlServer.Types 160.1000.6' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8, .NETFramework,Version=v4.8.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.	ClassLibrary1

**Comment by ErikEJ** [comment]
@DanPatten you need to target net462 or netstandard2.1 (or both) with Microsoft.SqlServer.Types (bad design decision imgo)

**Comment by DanPatten** [comment]
Makes sense, really makes it hard to upgrade when 2.1 standard isn't compatible with framework.

**Comment by ErikEJ** [comment]
You can target multiple "frameworks" on the same project and/or share code..
