### ISSUE TITLE
Error while importing the System.Data.SqlClient namespace in Azure Function V4 

### ISSUE THREAD

**Issue by Kumar-Akshay** [dotnet/SqlClient#1929]
### Describe the bug

Hi,
I have created the Azure Function on the portal using the csx file.
I have been trying to use the system.data.sqlclient library in my Azure Function V4 with .NET 6, but this error occurs

> run.csx(7,20): error CS1069: The type name 'SqlConnection' could not be found in the namespace 'System.Data.SqlClient'. This type has been forwarded to assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

When I downgraded my function App from V4 to V3. It was working fine with same code but when I was trying to upgrade the function App with V4, it returns the same error.
I am only getting this issue while creating the Azure Function on the portal.

This is simple run.csx file

```
#r "System.Data.SqlClient.dll"
using System.Data.SqlClient;
using System;
public static void Run(TimerInfo myTimer, ILogger log)
{
    var conn = new SqlConnection("MyConnectionString");
    log.LogInformation($"C# Timer trigger function executed at: {DateTime.Now}");
}
```

I have tried to put the system.data.sqlclient.dll in the bin folder of function using kudu console, but still getting same error.

### To Reproduce
Create new Azure Function using the Azure Portal and using above mention code in the csx file and execute the function check the output.

 Any help much appreciated
 Thanks

**Comment by Kumar-Akshay** [comment]
https://github.com/dotnet/SqlClient/issues/1512
This problem is similar, but they only reduced the function V4 to V3 to resolve the issue. However, I do not wish to downgrade the function app. I want to use the Azure Function V4.

**Comment by JRahnama** [comment]
@Kumar-Akshay it is better to contact Azure support for this issue. In order to get a better solution for binding area.
