### ISSUE TITLE
Clarify the difference between System.Data.SqlClient and Microsoft.Data.SqlClient in NuGet

### ISSUE THREAD

**Issue by ericstj** [dotnet/SqlClient#1963]
@sharwell raised the concern that he couldn't tell the difference between 
https://www.nuget.org/packages/System.Data.SqlClient
and
https://www.nuget.org/packages/Microsoft.Data.SqlClient

Which should he use, and why?

### Describe the solution you'd like
Clear messaging in the package descriptions around which package to use.  Potentially marking the old one as obsolete.

**Comment by ericstj** [comment]
I'm aware of those sources.  I believe @sharwell's request was to make the guidaince more visible for the user who's just coming through NuGet.

For example: https://www.nuget.org/packages?q=SqlClient
<img width="759" alt="image" src="https://user-images.githubusercontent.com/8918108/227365161-088a6aba-c8c0-4d8a-9f60-a167d5170793.png">

From this it's not clear what to choose, as both have nearly identical descriptions.

**Comment by lcheunglci** [comment]
Thanks @ericstj for the clarification.  I'll bring it up to the team and see if we can update the nuget description to make it easier to distinguish between them.

**Comment by JRahnama** [comment]
Closing as it was fixed by #1973
