### ISSUE TITLE
Release Nuget package generation

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#197]
I started trying to do some perf measurements but had some trouble generating a release nuget package. I managed it but the command is a little confusing `msbuild /p:Configuration=Release /t:BuildAllConfigurations` if I'm setting the configuration I shouldn't then ask for all configurations.

I had a play around and found the GenerateNugetPackage task but it doesn't work without a build all. I expected to be able to do `msbuild /p:Configuration=Release` followed by `msbuild /p:Configuration=Release /t:GenerateNugetPackage` but this fails with the error messages:

```
  E:\Programming\csharp7\SqlClient\src\..\.nuget\nuget.exe pack E:\Programming\csharp7\SqlClient\src\..\tools\specs\Microsoft.Data.SqlClient.nuspec -Version 1.1.0-dev -OutputDirectory E:\Programming\csharp7\SqlClient\src\..\packages\ -p
  roperties Configuration=Release
  Attempting to build package from 'Microsoft.Data.SqlClient.nuspec'.
  Could not find a part of the path 'E:\Programming\csharp7\SqlClient\bin\AnyOS\Release\Microsoft.Data.SqlClient\ref\netcoreapp2.1'.
E:\Programming\csharp7\SqlClient\tools\targets\GenerateNugetPackage.targets(10,5): error MSB3073: The command "E:\Programming\csharp7\SqlClient\src\..\.nuget\nuget.exe pack E:\Programming\csharp7\SqlClient\src\..\tools\specs\Microsoft.D
ata.SqlClient.nuspec -Version 1.1.0-dev -OutputDirectory E:\Programming\csharp7\SqlClient\src\..\packages\ -properties Configuration=Release" exited with code 1. [E:\Programming\csharp7\SqlClient\build.proj]
Done Building Project "E:\Programming\csharp7\SqlClient\build.proj" (GenerateNugetPackage target(s)) -- FAILED.
```
I'm pretty sure the problem is that it's looking for `bin\AnyOS` which doesn't exist, I've only got `bin\Windows_NT` once the release build completes. 

It might also be a good idea to add the .nuget/ folder to the .gitignore file

**Comment by cheenamalhotra** [comment]
Sure, I'm looking into some improvements there too, will push some updates soon!

**Comment by cheenamalhotra** [comment]
Hi @Wraith2 
The default target has been changed to "BuildAllConfigurations" and has been checked in.

Closing issue.
