### ISSUE TITLE
Transient Fault Handling is disabled by default with SqlConnection.OpenAsync()

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#1982]
### Describe the bug
When opening a connection with `SqlConnection.OpenAsync()`, transient fault handling is not enabled.
Test with placing breakpoints on below locations:
https://github.com/dotnet/SqlClient/blob/a5ad8382a390ea599740bd3ab51b19601bbd92e0/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L1859
https://github.com/dotnet/SqlClient/blob/a5ad8382a390ea599740bd3ab51b19601bbd92e0/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L1888

`_applyTransientFaultHandling` is set to `false` as `retry` is not `null` in this method when opening connection asynchronously.
When opening connection with `Open()`, `_applyTransientFaultHandling` is set to `true` as expected.

**Comment by David-Engel** [comment]
Thanks for filing the issue and submitting a PR for the fix!
