### ISSUE TITLE
Valid token definition duplication?

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#200]
When profiling i was looking at the definition of [TdsParser.IsValidTdsToken](https://github.com/dotnet/SqlClient/blob/456268c8400adf70272c6b45ef28be137f2a8547/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs#L1686) and wondered if there was a better way to do the comparison than 29 sequential comparisons. So i dumped the values to look for patterns and found that two of the comparisons are the same value with different names in `TdsEnums`.
```csharp
public const byte SQLSECLEVEL = 0xed;    // Security level token ???
public const byte SQLSSPI = 0xed;    // SSPI data
```
I'm not sure where the internal definitions come from. It could do with checking to see if they really do have the same value and if so which should be used.

**Comment by karinazhou** [comment]
Hi @Wraith2 ,

The value `0xed` is from the [TDS Protocol](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/b46a581a-39de-4745-b076-ec4dbb7d13ec) if you search for SSPI Token. 

Yeah, I looked into the code and didn't find any usage of this `SQLSECLEVEL` token. It could be some leftover from a long time ago. Good catch!

Thanks,

**Comment by Wraith2** [comment]
There are quite a few constants in that file that I suspect aren't used anymore, the banyan vines protocol schema for example. I'll have another browse through and see if there is any other low hanging fruit then probably eliminate this one and any others in a small PR. Just needed confirmation on the suspected invalidity.

Incidentally the reason I was looking at the constants in the original post was to see if I could make it faster to check if a token is valid. The answer turns out to be that no, I can't. The current linear check looks inefficient but is the fastest and most reliable method unless we had a netcoreapp3.0 build target and in that case there's an SSE path that's 30% faster.
