### ISSUE TITLE
Could not load assembly Microsoft.data.sqlclient

### ISSUE THREAD

**Issue by ridhansh** [dotnet/SqlClient#2008]
I am creating my project in .net core 6 , in my local it's working fine but when I m deploying my binaries to server it is saying could not find assembly for Microsoft.data.sqlclient

**Comment by ridhansh** [comment]
Publishing and then deploying manually, no pipeline is setup yet

**Comment by JRahnama** [comment]
@ridhansh we need more information. Can you provide very specific details of tools and commands you are using please?

**Comment by JRahnama** [comment]
Closing the issue due to inactivity. Feel free to open a new issue or comment here.
