### ISSUE TITLE
Publish symbols to NuGet symbol server

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/SqlClient#2017]
Symbols should be published to NuGet symbol server according to [Creating symbol packages (.snupkg)](https://learn.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg).

**Comment by JRahnama** [comment]
@paulomorgado seems like duplicate of #2016

**Comment by paulomorgado** [comment]
Related, but not duplicate.

I've since found out that source linking is also missing.

**Comment by MichelZ** [comment]
This can probably be closed due to #2137
