### ISSUE TITLE
Invalid value for key 'Encrypt'

### ISSUE THREAD

**Issue by qizu0302** [dotnet/SqlClient#2019]
I'm using Microsoft.Data.SqlClient **5.1.0**, set SqlConnectionStringBuilder.Encrypt to **SqlConnectionEncryptOption.Strict**, it always pop up _"Invalid value for key 'Encrypt' "_ error, I tried other values as well, like true/false/SqlConnectionEncryptOption.Optional, all failed.

![image](https://user-images.githubusercontent.com/103396968/234210827-0cb83bca-ffce-44a7-b97c-4f7b170ff1f4.png)

**Do you know the right value for 'Encrypt' value? 
And if I want to set up a TLS 1.3 connection to SQL server, do I need to use the latest SQL Server release?**

**Comment by ErikEJ** [comment]
@qizu0302 Sure you are not referencing the System.data.SqlClient SqlConnectionStringBuilder?

**Comment by qizu0302** [comment]
@ErikEJ Pretty sure I use M.D.S lib
![image](https://user-images.githubusercontent.com/103396968/234223880-9049e44f-0c7c-4d9a-9df9-c007e59e292a.png)

**Comment by JRahnama** [comment]
@qizu0302 not sure on your setup, I just tested with that version and it worked fine. Can you provide a repro please?

**Comment by Wraith2** [comment]
could this be the same issue as https://github.com/dotnet/SqlClient/issues/2015 ?

**Comment by qizu0302** [comment]
Here's my code:
`configDatabaseConnection = new SqlConnectionStringBuilder();
configDatabaseConnection.DataSource = server;
            configDatabaseConnection.InitialCatalog = configDatabase;
            configDatabaseConnection.Encrypt = SqlConnectionEncryptOption.Strict;
            configDatabaseConnection.TrustServerCertificate = true;`

**Comment by qizu0302** [comment]
Here's my part of code:

`configDatabaseConnection = new SqlConnectionStringBuilder();`
`configDatabaseConnection.DataSource = server;`
`configDatabaseConnection.InitialCatalog = configDatabase;`
`configDatabaseConnection.Encrypt = SqlConnectionEncryptOption.Strict;`
`configDatabaseConnection.TrustServerCertificate = true;`
`configDatabaseConnection.IntegratedSecurity = true;`

configDatabaseConnection is used to set up the connection between SharePoint server and SQL Server, the output is below:

`Exception: System.ArgumentException: Invalid value for key 'Encrypt'.`
   `at Microsoft.Data.Common.DbConnectionStringBuilderUtil.ConvertToSqlConnectionEncryptOption(String keyword, Object value)`
   `at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Item(String keyword, Object value)`
   `at Microsoft.SharePoint.Utilities.SafeSqlConnectionStringBuilder..ctor(SqlConnectionStringBuilder builder, Boolean copy)`
   `at Microsoft.SharePoint.Administration.SPConfigurationDatabase.Provision(SqlConnectionStringBuilder connectionString)`
   `at Microsoft.SharePoint.Administration.SPFarmFactory.CreateConfigurationDatabase()`
   `at Microsoft.SharePoint.Administration.SPFarmFactory.Create()`
   `at Microsoft.SharePoint.Administration.SPFarm.Create(SqlConnectionStringBuilder configurationDatabase, SqlConnectionStringBuilder administrationContentDatabase, SqlConnectionStringBuilder siteMapDatabase, SqlConnectionStringBuilder timerServiceDatabase, IdentityType identityType, String farmUser, SecureString farmPassword, SecureString masterPassphrase)`
   `at Microsoft.SharePoint.Administration.SPFarm.Create(SqlConnectionStringBuilder configurationDatabase, SqlConnectionStringBuilder administrationContentDatabase, String farmUser, SecureString farmPassword, SecureString masterPassphrase)`
   `at Microsoft.SharePoint.PostSetupConfiguration.ConfigurationDatabaseTask.CreateOrConnectConfigDb()`
   `at Microsoft.SharePoint.PostSetupConfiguration.ConfigurationDatabaseTask.Run()`
  `at Microsoft.SharePoint.PostSetupConfiguration.TaskThread.ExecuteTask()`

**Comment by qizu0302** [comment]
@JRahnama does your PR aim at this issue? After your PR check in, how can I get the latest library? I mean which NuGet package version I need to use.

**Comment by Wraith2** [comment]
I think it's this set of artifacts from the CI build https://sqlclientdrivers.visualstudio.com/904996cc-6198-4d39-8540-eca72bdf0b7b/_apis/build/builds/64525/artifacts?artifactName=Artifacts&api-version=7.0&%24format=zip

**Comment by qizu0302** [comment]
This is 5.10.0 version, I don't see it on https://www.nuget.org/packages?q=Microsoft.Data.SqlClient. 
Only using this package in my lab also has some errors, so I need to clarify its dependency versions
![image](https://user-images.githubusercontent.com/103396968/236098711-6b7f0365-de48-4fdb-b2dc-a6c263ca6e33.png)

**Comment by qizu0302** [comment]
BTW, in order to use TLS 1.3, do I have to use SQL Server 2022 and SSMS 19.0?

**Comment by JRahnama** [comment]
for TLS 1.3 it has to be SQL Server 2022 and Encrypt type Strict. SSMS 19 yet to add support for it. You can use M.D.SqlClient to achieve that.

**Comment by qizu0302** [comment]
Another issue, set "Force strict Encryption" in Sql Server Configuration Manager, disable legacy SSL version, enable TLS 1.3 in registry, then Sql Server service can't start
![image](https://github.com/dotnet/SqlClient/assets/103396968/1ab3884d-1f31-46a8-b17f-dabe67c0b7fd)

The cert I use is a self-signed one generated on Sql Server, does this issue relate to the cert?
![image](https://github.com/dotnet/SqlClient/assets/103396968/4f3d184f-11dd-42d2-998b-52bfa54ac7ec)

**Comment by ErikEJ** [comment]
SSMS 19.0 does not support TLS 1.3

**Comment by JRahnama** [comment]
> I have a basic question, if I do following steps:
> 
> 1. Set 'Force Strict Encryption' to yes in Sql Server Configuration Manager
> 2. Enable TLS 1.3 in \HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Server(Client)
> 3. Set 'Encrypt connection' and 'Trust server certificate' in SSMS 19
> 
> Does it use TLS 1.3 when connecting to localDB via SSMS?
> 
> If I want to let a client to connect to SQL Server using TLS 1.3, is there any configurations need to do on SQL Server side besides setting specific configurations in ConnectionString and registry on client side?

Encryption types are not supported on LocalDB. Also to add more SSMS 19, as @ErikEJ mentioned, is not supporting Strict and TLS 1.3. From what I know, you can check and confirm with SSMS team, it will be added in next version of SSMS.

**Comment by qizu0302** [comment]
If SSMS 19 doesn't support Strict and TLS 1.3, how can we connect to DB and do some operations?

**Comment by yuanhe772** [comment]
Hi team, any updates on this? Im using `Microsoft.Data.SqlClient=v5.2.0` and `Microsoft.EntityFrameworkCore=v6.0.26`, and Im getting a similar error that `SqlConnectionStringBuilder` cannot recognize "Strict" as the Encrypt option

```
"InnerException":{"ClassName":"System.FormatException","Message":"String 'Strict' was not recognized as a valid Boolean.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"
   at System.Boolean.Parse(ReadOnlySpan`1 value)\r\n
   at System.Boolean.Parse(String value)\r\n
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder.set_Item(String keyword, Object value)\r\n
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)\r\n
   at Microsoft.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)\r\n
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.<>c.<get_IsMultipleActiveResultSetsEnabled>b__7_0(String cs)\r\n
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)\r\n
   at Microsoft.EntityFrameworkCore.SqlServer.Query.Internal.SqlServerCompiledQueryCacheKeyGenerator.GenerateCacheKey(Expression query, Boolean async)\r\n
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)\r\n
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)\r\n
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)\r\n
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)\r\n
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)\r\n
```

**Comment by cheenamalhotra** [comment]
Please update EF Core to v7 to use MDS 5.1+. Closing as compatibility error.
