### ISSUE TITLE
I'm getting this error in my last project I'm developing. No problem connecting to sql server. error is attached

### ISSUE THREAD

**Issue by grbzemir** [dotnet/SqlClient#2036]
System.TypeInitializationException: ''Microsoft.Data.SqlClient.SNINativeMethodWrapper' type initializer returned exception.'
Win32Exception: The specified module could not be found

**Comment by JRahnama** [comment]
@grbzemir can you provide more info please? A sample repro would help. Also version of M.D.SqlClient and platform is required as well.

**Comment by JRahnama** [comment]
@grbzemir can you look at similar issues such as #361 or other similar questions.
