### ISSUE TITLE
Microsoft.Data.SqlClient dependency old version of Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by dgxhubbard** [dotnet/SqlClient#2039]
We use Microsoft.Data.SqlClient for connecting to azure and to get sql connections. As part of this push we are also using an identity provider. Both the identity provider and Microsoft.Data.SqlClient depend on 
Microsoft.IdentityModel.Protocols. Microsoft.Data.SqlClient uses verion 6.24.0 (or greater) of Microsoft.IdentityModel.Protocols, while our identity provider uses 6.30.0 (or greater). The identity provider code tries to use Microsoft.IdentityModel.Protocols and an exception is produced because version 6.24.0 is there instead of 6.30.0. Can you update your code to the latest version of Microsoft.IdentityModel.Protocols whenever  Microsoft.Data.SqlClient is release. It would be very helpful

**Comment by JRahnama** [comment]
Can you try and reference that version directly? It will overwrite the prev. version.

**Comment by dgxhubbard** [comment]
That is exactly what I did and it worked thank you

**Comment by JRahnama** [comment]
If the issue is solved feel free to close the issue.
 Dependencies version bump will be done in future, but not now as other libraries are dependent to this versions, unless there is a security bug that needs immediate update.
