### ISSUE TITLE
Cannot connect to SQL Server

### ISSUE THREAD

**Issue by Bykiev** [dotnet/SqlClient#2053]
On my development machine EF successfully connecting to SQL Server, I've deployed the .NET 6 app with EF Core 7 on Windows Server 2012r2 and SQL Server 2014. Now I'm getting this error message:

`A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - An existing connection was forcibly closed by the remote host.)`

I've included `TrustServerCertificate=True` in connection string with no luck.

In server log I can see these errors:

`A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 10. The Windows SChannel error state is 1200.`

`A fatal alert was generated and sent to the remote endpoint. This may result in termination of the connection. The TLS protocol defined fatal error code is 10. The Windows SChannel error state is 1202.`

What can be the issue? Login and password are correct.

**Comment by Bykiev** [comment]
Can be this issue related to my?
https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/apps-forcibly-closed-tls-connection-errors

**Comment by Bykiev** [comment]
It seems SQL Server version doesn't matter, smth with windows server 2012r2

**Comment by JRahnama** [comment]
@Bykiev can you check the registry to see what TLS versions are enabled?

**Comment by Bykiev** [comment]
In Advanced settings of IE TLS 1.0, 1.1, 1.2 ans SSL 3.0 protocols enabled

**Comment by JRahnama** [comment]
can you disable 1.0, 1.1 and ssl3.0 and test with 1.2 to see if that solves the issue? Also if you can check at to see if those are set at `Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols` in registry editor. 

you can read on that part [here](https://learn.microsoft.com/en-us/mem/configmgr/core/plan-design/security/enable-tls-1-2-client) to enable it for clients. You will need to set it up for server as well.

**Comment by Bykiev** [comment]
Unfortunately, I can't disable them as it can be used by some software on this server.
I've checked the registry, and attached the screenshot.
![registry](https://github.com/dotnet/SqlClient/assets/13969777/89ed4b0c-b85b-4bbe-acb8-bfee2459e165)

**Comment by Bykiev** [comment]
The whole error message:

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfull
y established with the server, but then an error occurred during the login proce
ss. (provider: SSL Provider, error: 0 - An existing connection was forcibly clos
ed by the remote host.)
 ---> System.ComponentModel.Win32Exception (10054): An existing connection was f
orcibly closed by the remote host.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException except
ion, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserState
Object stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.ThrowExceptionAndWarning(Boo
lean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.SNIWritePacket(PacketHandle
packet, UInt32& sniError, Boolean canAccumulate, Boolean callerHasConnectionLock
, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WriteSni(Boolean canAccumula
te)
   at Microsoft.Data.SqlClient.TdsParserStateObject.WritePacket(Byte flushMode,
Boolean canAccumulate)
   at Microsoft.Data.SqlClient.TdsParser.TdsLogin(SqlLogin rec, FeatureExtension
 requestedFeatures, SessionData recoverySessionData, FederatedAuthenticationFeat
ureExtensionData fedAuthFeatureExtensionData, SqlConnectionEncryptOption encrypt
)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Login(ServerInfo server,
 TimeoutTimer timeout, String newPassword, SecureString newSecurePassword, SqlCo
nnectionEncryptOption encrypt)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerIn
fo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignor
eSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerIn
fo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redir
ectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credenti
al, TimeoutTimer timeout)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutT
imer timeout, SqlConnectionString connectionOptions, SqlCredential credential, S
tring newPassword, SecureString newSecurePassword, Boolean redirectedUserInstanc
e)
   at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolId
entity identity, SqlConnectionString connectionOptions, SqlCredential credential
, Object providerInfo, String newPassword, SecureString newSecurePassword, Boole
an redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionDat
a reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken,
 DbConnectionPool pool)
   at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectio
nOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbC
onnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptio
ns)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbC
onnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbCo
nnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection own
ingObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnectio
n owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnect
ion)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection
 owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolea
n onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&
 connection)
   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection
 owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, Db
ConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnect
ion owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOpti
ons, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal
(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskComple
tionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnect
ion outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource
`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retr
y, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrid
es)
   at Microsoft.Data.SqlClient.SqlConnection.Open()
```

**Comment by Bykiev** [comment]
I've tested it on another windows server 2012r2 - working fine. What can be the issue on this server?

**Comment by alex-radch** [comment]
I have a similar problem on `Windows Server 2012 R2` and SQL Server 2014, but with a different error text:
`A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - No process is on the other end of the pipe.)`

Error starts reproducing when you change version of package "Microsoft.Data.SqlClient" from `5.0.2 to >= 5.1.0`, also tried prerelease version - problem remains. I also tried to install SQL Server 2017 - the maximum available version for this Windows Server 2012 R2, problem remains. Options with disabling some versions of TLS/SSL do not help in any variations: leaving only TLS 1.0; only TLS 1.2, etc. (I used the IISCrypto tool and rebooted machine every time).

Client and server are on the SAME machine at the same time, that is, my application ASP.NET Core (EF Core -> Microsoft.Data.SqlClient (>=5.1.0 version)) tries to connect to SQL Server database when application starts.

Database connection string: `Data Source=.;Initial Catalog=DatabaseName;Integrated Security=true;TrustServerCertificate=true;`,
which means I want to connect to the database via windows authentication. If I change connection string to connect via SQL Server authentication via IP address (like `Data Source=127.0.0.1;Initial Catalog=DatabaseName;User ID=user;Password='password';TrustServerCertificate=true;`), then I will get the same error as in this Issue:
`A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - An existing connection was forcibly closed by the remote host.)`

Any ideas?

**Comment by Bykiev** [comment]
> I have a similar problem on `Windows Server 2012 R2` and SQL Server 2014, but with a different error text: `A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - No process is on the other end of the pipe.)`
> 
> Error starts reproducing when you change version of package "Microsoft.Data.SqlClient" from `5.0.2 to >= 5.1.0`, also tried prerelease version - problem remains. I also tried to install SQL Server 2017 - the maximum available version for this Windows Server 2012 R2, problem remains. Options with disabling some versions of TLS/SSL do not help in any variations: leaving only TLS 1.0; only TLS 1.2, etc. (I used the IISCrypto tool and rebooted machine every time).
> 
> Client and server are on the SAME machine at the same time, that is, my application ASP.NET Core (EF Core -> Microsoft.Data.SqlClient (>=5.1.0 version)) tries to connect to SQL Server database when application starts.
> 
> Database connection string: `Data Source=.;Initial Catalog=DatabaseName;Integrated Security=true;TrustServerCertificate=true;`, which means I want to connect to the database via windows authentication. If I change connection string to connect via SQL Server authentication via IP address (like `Data Source=127.0.0.1;Initial Catalog=DatabaseName;User ID=user;Password='password';TrustServerCertificate=true;`), then I will get the same error as in this Issue: `A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - An existing connection was forcibly closed by the remote host.)`
> 
> Any ideas?

Just a suggestion, do you have a Kaspersky Antivirus installed or CryptoPro CSP installed? Still can't find the root of the issue

**Comment by alex-radch** [comment]
> Just a suggestion, do you have a Kaspersky Antivirus installed or CryptoPro CSP installed? Still can't find the root of the issue

Yes, both programs are installed

**Comment by alex-radch** [comment]
> It seems we have equal environment, but I can't disable/uninstall any of them to check is any of them causing the issue. Can you disable/uninstall them?

I'm not 100% sure, but I'll try

**Comment by Bykiev** [comment]
Thank you, I've tested on clean Windows 2012r2 server without these programs and connection established without any issues. So, Kaspersky and/or CryptoPro can cause the issue.

**Comment by Bykiev** [comment]
@alex-radch , just a thoughts, what version of CryptoPro CSP do you have installed?

**Comment by alex-radch** [comment]
@Bykiev 4.0.9944

**Comment by Bykiev** [comment]
I'm pretty sure, the issue with CryptoPro CSP, if you'll check the [release notes](https://www.cryptopro.ru/forum2/default.aspx?g=posts&t=13703&p=2) almost every version contains changes to tls protocol. On my server 5.0.12600 version install

**Comment by Bykiev** [comment]
@alex-radch, will it be possible to check on your side or I'll ask our system administrator to create a test environment with CryptoPro and Kaspersky installed on windows server 2012R2 (but it'll take up to week)? I can't test it on a production server.

**Comment by alex-radch** [comment]
@Bykiev I'm already trying to ask system administrator for this. But I also can't say how long it will take

**Comment by Bykiev** [comment]
> @Bykiev I'm already trying to ask system administrator for this. But I also can't say how long it will take

Got it, thank you! If you will not respond till the end of the week, we'll test on our side, but it'll take some time

**Comment by Bykiev** [comment]
@alex-radch , we've deployed a test server and I can confirm the issue with CryptoPro (tested without Kaspersky Antivirus installed), before installing CryptoPro CSP everything is working as expected. I've tried even with the latest version of CryptoPro CSP and the issue still remains

**Comment by Bykiev** [comment]
@alex-radch, you can find some more information here: https://www.cryptopro.ru/forum2/default.aspx?g=posts&m=141401#post141401

**Comment by Bykiev** [comment]
> @Bykiev At the moment we just deleted CryptoPro because it is not used. Options with some kind of CryptoPro fix were not considered

Is all working after remove of CryptoPro?

**Comment by alex-radch** [comment]
> Is all working after remove of CryptoPro?
yeah

**Comment by Bykiev** [comment]
The issue will be fixed in the next update of CryptoPro CSP
