### ISSUE TITLE
Azure Active Directory Default Connection Speed

### ISSUE THREAD

**Issue by davidhendrickmb** [dotnet/SqlClient#2072]
Hi,

We have transitioned to using "Authentication=Active Directory Default" in our EF Core connection strings as opposed to usernames and passwords.
When connecting via Visual Studio, it is now taking 3 times as long to process the first request as it appears to be attempting to authenticate via unsupported mechanisms prior to using VisualStudio authentication to retrieve a token.
Is there any way I can have EFCore skip these steps and go straight to Visual Studio authentication?

<https://github.com/Azure/azure-sdk-for-net/blob/e9cbf9b31df595b2b34268fa91e14be9d57bdfd3/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredentialOptions.cs#L213>
<https://github.com/dotnet/SqlClient/issues/1473>

**Comment by roji** [comment]
Transferred to SqlClient as this doesn't seem to be EF-related.

**Comment by ErikEJ** [comment]
@davidhendrickmb Maybe create a custom authentication provider? https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlauthenticationprovider?view=sqlclient-dotnet-standard-5.1

**Comment by davidhendrickmb** [comment]
@ErikEJ thanks for your reply. Is there a way to implement this with entity framework core?

**Comment by ErikEJ** [comment]
Given that it is initialized with a static method I see nothing preventing that. What have you tried?

**Comment by davidhendrickmb** [comment]
I am currently trying to add a DbConnectionInterceptor with AzureServiceTokenProvider, however I'm not sure how I can instuct this to skip the managed identity process.

**Comment by ErikEJ** [comment]
Did you read the sample code in the link above?

**Comment by davidhendrickmb** [comment]
I did but to be honest I'm not really sure how that integrates.
What I have done now is to add the interceptor like the below and added it as part of optionsBuilder.AddInterceptors(new AadAuthenticationInterceptor());

It doesn't appear to have any caching so I have implemented a basic memory cache but might also include a file system cache also to persist application restarts. 


`public class AadAuthenticationInterceptor : DbConnectionInterceptor
    {
        public override InterceptionResult ConnectionOpening(
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result)
            => throw new InvalidOperationException("Open connections asynchronously when using AAD authentication.");

        public override async ValueTask<InterceptionResult> ConnectionOpeningAsync(
            DbConnection connection,
            ConnectionEventData eventData,
            InterceptionResult result,
            CancellationToken cancellationToken = default)
        {
            var sqlConnection = (SqlConnection)connection;
            
            var tokenCredential = new DefaultAzureCredential(new DefaultAzureCredentialOptions
            {
                ExcludeEnvironmentCredential = true,
                ExcludeInteractiveBrowserCredential = true,
                ExcludeAzurePowerShellCredential = true,
                ExcludeSharedTokenCacheCredential = true,
                ExcludeVisualStudioCodeCredential = true,
                ExcludeManagedIdentityCredential = true,
                ExcludeAzureCliCredential = true,
            });

            AccessToken tkn = await tokenCredential.GetTokenAsync(new TokenRequestContext(new[] { "https://database.windows.net/" }));

            sqlConnection.AccessToken = tkn.Token;
            return result;
        }
    }`

**Comment by ErikEJ** [comment]
I think you just implement the class and register it with the static method early in the app. There is no interceptor mentioned in the sample.

**Comment by Kaur-Parminder** [comment]
@davidhendrickmb the related issue was provided with the work around to open a connection before opening simultaneous connection. There is enhancement opportunity for sqlclient to improve token caching. For EFCore scenario, Can you provide repro project and we can investigate further?

**Comment by phatcher** [comment]
I have a similar problem, and adapted the ActiveDirectoryAuthenticationProvider code to take custom options...

```
/// <summary>
/// A <see cref="SqlAuthenticationProvider" /> for <see cref="SqlAuthenticationMethod.ActiveDirectoryDefault"/> that takes custom <see cref="DefaultAzureCredentialOptions" />
/// </summary>
public class ActiveDirectoryDefaultAuthenticationProvider : SqlAuthenticationProvider
{
    private readonly DefaultAzureCredentialOptions options;
    const string DefaultScopeSuffix = "/.default";

    public ActiveDirectoryDefaultAuthenticationProvider(DefaultAzureCredentialOptions options)
    {
        this.options = options;
    }

    public override async Task<SqlAuthenticationToken> AcquireTokenAsync(SqlAuthenticationParameters parameters)
    {
        var cts = new CancellationTokenSource();

        // Use Connection timeout value to cancel token acquire request after certain period of time.
        cts.CancelAfter(parameters.ConnectionTimeout * 1000); // Convert to milliseconds

        var scope = parameters.Resource.EndsWith(DefaultScopeSuffix, StringComparison.Ordinal) ? parameters.Resource : parameters.Resource + DefaultScopeSuffix;
        var scopes = new string[] { scope };
        TokenRequestContext tokenRequestContext = new(scopes);

        var seperatorIndex = parameters.Authority.LastIndexOf('/');
        var authority = parameters.Authority.Remove(seperatorIndex + 1);
        var audience = parameters.Authority.Substring(seperatorIndex + 1);
        var clientId = string.IsNullOrWhiteSpace(parameters.UserId) ? null : parameters.UserId;

        DefaultAzureCredentialOptions defaultAzureCredentialOptions = new()
        {
            AuthorityHost = new Uri(authority),
            SharedTokenCacheTenantId = audience,
            VisualStudioCodeTenantId = audience,
            VisualStudioTenantId = audience,

            ExcludeEnvironmentCredential = options.ExcludeEnvironmentCredential,
            // Kubernetes
            ExcludeWorkloadIdentityCredential = options.ExcludeWorkloadIdentityCredential,
            ExcludeManagedIdentityCredential = options.ExcludeManagedIdentityCredential,

            ExcludeAzureDeveloperCliCredential = options.ExcludeAzureDeveloperCliCredential,
            ExcludeSharedTokenCacheCredential = options.ExcludeSharedTokenCacheCredential,
            ExcludeVisualStudioCredential = options.ExcludeVisualStudioCredential,
            ExcludeVisualStudioCodeCredential = options.ExcludeVisualStudioCodeCredential,

            ExcludeAzureCliCredential = options.ExcludeAzureCliCredential,
            ExcludeAzurePowerShellCredential = options.ExcludeAzurePowerShellCredential,
            ExcludeInteractiveBrowserCredential = true // Force disabled, even though it's disabled by default to respect driver specifications.
        };

        // Optionally set clientId when available
        if (clientId is not null)
        {
            defaultAzureCredentialOptions.ManagedIdentityClientId = clientId;
            defaultAzureCredentialOptions.SharedTokenCacheUsername = clientId;
        }

        var accessToken = await new DefaultAzureCredential(defaultAzureCredentialOptions).GetTokenAsync(tokenRequestContext, cts.Token).ConfigureAwait(false);

        return new SqlAuthenticationToken(accessToken.Token, accessToken.ExpiresOn);
    }

    public override bool IsSupported(SqlAuthenticationMethod authenticationMethod)
    {
        return authenticationMethod == SqlAuthenticationMethod.ActiveDirectoryDefault;
    }
}
```
Usage is as per the sample code
```
var options = new DefaultAzureCredentialOptions
{
    ExcludeEnvironmentCredential = true,
    // Kubernetes
    ExcludeWorkloadIdentityCredential = true,
    ExcludeManagedIdentityCredential = true,

    ExcludeAzureDeveloperCliCredential = true,
    ExcludeSharedTokenCacheCredential = true,
    ExcludeVisualStudioCredential = false,
    ExcludeVisualStudioCodeCredential = true,

    ExcludeAzureCliCredential = true,
    ExcludeAzurePowerShellCredential = true,
    ExcludeInteractiveBrowserCredential = true
};

SqlAuthenticationProvider.SetProvider(SqlAuthenticationMethod.ActiveDirectoryDefault, new ActiveDirectoryDefaultAuthenticationProvider(options));
```

Thought this might be useful to the community or could be adopted into the code base with some refactoring for commonality since this is the entire behaviour for Active Directory Default.

**Comment by markgould** [comment]
Agree with @phatcher being able to customize the DefaultAzureCredentialOptions without having to resort to implementing a custom SqlAuthenticationProvider would be nice

**Comment by David-Engel** [comment]
There was an access token callback feature added in 5.2 preview 3 that makes this much easier. (Not quite as easy as a connection string adjustment, but a-few-lines-of-code easy.)

```
using Azure.Core;
using Azure.Identity;
using Microsoft.Data.SqlClient;
...

            string s_defaultScopeSuffix = "/.default";
            DefaultAzureCredentialOptions options = new()
            {
                //set your options here
                ExcludeAzureCliCredential = true,
                ExcludeVisualStudioCredential = true
            };
            var cred = new DefaultAzureCredential(options);
            Func<SqlAuthenticationParameters, CancellationToken, Task<SqlAuthenticationToken>> myTokenCallback = async (ctx, cancellationToken) =>
            {
                string scope = ctx.Resource.EndsWith(s_defaultScopeSuffix) ? ctx.Resource : ctx.Resource + s_defaultScopeSuffix;
                AccessToken token = await cred.GetTokenAsync(new TokenRequestContext(new[] { scope }), cancellationToken);
                return new SqlAuthenticationToken(token.Token, token.ExpiresOn);
            };

            using (SqlConnection sqlConnection = new SqlConnection("Server=name.database.windows.net;Database=db;"))
            {
                sqlConnection.AccessTokenCallback = myTokenCallback;
                sqlConnection.Open();
                Console.WriteLine("Connected successfully!");
            }
```

**Comment by markgould** [comment]
This is excellent! Look forward to trying this out.
