### ISSUE TITLE
Support for "Arrays of Parameter Values" in SqlCommand

### ISSUE THREAD

**Issue by clovisribeiro** [dotnet/SqlClient#2109]
Unless I was not able to find in the documentation, it seems to me that Microsoft.Data.SqlClient (and the legacy libraries too) do not support the use of "Arrays of Parameter Values" in SqlCommand.

Just to clarify, when using the ODBC API in C++, we can easily use arrays of parameters to be able to make a single SQLExecute() and pass multiple statements (like multiples INSERT INTO, UPDATE, etc...). 

More details can be found at:

https://learn.microsoft.com/en-us/sql/odbc/reference/develop-app/arrays-of-parameter-values?view=sql-server-ver16

Are you planning to support this kind of feature in the c# driver? We use that a lot in our C++ components and the performance gains are impressive.

If you do support it already, appreciate guidance on where to find the code/examples.

Best Regards,

Clovis

**Comment by ErikEJ** [comment]
SqlBatch ?

**Comment by clovisribeiro** [comment]
What the ODBC support is not exactly a batch of statements but a single statements with an array containing multiple sets of parameters, so you can send to the server a single command to be executed multiple times using different sets of parameters.

In short, this let us send to the server a single INSERT INTO command with "multiple" rows to be inserted.

I have never used SqlBatch but I am not sure it will have the same performance gain as what we can do with the ODBC API

**Comment by roji** [comment]
@clovisribeiro for this kind of usage, isn't SqlBulkCopy a better fit anyway?

**Comment by clovisribeiro** [comment]
I understand SqlBulkCopy requires a destination table and in our use case the account in use can only make stored procedure calls (the USP code performs extra checks before the actual insert or update).

We could use Table-Valued parameters and pass the set of records as a DataTable to the USPs but that would require changes in the underlying database layer/procedures.

I am not sure either what would be the performance gains either as we have not tested that approach.

The functionality provided by the ODBC driver is great as it requires no changes in the database layer and reduces the number of server calls.

If SQL Server provides a way for the ODBC driver to do that, maybe the c# code could so the same.

Just a thought. Thank you for your time replying.

________________________________

**Comment by Kaur-Parminder** [comment]
@clovisribeiro You can give try to Batch operations using Data Adapters. https://learn.microsoft.com/en-us/sql/connect/ado-net/batch-operations-using-dataadapters?view=sql-server-ver16

**Comment by clovisribeiro** [comment]
@Kaur-Parminder , it feels to me that under the hood 'UpdateBatchSize' makes the DataAdapter perform exactly the same as the ODBC feature I commented about. It is a bit different than what I would expect, but it feels the performance gains will be the same. 
Thanks for your guidance/suggestion, this looks better than modifying procedures to use DataTables as parameters. I will compare later to see which solution performs better.

**Comment by roji** [comment]
@clovisribeiro it's worth mentioning that SqlDataAdapter with UpdateBatchSize works very differently from any sort of TVP/array-based solution. The former simply batches multiple SQL statements in a single database roundtrip, whereas the latter can work with a single SQL statement. That can have big implications both on performance and transactional consistency (since multiple SQL statements don't necessarily guarantee consistency, based on the transaction isolation level).

So while the batching performance may be enough for your needs and obviates looking into array-based solutions, the two are quite different and an array-based solution will still generally be more efficient.
