### ISSUE TITLE
Pooling & SqlConnection Lifetime Recommendations

### ISSUE THREAD

**Issue by haledv** [dotnet/SqlClient#2114]
**About**
We have a classic CRM, runs on Windows, Server/Client Arch, .net Framework 4.8 and uses Sql Server. The DB layer is using Ado.net with a custom DB Framework => think of it as minimal EF  that was written 20 Years ago. It's nothing special, but it has a custom THREAD based pooling. 

This pooling works so that the the first Db action within a thread creates a SqlConnection object, opens it, executes the query etc, and then all next db actions will try to find an SqlConnection on the thread they are running and reuse the SqlConnection object. The state of the SqlConnection is Open and they don't need to open it again. After 5 minutes if a SqlConnection isn't used, it "expires", it's closed and disposed. This should help reduce the overhead of creating & opening the SqlConnection object. While running, our app can sometimes produce hunderts of "micro" queries due to custom lazy loading in a few seconds.  In the Microsoft documentation, the recommendation is that the SqlConnection should be closed&disposed ASAP, and that Ado.Net has it's own pooling already.  **I am wondering, if this approach of using and SqlConnection object and having it open for multiple queries is Valid or does it have some pitfalls with it?**  I could not find ressoures in the documentation which talk about this approach.  

I did notice that on large datasets and lof of nested application code (for loops + lazy loading), the Memory Pressure gets high and the GC runs wild trying to collect those Tdsparserobjects (I don't have current access to one of our memory dumps, but I will update this when I have).

I am gonna write a few benchmarks testing a few approahces, but I would be gratefull for any input if this is a valid approach (custom pooling on top of ado.net pooling), on which I should iterate and improve (thread based pooling doesn't really work with async :D) or should I ditch it and do it the "recommended" way.

Much Thanks!

**Comment by roji** [comment]
> In the Microsoft documentation, the recommendation is that the SqlConnection should be closed&disposed ASAP, and that Ado.Net has it's own pooling already.

I'm not a SqlClient maintainer (or even expert), but this is the important point: instantiating a SqlConnection and disposing it are very light, in-memory operations, given that the driver pools connections internally. In other words, disposing simply places the physical connection back into the pool, and it's taken out the next time you call Open() on a connection. I usually see people doing this because they misunderstand how pooling actually works.

So in the general case, implementing your own per-thread SqlConnection doesn't improve performance in any way, and both increases complexity and risk of getting something wrong. Of course, it's always possible your application has some very special characteristics or perf requirements that justify this, but that's very rarely the case.

> I did notice that on large datasets and lof of nested application code (for loops + lazy loading), the Memory Pressure gets high and the GC runs wild trying to collect those Tdsparserobjects (I don't have current access to one of our memory dumps, but I will update this when I have).

That's unlikely to be related to the connection management being discussed here. I'd open a separate issue with a minimal BenchmarkDotNet benchmark showing the high memory pressure etc.

**Comment by haledv** [comment]
Thank you for your input., much appreciate. The original devs are long gone and there is no documentation, so I am basically trying to figure out what kind of Problem this approach tries to solve.  I also noticed that every Db Operation is wrapped in a Transaction with ReadUncommitted level, which seems a bit odd at first (at least for me).

Some initial benchmark on a single query (with single & multithreading) showed that the approach is almost identical to the recommended way., in terms of speed & allocation. I suspect when I setup a benchmark with multiple levels of nested db calls and mapping to business object, it could show some differences (which I am about to do).

> That's unlikely to be related to the connection management being discussed here. I'd open a separate issue with a minimal BenchmarkDotNet benchmark showing the high memory pressure etc.

My initial thoughts was that with the pooling the SqlConnection lives longer then it is supposed to do (by design), so it's holding on to memory that it shoulnd't and that has a chain effect on the everything else. I do need to investigate it a bit more but it seemed that GC was overwehlmed with the tdsparserobjects spawning in such a high rate. I will open an separate issue for that as soon as I get a bit more Info about what's happening and some benchmarks.

**Comment by JRahnama** [comment]
@haledv is the observation on `System.Data.SqlClient` or `Microsoft.Dzta.SqlClient`?

**Comment by haledv** [comment]
Microsoft.Data.SqlClient 2.3.1. 

Definetly a bit behind with the latest Package Version. I will try to setup a benchmark and reproduce the issue.
