### ISSUE TITLE
Minor code issue

### ISSUE THREAD

**Issue by andrew-kuzovov** [dotnet/SqlClient#2133]
https://github.com/dotnet/SqlClient/blob/3185ce235b1d01da51bddc98415a77983e54defb/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L2429

**Comment by JRahnama** [comment]
Empty statements are valid in C# and have some use-cases. This, however seemed oversighted, but had no effect on perf or caused any issue at compile time. For code-cleanup purposes I have addressed it in PR #2136 .

**Comment by JRahnama** [comment]
Closing the issue as PR #2136 is made to address the issue.
