### ISSUE TITLE
AssemblyLoadContext.Resolving handler may not be thread safe

### ISSUE THREAD

**Issue by bricelam** [dotnet/SqlClient#2134]
We've started seeing occasional failures in our tests with the following exception:

```
Microsoft.EntityFrameworkCore.Scaffolding.Internal.CSharpRuntimeModelCodeGeneratorTest.Sqlite [FAIL]
  System.TypeInitializationException : The type initializer for 'Microsoft.Data.Sqlite.SqliteConnection' threw an exception.
  ---- System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null'. An operation is not legal in the current state. (0x80131509)
  -------- System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
  Stack Trace:
    D:\a\_work\1\s\src\Microsoft.Data.Sqlite.Core\SqliteConnection.cs(95,0): at Microsoft.Data.Sqlite.SqliteConnection..ctor()
```

As far as we can tell, this is being caused by your `Microsoft.Data.SqlClient.SqlConfigurableRetryLogicLoader.Default_Resolving()` handler not being thread safe.

/cc @ajcvickers

**Comment by bricelam** [comment]
Not, we're still not 100% sure it's your implementation. We're also following up in https://github.com/dotnet/runtime/issues/90415

**Comment by JRahnama** [comment]
@bricelam is this M.D.SqlClient related issue or Sqlite?

**Comment by jkotas** [comment]
This issue can be closed.

The EFCore problem is a bug in xunit: https://github.com/dotnet/runtime/issues/90415#issuecomment-1688738260.
