### ISSUE TITLE
dotnet test fails if solution has sqlproj and data tools missing

### ISSUE THREAD

**Issue by mac2000** [dotnet/SqlClient#2138]
in case of solution has sqlproj, attempt to run `dotnet test` fails with error:

> error MSB4019: The imported project "/usr/local/share/dotnet/sdk/7.0.201/Microsoft/VisualStudio/v11.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/share/dotnet/sdk/7.0.201//Microsoft/VisualStudio/v11.0/SSDT/Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.

Note: this is because of lack of data tools being installed which may be a case especially in different ci like github actions

expectations are: either download and install wanted targets the same way as it is happening for dependencies or allow ignore projects with missing targets when running tests or do nothing :) 

just wanted to share because suddenly got an complain from one of engineers about broken builds and as a workaround for now, before running `dotnet test` we are executing `for file in */*.sqlproj; do dotnet sln remove "$file"; done`, may be will be helpful if someone struggling with same issue

---

Notes:

- not sure if that is a bug or feature request so other option was chosen
- cross posted from [here](https://github.com/dotnet/core/issues/8629), asked by @tarekgh

**Comment by JRahnama** [comment]
@mac2000 I am not sure if this is SqlClient related. Looks more like a visual studio issue. Is there any mention of Microsoft.Data.SqlClient or System.Data.SqlClient in the stack trace?

**Comment by mac2000** [comment]
To be fair I am not sure as well, just did as your teammates suggested in original [issue](https://github.com/dotnet/core/issues/8629) 🤷‍♂️

**Comment by JRahnama** [comment]
@sharwell is this something related to your team?

**Comment by dzsquared** [comment]
This sounds like it's an SSDT-style SQL project, so I'd guide you towards sharing this feedback with Visual Studio: https://developercommunity.visualstudio.com/home


If you're looking to lean into cross-platform support, we do have a preview of SDK-style SQL projects in the Microsoft.Build.Sql library - https://github.com/microsoft/DacFx/tree/main/src/Microsoft.Build.Sql

**Comment by JRahnama** [comment]
Closing the issue as external. Feel free to comment here or open a new issue.
