### ISSUE TITLE
The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading, Version=7.0.0.0' on .NET 7

### ISSUE THREAD

**Issue by MaddyDev** [dotnet/SqlClient#2154]
Hello, I am creating Azure Function with Sql Trigger binding from the project templates using VS 2022 targeting .NET 7. It is a simple sql trigger function app that targets .NET 7 on an isolated process on Azure functions v4 and it has a Microsoft.Data.SqlClient (using version 5.0.1) dependency. When running the project, we are seeing the below error message:

Failed to start SQL trigger listener for table: '', function ID: ''. Exception: System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception.
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'For detailed output, run func with --verbose flag.
at System.Configuration.ConfigurationManager.EnsureConfigurationSystem()
at System.Configuration.ConfigurationManager.PrepareConfigSystem()
at System.Configuration.ConfigurationManager.GetSection(String sectionName)
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager.FetchConfigurationSection[T](String name)
at Microsoft.Data.SqlClient.SqlAuthenticationProviderManager..cctor()
--- End of inner exception stack trace ---

The same app works as expected with the same library when targeting .NET 6. Appreciate your help on this. Thanks!

**Comment by Wraith2** [comment]
SqlClient is loaded and the failure is telling you that it can't load System.Threading, so is System.Threading present in the output directory?

**Comment by MaddyDev** [comment]
> SqlClient is loaded and the failure is telling you that it can't load System.Threading, so is System.Threading present in the output directory?

I don't see the System.Threading library in the output directory and even if I want to add it as a dependency, I don't see the version 7.0.0.0 it's looking for on nuget (https://www.nuget.org/packages/System.Threading/4.3.0)

**Comment by David-Engel** [comment]
@MaddyDev I don't see System.Threading even referenced from Microsoft.Data.SqlClient.SqlAuthenticationProviderManager. Can you provide a small repro project that we can troubleshoot with?

**Comment by vl4d4** [comment]
I can reproduce it as well. As mentioned above net6 works but net7 does not.

**Comment by shridevi30** [comment]
I do have the same issue with HttpTrigger with Sql input binding on .net 7 azure function. Function was working fine and is deployed to prod a month back. When I went back to check something on my local today, I started getting this run time error. 

System.Private.CoreLib: Exception while executing function: Functions.AAAA. Microsoft.Data.SqlClient: The type initializer for 'Microsoft.Data.SqlClient.SqlAuthenticationProviderManager' threw an exception. System.Configuration.ConfigurationManager: Could not load file or assembly 'System.Threading, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

I have tried to get latest System.Threading which is only version 4.3.0. Not sure why it is looking at version 7.
Thanks for any help.
Regards.

**Comment by davetheunissen** [comment]
Downgrading Microsoft.Azure.Functions.Worker.Extensions.Sql to v2.0.145 resolved this issue for me

**Comment by shridevi30** [comment]
> Downgrading Microsoft.Azure.Functions.Worker.Extensions.Sql to v2.0.145 resolved this issue for me

Yes. Downgrading as mentioned worked for me too. Thank you @davetheunissen

**Comment by cheenamalhotra** [comment]
@JRahnama is there any update on the issue you can provide?

**Comment by JRahnama** [comment]
@cheenamalhotra  we discussed the issue internally and I believe it is resolved.
Closing as completed. @MaddyDev feel free to comment here or open a new issue if you still experiencing the issue.
