### ISSUE TITLE
Execution Timeout Expired After Last Query Is Done

### ISSUE THREAD

**Issue by MEvanAW** [dotnet/SqlClient#2167]
Hi, we are maintaining a project with dependency to Microsoft.Data.SqlClient v1.1.4. On June 12, 2023, we got an "Execution Timeout Expired" exception on Production. I checked the logs and found that the last query of the request was already done before the exception happened. This is a first for me... This is odd in 2 ways:

1. Usually, a timeout happened when executing one of our queries instead of after all was done.
2. We used the default timeout of 30 seconds, but the timeout happened 19 seconds after the last query is done instead.

Relevant logs:
[Microsoft.EntityFrameworkCore 47b31e63-4eef-4eea-b330-a13d0003dd7d.log](https://github.com/dotnet/SqlClient/files/12698101/Microsoft.EntityFrameworkCore.47b31e63-4eef-4eea-b330-a13d0003dd7d.log)

Please offer insight on how we might prevent this in the future.
Thanks!

**Comment by JRahnama** [comment]
@MEvanAW is the issue reproduceable on a newer version of MDS? v1.1.4 is out of support.

**Comment by MEvanAW** [comment]
Hi @JRahnama, before I try that, how do I know what breaking changes are from v1.1.4 to target version? For example, if I want to upgrade to v3.1.3, I don't know if I should list breaking changes from v2.0.0 to v2.1.6 and v3.0.0 to v3.1.3 or how. Please enlighten me.

https://github.com/dotnet/SqlClient/blob/main/CHANGELOG.md

**Comment by David-Engel** [comment]
> how do I know what breaking changes are from v1.1.4 to target version? For example, if I want to upgrade to v3.1.3, I don't know if I should list breaking changes from v2.0.0 to v2.1.6 and v3.0.0 to v3.1.3 or how. Please enlighten me.

Breaking changes would only be made in a major version bump. So you can simply look at the release notes for each x.0.0 release between what you have and where you want to go. Within the release notes, a summary of all changes from the last a.x release to b.0 includes a summary of breaking changes. Here's that section in the 2.0 release notes, for example:

https://github.com/dotnet/SqlClient/blob/main/release-notes/2.0/2.0.0.md#breaking-changes-1
