### ISSUE TITLE
Version 5.0.1 has major memory retention problem but is not marked as deprecated

### ISSUE THREAD

**Issue by Timo-Weike** [dotnet/SqlClient#2177]
The version 5.0.1 has the memory retention problem discussed in https://github.com/dotnet/SqlClient/issues/1810, but dispite multiple comments suggesting that the version should be marked as deprecated or having a bug, the version is still up and unmarked on NuGet.

I just took some days to "rediscover" this problem and am grateful for it being already solved. However I think it would be very helpful for all users of the version. 

And as you can see on the nuget stats page for the package, version 5.0.1 was downloaded over 3 million times in the last 6 weeks
![image](https://github.com/dotnet/SqlClient/assets/25256020/00c0525a-369b-4bab-b79d-1fc0df3ebb63)

So version 5.0.1 is far from not being used, but IMHO should be with this kind of problem.

**Comment by ErikEJ** [comment]
A lot of downloads of this package come via EF Core 7 and the latest version of EF Core 7 was just Updated to use 5.11

**Comment by DavoudEshtehari** [comment]
Thank you for providing the feedbacks, we'll look into it and try to improve it on NuGet.org.

**Comment by Timo-Weike** [comment]
> A lot of downloads of this package come via EF Core 7 and the latest version of EF Core 7 was just Updated to use 5.11

As of now the version 5.0.1 was still downloaded over 3 million times in the last l weeks
![image](https://github.com/dotnet/SqlClient/assets/25256020/79839165-6920-4ed8-9416-4929609eefb4)

I think a deprecation flag would improve these numbers.

**Comment by David-Engel** [comment]
I marked it as deprecated with a recommendation to update to at least 5.0.2: https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.0.1
