### ISSUE TITLE
Deployment request for new preview nuget package: 5.2.0-preview4

### ISSUE THREAD

**Issue by Havunen** [dotnet/SqlClient#2179]
Hi,

Our application is having constantly slowness related to https://github.com/dotnet/SqlClient/issues/2120  https://github.com/dotnet/SqlClient/pull/2121 

The estimated release date was supposed to be in the last month https://github.com/dotnet/SqlClient/issues/2120#issuecomment-1679946792 https://github.com/dotnet/SqlClient/issues/2120#issuecomment-1703243010 

Could we have a new release or preview release please!

**Comment by Havunen** [comment]
Is there any particular reason why the current main branch cannot be released as a new preview Nuget package? If its waiting for some fixes can't those be included in the next preview version?

**Comment by Havunen** [comment]
Or if there are some major issues with the current main branch, could those be opened as tickets to Github so the community could possibly help resolving them?

**Comment by David-Engel** [comment]
The current holdup is the team is working on internal escalations and a round of hotfix releases that are pushing out work on the next preview release. Looking forward, the next preview release should land sometime in November.

**Comment by Havunen** [comment]
Are there any blockers why current main branch cant be released as a new preview as is?

**Comment by Wraith2** [comment]
Time. The blocker is always dev time. You just have to get used to things moving slowly here.
In general there is no reason that you couldn't compile and use your own version from main until a release happens. Nothing inherently unsafe has been added as far as I'm aware.

**Comment by Havunen** [comment]
If I compile the nuget myself how can I override the dependency of existing third party libraries like EF?

**Comment by Havunen** [comment]
Would it be acceptable to have CI publish nightly releases to Nuget.org? Then if it would be automated every night if there are new commits it could publish a new package automatically and developers does not need to do it manually?

**Comment by ErikEJ** [comment]
>> If I compile the nuget myself how can I override the dependency of existing third party libraries like EF?

Not an issue, EF Core uses your explict reference

**Comment by ErikEJ** [comment]
>> Would it be acceptable to have CI publish nightly releases to Nuget.org? Then if it would be automated every night if there are new commits it could publish a new package automatically and developers does not need to do it manually?

Publishing daily builds to NuGet is not how you usually do this, you would set up an alternate NuGet server, and this is not something the team has done yet. You can however use the output package from the latest CI build: https://sqlclientdrivers.visualstudio.com/public/_build?definitionId=1139&_a=summary

**Comment by Havunen** [comment]
I downloaded the Artifact from the CI main branch and installed it as a local nuget package. However now C# compiler is throwing error about: 
`
Error	CS0012	The type 'SqlConnection' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Data.SqlClient, Version=5.0.0.0, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5'.
`

![image](https://github.com/dotnet/SqlClient/assets/2021355/2f20bf9b-0ec3-43e7-9ddd-6d359dbb8f9b)

Comparing the nuget packages from CI pipeline to the published nuget packages in nuget org it the CI artifact does not have public key token? Why is that?

![image](https://github.com/dotnet/SqlClient/assets/2021355/480e319f-92c5-4861-a0aa-7730aa214096)

Browsing through the package tree in Visual Studio shows that the package does get resolved but the code does not compile due to that error from `AspNetCore.HealthChecks.SqlServer` -Nuget startup configs

![image](https://github.com/dotnet/SqlClient/assets/2021355/1e76ac79-52a0-4d07-b7ae-342088e021b4)

I dont think there is any relevant change in SqlConnection between 5.3preview and latest main branch that would cause this so it has to do something with the published CI artifact

**Comment by Havunen** [comment]
That package is however out of my control. Also the way it depends on Microsoft.Data.SqlClient seems very standard to me https://github.com/Xabaril/AspNetCore.Diagnostics.HealthChecks/blob/master/src/HealthChecks.SqlServer/HealthChecks.SqlServer.csproj#L11

**Comment by roji** [comment]
@Havunen you can take a direct reference to a newer version of Microsoft.Data.SqlClient in your application's csproj. That will use the newer package for your entire application, overriding the older transitive dependency via AspNetCore.Diagnostics.HealthChecks.

**Comment by Havunen** [comment]
@roji That is exactly what I did.

I downloaded the CI artifact.
I created a nuget.config file and added a local directory as a feed to the nuget.config.
I placed all the CI artifacts to the local nuget folder.
I changed entry level project package reference to `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.20.0-pull.29401" />`
Then I try to compile the project and it fails to the error above.

I created a full repro here: https://github.com/Havunen/cant_use_microsoft_data_sqlclient_artifact/tree/main

**Comment by Santas** [comment]
+1 on separate nightly build or releasing the package more often.

**Comment by Havunen** [comment]
@David-Engel Is it possible to have a new preview version of the SQL Client published to Nuget please?  Because of this issue https://github.com/dotnet/SqlClient/issues/2179#issuecomment-1765992210 it is not possible to build the Nuget manually. Or if it is not possible having a hotfix to fix the GC pressure works as well 

This is the commit where the performance problem was fixed. 
https://github.com/dotnet/SqlClient/pull/2121/commits/83231752f73524f40d1b4e14d54f542e8a9b6125 
and it was a bug fix on top of this: https://github.com/dotnet/SqlClient/pull/1866

**Comment by ErikEJ** [comment]
@Havunen Can you not download the artifact from the CI build?

**Comment by Havunen** [comment]
@ErikEJ  I can download it, but I cannot use it. https://github.com/dotnet/SqlClient/issues/2179#issuecomment-1773741660 

full repro here: https://github.com/Havunen/cant_use_microsoft_data_sqlclient_artifact/tree/main  just git clone and open it in visual studio

**Comment by ErikEJ** [comment]
@Havunen preview 4 is out now

**Comment by ErikEJ** [comment]
@JRahnama Could this be closed?

**Comment by Havunen** [comment]
Yes, I think this issue can be closed. If the GC issue still occurs I can open a new ticket. Thanks.
