### ISSUE TITLE
Document process and tools for code coverage

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#218]
### Is your feature request related to a problem? Please describe.
In order to ensure code quality code coverage is requested for pull requests to make sure there is evidence of testing. The tools for generating and viewing this information are currently undocumented.

### Describe the solution you'd like
The workflow and suggestions for tooling (built in code analysis in visual studio is an enterprise only feature, community contributors may not have those versions) for generation and viewing of coverage data should be described so users can do as much work as possible to get high quality contributions without needing to create their own workflow.

### Describe alternatives you've considered
coverlet is already used as a dependency but the steps for generating code coverage are not documented. Resharper and some VisualStudio versions may also be able to generate coverage data.

### Additional context
Coverage in visual studio is blocked by tests not running in the ide.

**Comment by MarcoRossignoli** [comment]
@ViktorHofer will SqlClient repo follow the same process of corefx/coreclr?

**Comment by cheenamalhotra** [comment]
Ack: It is in our backlog, to be done sometime soon.

**Comment by ViktorHofer** [comment]
Honestly I don't know. We haven't integrated code coverage into arcade yet.
