### ISSUE TITLE
Package dependency Azure.Identity with high vulnerability

### ISSUE THREAD

**Issue by pampua84** [dotnet/SqlClient#2195]
### Describe the bug
Hi,
as per the description in the object, when the package is installed, it brings as a dependency version 1.7.0 of Azure.Identity which has a strong vulnerability up to version 1.10.2 , as also reported in the link:

[https://github.com/advisories/GHSA-5mfx-4wcx-rv27](url)

and also on nuget.org:

[https://www.nuget.org/packages/Azure.Identity/1.7.0](url)

![image](https://github.com/dotnet/SqlClient/assets/17255890/00188217-ae43-4b38-ab76-9049ee68239c)

If you update the Azure.Identity library to the latest version, are there any breaking changes?

**Comment by ErikEJ** [comment]
@pampua84 What have you tried? In addition, this will be fixed in 5.2 preview 4

**Comment by pampua84** [comment]
Hi @ErikEJ,
 I was actually running a vulnerability test for packages installed on a project via the command:

> dotnet list package --vulnerable --include-transitive

I see that Microsoft.Data.SqlClient 5.1.1 supports any version later than >= 1.7.0, of Azure.Identity, so updating it shouldn't cause any problems. Right?

**Comment by ErikEJ** [comment]
Correct

**Comment by JRahnama** [comment]
Closing as a duplicate of #2181.
