### ISSUE TITLE
Microsoft.Data.SqlClient Transitive Packages

### ISSUE THREAD

**Issue by TRCarbone** [dotnet/SqlClient#2201]
I have a .NET Framework 4.8 app and I just installed the NuGet package for Microsoft.Data.SqlClient 5.1.2.

It added 38 transitive packages. I was hoping for just a few additional files, but that's a lot of additional DLLs to add to my distribution.

Am I doing something wrong?

**Comment by SimonCropp** [comment]
partially related to https://github.com/dotnet/SqlClient/issues/1108

**Comment by TRCarbone** [comment]
> partially related to #1108

I read through that, and in my case I am connecting to an Azure database using MFA. I'm OK with needing the Azure DLLs.

What I'm confused about is all of the "System." Dlls. For example, System.Memory. If I remove the System.Memory.dll file from the output directory the program fails to load with an error that it can't find the file of that version.

Forgive me if I just don't understand enough about this, but wouldn't that DLL be part of the framework? Is it part of the framework but Microsoft.Data.SqlClient needs a different version of the DLL?

Do I just go ahead and distribute all of these System DLL files with my application and put them in the same folder as my EXE on the installation target folder?

**Comment by SimonCropp** [comment]
System.Memory.dll is shipped in a nuget. it has never been shipped as part of net4x

> Do I just go ahead and distribute all of these System DLL files with my application and put them in the same folder as my EXE on the installation target folder?

yes

**Comment by DavoudEshtehari** [comment]
Microsoft.Data.SqlClient is an individual NuGet package, unlike System.Data.SqlClient.

**Comment by JRahnama** [comment]
@TRCarbone this is by design. There is nothing could be done.
