### ISSUE TITLE
Regression: Enabled Multiple Active Results Set throws exception when connection string is retreived from GetDbConnection().ConnectionString and used in SqlConnection.

### ISSUE THREAD

**Issue by LightBender** [dotnet/SqlClient#2208]
### Describe the bug
When attempting to connect to create a SqlConnection using the connection string stored in the DbContext (derived from the SqlConnectionStringBuilder) the following exception occurs. Note that the exception does _not_ occur when attempting to create a DbContext.

```
Exception message:
Stack trace:
System.ArgumentException
  HResult=0x80070057
  Message=Keyword not supported: 'multiple active result sets'.
  Source=System.Data
  StackTrace:
   at System.Data.Common.DbConnectionOptions.ParseInternal(Hashtable parsetable, String connectionString, Boolean buildChain, Hashtable synonyms, Boolean firstKey)
   at System.Data.Common.DbConnectionOptions..ctor(String connectionString, Hashtable synonyms, Boolean useOdbcRules)
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString, SqlCredential credential)
```

### To reproduce

```c#
public static void AddTestDatabase(this IServiceCollection services) {
	var csb = new SqlConnectionStringBuilder(connection) {
		DataSource = "<server>",
		InitialCatalog = "<database>",
		UserID = "<user>",
		Password = "<password>",
		Authentication = SqlAuthenticationMethod.SqlPassword,
		Encrypt = SqlConnectionEncryptOption.Mandatory,
		TrustServerCertificate = true,
		ConnectRetryCount = 48,
		ConnectRetryInterval = 5,
		TypeSystemVersion = "Latest",
		MultipleActiveResultSets = true,
	};

	var optionsBuilder = new DbContextOptionsBuilder<TestDb>().UseSqlServer(csb.ToString(),
		sqlServerOptionsAction: sqlOptions =>
		{
			sqlOptions.EnableRetryOnFailure(
				maxRetryCount: 6,
				maxRetryDelay: TimeSpan.FromSeconds(15),
				errorNumbersToAdd: new List<int>());
		}).EnableSensitiveDataLogging();
	services.AddSingleton(optionsBuilder.Options);
	services.AddTransient<TestDb>();
	var sp = services.BuildServiceProvider();
	var db = sp.GetRequiredService<TestDb>();
	var cs = db.Database.GetDbConnection().ConnectionString; 
	using var conn = new SqlConnection(cs); // Error here
}

```

### Expected behavior
Using the DbContext.Database.GetDbConnection().ConnectionString connection string should work in SqlConnection without throwing as it worked in prior versions. (Regression)

### Further technical details
Microsoft.Data.SqlClient version: 5.1.2
.NET target: Framework 4.8.1
SQL Server version: SQL Server 2022
Operating system: Ubuntu 20.04

**Additional context**
Is it possible that this is due to the fact that the upper-cased version of "multiple active result sets" exists in DbConnectionStringCommon.cs but not a lower-cased version and the ignore string case equality was removed at some point?

**Comment by ErikEJ** [comment]
Connedtion strings between System.Data.SqlCliient and Microsoft.Data.SqlClient do not roundtrip. Update your code to use Microsoft.Data.SqlClient everywhere.

**Comment by LightBender** [comment]
> Connedtion strings between System.Data.SqlCliient and Microsoft.Data.SqlClient do not roundtrip. Update your code to use Microsoft.Data.SqlClient everywhere.

Thank you for the pointer. That was very non-obvious. There where no references to the System.Data.SqlClient package, but there was a rogue implicit reference to the SqlClient in System.Data.dll via `using System.Data.SqlClient` that is loaded when you need to use DataTable, et al.

**Comment by ErikEJ** [comment]
https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md
