### ISSUE TITLE
Segmentation fault error occurs while running EF core migration bundle in docker desktop on MacOS after migrating from ef core 6 to ef core 8

### ISSUE THREAD

**Issue by nikjuice** [dotnet/SqlClient#2220]
Hi,

I'm currently in the process of updating my project from .NET 6 to .NET 8, which involves migrating from EF Core 6 to EF Core 8. The project heavily relies on Docker containers.

I've provided the Dockerfile below, which is responsible for building the database:

`FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY  //Here I copy project files

RUN dotnet tool install dotnet-ef --tool-path "./bin" --version 8.0.0
RUN ./bin/dotnet-ef migrations bundle --self-contained -r linux-x64 -o ./bin/efbundle

FROM mcr.microsoft.com/mssql/server:2022-CU8-ubuntu-20.04
ENV MSSQL_SA_PASSWORD=PASSWORD
ENV DB_NAME=DBNAME
ENV ACCEPT_EULA Y
ENV DOTNET_BUNDLE_EXTRACT_BASE_DIR=/var/tmp/bundle-extract
EXPOSE 1433

COPY --from=build PATH_TO_THE_PROJECT /var/tmp/

USER mssql
RUN ( /opt/mssql/bin/sqlservr & ) | grep -q "Recovery is complete" \
    && ./var/tmp/efbundle --connection "Data Source=.;Initial Catalog=$DB_NAME;User Id=sa;Password=$MSSQL_SA_PASSWORD;Encrypt=False;" \
    && pkill sqlservr
`
The project references are the following:

![image](https://github.com/dotnet/efcore/assets/7226351/1c862f54-dcaf-4ad7-99b9-c4a09d5915ee)

first after I changed SDK and EF core version, first I get the following error:

_A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
7.818  ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback._

To resolve this, I modified the connection string to have Encrypt=false (the same result was observed with TrustServerSertificate=true). However, this led to a new error: "Segmentation fault"

![image](https://github.com/dotnet/efcore/assets/7226351/dde5eede-2347-4195-8dad-7f1ae6534a9a)

when I tried to disable rosetta, I got a bit different but similar error:
![image](https://github.com/dotnet/efcore/assets/7226351/525d0d46-499e-4564-a52a-7d4cd5203072)

I asked collegue with windows machine to test this and it works there. 

My setup is: MacOS sonoma 14.1 on m2 pro chip. Docker desktop 4.25.1 running with Rosetta emulation enabled. 

Any insights or suggestions on resolving this issue would be greatly appreciated.

Thank you!

**Comment by nikjuice** [comment]
Thanks, Arthur. Yeah, I saw that breaking change and that is why I have added Encrypt=false.

**Comment by nikjuice** [comment]
More details when I added --verbose to the bundle:

![image](https://github.com/dotnet/SqlClient/assets/7226351/0c8d706a-5fb2-43a6-a0d3-fd3fe2fbc9fb)

**Comment by JRahnama** [comment]
@nikjuice so, is it confirmed that this is not SqlClient related issue?

**Comment by nikjuice** [comment]
@JRahnama  I don't think it is confirmed. With my knowledge and result that I have it is hard to say is it SQLClient related or not. I suspect that it is something specific in core .net related to Linux implementation that is used by SQLClient.

**Comment by ajorkowski** [comment]
I am getting a similar issue, but in our case we are running a build server on Ubuntu (via Azure Devops), using Standard_F2s_v2 Azure virtual machines. This started to happen after we updated EF core to .net 8.

Here is how we generate the bundle:
```
dotnet tool install --global dotnet-ef
dotnet ef migrations bundle -p "..." --configuration Release -r linux-x64 -o $(Build.ArtifactStagingDirectory)/Migrations
```

And then we run it during release (on the same build environment). Note that we have always used the 'Encrypt=True' option in the connection string here:
```
./Migrations -- --connection "Server=...,1433;Initial Catalog=...;Encrypt=True;Connection Timeout=30;"
```

Here is the error we are seeing
```
2023-11-29T14:13:00.0872552Z ##[error]Bash exited with code '139'.
2023-11-29T14:13:00.0881833Z ##[error]Bash wrote one or more lines to the standard error stream.
2023-11-29T14:13:00.0888664Z ##[error]/agent/_work/_temp/cd21926e-7954-4a21-be9c-c2458442782e.sh: line 10:  4200 Segmentation fault
```

I tried it with the --verbose flag, but there are no additional logs - it seems to crash right away?

**Comment by henrikwidlund** [comment]
We're also seeing this when running our application inside of Docker on a ARM Mac with Rosetta. Running the application outside of Docker works. Tried the same as @ajorkowski. I've got `TrustServerCertificate=True`. Also tried using the latest 6.0 packages of EF Core, but that didn't make a difference.

**Comment by henrikwidlund** [comment]
This workaround worked for me: https://github.com/dotnet/runtime/issues/94909#issuecomment-1816543071

**Comment by ajorkowski** [comment]
I managed to fix my issue as well - I think it may have been the fact that I was using `snap` to install the dotnet SDK. When I used `apt` instead this resolved the segmentation fault.

**Comment by nikjuice** [comment]
Workaround mentioned by @henrikwidlund  also works for me.
