### ISSUE TITLE
Missing functionality in batch API

### ISSUE THREAD

**Issue by mgravell** [dotnet/SqlClient#2222]
Relates to https://github.com/dotnet/SqlClient/pull/1825

Testing local build (`main`) with Dapper shows a few problems, i.e. "it doesn't work"; severity: IMO critical, this should absolutely be fixed before next build; the batch API is not usable by non-provider scenarios without it

1. `SqlConnection` fails to `override` the `CanCreateBatch` and `CreateDbBatch()` members (net6+)
2. `SqlBatchCommand` *does* `override` the `CanCreateParameter` and `CreateParameter()` members (net8+), but: the library does not currently build for net8, so: this code is never actually compiled as far as I can see

Suggestions:

for `SqlConnection`:

``` csharp
#if NET6_0_OR_GREATER
        /// <inheritdoc/>
        public override bool CanCreateBatch => true;

        /// <inheritdoc/>
        protected override SqlBatch CreateDbBatch() => new SqlBatch(this);
#endif
```

(you may have local rules on docs, especially since we're doing type variance here)

---

in the csproj:

- add `net8.0` to `<TargetFrameworks>`

---

tests:

for net6+

``` csharp
using var cnn = new SqlConnection();
Assert.True(cnn.CanCreateBatch);
var batch = cnn.CreateBatch();
Assert.Is<SqlBatch>(batch);
Assert.Same(cnn, batch.Connection);
Assert.Null(batch.Transaction);
```

for net8+

``` csharp
var cmd = new SqlBatchCommand();
Assert.True(cnn.CanCreateParameter);
Assert.Is<SqlParameter>(cnn.CreateParameter());
```

**Comment by mgravell** [comment]
note that adding net8 triggers a few `[Obsolete]` warnings, CS0672; requires

```
#if NET8_0_OR_GREATER
        [Obsolete]
#endif
```

on

- `SqlException.GetObjectData`
- `SqlException.ctor(SerializationInfo, StreamingContext)`
- `OperationAbortedException.ctor(SerializationInfo, StreamingContext)`

I also get a build error from `Microsoft.Data.SqlClient.notsupported.cs` via `GetnAPI`; not sure what to do about that one, but: it needs fixing

**Comment by Wraith2** [comment]
I'll take a look.

**Comment by mgravell** [comment]
awesome; I'll go ahead and do what I can with my locally hacked version that targets net7 with the first half of the fixes; I can't test the net8 parameter fix, but... that's the small end of the wedge for this
