### ISSUE TITLE
Result of System.AppContext.GetData is not being cached

### ISSUE THREAD

**Issue by JulianRooze** [dotnet/SqlClient#2225]
In profiling our application under high load, we've found that calls to System.AppContext.GetData(string) make up ~3% of our total CPU time, making it a top 5 CPU consumer function overall for us. All these calls originate from this project.

The main argument it's being called with is `"Switch.Microsoft.Data.SqlClient.MakeReadAsyncBlocking"` which originates from this file:

https://github.com/dotnet/SqlClient/blob/main/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/LocalAppContextSwitches.cs

I've filed a runtime [issue](https://github.com/dotnet/runtime/issues/94894) to potentially make AppContext.GetData more performant for reads, but one commenter in that issue pointed out that it's likely unintentional that it's being called this often as there are bool fields to cache the return value but it's only being assigned to and not read in two cases. 

I think the performance here can be improved by using the same kind of pattern as in the other properties of that class;

```csharp
 public static bool LegacyRowVersionNullBehavior
        {
            get
            {
                if (s_legacyRowVersionNullBehavior is null)
                {
                    bool result;
                    result = AppContext.TryGetSwitch(LegacyRowVersionNullString, out result) && result;
                    s_legacyRowVersionNullBehavior = result;
                }
                return s_legacyRowVersionNullBehavior.Value;
            }
        }
``` 

### Expected behavior

The AppContext.GetData is only performed once and then cached.

**Comment by Wraith2** [comment]
Seems reasonable. I'll implement it.

**Comment by JulianRooze** [comment]
Thanks so much @Wraith2 ! 🙌
