### ISSUE TITLE
System.Configuration.ConfigurationManager Version

### ISSUE THREAD

**Issue by noxe** [dotnet/SqlClient#2232]
Hi,

the current Microsoft.Data.SqlClient depends on the System.Configuration.ConfigurationManager Version 6.0.1 - which forces us the System.Drawing.Common Version 6.0 - which is not wanted since this is Win-Only - https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/6.0/system-drawing-common-windows-only

![image](https://github.com/dotnet/SqlClient/assets/158478/7c9e92c3-dc67-4548-9cf5-09cf2c7191e0)

Is there any info on this? It would be at least helpful if there would be a newer release based on .net8 since System.Configuration.ConfigurationManager or the be more precise the System.Windows.Extensions does not depend on System.Drawing.Common anymore.

Any thoughts?

**Comment by Wraith2** [comment]
Can you try the latest preview version and see if the dependency is now updated, i think it should have been.

**Comment by JRahnama** [comment]
@noxe have you tried referencing System.Configuration.ConfigurationManager with a newer version in your csproj to see the outcome?

**Comment by noxe** [comment]
> Can you try the latest preview version and see if the dependency is now updated, i think it should have been.

Hi - Nuget says it still references the same?

![image](https://github.com/dotnet/SqlClient/assets/158478/93290fc2-b38b-4c29-b0c9-19b79a94781c)

**Comment by noxe** [comment]
> System.Configuration.ConfigurationManager

i do not see any difference when using System.Configuration.ConfigurationManager 8.0.0

**Comment by ErikEJ** [comment]
S.C.C 8.0.0 no longer depends on System.Security.Permissions and therefore fixes this issue

**Comment by ErikEJ** [comment]
@JRahnama @H-Yeo This is fixed in 5.2 preview 5

**Comment by H-Yeo** [comment]
Javad looks like he goes through and helps to clean up dangling tickets. Thanks for point it out. Hopefully everything will be released today. We had a hiccup with one of the internal pipelines which prevented our release y'day. Thanks!

**Comment by ErikEJ** [comment]
@H-Yeo The package is on NuGet...

**Comment by H-Yeo** [comment]
> @H-Yeo The package is on NuGet...

Thanks. Davoud pushed out the release, and I'll be wrapping up the last of the Release Activities.

**Comment by kf-gonzalez** [comment]
Addressed by #2303
