### ISSUE TITLE
EF Core 8:  Only the invariant culture is supported in globalization-invariant mode

### ISSUE THREAD

**Issue by ttosello** [dotnet/SqlClient#2239]
In .NET 8, using EntityFrameWorkCore, when I attempt to run the update-database command (with or without pending migration), the following error is thrown:

`System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-us is an invalid culture identifier.
   at System.Globalization.CultureInfo.GetCultureInfo(String name)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
   at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.<Exists>b__0(DateTime giveUp)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`

Removing the following from the Project file resolves the error:

`<InvariantGlobalization>true</InvariantGlobalization>`

**Comment by DavoudEshtehari** [comment]
@ttosello Can you provide a simple repro console app just with M.D.SqlClient?

**Comment by adeyinkaroyal** [comment]
![image](https://github.com/dotnet/SqlClient/assets/126711739/f41e610f-2d76-432f-b08a-5c479d9645fe)
Hi @ttosello, look for InvariantGlobalization property in your project setting and change it to false. I had the same issue and this solves it.

**Comment by eduardscript** [comment]
Having the same error. It worked @adeyinkaroyal, but I don't understand the error. It started at .NET 8.

**Comment by vonzshik** [comment]
@eduardscript it started at .NET 8 because that flag is now set by default in api templates (dotnet/aspnetcore#47066). Might be a good idea to raise this issue with aspnetcore folks.

**Comment by lediodamo** [comment]
@adeyinkaroyal I had the same problem when trying to Update-Database, with a project .net core 8 and your solution works.

**Comment by JohnReyes-Dev** [comment]
Just encase someone doesn't know how to change InvariantGlobalization . Make your you unload your project.

**Comment by Mohandsad** [comment]
Est ce que quelqu'un a une solution a ce problème:
 System.Globalization.CultureNotFoundException : 'Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
j'ai program.cs uniquement dans mon application. merci

**Comment by SDONER** [comment]
I am using .net 8 and Entity Framework Core 8.0.0 versions in my project. When I made a request from api, I got the error in the image and it was solved by making the setting false in sdk. But I'm trying to understand something, is this problem caused by collation mismatch when connecting to the data with EF?  Because the collation of the database I created in MSSQL DB is Turkish_CI_AS, I wanted to try changing it to a collation that supports en-us, but this was not a solution. I solved my problem but I don't understand the logic here.

Translated with DeepL.com (free version)
![ZwIP6sBl0X](https://github.com/dotnet/SqlClient/assets/47286325/8ac9f343-b76a-45ce-9d1d-fc2dbb75a5eb)

**Comment by David-Engel** [comment]
> But I'm trying to understand something, is this problem caused by collation mismatch when connecting to the data with EF? Because the collation of the database I created in MSSQL DB is Turkish_CI_AS, I wanted to try changing it to a collation that supports en-us, but this was not a solution. I solved my problem but I don't understand the logic here. Someone explain for me.

@SDONER 

The "problem" is that SqlClient simply doesn't support invariant globalization mode. There is a check in SqlClient that is supposed to throw a nice error, but that check was broken by changes in .NET (7 or 8?). The check has been fixed but not yet released.

The reason SqlClient doesn't support invariant globalization mode is that there are many places in the library where it is just assumed that the underlying globalization libraries are available (as they were for years) for various data operations. Going through the code and updating every one of those places and then testing the resulting changes is a lot of work. Failures in those areas are data-dependent and can produce unpredictable results.

**Comment by Gerard0000** [comment]
thanks adeyinkaroyal

**Comment by Michealdgreat** [comment]
> ![image](https://private-user-images.githubusercontent.com/126711739/285121914-f41e610f-2d76-432f-b08a-5c479d9645fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1MzczNTQsIm5iZiI6MTcwMzUzNzA1NCwicGF0aCI6Ii8xMjY3MTE3MzkvMjg1MTIxOTE0LWY0MWU2MTBmLTJkNzYtNDMyZi1iMDhhLTVjNDc5ZDk2NDVmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyNVQyMDQ0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMmY2NGQzNjE5ODgyYmYxNGVkYjg4ZGY0MDUzNDczNTEzMGZkN2NlZGZkYmJiMGFlZGU5ZDAxZjZkNWU2ZWEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F5ouaKAkn_7OvcMA3O5BN9jHycI1IifZUyC0ewLaDLo) Hi @ttosello, look for InvariantGlobalization property in your project setting and change it to false. I had the same issue and this solves it.

Thank you soooooo much. One love baba mi 💖

**Comment by muni00** [comment]
```
 <PropertyGroup>
   <TargetFramework>net8.0</TargetFramework>
   <Nullable>enable</Nullable>
   <ImplicitUsings>enable</ImplicitUsings>
   <InvariantGlobalization>false</InvariantGlobalization>
 </PropertyGroup>
```
InvariantGlobalization özelliğini false yaparak sorunu giderdim , teşekkür ederim.

**Comment by CWT-Sachin** [comment]
> In .NET 8, using EntityFrameWorkCore, when I attempt to run the update-database command (with or without pending migration), the following error is thrown:
> 
> `System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name') en-us is an invalid culture identifier. at System.Globalization.CultureInfo.GetCultureInfo(String name) at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides) at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.OpenDbConnection(Boolean errorsExpected) at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected) at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.<>c__DisplayClass18_0.b__0(DateTime giveUp) at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext _, TState s) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded) at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation, Func`2 verifySucceeded) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists(Boolean retryOnNotExists) at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerDatabaseCreator.Exists() at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.Exists() at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration) at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String connectionString, String contextType) at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabaseImpl(String targetMigration, String connectionString, String contextType) at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_0.<.ctor>b__0() at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)`
> 
> Removing the following from the Project file resolves the error:
> 
> `<InvariantGlobalization>true</InvariantGlobalization>`

Thank you Very much.. very helpful

**Comment by khojianvar** [comment]
Thank you guys

**Comment by imAneeshD** [comment]
@ttosello in which file I should edit that changes in .NET 8?

**Comment by maaxelsson** [comment]
@imAneeshD The .csproj file is in the project folder. If you are using visualstudio - the file is not visible by default, you can right click the project -> Open folder in File Explorer. 

![sql-csproj](https://github.com/dotnet/SqlClient/assets/70094860/df76ccdf-3534-43b9-94d7-7b16bd751945)

**Comment by imAneeshD** [comment]
> @imAneeshD The .csproj file is in the project folder. If you are using visualstudio - the file is not visible by default, you can right click the project -> Open folder in File Explorer.

Thank you

**Comment by saman-ar** [comment]
thanks @adeyinkaroyal.  it worked.

**Comment by ferflores28032002** [comment]
Estoy teniendo el mismo problema tengo un proyecto de arquitectura hexadecimal y ya coloque en los 4 capas el 	<InvariantGlobalization>false</InvariantGlobalization> pero me sigue dando el mismo error 
![image](https://github.com/dotnet/SqlClient/assets/110640664/a660f97d-3577-4cc3-a333-75a104b45ab5)
![image](https://github.com/dotnet/SqlClient/assets/110640664/2c62faa4-55d3-44a5-ab47-ba13c9cbf3b8)
que puedo hacer?

**Comment by DavoudEshtehari** [comment]
@ferflores28032002 Please be respectful to the open source community and use English to share your findings and be more valuable on this repository. Otherwise, your comments will be ignored by majority of the contributors.

**Comment by sfernandez131** [comment]
Disabling that flag works fine but what if I want it set to true? What's the proper solution for this?

**Comment by estysherman** [comment]
I deleted this line: `<InvariantGlobalization>false</InvariantGlobalization>`
from the Project file, So It will look like this: 
```
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
```
And I added the setting `TrustServerCertificate=true;` to the ConnectionString in `appsettings.json`
It will look like this: 
```
"ConnectionStrings": {
  "DefaultConnection": "Data Source='YourServerName';Initial Catalog='YourDataBaseName';TrustServerCertificate=true;Integrated Security=True;"
},
```

This is what solved the error.

**Comment by GiorgosBetsos** [comment]
> k was broken by changes in .NET (7 or 8?). The check has been fixed b

It solved my issue. I was getting the error after trying to do a batch delete.

**Comment by Souschili** [comment]
Спасибо чуваки мне помогло

**Comment by sfernandez131** [comment]
> Спасибо чуваки мне помогло

Translation: Thanks guys it helped me

**Comment by atrakic** [comment]
If you are build in docker, take a look into this: https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md

**Comment by cnikula** [comment]
Thank you guys

**Comment by oAleshao** [comment]
Thanks guys!

**Comment by rhenry26** [comment]
I'm attempting to run Scaffold-DbContext in a .Net Core project with .NET 8. I'm getting CultureNotFoundException and stumbled across this page while searching for answers. My .csproj initially had no setting for InvariantGlobalization, so I added that property, setting it to false, then tried true, and then tried removing it. It always throws  CultureNotFoundException regardless of the setting. It looks like I'm going to have to solve my problem a different way, but I thought I'd leave a note about this issue.

**Comment by brahimABD98** [comment]
stil broken tried all suggestions above and still didn't work

**Comment by ElectroSpyder** [comment]
Thx @adeyinkaroyal , in my case i have error using UOW whit ado.net and repository pattern, and i use Microsoft.Data.SqlClient.

**Comment by GUILHERMEPSANTOS** [comment]
Obrigado!

**Comment by johnnyreilly** [comment]
If you're running in Docker, the following links may be helpful:

- https://github.com/dotnet/dotnet-docker/blob/main/samples/enable-globalization.md#use-of-microsoftdatasqlclient-requires-icu-to-be-installed
- https://github.com/dotnet/dotnet-docker/discussions/5092
- - https://github.com/dotnet/dotnet-docker/blob/main/documentation/ubuntu-chiseled.md#how-do-i-use-globalization-with-chiseled-images

**Comment by asimkhan224456** [comment]
Click on the Project and Remove 
<InvariantGlobalization>true</InvariantGlobalization> 
and Rebuild You Issuse will be Slove

**Comment by MinakshiSi** [comment]
after setting <InvariantGlobalization>false</InvariantGlobalization> I am getting below error 

SqlException: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)

I have tried all the solution mentioned in below URL still not working
https://stackoverflow.com/questions/18060667/cannot-connect-to-server-a-network-related-or-instance-specific-error

**Comment by omersenpai** [comment]
![1](https://github.com/dotnet/SqlClient/assets/96244199/e2835095-fad7-49d6-9377-3f07be4d18b9)
![2](https://github.com/dotnet/SqlClient/assets/96244199/ae6810f0-f62d-40b4-b5b2-ed61815227f3)
I made invariantglobalization false but it did not work. Does anyone have any other suggestions by looking at my codes?

**Comment by ErikEJ** [comment]
Not easy with just screenshots and no actual code, but did you set it on your executable project, and not just a class library?

**Comment by omersenpai** [comment]
no,its just a class library.

**Comment by ErikEJ** [comment]
You cannot run a class library!

**Comment by ElectroSpyder** [comment]
@omersenpai bro, this ->    <InvariantGlobalization>false</InvariantGlobalization> must be in HotelProject.WebApi.csproj

Test pls, thx

**Comment by omersenpai** [comment]
> @omersenpai bro, this -> ( InvariantGlobalization ) must be in HotelProject.WebApi.csproj
> 
> Test pls, thx

it didn't work.Still thanks for answer bro

**Comment by omersenpai** [comment]
> I deleted this line: `<InvariantGlobalization>false</InvariantGlobalization>` from the Project file, So It will look like this:
> 
> ```
>   <PropertyGroup>
>     <TargetFramework>net8.0</TargetFramework>
>     <Nullable>enable</Nullable>
>     <ImplicitUsings>enable</ImplicitUsings>
>   </PropertyGroup>
> ```
> 
> And I added the setting `TrustServerCertificate=true;` to the ConnectionString in `appsettings.json` It will look like this:
> 
> ```
> "ConnectionStrings": {
>   "DefaultConnection": "Data Source='YourServerName';Initial Catalog='YourDataBaseName';TrustServerCertificate=true;Integrated Security=True;"
> },
> ```
> 
> This is what solved the error.

I CAN FİX THAT ,THANKS TO THİS COMMENT.

**Comment by nap2610** [comment]
**SOLUTION**

If you worrking through container, add this before `ENTRYPOINT`

```
RUN apk add --no-cache icu-libs
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
```
