### ISSUE TITLE
Azure.Identity version used has a high vulnerability

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/SqlClient#2241]
### Describe the bug
All versions of the library are using a version of Azure.Identity which has an identified vulnerability which has been fixed in newer version of the library

### To reproduce
Open nuget package manager with library installed
Look at vulnerabilities of transitive packages and observe warning about vulnerability for Azure.Identity 
Look at dependencies of Microsoft.Data.SqlClient and observe this is the source of the vulnerable library

### Expected behavior
Azure.Identity version increased to 1.10.2+

### Further technical details
https://github.com/advisories/GHSA-5mfx-4wcx-rv27

**Comment by JRahnama** [comment]
Duplicate of #2195
