### ISSUE TITLE
SSL Provider issue with OpenSSL 3 throwing a failed handshake exception

### ISSUE THREAD

**Issue by AntonZhernosek** [dotnet/SqlClient#2242]
Good day

Running db queries on older mssql databases with OpenSSL3 as SSL Provider results in the following issue

> Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: SSL Provider, error: 31 - Encryption(ssl/tls) handshake failed)
> ---> System.IO.IOException: Received an unexpected EOF or 0 bytes from the transport stream.
> at System.Net.Security.SslStream.ReceiveHandshakeFrameAsync[TIOAdapter](CancellationToken cancellationToken)
> at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
> at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
> at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)
> at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)
> at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
> at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
> at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)
> at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)
> at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)
> at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)
> at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)
> at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)
> at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)
> at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
> at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
> at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
> at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
> at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
> at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()

Repro:
1) Get an old mssql database. I've reproed this by pulling the oldest available mssql image
```
docker pull mcr.microsoft.com/mssql/server:2017-CU1-ubuntu
docker tag mcr.microsoft.com/mssql/server:2017-CU1-ubuntu mssql2017
docker run -d -p 1533:1433 -e 'ACCEPT_EULA=Y' -e 'MSSQL_PID=Express' -e 'MSSQL_SA_PASSWORD=SAPassword123!' mssql2017
```

2) Create a simple dotnet 8 program with M.D.S. and Dapper
```
SqlConnectionStringBuilder sqlConnectionStringBuilder = new()
{
    DataSource = "host.docker.internal,1533",
    InitialCatalog = "master",
    UserID = "SA",
    Password = "SAPassword123!",

    Encrypt = false,
    TrustServerCertificate = true,
};

SqlConnection sqlConnection = new(sqlConnectionStringBuilder.ConnectionString);
string query = "SELECT 1";

int result = await sqlConnection.QuerySingleAsync<int>(query);

Console.WriteLine($"Query result: {result}");
```

3) Create a dockerfile for the program
```
# Build stage with sdk image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
SHELL ["/bin/bash", "-c"]

WORKDIR /src
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o /app

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:8.0 AS final

WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "{YOUR_APP_NAME}.dll"]
```

4) Build and run your application in docker
5) Observe the above error

The same program and setup work fine when run from Windows without OpenSSL. It's also fine when run as a dotnet 7 application with the default bullseye image (Debian 11 with OpenSSL1.1), but fails with bookworm-slim (Debian 12 with OpenSSL3).

There have been similar issues previously such as https://github.com/dotnet/SqlClient/issues/633 and also several threads on StackOverflow. However the error is slightly different, it seems to have a clear cause (in my mind), I've reproduced it from at least 2 different set-ups, and it's not fixable by the suggested approaches
1) Not fixed by Encrypt = false in the connection string
2) Not fixed by TrustServerCertificate = true
3) I've messed around a lot with the openssl.cnf file and setting MinProtocol = TLSv1 doesn't fix it
4) Same as above, setting CipherString = DEFAULT@SECLEVEL=1 or ALL@SECLEVEL=1 or to a colon-separated list doesn't fix it

I believe that the underlying issue is that OpenSSL has introduced a breaking change within their SLL_shutdown logic
https://www.openssl.org/docs/manmaster/man3/SSL_shutdown.html
> There are SSL/TLS implementations that never send the required close_notify alert message but simply close the underlying transport (e.g. a TCP connection) instead. This will ordinarily result in an error being generated.

The suggested fix is
> If compatibility with such peers is desired, the option SSL_OP_IGNORE_UNEXPECTED_EOF can be set.

I've tried specifying it within the openssl.cnf file as described here https://github.com/openssl/openssl/discussions/22690
However this doesn't resolve the error or I'm doing something incorrectly

Since dotnet 8 uses Debian 12 with OpenSSL3 as the default, this makes dockerized dotnet 8 applications using sql connections potentially incompatible with old versions of mssql or other databases (I haven't tested it with a newer version, so there's a chance it works fine there, I have also not tested other db providers).
The other solutions are to not upgrade existing applications beyond dotnet 7, remove OpenSSL3 and install OpenSSL1.1 on the image, create your own image or to upgrade the existing database. All of the above options are potentially not great in their own way and there will likely be plenty of legacy databases that are not easily update-able to handle SSL streams better

This poses a set of questions from my side:
1) Is there actually a way to edit the openssl.cnf file in a way that would make the flag work and not throw an error?
2) Can we somehow influence the SSL stream or interact with the SSL provider at the application level to add the abovementioned flag or ignore the error? P/Invoke does allow to do interop with OpenSSL's C API, but there's no way to get your hands on the SSL_Ctx used by the application to set the necessary flag globally for all sql connections (or at least I haven't found one)
3) If both of the above options are unavailable, would this signify a need to have some config and a publicly available property at the SqlConnection level to ensure we don't error out from this?

**Comment by ErikEJ** [comment]
Which "older SQL Server version" exactly?

**Comment by AntonZhernosek** [comment]
The original issue showed up when trying to establish a connection to an mssql 2016 database deployed on a windows machine.
I've used a containerized mssql2017-ubuntu version to repro locally, as outlined in the post above. Have also just tested with the latest mssql image and it's not an issue. Haven't tested anything in-between since there is quite a large amount of available image versions

**Comment by AntonZhernosek** [comment]
Okay. Have to apologise becuase I was wrong about the underlying cause of the issue.

What I've done is, I've taken the openssl.cnf file from the dotnet7 image and tried messing around with that. Replacing the original openssl.cnf on the dotnet8 image and adjusting the CipherString.

To my surprise, the same program from the original post has started working when I adjusted the config with

```
CipherString = DEFAULT@SECLEVEL=1
```

Now, I've tried the same thing on the original setup with MSSQL 2016 and it didn't work out the same way. But apparently you can also set the seclevel to 0 and it will accept any cipher. So I've done that and the error goes away. So my original assumption is incorrect and it's just related to the fact that OpenSSL3 has lowered the the security level for some ciphers.

However, you can't run the sed command that was described in the original threads because the openssl.cnf file is different on the dotnet8 image and doesn't have the CipherString property configured by default.
So as a workaround, here's the config file that you can use to replace the original.

[openssl.zip](https://github.com/dotnet/SqlClient/files/13474935/openssl.zip)

MSSQL 2022 -> you don't actually need it, it has worked out of the box without issues
MSSQL 2017 -> Adjust CipherString to use seclevel = 1
MSSQL 2016  (and assume older) -> Adjust CipherString to use seclevel = 0 (and hopefully convince everyone to upgrade the db)
I haven't tested the version between 2017 and 2022.

If you're building from a Dockerfile, add this somewhere in there

```
COPY openssl.cnf /etc/ssl/openssl.cnf
```

Closing the thread because this isn't actually related to M.D.S.

**Comment by nop00** [comment]
If you want to keep debian 12's original `openssl.cnf` file, you can modify it from the dockerfile like so:
```
RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf
RUN echo '\n\n[openssl_init]\nssl_conf = ssl_sect\n\n[ssl_sect]\nsystem_default = ssl_default_sect\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n' >> /etc/ssl/openssl.cnf
```

The first line comments out the default `openssl_init` section, and the second one defines it to set up a default ssl configuration section that we use to configure a `MinProtocol` of TLSv1 and seclevel of 0 (I use 0 to connect to a MSSQL 2014 instance, change it according to what version you're connecting to).

**Comment by jorge-llanque** [comment]
If your case is dotnet 8 with MSSQL 2012, it works perfectly :
```
RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf

RUN printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf
RUN printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf
RUN printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf
```

**Comment by masterlifting** [comment]
> If your case is dotnet 8 with MSSQL 2012, it works perfectly :
> 
> ```
> RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf
> 
> RUN printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf
> RUN printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf
> RUN printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf
> ```

It helped me connect to specific websites with the HttpClient with the same error.

**Comment by Terryio** [comment]
> If your case is dotnet 8 with MSSQL 2012, it works perfectly :
> 
> ```
> RUN sed -i 's/\[openssl_init\]/# [openssl_init]/' /etc/ssl/openssl.cnf
> 
> RUN printf "\n\n[openssl_init]\nssl_conf = ssl_sect" >> /etc/ssl/openssl.cnf
> RUN printf "\n\n[ssl_sect]\nsystem_default = ssl_default_sect" >> /etc/ssl/openssl.cnf
> RUN printf "\n\n[ssl_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT@SECLEVEL=0\n" >> /etc/ssl/openssl.cnf
> ```

Thanks, you saved me from a lot of hours of research !

**Comment by dennisvanderpool** [comment]
I did not want lower the security of my complete system. In my case I only need it for Azure Data Studio.
So I made a copy of my openssl.cnf called lowsecurity_openssl.cnf and applied the lowered security to it as posted by @masterlifting 

Now when I run Azure Data Studio I set the OPENSSL_CONF env var to point the low security version.

```bash
$ cat run_azuredatastudio_with_lowsecurity 
export OPENSSL_CONF=/etc/ssl/lowsecurity_openssl.cnf
azuredatastudio
```
