### ISSUE TITLE
Extended Connection Timeout Duration Does Not Affect EF Core's Connection Attempt Duration

### ISSUE THREAD

**Issue by hasancaktar** [dotnet/SqlClient#2250]
When attempting to establish a connection to the database, if the database server is offline or the connection string is incorrect, it tries to connect for approximately 1 minute before failing with an error. To address this, the configuration is set in the OnConfiguring method as follows:
`protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder.UseSqlServer(
        "Connection string",
        op =>
        {
            op.CommandTimeout(1).EnableRetryOnFailure(1, TimeSpan.FromSeconds(1), null);
        });
}`

However, despite this configuration, it still attempts to connect for about a minute before throwing an error.

Versions Used:

    .NET Core 7 Web API
    EF Core 7
    Windows 10

Issue:
Despite applying the configuration correctly, the specified connection attempt duration exceeds one minute, resulting in an error. How can I resolve this? Please inform me if you have any alternative solutions.

**Comment by hasancaktar** [comment]
> Moving this to SqlClient as AFAIK the long timeout originates from there.

I am not familiar wıth AFAIK. Can you please explain your answer in more detail and if possible with an example.

**Comment by ajcvickers** [comment]
@hasancaktar Note also that you are setting the "command timeout" not the "connection timeout".

**Comment by hasancaktar** [comment]
> @hasancaktar Note also that you are setting the "command timeout" not the "connection timeout".

Unfortunately, there is no option called "Connection Timeout." There is only the option for "Command Timeout."

**Comment by ErikEJ** [comment]
You can add "Connection Timeout" to your connection string

**Comment by hasancaktar** [comment]
> Connection Timeout

"I tried, but still couldn't close the connection within the specified time."

**Comment by ErikEJ** [comment]
Sorry - you can add "ConnectRetryCount=0" to avoid the initial 10 second wait time (and combine with "Connection Timeout=1")

**Comment by ErikEJ** [comment]
See https://github.com/dotnet/efcore/issues/7283
