### ISSUE TITLE
[Component Governance] vulnerability for Azure.Identity 1.7.0

### ISSUE THREAD

**Issue by Kangaxx-0** [dotnet/SqlClient#2268]
We have a component governance s360, it complains about Azure.Identity 1.7.0, and the root dependency is Microsoft.Data.SqlClient(5.1.2) 

5.1.2 is the latest release build, so our team wonders when the plan is to release a new version.

Thanks for the support!

**Comment by JRahnama** [comment]
@Kangaxx-0 the fix is included in our latest preview release [v5.2.0-preview4](https://www.nuget.org/packages/Microsoft.Data.SqlClient/5.2.0-preview4.23342.2). Our next GA is scheduled for  some time in February.
