### ISSUE TITLE
Any plans to support `Microsoft.SqlServer.Server.SqlProcedureAttribute` attributes

### ISSUE THREAD

**Issue by msschl** [dotnet/SqlClient#2282]
In modern .net?

In net framework there were attributes like SqlProcedure to create external sql procedures and load them via an external assembly into the Sql server. Is there any plan to port those into modern .net or is there an alternative?

**Comment by JRahnama** [comment]
@msschl, Although this does not look like a SqlClient issue,  we will look into this to provide you a proper response.

Adding some more info here for review process:
According to [MS Documentation](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.server.sqlprocedureattribute?view=netframework-4.8.1#remarks)

> [SqlProcedureAttribute](https://learn.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.server.sqlprocedureattribute?view=netframework-4.8.1) is used only by Microsoft Visual Studio to automatically register the specified method as a stored procedure. It is not used by SQL Server.

**Comment by msschl** [comment]
We create functions and procedures in c# and register them in the sql server. Currently, we use net472 for this.

Here is a simple sample of what we are using:

Sample function
```cs
using System.Data.SqlTypes;

using Microsoft.SqlServer.Server;

using System.Text.RegularExpressions;

namespace Company.Extensions.Sql.Database.Functions;

public partial class RegexFunctions
{
    [SqlFunction(Name="fn_RegexIsMatch")]
    public static SqlBoolean IsMatchFunction(SqlString Input, SqlString Pattern)
    {
        if (Input.IsNull || Pattern.IsNull)
            return false;

        return Regex.IsMatch(Input.Value, Pattern.Value);
    }
}
```

```sql
USE [%DATABASE%]
GO

CREATE ASSEMBLY [Company.Extensions.Sql]
FROM '\\sqlserver\c$\Program Files\Microsoft SQL Server\Assemblys\Company.Extensions.Sql.dll'
GO
```

```sql
USE [%DATABASE%]
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO

CREATE FUNCTION [dbo].[fn_RegexIsMatch]
(
    @Input       NVARCHAR(MAX),
    @Pattern    NVARCHAR(MAX)
)
RETURNS BIT
WITH EXECUTE AS CALLER
AS
EXTERNAL NAME [Company.Extensions.Sql].[Company.Extensions.Sql.Database.Functions.RegexFunctions].[IsMatchFunction]
GO
```

Are those attributes `SqlFunction`, `SqlProcedure`, ... ported to modern .net?

**Comment by ErikEJ** [comment]
This is a Server side feature request:

https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0

**Comment by msschl** [comment]
Should I open a post there?

**Comment by ErikEJ** [comment]
You could try if you think it is important. I would not hold my breath though

**Comment by kf-gonzalez** [comment]
This feedback link is the appropriate forum for SQL features

https://feedback.azure.com/d365community/forum/04fe6ee0-3b25-ec11-b6e6-000d3a4f0da0
