### ISSUE TITLE
Any reason installing SqlClient should bring WebView2?

### ISSUE THREAD

**Issue by R2D221** [dotnet/SqlClient#2298]
### Describe the bug
I just updated the Microsoft.Data.SqlClient package to version 5.1.4. After that, in the list of transitive packages it shows the following:

> **Microsoft.Web.WebView2** by Microsoft
> **Transitively referenced version** 1.0.864.35 by
> Microsoft.Data.SqlClient.5.1.4

### To reproduce
Just install Microsoft.Data.SqlClient 5.1.4 in a console project.

### Expected behavior
A GUI component shouldn't be part of the dependencies for a database library.

### Further technical details
Microsoft.Data.SqlClient version: 5.1.4
.NET target: 8.0
SQL Server version: -
Operating system: Windows 10 21H2

**Additional context**

**Comment by ErikEJ** [comment]
Is the WebView2 dll included when you publish the app. It comes from Azure.Identity, but only when targeting net6.0-windows7.0 

https://www.nuget.org/packages/Microsoft.Identity.Client/

**Comment by R2D221** [comment]
1. It does, it outputs the following DLLS:
    * Microsoft.Web.WebView2.Core.dll
    * Microsoft.Web.WebView2.WinForms.dll
    * Microsoft.Web.WebView2.Wpf.dll
2. Even then, I still have some projects in .NET 6. WebView2 shouldn't be included in them either.

**Comment by JRahnama** [comment]
I just created a sample application with net8 and was not able to see that reference. As @ErikEJ has mentioned it will be mapped when targeting net6.0-windows7.0. Can you share the csproj?

![image](https://github.com/dotnet/SqlClient/assets/32077152/7f116ccd-0a37-4c9b-abb3-565758a3b8fb)

**Comment by R2D221** [comment]
The csproj only has <TargetFramework>net8.0-windows</TargetFramework> and the dependencies, but I think the real reason is that some of my project references (common libraries for all our projects) are targeting net6.0-windows and also use Microsoft.Data.SqlClient.

**Comment by ErikEJ** [comment]
@R2D221 what if you target net8.0  ONLY?

**Comment by R2D221** [comment]
Give me a moment and I'll test it

**Comment by R2D221** [comment]
With this project I first had issue with, I moved ALL dependencies to net8.0-windows (can't remove Windows since I do indeed use Windows-specific code), and WebView2 is still present.

So, I'm making a new test project:

With net8.0 (NOT windows):

![image](https://github.com/dotnet/SqlClient/assets/774575/00ca0c31-231a-45fd-b954-9ccc2e33125b)

With net8.0-windows:

![image](https://github.com/dotnet/SqlClient/assets/774575/6e1ea040-126d-4033-bbf7-92dc69b060f5)

**Comment by ErikEJ** [comment]
This seems to be by design...

**Comment by ErikEJ** [comment]
If it was a true console project you would not need net8.0-windows

**Comment by R2D221** [comment]
I have a dependency on System.DirectoryServices for some Active Directory stuff. That still doesn't invoke any UI of any kind, but the package gives warnings about the only supported platform being Windows, so I made my project Windows-only.

**Comment by R2D221** [comment]
But anyway, even when I'm using SqlClient on WPF projects, I still don't need the WebView2 component since I'm not showing any HTML stuff.

**Comment by AdaskoTheBeAsT** [comment]
same situation is with System.Drawing.Common 

Microsoft.Data.SqlClient is dependant on System.Runtime.Caching which is dependant on System.Configuration.ConfigurationManager which is dependant on System.Security.Permissions which is dependant on System.Windows.Extensions which is dependant on System.Drawing.Common

it is only db driver 
please use AI to sort out dependencies

**Comment by David-Engel** [comment]
Microsoft.Identity.Client is MSAL. It provides AAD authentication, including interactive auth. I'd guess those libraries are included to provide a nicer interactive experience on Windows and/or WAM integration, versus the typical browser popup implementation. This dependency chain isn't something we have control over in MDS.
