### ISSUE TITLE
Licence type is not being recognised

### ISSUE THREAD

**Issue by thompson-tomo** [dotnet/SqlClient#2314]
### Describe the bug
The licence type is not being recognised by NUGET & is not able to be populated to SBOM

### To reproduce
- Find an affected package on nuget. 
- Open package in Nuget Package Explorer
- Observe that the licence property is not populated

### Expected behavior
Package shows as having a MIT licence

**Additional context**
Atleast the following packages are impacted:
- Microsoft.Data.SqlClient.Sni
- Microsoft.Data.SqlClient.Sni.Runtime

**Comment by kf-gonzalez** [comment]
also please specify the specific NUGET url

**Comment by thompson-tomo** [comment]
@kf-gonzalez I have now gone and provided explicit instructions on how to reproduce the issue. The packages which I have seen are impacted has been moved to the additional context but it should be checked if others are impacted

**Comment by JRahnama** [comment]
If you are referring below packages the license link is working correctly. Did I miss something?
![image](https://github.com/dotnet/SqlClient/assets/32077152/9ef53477-f808-48b8-8b54-05f19ae7f6b7)

![image](https://github.com/dotnet/SqlClient/assets/32077152/b7b8c5e3-f7aa-414b-9fbd-b32c0ba9e426)

**Comment by thompson-tomo** [comment]
Here is the SQLClient.SNI package in package explorer
<img width="925" alt="SQLClient SNI" src="https://github.com/dotnet/SqlClient/assets/19771933/022328b1-d9f5-4bfb-b1bd-028f0b83a15e">

Where as the SQLClient package in package explorer has the property set
<img width="929" alt="SQLClient" src="https://github.com/dotnet/SqlClient/assets/19771933/af55e453-04a3-474c-8220-05605630d2f7">

**Comment by JRahnama** [comment]
@thompson-tomo the first package is Microsoft.Data.SqlClient.SNI which is not public repo and has a Microsoft license. The second image is Microsoft.Data.SqlClient which is an open source driver and has MIT license. I cannot see the problem here.
