### ISSUE TITLE
$(IsUAPAssembly)

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#2323]
Is this still in use/built?

**Comment by David-Engel** [comment]
It's not currently in use. It's left over from the SDS fork. Plans to support UAP/UWP in MDS were in the future plans. But I don't see them getting prioritized given that MS has said that UWP is no longer the future.

https://github.com/microsoft/WindowsAppSDK/discussions/1615
https://www.techradar.com/news/microsoft-is-finally-dropping-uwp-app-support-windows-app-sdk-heres-why

I also don't know if MDS needs to make any changes for the Windows App SDK, at this point. Or if it just works with it as-is.
