### ISSUE TITLE
Test connection failed because of an error in initializing provider

### ISSUE THREAD

**Issue by kileri** [dotnet/SqlClient#233]
I am having an issue with my .Net Provider\SqlClient Data Provider used in a SqlServer Analysis Services server. Trying to troubleshoot a recent failure I see on a recurring sql agent job that triggers processing of an ssas table. I started getting 

Failed to save modifications to the server. Error returned: 'One or more errors occurred.;One or more errors occurred.
AADSTS50079: Due to a configuration change made by your administrator, or because you moved to a new location, you must enroll in multi-factor authentication to access …….
Timestamp: 2019-09-28 19:16:42Z. The exception was raised by the IDbConnection interface.
A connection could not be made to the data source with the Name of ……'.

I am trying to test the connection listed in the ssas model from ssms but getting below. 
 
![image](https://user-images.githubusercontent.com/36460291/65823243-71003c00-e207-11e9-8d28-dd60c13b56aa.png)

I recently installed the ssms v18.3 on this box and it appears to have upgraded my .net framework. Here is the current .net fx setup registry entries
 
![image](https://user-images.githubusercontent.com/36460291/65823247-7fe6ee80-e207-11e9-8abb-d6e6296304c9.png)

Also have adalsql.dll in Sys32 as 
 
![image](https://user-images.githubusercontent.com/36460291/65823250-84130c00-e207-11e9-95b4-d6f5feaae758.png)

And in SysWOW64 as
 
![image](https://user-images.githubusercontent.com/36460291/65823252-89705680-e207-11e9-8fa7-b0b20523ac81.png)

Are there any known issues with this version of .net fx that could have caused this?

**Comment by cheenamalhotra** [comment]
Hi @kileri 

Please verify this behaviour with SSMS and Active Directory if your crendentials have been enforced to work in Multi-Factor Authentication only. This is very common if organization policies make it mandatory for user accounts to use Multi Factor Authentication only.

In which case, you can no longer to connect with "Active Directory Password" authentication with your account and must use either "Active Directory Integrated" mode (from domain joined machine) or "Active Directory Interactive", also known as "Multi Factor Authentication" mode of authentication with SqlClient Provider.

**Comment by kileri** [comment]
Thank you @cheenamalhotra SSMS login attempt with Active Directory Password does end up with the same error.
