### ISSUE TITLE
PowerShell can't recognize "Mandatory"

### ISSUE THREAD

**Issue by qizu0302** [dotnet/SqlClient#2336]
Here's my code, there is a parameter in my PowerShell cmdlet,
`[Parameter(Mandatory = true, ValueFromPipeline = true, ValueFromPipelineByPropertyName = true)]`
`[ValidateSet("Mandatory", "True", Optional", "Strict", IgnoreCase = true)]`
`public SqlConnectionEncryptOption DatabaseConnectionEncryption`
`{`
`    get { return m_Encrypt; }`
`    set { m_Encrypt = value; }`
`}`

When I input Optional (or "Optional") as its value in terminal, it shows this error
![image](https://github.com/dotnet/SqlClient/assets/103396968/d43deee2-8530-47b0-b871-5d4bf48bf7da)

I'm wondering why SQL library doesn't recognize "False" as SqlConnectionEncryptOption.Optional internally.

**Comment by David-Engel** [comment]
I don't think this has anything to do with MDS. It looks like you simply forgot to include "False" in your validation attribute:

```
[ValidateSet("Mandatory", "True", Optional", "Strict", IgnoreCase = true)]
```

Also, "Optional" is missing the starting double quote.

I'm not a PowerShell commandlet expert, but I would guess you need this:

```
[ValidateSet("Mandatory", "True", "Optional", "False", "Strict", IgnoreCase = true)]
```

**Comment by qizu0302** [comment]
Yes, add "False" into ValidateSet is OK, but we only want to use "Mandatory", "Optional" and "Strict" in ValidateSet finally to avoid confusion.

**Comment by David-Engel** [comment]
Sounds like you need to figure out where `False` is coming from and, if needed, translate it to `Optional` somewhere in your code. This is outside of the scope of this library, though.

**Comment by JRahnama** [comment]
Closing the issue as it is external to SqlClient.
