### ISSUE TITLE
.NET 3.5 to .NET 4.7.2 Project 

### ISSUE THREAD

**Issue by TLEREW325** [dotnet/SqlClient#2337]
Hello everyone;

I am having an issue with my program. I recently moved from VS2008 to VS2022. I created an ERP Program in VS2008 (Visual Basic) and it has been published and deployed and have been using it for 12 years. I migrated the project into VS2022 (Visual Basic), and can run the ERP Program in the debugger, to test, change, troubleshoot, etc. and it runs fine. When I publish from VS2022 and all of the client computers get the update, when I download and install the update, none of the client computers will run the application. The original program target was .NET 3.5 but in the new VS2022, it is .NET 4.7.2. The client computers see the update, install it, but when it comes to run, it errors. Based on the error, I think the program is trying to run using CLR 2.0 when CLR 4.0 is required for .NET 4.0 and higher. I do not know how to fix this. I have tried many things and I need some help. Can anyone please help.

Thanks,

Todd

**Comment by David-Engel** [comment]
How is this related to the SqlClient library (Microsoft.Data.SqlClient or System.Data.SqlClient)?

Seems like this is a general Visual Studio question better suited to a different forum. If there is something about your project related to SqlClient, please include that information and error details that indicate you are having a problem with SqlClient.

Thanks,
David

**Comment by David-Engel** [comment]
Seems like this is the same as #2339, which you marked as resolved.
