### ISSUE TITLE
Add community contributions in release notes

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/SqlClient#2341]
I'm just filing an issue here to help push an effort of giving small thanks to community contributions.

Over at NuGet we do this in release notes like this:

https://learn.microsoft.com/en-us/nuget/release-notes/nuget-6.8#community-contributions

I think it would mean a lot to folks who contribute to these open projects if they saw their name next to issues they fixed/contributed on.

https://twitter.com/danielmarbach/status/1753817828732338402

**Comment by Wraith2** [comment]
It seems like extra admin for an already tricky release process with no upside. If people want to know _who_ is fixing things they can look at the PR's.

**Comment by danielmarbach** [comment]
@Wraith2 which in my case wasn't even linked ;)

FYI Other teams are doing something similar. Example https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/CHANGELOG.md#7160-2023-08-07

And I'm guessing the manual work could probably be mostly automated if needed.

**Comment by roji** [comment]
Agreed that explicit call-outs of community contributions are important and are a fundamental part of how open source works - I definitely wouldn't agree that there is "no upside" to it. Given that release notes are already being written, it doesn't seem that a simple call-out for the contributor doesn't add significant work.

**Comment by David-Engel** [comment]
I agree that this is something we should do. I'll add it to our release notes checklist and a backlog task for myself to go back through the last couple of release notes (unless someone beats me to it).
