### ISSUE TITLE
Microsoft.SqlClient.Data 5.1.5 reference pulls 5.1.1.0 when the project is published

### ISSUE THREAD

**Issue by yogigrantz** [dotnet/SqlClient#2355]
### Describe the bug

I have this Nuget reference in my project: 

  `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" />`

When I publish my solution, whether with Visual Studio 2022 publish button or command line, it produce the same result: 

The Microsoft.Data.SqlClient.SNI.dll in the publish folder is version 5.1.1.0

### To reproduce

1. Reference this Nuget package: 

  `<PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.5" /> `

2. Publish the project
3. Check the version of Microsoft.Data.SqlClient.SNI.dll in the output folder

![MSD](https://github.com/dotnet/SqlClient/assets/14880717/301f3b2e-39e1-40a8-b4fd-39352f35e3d0)

**Comment by yogigrantz** [comment]
also, when I published with this command line:

dotnet publish (myAppName) -o C:\temp\publish /p:PublishSingleFile=true /p:PublishTrimmed=true --runtime win-x64

it does produce a single executable, but when I ran that executable, I would get this MDS exception error:

" at Microsoft.Data.SqlClient.SNINativeMethodWrapper.SNIAddProvider(SNIHandle pConn, ProviderEnum ProvNum, AuthProviderInfo& pInfo)\r\n at Microsoft.Data.SqlClient.TdsParserStateObjectNative.EnableSsl(UInt32& info, Boolean tlsFirst, String serverCertificateFilename)\r\n at Microsoft.Data.SqlClient.TdsParser.EnableSsl(UInt32 info, SqlConnectionEncryptOption encrypt, Boolean integratedSecurity, String serverCertificateFilename)\r\n at Microsoft.Data.SqlClient.TdsParser.ConsumePreLoginHandshake(SqlConnectionEncryptOption encrypt, Boolean trustServerCert, Boolean integratedSecurity, Boolean& marsCapable, Boolean& fedAuthRequired, Boolean tlsFirst, String serverCert)\r\n at Microsoft.Data.SqlClient.TdsParser.Connect(ServerInfo serverInfo, SqlInternalConnectionTds connHandler, Boolean ignoreSniOpenTimeout, Int64 timerExpire, SqlConnectionString connectionOptions, Boolean withFailover)\r\n at Microsoft.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean ignoreSniOpenTimeout, TimeoutTimer timeout, Boolean withFailover)\r\n at Microsoft.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(ServerInfo serverInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString connectionOptions, SqlCredential credential, TimeoutTimer timeout)\r\n at Microsoft.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(TimeoutTimer timeout, SqlConnectionString connectionOptions, SqlCredential credential, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance)\r\n at Microsoft.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling, String accessToken, DbConnectionPool pool)\r\n at Microsoft.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)\r\n at Microsoft.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)\r\n at Microsoft.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n at Microsoft.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)\r\n at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)\r\n   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)\r\n at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions)\r\n   at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource1 retry, DbConnectionOptions userOptions)\r\n at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)\r\n at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)\r\n at Microsoft.Data.SqlClient.SqlConnection.Open()\r\n at .... (my class library)

But when I published the project with VS2022 publish button, the executable works fine. Either way, Microsoft.Data.SqlClient.SNI File version 5.1.1 is produced in the output folder and not the 5.1.5 as I saw in my .nuget folder: 

![MDS515](https://github.com/dotnet/SqlClient/assets/14880717/69b9e817-2424-4721-8463-5889aeab5d97)

**Comment by NotTsunami** [comment]
Microsoft.Data.SqlClient.SNI.dll =/= Microsoft.Data.SqlClient.dll

This is [not a bug](https://github.com/dotnet/SqlClient/blob/v5.1.5/tools/props/Versions.props#L26).

**Comment by David-Engel** [comment]
As stated, the Microsoft.Data.SqlClient and Microsoft.Data.SqlClient.SNI packages are independent with different files and versions.

**Comment by yogigrantz** [comment]
@David-Engel  & @NotTsunami  : 

I do get Microsoft.Data.SQLClient.SNI, but, the dll file size and date are different from my Nuget package local folder: 

the top image shows the dll that is in my .nuget folder, 270kb dated 1/26/2024, file version 5.15.24027.2 . The bottom shows the dll that is in the deployed folder, 494kb dated 8/11/2023, file version 5.1.1.0. Both are SNI and sure they are not the same with the not SNI one, but, my worry is, the size, date, and file version are different between .nuget and /publish folder

![image](https://github.com/dotnet/SqlClient/assets/14880717/2d76bbe9-a19b-4c6b-ab5b-7bbbe7e973f9)

**Comment by yogigrantz** [comment]
ok if the File version does not have to match the package version, I will close this ticket then. Thank you
