### ISSUE TITLE
Microsoft.Data.SqlClient not restoring from Global NuGet Cache - 1.0.19249.1

### ISSUE THREAD

**Issue by JaimeStill** [dotnet/SqlClient#236]
### Describe the bug
> I know that the culprit of this is originally EF Core 3, but as the issue explicitly stems from Microsoft.Data.SqlClient's NuGet dependencies, I thought this was the best venue for this issue. If this is incorrect, I will close and open with the EF Core repository.  

I'm using EF Core 3 in an offline environment (I import my `%USERPROFILE%\.nuget\packages` global cache from an internet connected machine). Whenever I attempt to build a project, it errors out because it is trying to reach out to the online NuGet repository. 

It wasn't giving me any more concise details about what was causing it to fail, so I did a restore pointed to the local global package source. Although the restore completed successfully, it triggered the following warning for all projects that depend on EF Core 3:

```
warning NU1603: Microsoft.Data.SqlClient 1.0.19249.1 
depends on runtime.native.System.Data.SqlClient.sni (>= 4.4.0) 
but runtime.native.System.Data.SqlClient.sni 4.4.0 was not found.  
An approximate best match of runtime.native.System.Data.SqlClient.sni 4.5.0 was resolved.
```

### To reproduce

The projects that produced this warning have any one of the following package dependencies:

```
Target Framework: netcoreapp3.0

Microsoft.EntityFrameworkCore.SqlServer 3.0.0
Microsoft.EntityFrameworkCore.Relational 3.0.0
Microsoft.EntityFrameworkCore.Tools 3.0.0
Microsoft.EntityFrameworkCore.Design 3.0.0
```

### Expected behavior
Restore from cache without warnings if an acceptable version of `System.Data.SqlClient` is available, in this case, **4.5.0**.

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19249.1
.NET target: Core 3.0.100
SQL Server version: SQL Server 2017
Operating system: Windows 10 1703 15063.0

**Comment by Wraith2** [comment]
You will need to pull a copy of that package into your local nuget store. It contains the native implementaiton of the network interface used by sqlclient in windows environments and is not optional.

**Comment by JaimeStill** [comment]
> 
> 
> You will need to pull a copy of that package into your local nuget store. It contains the native implementaiton of the network interface used by sqlclient in windows environments and is not optional.

In my local nuget store, I have version `System.Data.SqlServer 4.5.0`, which fits the **>= 4.4.0** requirement.

I'm suspecting it may have to do with the fact that the disconnected Windows 10 environment is running an older build (1703 as opposed to 19xx). In the environment that I use at home (which I use to acquire the nuget store for my disconnected environment), a disconnected build works just fine with the same project configuration. The only difference in environment is the windows version.

**Comment by Wraith2** [comment]
I meant the other package, in your post you have
```warning NU1603: Microsoft.Data.SqlClient 1.0.19249.1 
depends on runtime.native.System.Data.SqlClient.sni (>= 4.4.0) 
but runtime.native.System.Data.SqlClient.sni 4.4.0 was not found.  
An approximate best match of runtime.native.System.Data.SqlClient.sni 4.5.0 was resolved.
```

where it tells you that it wants `runtime.native.System.Data.SqlClient.sni` , which isn't the same package as `System.Data.SqlClient` You need to make sure you've got that native runtime package copied over as well. Though it does say it's resolved a match using 4.5.0 which should mean it's worked.

**Comment by JaimeStill** [comment]
Per the NuGet gallery:

```
Internal implementation package not meant for direct consumption. 
Please do not reference directly.
When using NuGet 3.x this package requires at least version 3.4.
```

When I look in my `.nuget\packages` directory, I only have `System.Data.SqlClient`, no `runtime.native.System.Data.SqlClient.sni`. And the version contained is **4.5.0**.

If I'm not supposed to consume the native runtime package directly, shouldn't it follow that this should automatically be cached in the global nuget store as a result of building a project where `Microsoft.Data.SqlClient` is a dependency (as with any other dependent package)?

What's really confusing to me is that a disconnected build using the local store works in an environment where the latest windows updates are in place, but not in an environment where the only difference is that I'm on windows 10 1703.

**Comment by cheenamalhotra** [comment]
HI @JaimeStill 

> Internal implementation package not meant for direct consumption.

This implies for `runtime.native.System.Data.SqlClient.sni`, that this package is meant for use with SqlClient drivers, reference from client application is not recommended.

But technically, it is a separate NuGet package, independent of `System.Data.SqlClient` or `Microsoft.Data.SqlClient` and needs to be present in your local NuGet cache, if working in disconnected mode.

I can't say how latest Windows Updates are connected to this, but if you have this package in your local NuGet cache, it should work fine.

> Restore from cache without warnings if an acceptable version of System.Data.SqlClient is available, in this case, 4.5.0.

Assuming you have acceptable version of `runtime.native.System.Data.SqlClient.sni` (4.5.0 or 4.6.0) available, the warning "NU1603" cannot be removed, as this is as designed from NuGet. Refer https://github.com/NuGet/Home/issues/5764

**Comment by JaimeStill** [comment]
I did further troubleshooting with the following steps:

1. Downloaded [runtime.native.System.Data.SqlClient.sni](https://www.nuget.org/packages/runtime.native.System.Data.SqlClient.sni/4.4.0) version 4.4.0.
2. Added and unpacked to `%USERPROFILE%\.nuget\packages\runtime.native.System.Data.SqlClient.sni\4.4.0\`
    * Prior to this, `runtime.native.System.Data.SqlClient.sni` did not exist in the global nuget cache
3. Created a .NET Core 3 `classlib` project via `dotnet new classlib -f netcoreapp3.0`

When attempting to add a reference to `Microsoft.Data.SqlClient` (version 1.0.19249.1 is in the global cache) via:

```
dotnet add package Microsoft.Data.SqlClient
```

I get the following error at package restoration in the above command:

```
Unable to load the service index for source https://api.nuget.org/v3/index.json
```

I manually added `Microsoft.Data.SqlClient` to the .csproj as follows:

```
<ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="1.0.19249.1" />
</ItemGroup>
```

Running `dotnet build` generates the same error as above.

Running `dotnet restore -s %USERPROFILE%\.nuget\packages` generates the following error:

```
warning: NU1603: Microsoft.Data.SqlClient 1.0.192491 depends on runtime.native.System.Data.SqlClient.sni (>= 4.4.0) but runtime.native.System.Data.SqlClient.sni 4.4.0 was not found. An approximate best match of runtime.native.System.Data.SqlClient.sni 4.5.0 was resolved.
```

**Comment by JaimeStill** [comment]
Just got home from work and, in order to verify further, I attempted the same steps on my computer with the latest windows updates. I also took the following additional steps:

* Restored the packages into a local packages cache, and `runtime.native.System.Data.SqlClient.sni` is definitely not loaded into the packages cache.
* Deleted the `obj` and `bin` directories out of the class library project.
* Disconnected my machine from the internet
* Verified that `runtime.native.System.Data.SqlClient.sni` was not in my global nuget cache
* Executed a build.

The build was successful, which leads me to believe that it HAS to have something to do with the Windows 10 version.

### Technical Details for Computer at Home
Microsoft.Data.SqlClient version: 1.0.19249.1
.NET target: Core 3.0.100
SQL Server version: SQL Server 2017
Operating system: Windows 10 1903 18362.387  

![restore-successful](https://user-images.githubusercontent.com/14102723/65916646-b5c0da00-e3a3-11e9-93ed-38a3bc76b298.png)

**Comment by Wraith2** [comment]
Ok, so not caching. Is that the only problem though? Can you try adding it to the cache (nuget package explorer or rename to zip an extract contents) and see if everything works if it is in the cache folder?

**Comment by cheenamalhotra** [comment]
Hi @JaimeStill  I just reproduced the issue and looks like this is available in "C:\Program Files\dotnet\sdk\NuGetFallbackFolder", hence not available in NuGet cache.

It means this was shipped with dotnet SDK. While discussion on that issue continues, I think you'll get your dependencies resolved from Fallback Folder first, and then looking into NuGet cache.

Hopefully you can find your answers now!

**Comment by JaimeStill** [comment]
@Wraith2 I did unpack it with 7-Zip before testing in that phase of my research, so that wasn't the issue.

@cheenamalhotra thanks a ton for this! I will verify as soon as I get the chance and get back to you.

**Comment by JaimeStill** [comment]
@cheenamalhotra the fix you provided worked! Opened issue at [NuGet Home - Provide Detailed Missing Dependency Messages](https://github.com/NuGet/Home/issues/8650) with the suggestion that when a missing dependency is encountered, details about the dependency and the location it was missing from be provided.
