### ISSUE TITLE
Generate API docs

### ISSUE THREAD

**Issue by smitpatel** [dotnet/SqlClient#238]
So it shows up here https://docs.microsoft.com/en-us/dotnet/api/?view=netcore-3.0

**Comment by cheenamalhotra** [comment]
@smitpatel 

Work is in progress for the same, PR #210 is for the same purpose.
We are working with Docs publishing team to resolve publishing roadblocks.

This activity is being tracked in #167 and [GitHub Project v1.1.0](https://github.com/dotnet/SqlClient/projects/4#card-26135257). It is currently our Highest Priority.

Closing issue as already addressed and tracked.
