### ISSUE TITLE
Server principle name lookup does not include port number in the name

### ISSUE THREAD

**Issue by trexx** [dotnet/SqlClient#2394]
### Describe the bug
Upon updating from 5.1.5 to 5.2.0, our applications running on Linux fail to connect to our databases using Integrated Security / Kerberos with an error:
` Microsoft.Data.SqlClient.SqlException (0x80131904): The target principal name is incorrect. Cannot generate SSPI context.`

This is with a connection string such as:
`"Data Source=server.domain.local;Integrated Security=true"`

`server.domain.local` here is a CNAME which resolves to `server001.domain.local`

In version 5.1.5 I can see it resolves the SPN in 2 different ways. It first resolves the SPN without the port number, and if that fails it retries with the port number in the SPN.
1st try   -> `MSSQLSvc/server001.domain.local@DOMAIN.LOCAL`
2nd try  -> `MSSQLSvc/server001.domain.local:1433@DOMAIN.LOCAL` < Lookup successful 

In version 5.2.0, it only resolves the SPN without the port number, and then performs no more searches causing connectivity to fail.
1st try   -> `MSSQLSvc/server001.domain.local@DOMAIN.LOCAL`

Our workaround has been to specify the port number in the connection string.
`"Data Source=server.domain.local,1433;Integrated Security=true"`

Is this change of behaviour intentional or a result of a bug? We're not sure if this will be fixed in SqlClient, or if we should update our SPNs, or whether we should start including port numbers in all our connection strings.

### Further technical details
Microsoft.Data.SqlClient version: 5.2.0
.NET target: 8.0
Operating system: Linux Container

**Comment by JRahnama** [comment]
@trexx We are aware of this issue in v5.2.0. Currently, we are investigating the code change that caused this behavior change. Could you please test with v5.2.0-preview5 and see if it works as you expect?

**Comment by ErikEJ** [comment]
@JRahnama could it be this?

**Comment by trexx** [comment]
@JRahnama The behaviour and result is the same with v5.2.0-preview5; The SPN its searching for does not include the port number and connectivity fails.

**Comment by David-Engel** [comment]
@trexx To narrow it down even further, can you try the earlier previews? I suspect 5.2.0 preview 4 will start working for you, but if it doesn't it will be good to know which one contains the behavior change.

**Comment by trexx** [comment]
Hi @David-Engel I've been able to narrow it down to 5.2.0-preview2.23159.1 when the SPN behaviour is that same as 5.1.5. Preview versions after this fail.

**Comment by trexx** [comment]
@JRahnama
1. 
```
Microsoft.Data.SqlClient.SqlException (0x80131904): The target principal name is incorrect. Cannot generate SSPI context.
GenericFailure
```

2. Yes. Building with net6 and SqlClient 5.2.0 results in a successful connection, and a return to the behaviour seen in version 5.2.0-preview2.23159.1 and older.

3. Our tickets are very much valid during the times we encounter this. Its farily easy for me to reproduce the error across the different versions and builds.
I suspect if you want to reproduce this on your end, you'll need to remove the default instance SPN for your SQL instance that doesn't have the port number listed and keep the SPN containing :1433.

**Comment by arellegue** [comment]
@trexx, Could you please confirm if the Sql Server that you are connecting to has a defined Instance name or just default instance name.

**Comment by kf-gonzalez2** [comment]
@trexx please try again after the 5.2.1 Hotfix is published and please let us know if you are still having an issue

**Comment by JRahnama** [comment]
Hotfix v5.2.1 is released. Can you try with that version please?

**Comment by trexx** [comment]
@arellegue Sorry for the late reply, it has a defined instance name (Listening on both a random port and 1433).

I've just tested again 5.2.1 and I get the same error. Once adding 1433 to the connection string it connects fine, otherwise without it, otherwise its `Server not found in Kerberos database`
