### ISSUE TITLE
Unable to read data from the transport connection: Connection reset by peer.

### ISSUE THREAD

**Issue by daredude123** [dotnet/SqlClient#2405]
Good morning. 
Im using Testcontainers from ubuntu (22.04) with dotnet 8. And I keep getting the following exception: 
`Error Message:
   Microsoft.Data.SqlClient.SqlException : A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
---- System.IO.IOException : Unable to read data from the transport connection: Connection reset by peer.
-------- System.Net.Sockets.SocketException : Connection reset by peer
`
TrustServerCertificate=True is enabled. My googlin' abilities is at an end, any idea what can be the issue here?

Thanks for any help.

**Comment by arellegue** [comment]
Before we can begin our investigation, would you be able to provide us with a reproduction code?  We would also need to know the connection string and the version of the Microsoft.Data.SqlClient and Sql Server.

**Comment by daredude123** [comment]
Thanks for the response. I was however able to figure it out in the last minute. The issue was my internet configuration, more specifically the VPN. I am interested in why it would crash the connection towards the local docker instance, but I am just pleased to find the reason for my problem.

SO for anyone with the same, turn of the GODDAMN vpn, and give it a go.
