### ISSUE TITLE
Win10 vs 11 and 0x80090325: certificate chain issue

### ISSUE THREAD

**Issue by awdorrin** [dotnet/SqlClient#2437]
Co-worker and I are updating our app from .Net 6 to .Net 8.

This morning I upgraded to 8.0.3 libraries and started getting the exception: (0x80090325): The certificate chain was issued by an authority that is not trusted

We encountered this previously due to the .net7 breaking change, and we updated our database connection string to include:

- Integrated Security=True; TrustServerCertificate=true; Encrypt=false

I get the error, on Windows 11
Co-Worker on Win10 has no error.

Clean-Rebuild of app, we synced our changes through Git and confirmed we are on the same baselines.
I'm not sure what else to check, so not sure if this is a weird Win11 difference.

### Include stack traces

```
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)
 ---> System.ComponentModel.Win32Exception (0x80090325): The certificate chain was issued by an authority that is not trusted.
```

### Include provider and version information

EF Core version: 8.0.3 / SqlClient 5.1.5
Database provider: Microsoft.EntityFrameworkCore.SqlServer to SQL Server 2016 DB
Target framework: .NET 8.0
Operating system: Windows 11 vs Windows 10
IDE: Visual Studio 2022 17.9

**Comment by awdorrin** [comment]
I managed to get the DB Connection to work on Win11, for me, finally... and I don't think it is the SqlClient.

We use EF Core Power Tools to generate/update the models our database project.
I just found that EF Core Power Tools is creating an OnConfiguring method:
```
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=OurServer;Initial Catalog=OurDB;Integrated Security=True;Encrypt=false");
```
During startup of the app, even though we've configured the context in Startup.cs ConfigureServices(), this OnConfiguring is getting called instead.

``` Structure.dll!Lib.DB.Services.Database.MainDBContext.OnConfiguring(Microsoft.EntityFrameworkCore.DbContextOptionsBuilder optionsBuilder) Line 337	C#
[External Code]	
App.dll!Services.CommonUtilities.ValidateOrAddUser(Lib.DB.Services.Database.MainDBContext _context, Lib.DB.Services.Database.WarehouseDB.WarehouseDBContext _prismContext, string ntid) Line 81	C#
 	App.dll!Controllers.UserClaimsController.GetCurrent() Line 37	C#
 	[External Code]	
>	App.dll!Startup.Configure.AnonymousMethod__8_0(Microsoft.AspNetCore.Http.HttpContext context, System.Func<System.Threading.Tasks.Task> next) Line 190	C#
```
I'm not sure why it is calling the OnConfiguring method, rather than using what is configured in ConfigureServices (and getting pulled from user.secrets and appsettings.json.
But, it I add **TrustServerCertificate=true** it works properly.

I don't know why I'm seeing this on Win11 and my coworker isn't on Win10, wondering if we might be on a different version of VS2022...

**Comment by JRahnama** [comment]
@awdorrin it seems like this is related to different setup on different machine and does not have anything to do with SqlClient.
