### ISSUE TITLE
TdsParser.ProcessSSPI in NetCore uses ArrayPool.Shared.Rent which might return an non zero-initialized array

### ISSUE THREAD

**Issue by stuka120** [dotnet/SqlClient#2441]
### Describe the bug
TdsParser for NetCore uses ArrayPool.Shared.Rent(...) which might return an non-zero-initialized array.
https://github.com/dotnet/SqlClient/blob/faf9b95995e6200a980bb6b1980f1d7af9f46cef/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParser.cs#L8654-L8683

The first bytes of that array are then replaced with the [negTokenResp](https://www.rfc-editor.org/rfc/rfc4178).

But as the array has some bytes set from the beginning, there might be some additional data after the actual negTokenResp, which causes the MIT-krb5 implementation to fail with a DEFECTIVE-TOKEN [here](https://github.com/krb5/krb5/blob/krb5-1.20/src/lib/gssapi/spnego/spnego_mech.c#L3731).

```
Exception message:
Cannot authenticate using Kerberos. Ensure Kerberos has been initialized on the client with 'kinit' and a Service Principal Name has been registered for the SQL Server to allow Kerberos authentication.\nErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error - Invalid token was supplied (Unknown error).\n  

Stack trace:
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)\n  
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)\n  
   at Microsoft.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[][] serverName)\n  
   at Microsoft.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[][] _sniSpnBuffer)\n  
   at Microsoft.Data.SqlClient.TdsParser.SSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
```

### To reproduce
I'm using an application with multiple connection-strings which - for testing purposes - queries the database very often, afterwards it invokes `SqlConnection.ClearAllPools();`. And this is done in an endless loop -> This causes the client to establish new security-contexts heavily which causes the error to appear.

### Expected behavior
Only the negTokenResp bytes are sent to the underlying GSSAPI implementation

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: (e.g. .NET6)
SQL Server version: Microsoft SQL Server 2019 
Operating system: aspnet:7.0-bookworm-slim

**Additional context**

I event tried the latest debian distro, but there the latest krb5 version is 1.20 which still does that check. In 1.21 they kind of revamped that check, but it's not available for debian as it stands now.

**Comment by vonzshik** [comment]
The problem is in `GenerateSspiClientContext`, which while does receive the size of the array (`receivedLength`), but completely ignores it.

https://github.com/dotnet/SqlClient/blob/faf9b95995e6200a980bb6b1980f1d7af9f46cef/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/TdsParserStateObjectManaged.cs#L392-L414

**Comment by stuka120** [comment]
If we need to respect the actual size of the negTokenResp, which is available in `receivedLength`, does it then make sense to use the `ArrayPool.Shared.Rent(...)` mechanism at all? 

Maybe a `byte[] receivedBuff = new byte[receivedLength];`, like it has been done in the old [System.Data.SqlClient#TdsParser](https://github.com/microsoft/referencesource/blob/master/System.Data/fx/src/data/System/Data/SqlClient/TdsParser.cs#L7550-L7569) would be a better fit here?

**Comment by JRahnama** [comment]
PR #2447 is under review to solve this issue.
