### ISSUE TITLE
SqlClient throws an exception but executing Sql in SSMS does not

### ISSUE THREAD

**Issue by kvattikuti** [dotnet/SqlClient#2463]
Trying to execute MERGE...OUTPUT...INTO on a table with triggers in c# using SqlClient 5.4.0 even though INTO is used. 
Sql Server version is 2017.

This same SQL snippet works totally fine when executed on sql prompt like in SSMS (Sql Server Management Studio) but fails with an exception when executed with SqlClient in .net 6:

`Microsoft.Data.SqlClient.SqlException: 'The target table 't' of the DML statement cannot have any enabled triggers if the statement contains an OUTPUT clause without INTO clause.'`

Here is the snippet of sql that I run with `ExecuteReaderAsync()`:
```
DECLARE @MergeResults TABLE (CorrelationId INT, IDCountry INT);
MERGE Countries AS t
USING
( SELECT * FROM ( VALUES (0,@Country0,@Currency0,@CurrencyCode0,@GLCountryCode0,@GLCountryCode20,@IDTypeOfCurrency0),(1,@Country1,@Currency1,@CurrencyCode1,@GLCountryCode1,@GLCountryCode21,@IDTypeOfCurrency1) ) AS Source ( CorrelationId,Country,Currency,CurrencyCode,GLCountryCode,GLCountryCode2,IDTypeOfCurrency ) ) AS s
ON 1 = 0
WHEN NOT MATCHED THEN
INSERT ( Country,Currency,CurrencyCode,GLCountryCode,GLCountryCode2,IDTypeOfCurrency )
VALUES ( s.Country,s.Currency,s.CurrencyCode,s.GLCountryCode,s.GLCountryCode2,s.IDTypeOfCurrency )
OUTPUT s.CorrelationId,INSERTED.IDCountry
INTO @MergeResults;
SELECT * FROM @MergeResults;
```

Any thoughts what could be the reason?

**Comment by roji** [comment]
I'd double-check that you're executing the exact same SQL against the same table in the same database; if your table has a trigger defined on it, the above SQL should fail regardless of where/how you execute it.

**Comment by kvattikuti** [comment]
Thank you for the response. You are right, I was being stupid. It was mix up of my test code.
