### ISSUE TITLE
SQL Client Upgrade from 5.1.1 to 5.1.2 or Later Causes Selenium Tests to Run Slower

### ISSUE THREAD

**Issue by johncrodriguez96** [dotnet/SqlClient#2481]
### Describe the bug
Our team has narrowed down the reason for our build timeouts to this newer version of SQL Client.
Below are images of tests with timestamps related to this package.

v5.1.1 - Before upgrading
![image](https://github.com/dotnet/SqlClient/assets/168847756/ebc8962a-4c41-4d4c-9126-e17d43582297)

v5.1.2 - After upgrading
![image](https://github.com/dotnet/SqlClient/assets/168847756/5440857b-8d2a-4a69-9342-6f149bca4c07)

After a second run of the same tests, the time looks so much better. Could there be something being cached?
![image](https://github.com/dotnet/SqlClient/assets/168847756/c0332b3a-83ea-4ccc-8001-4a88a93ff15c)

### To reproduce
This is how our test SQL Connections are constructed. We use Selenium for unit testing. Below shows the SqlConnectionStringBuilder:
```c#
		var sqlConnectionStringBuilder = new SqlConnectionStringBuilder
		{
			DataSource = ".",
			InitialCatalog = nameOfSccServer,
			Encrypt = true,
			MultipleActiveResultSets = false,
			PersistSecurityInfo = false,
			TrustServerCertificate = true,
			ConnectTimeout = 30
		};

```
Here are more timestamps taken using dotTrace. It's a tool that shows the call stack made during a test run along with time stamps.
Below shows the call DbConnectionPool.TryGetConnection is much slower in the newer package
![image](https://github.com/dotnet/SqlClient/assets/168847756/7a793707-273e-46b4-8da8-e0b73e146e08)

### Expected behavior
The time results from the second run is what would be expected.

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: net8.0
SQL Server version: SQL Server 15.0.2101.7
Operating system: Windows 11 Pro Version 22H2

**Comment by roji** [comment]
Likely a dup of https://github.com/dotnet/efcore/issues/33399 (caused by #1983). The mitigation will probably be #2433.

**Comment by JRahnama** [comment]
> Likely a dup of [dotnet/efcore#33399](https://github.com/dotnet/efcore/issues/33399) (caused by #1983). The mitigation will probably be #2433.

@roji, I am a bit confused. Do we need to revert #1983?

**Comment by roji** [comment]
@JRahnama I don't think so, I'm not sure what @kf-gonzalez2's reasoning is...

**Comment by ErikEJ** [comment]
Is it not a question of getting #2433 finished and approved?

**Comment by David-Engel** [comment]
The behavior change of #1983 was not intended in the 5.x line, particularly in the 5.1 backport. I consider it a breaking change. So the plan is to revert it in 5.x and bring it into 6.x where it will also include the connection override options to disable connection retries in order to maintain fast fail functionality.

**Comment by JRahnama** [comment]
Hotfix version 5.2.1 is released. Can you test with that version please?

**Comment by ajcvickers** [comment]
Verified that the EF regression is fixed in 4.2.1.

**Comment by ErikEJ** [comment]
@ajcvickers assume you mean 5.2.1 ?

**Comment by johncrodriguez96** [comment]
It seems to have been fixed now. Thanks everyone!
