### ISSUE TITLE
Proposal to streamline use of conditional compilation symbols

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#2484]
With the recent removal of NETSTANDARD support, these symbols in use can be simplified / rephrased:

!NETFRAMEWORK => NET6_0_OR_GREATER
!NET50_OR_LATER => NETFRAMEWORK
!NET6_0_OR_GREATER => NETFRAMEWORK
NET7_0_OR_GREATER => NET8_0_OR_GREATER
!NET7_0_OR_GREATER => !NET8_0_OR_GREATER
NETCOREAPP => NET6_0_OR_GREATER
net462 => NETFRAMEWORK

This will result in the following symbols being present in the code base:

NETFRAMEWORK
NET6_0_OR_GREATER
NET8_0_OR_GREATER

!NET8_0_OR_GREATER (can be removed later, when .NET 6 support is dropped)
NET6_0 (can be removed later, when .NET 6 support is dropped)

https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives#conditional-compilation

**Comment by ErikEJ** [comment]
@roji Wonder if these can be replaced? (Current targets are .NET 6 and .NET 8) 

NET7_0_OR_GREATER => NET8_0_OR_GREATER

!NET7_0_OR_GREATER  => !NET8_0_OR_GREATER

**Comment by roji** [comment]
@ErikEJ yeah, that makes sense... If net7.0 isn't being targeted (and it's just about to go out of support), then there's no reason to have NET7_0_OR_GREATER any more.

**Comment by ErikEJ** [comment]
Thanks, @roji , I have updated specs above accordingly
