### ISSUE TITLE
Microsoft.Data.SqlClient v 5.2.0: NET 8.0 assembly in NET 6.0 dll?

### ISSUE THREAD

**Issue by Thorium** [dotnet/SqlClient#2535]
I was debugging a few hours why I get weird "Microsoft.Data.SqlClient is not supported on this platform."

There is something fishy going on with the v5.2.0:

![image](https://github.com/dotnet/SqlClient/assets/229355/b6d61f26-b0df-45cf-a6ab-b55b7fbb21e4)

**Comment by Thorium** [comment]
This seems to be the case with the current version (5.2.1) too.

To reproduce the issue: 
1. Delete any Microsoft.Data.SqlClient from your .nugetcache, e.g. `C:\Users\(yourname)\.nuget\packages\microsoft.data.sqlclient`
2. Install ILSpy that can tell the file versions, `choco install ilspy`
3. Create a .net6.0 library: `dotnet new console --framework net6.0`
4. Add reference to download the nuget package: `dotnet add package Microsoft.Data.SqlClient`
5. Go to your nuget cache .net6.0 folder, e.g. `C:\Users\(yourname)\.nuget\packages\microsoft.data.sqlclient\5.2.1\lib\net6.0`
6. Open the `Microsoft.Data.SqlClient.dll` with ILSpy and observe it's .NET 8.0 version in .NET 6.0 path.

**Comment by JRahnama** [comment]
The issue was coming from the fact that .AssemblyAttributes was put in netcore folder under path of `SqlClient\artifacts\Project\obj\Debug.AnyCPU\Microsoft.Data.SqlClient\netcore` and that was used for net8 and net6 with Net8 version set as global. 

Thanks for catching this @Thorium. I will send you package from a build of our CI pipeline to confirm that the fix has worked.

**Comment by JRahnama** [comment]
@Thorium can you test below unofficial package to see if that has issue addressed in it.
[Microsoft.Data.SqlClient.6.0.0-pull.115703.zip](https://github.com/user-attachments/files/15594273/Microsoft.Data.SqlClient.6.0.0-pull.115703.zip)

**Comment by Thorium** [comment]
Yes, this package has it correct.

**Comment by kf-gonzalez2** [comment]
Closing as PR to fix this has been merged

**Comment by Miloky** [comment]
Having the same issue with .net8 and azure-functions on the azure portal. 
 Any ideas how to fix this?

**Comment by JRahnama** [comment]
@Miloky what version of M.D.SqlClient are you using?

**Comment by Miloky** [comment]
@JRahnama tried different versions:
6.0.0-preview1.24240.8
5.2.0
5.1.3

**Comment by JRahnama** [comment]
5.2.0,  and 5.1.3 are problamtic ones, try testing with 5.1.6 and 5.2.2. I will check 6.0.0-preview1.24240.8

**Comment by arellegue** [comment]
@Miloky The original issue has been addressed, confirmed as working, and backported to version 5.2.2. If your issue is different from this one, please open a new GitHub issue with detailed steps to reproduce it. Thank you!
