### ISSUE TITLE
Blow-up of memory consumption after upgrade from 5.2.0 to 5.2.1

### ISSUE THREAD

**Issue by JiriZidek** [dotnet/SqlClient#2558]
### Describe the bug
We upgraded nuget package from V5.2.0 to V5.2.1 and our app **doubled memory consumption**, moreover steady memory ramp-up observed signalling some memory leak started to appear.  After reverting nuget back to V5.2.0 bad behavior disappeared. 
No Exceptions observed.

**V5.2.1 - 1GB of RAM** - notice two strange jumps just after startup (.net8+EF8)
![image](https://github.com/dotnet/SqlClient/assets/8578952/0ba8fb82-e63e-4db1-8bbf-3e357fa1a8fe)

**V5.2.0 - 450MG of RAM** - this is absolutely same code, just nuget reference changed; this is healthy, memory consumption fits well with our longer time observations (now .net8+EF8, it used to be .net7+EF7)
![image](https://github.com/dotnet/SqlClient/assets/8578952/3e045545-ce52-4333-b6bb-f26d4285cffd)

### To reproduce
We use it in multiple modules and it looks like some of our modules are more impacted, some of them less. No simple way to reproduce it by hand.

### Expected behavior
Newer version should not exhibit much more of consumption then previous one.

### Further technical details
Found on the nuget or Microsoft.Data.SqlClient.dll V5.2.1
.NET target: 8.0.6
SQL Server version: Azure Sql
Operating system: container image mcr.microsoft.com/dotnet/aspnet:8.0 (and mcr.microsoft.com/dotnet/runtime:8.0 as well) - i.e. Debian.
Same problem appear when run on Windows10 locally against MS SQL 2019.

**Additional context**
Application uses heavily Microsoft.EntityFrameworkCore 8.0.6 with Microsoft.EntityFrameworkCore.SqlServer 8.0.6. We keep this version of EF in the test above.
Our app is also able to run against Postgres using Npgsql 8.0.3 and Npgsql.EntityFrameworkCore.PostgreSQ 8.0.4 and there is no such memory consumption.
Our app is pure sync in terms of DB access - so **it does not use** cnx.OpenaAsync, ctx.ToListAsync or ctx.SaveAsync.

**Profiling**
We made profiling in VS2022 and we observed some strange data:
![image](https://github.com/dotnet/SqlClient/assets/8578952/35a0b92d-35e9-46c2-8020-6b33eabea0af)

Heap seen by GC (profiler) takes only 76MB:
![image](https://github.com/dotnet/SqlClient/assets/8578952/770c67b4-6db4-425c-8a5a-56b9c0fb8707)
In same time the consumption in TaskManager in Windows: Active Private Working Set = 1GB.

(From this we dare to guess the problem might be in leaking some unmanaged memory.)

**Comment by ErikEJ** [comment]
https://github.com/dotnet/SqlClient/projects/19 - list of all related changes. How does your connection string look?

**Comment by dauinsight** [comment]
Hi @JiriZidek, we'll take a closer look at each of our changes to see where the spike might have occurred.

**Comment by JiriZidek** [comment]
> Hi @JiriZidek, we'll take a closer look at each of our changes to see where the spike might have occurred.

If you let me know what, I can do more investigation when the app is running in VS 2022 Enterprise.

**Comment by JRahnama** [comment]
@JiriZidek that would be nice if you can look into memory dump and see what parts are being flagged for memory leak and other related stuff.

Also try collecting [EventSource](https://learn.microsoft.com/en-us/sql/connect/ado-net/enable-eventsource-tracing?view=sql-server-ver16) traces, we might be able to see some useful data in it.

**Comment by JiriZidek** [comment]
How would you do "memory dump and see what parts are being flagged for memory leak" ? In VS ? (Excuse my ignorance.)

I used PerfView to collect some data on starting the app - it is some 160MB of data. What is best way to send you this data?

**Comment by cheenamalhotra** [comment]
Wondering is this issue still occurring with the latest v5.2.2 or v6.0-preview1?

**Comment by JiriZidek** [comment]
> Wondering is this issue still occurring with the latest v5.2.2 or v6.0-preview1?

I'll give it a try (5.2.2) and let you know. Since there is no benefit of using 5.2.1 or 5.2.2 we kept using 5.2.0.

**Comment by JiriZidek** [comment]
Trivial tests do not show this problem on 5.2.2 - I'll keep watching it for few days and if 5.2.2 is flwaless I'll close this issue.

**Comment by JiriZidek** [comment]
On 5.2.2 problem no longer appears, closing.
