### ISSUE TITLE
Improve SqlBulkCopy truncation error message

### ISSUE THREAD

**Issue by Suchiman** [dotnet/SqlClient#256]
### Is your feature request related to a problem? Please describe.
When you try to BulkCopy a too large string, you receive following error from [here](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBulkCopy.cs#L1676):
```
System.InvalidOperationException: String or binary data would be truncated.
```
This message is "faked" by the managed code to look like the message sql server sends.
A year ago, this message is now available in an [improved form](https://blogs.msdn.microsoft.com/sql_server_team/string-or-binary-data-would-be-truncated-replacing-the-infamous-error-8152/), at least if the exception is actually thrown by MSSQL.

### Describe the solution you'd like
Please make similiar improvements (column and value affected) to the managed exception.

### Describe alternatives you've considered
If you can attach a debugger, you can enable first chance exception breaking for `InvalidOperationException`, then you'll see the string that was too long when you look in the locals window of the throwing stack frame. But this is only applicable when you can debug it.

**Comment by Wraith2** [comment]
>  then you'll see the string that was too long when you look in the locals window of the throwing stack

Can you see fhe field definition it was supposed to be put in? and by seeing it do you mean that you as a problem solving human recognise it as invalid or that all the information is present for a dumb computer to report it as you ask? If so it sounds like it would be easy enough to change.

**Comment by Suchiman** [comment]
Yes it seems everything is there, `object value` contains the string and `metadata.column` contains the column name. MaxLength is available as `metadata.length / 2`
