### ISSUE TITLE
1.0.19269.1 does not define RegisterColumnEncryptionKeyStoreProviders

### ISSUE THREAD

**Issue by cperras** [dotnet/SqlClient#257]
### Describe the bug

i checkout out tag 1.0.19269.1
i see RegisterColumnEncryptionKeyStoreProviders defined
however, my dotnet core project, which references

"Microsoft.Data.SqlClient" Version="1.0.19269.1"

does not resolve this method, and decompiling shows it is missing many other methods. i didn't see any obvious compiler switches, #if blocks, etc in the code.

i cleared the VS cache (.vs directory), and rebuilt cleanly. this is from the SqlConnection metadata

#region Assembly Microsoft.Data.SqlClient, Version=1.0.19269.1, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5
// C:\Users\cperras\.nuget\packages\microsoft.data.sqlclient\1.0.19269.1\ref\netstandard2.0\Microsoft.Data.SqlClient.dll
// Decompiled with ICSharpCode.Decompiler 4.0.0.4285
#endregion

**Comment by cheenamalhotra** [comment]
> // C:\Users\cperras.nuget\packages\microsoft.data.sqlclient\1.0.19269.1\ref\netstandard2.0\Microsoft.Data.SqlClient.dll

The reason why this happened is because "RegisterColumnEncryptionKeyStoreProviders" is defined only for netcore here: https://github.com/dotnet/SqlClient/blob/c8b60fc389ab01b7affeed673b634993d3179bfc/src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.NetCoreApp.cs#L93 

Probably all Always Encrypted feature implementation classes are exposed only in NetCore and not applicable to NetStandard.

**Comment by cperras** [comment]
thanks for the quick response. my project is dotnet core 2.1.

what's the difference between netcore, netstandard? i think netfx is clear.

**Comment by cheenamalhotra** [comment]
.NET Standard is a specification for implementing the BCL. It doesn't implement it itself and hence doesn't support many explicit driver features. .NET Core and .NET Fx are full frameworks as we know and they in turn implement .NET Standard.

.NET Core 2.1 should work normally for you, ensure your application targets netcore correctly:
```
<TargetFramework>netcoreapp2.1</TargetFramework>
```

Your project should load DLL from this path: `~\microsoft.data.sqlclient\1.0.19269.1\ref\netcoreapp2.1\Microsoft.Data.SqlClient.dll` which should contain desired APIs.

**Comment by cperras** [comment]
thanks! in the meantime, i found the underlying issue (aside from my app target) is open:
https://github.com/dotnet/SqlClient/issues/111
