### ISSUE TITLE
Remove ref reference to System.Security.Cryptography.Cng

### ISSUE THREAD

**Issue by David-Engel** [dotnet/SqlClient#2574]
After removing support for .NET Standard, references to System.Security.Cryptography.Cng were removed but one was left in the ref project:

https://github.com/dotnet/SqlClient/blob/689cc257fa250d42728c5d240b888b1f151cfd7c/src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj#L21

This should be removed.

Once done, #2048 can be closed.

**Comment by ErikEJ** [comment]
@David-Engel I will have a look
