### ISSUE TITLE
Missing Key, Value in Nuget.config on `System.Data.SqlClient` to `Microsoft.Data.SqlClient` porting cheat sheet 

### ISSUE THREAD

**Issue by eilonik** [dotnet/SqlClient#2647]
### Describe the bug
Hello,
I'm following the cheat sheet to migrate from [`System.Data.SqlClient` to `Microsoft.Data.SqlClient`](https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md), and after adding the required [configuration](https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md#configuration) and building I'm getting the following error messages:
```
Exception message:

Build FAILED.

C:\Program Files\dotnet\sdk\8.0.300\NuGet.targets(694,5): error : Unable to parse config file because: Missing required attribute 'key' in element 'add'.
```

And

```
C:\Program Files\dotnet\sdk\8.0.300\NuGet.targets(694,5): error : Unable to parse config file because: Missing required attribute 'value' in element 'add'.
```

Adding random key and value properties solved this issue. is there a specific `key: value` pair that needs to be used in this case?

**Comment by ErikEJ** [comment]
@eilonik Please share the FULL config file and .csproj file. The configuration file changes are for .NET Framework projects, not .NET 8

**Comment by cheenamalhotra** [comment]
Closing as stale
