### ISSUE TITLE
Mention that it supports SQL Server AND Azure SQL

### ISSUE THREAD

**Issue by yorek** [dotnet/SqlClient#265]
Documentation say that "Microsoft.Data.SqlClient is a data provider for Microsoft Sql Server." I would suggest to also explicity mention Azure SQL. Especially new developers how never used SQL Server in the past may not know that Azure SQL is (almost) SQL Server.

**Comment by ErikEJ** [comment]
Is the official product name not: "Azure SQL Database" ?

**Comment by yorek** [comment]
That's right :)
