### ISSUE TITLE
API Proposal: JSON support: SqlDbTypeExtensions for SqlDbType 

### ISSUE THREAD

**Issue by saurabh500** [dotnet/SqlClient#2668]
# Problem statement

`System.Data.SqlDbType` lives in .Net Runtime repo and .Net framework. 

.Net Runtime can evolve, however any changes made to SqlDbType will require the applications to be built on top of the version of .Net runtime, where SqlDbType enum has been added.

In .Net Framework, the enahancement of `SqlDbType` is not possible.

All other ADO.Net drivers ship their own equivalent of `SqlDbType`.

# SqlDbType usage

Look through the code on Github, as well as code in some internal repositories, the pattern of usage of SqlDbType involve

1. SqlDbType is a parameter to a function.
2. The function takes decisions on the value of SqlDbType parameter using `if/else` blocks or with `switch/case` statements. This is also true for the internals of SqlClient where `SqlDbType` is being honored. 

## Path forward
We need to be able to provide a strong typed value of `SqlDbType` which the applications can use to pass around.

# Solution: Strong typed value of `SqlDbType` 

We can take advantage of the fact that there is a defined integer value backing SqlDbType to build a solution

## Proposal

Add `SqlDbTypeExtensions` with the new Enum values added in `System.Data.SqlDbType` 
An application which cannot upgrade to new runtime versions, can use the class as described below

The API would be `SqlDbType SqlDbTypeExtensions.Json` 

Implementation on runtimes which are lagging behind .Net runtime with the enhanced SqlDbType
```C#
 /// <summary>
 /// Extensions for SqlDbType enum.
 /// </summary>
 public static class SqlDbTypeExtensions
 {
     /// <summary>
     /// Represents the JSON Data type in SQL Server.
     /// </summary>
     public const SqlDbType Json = (SqlDbType)35;
 }
```

Implemenatation on runtimes which are at par with .Net runtime

```C#
/// <summary>
/// Extensions for SqlDbType enum.
/// </summary>
public static class SqlDbTypeExtensions
{
    /// <summary>
    /// Represents the JSON Data type in SQL Server.
    /// </summary>
    public const SqlDbType Json = SqlDbType.Json;
}
```

If an application built on runtime which doesn't support SqlDbType.Json takes a dependency on `SqlDbTypeExtensions.Json`. 
The same application when migrated to a version of runtime, with `SqlDbType.Json` support, will continue to work. And hence migration from one runtime version to another is a possibility without code changes.

The migrated application can also to move to `SqlDbType.Json` on newer runtime versions. 
The applications which begin with .Net runtime supporting `SqlDbType.Json` can continue to use `SqlDbType` out of the box. 

## Future datatypes
Assuming that there is a new type called `MyMadeUpType` which needs to be supported.
In that case the `SqlDbType` in dotnet/runtime will be modified, and the enum value will be decided. Lets say that we use `36` as the enum value for `MyMadeUpType`. 

```C#
enum SqlDbType {
 ...
  MyMadeUpType = 36;
}
```

```C#
 /// <summary>
 /// Extensions for SqlDbType enum.
 /// </summary>
 public static class SqlDbTypeExtensions
 {
     /// <summary>
     /// Represents the JSON Data type in SQL Server.
     /// </summary>
     public const SqlDbType Json = (SqlDbType)35;
     
     public const SqlDbType MyMadeUpType = (SqlDbType)36;
 }
```

Implemenatation of `SqlDbTypeExtensions` in MDS for runtimes which are at par with .Net runtime

```C#
/// <summary>
/// Extensions for SqlDbType enum.
/// </summary>
public static class SqlDbTypeExtensions
{
    /// <summary>
    /// Represents the JSON Data type in SQL Server.
    /// </summary>
    public const SqlDbType Json = SqlDbType.Json;
    
    public const SqlDbType MyMadeUpType = SqlDbType.MyMadeUpType;
}
```

This change allows MDS to evolve with new data types, faster than dotnet/runtime and provide value to customers who have not yet upgraded to the newer versions of the runtime. 

# Alternatives considered

We considered duplicating `SqlDbType` to say `Microsoft.Data.SqlDbType2` and copy over the values. But this requires many new APIs in `SqlParameter` (constructors and properties, `ResetSqlDbType` ), `SqlParameterCollection` , `SqlMetaData` to be introduced, along with code changes in the internals of the driver to account for SqlDbType and SqlDbType2. 
This also causes confusion around the guidance for the usage of `SqlDbType` and `SqlDbType2` since `SqlDbType` will anyhow be enhanced in dotnet/runtime.

**Comment by saurabh500** [comment]
cc @roji  @uc-msft @David-Engel  @cheenamalhotra  @apoorvdeshmukh  @deepaksa1

**Comment by saurabh500** [comment]
Also @ErikEJ

**Comment by roji** [comment]
Nice idea… Another possible way here, is to introduce a SqlDbType2, but to have an implicit cast operator, that converts it to SqlDbType; this would obviate having to add all the APIs into SqlClient, in order to directly support the new enum type.

**Comment by saurabh500** [comment]
@roji yeah, that is the alternative we considered. The cost of implementation and the confusion around explaining `SqlDbType2` was a lot. I have added a blurb about this in the last section of the issue. I had written down a gist describing how I envision `SqlDbType2` 
Also took a shot at implementing this, to cost the changes. The blast radius was quite big for this change
