### ISSUE TITLE
Thread Exhaustion suspect

### ISSUE THREAD

**Issue by deaklasECB** [dotnet/SqlClient#2712]
### Describe the bug

We run into thread exhaustion, and we see many threads (hundreds) are standing on this method `OpenAsyncRetry.Retry`

Stacktrace:

Hundreds of threads stand here:
```
Thread (0x1FD2):
  [Native Frames]
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.SqlConnection+OpenAsyncRetry.Retry(class System.Threading.Tasks.Task`1<class Microsoft.Data.ProviderBase.DbConnectionInternal>)
  System.Private.CoreLib!System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(class System.Threading.Thread,class System.Threading.ExecutionContext,class System.Threading.ContextCallback,class System.Object)
  System.Private.CoreLib!System.Threading.Tasks.Task.ExecuteWithThreadLocal(class System.Threading.Tasks.Task&,class System.Threading.Thread)
  System.Private.CoreLib!System.Threading.ThreadPoolWorkQueue.Dispatch()
  System.Private.CoreLib!System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
```

One thread stands here:

```
  [Native Frames]
  System.Private.CoreLib!System.Threading.WaitHandle.WaitOneNoCheck(int32)
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.SqlConnection.Close()
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.SqlConnection.OnError(class Microsoft.Data.SqlClient.SqlException,bool,class System.Action`1<class System.Action>)
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(class Microsoft.Data.SqlClient.TdsParserStateObject,class Microsoft.Data.SqlClient.SqlCommand,bool,bool)
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.TdsParser.TryRun(value class Microsoft.Data.SqlClient.RunBehavior,class Microsoft.Data.SqlClient.SqlCommand,class Microsoft.Data.SqlClient.SqlDataReader,class Microsoft.Data.SqlClient.BulkCopySimpleResultSet,class Microsoft.Data.SqlClient.TdsParserStateObject,bool&)
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(class System.String,bool,int32,bool)
  Microsoft.Data.SqlClient!Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
```

### To reproduce

We don't have a stable way trigger this behavior, but once it enters the number of connections to AzureSQL grows steadily.
It seems to happen to one or another instance of a service at a time.

### Expected behavior
Threads not standing on Retry

### Further technical details
Microsoft.Data.SqlClient version: 5.2.1 - we updated from 5.1.5 a week ago
.NET target: .NET 8
SQL Server version: AzureSQL
Operating system: Linux/Docker

### Questions:

1. Would like to get suggestions on how to investigate the issue further, and what steps could be done to potentially mitigate the issue?
2. Is it possible that the close and the other threads in a deadlock?

**Comment by cheenamalhotra** [comment]
@deaklasECB 

Is this happening only with 5.2.0+ or this has been an issue with earlier versions as well?
Are there any other variables post upgrade like increased workload on your application or target framework version?

**Comment by deaklasECB** [comment]
I have never seen it happening with earlier versions. There was one additional error that was experienced around the same time: the Azure SQL DB "ran out of workers".

- There is no significant change in the amount of DB requests that the application makes.
- No target framework change.
- No OS change.

**Comment by deaklasECB** [comment]
@cheenamalhotra could running out of workers cause this?

**Comment by cheenamalhotra** [comment]
That explains it.

If Azure SQL DB is unable to process client requests, it's possible client app is also exhausted because all the open connections are trying to recover and reconnect.

Do you know what caused this worker exhaustion on the server side?

**Comment by deaklasECB** [comment]
The client connection count was not exhausted.

Not sure what caused the exhaustion on the DB server side, that is still being investigated.

However, that many threads were seems to be waiting on the `SqlConnection.Close()` and even after the issue, they did not complete. They seem to have got into a deadlock. Is there a timeout setting / close connection timeout that could be specified.

**Comment by cheenamalhotra** [comment]
> Is there a timeout setting / close connection timeout that could be specified that could be set to avoid the deadlock?

There is no such setting available.

**Comment by cheenamalhotra** [comment]
Closing as there's no pending action for driver team.
