### ISSUE TITLE
JSON Support : Investigate and update the conversion matrix used by smi and make sure that warning in the code is satisfied

### ISSUE THREAD

**Issue by apoorvdeshmukh** [dotnet/SqlClient#2733]
Investigate and update the conversion matrix used by smi and make sure that this warning in the code is satisfied
https://github.com/dotnet/SqlClient/blob/0c4519871c9b69f7e05fe90f59d224d5f9ab3e3e/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs#L2698-L2704

The CI runs on Release builds so the CI will not save you from violating assertions in this project.

You will probably need the sql server team to define the extensions to the conversion operations tables that start at https://github.com/dotnet/SqlClient/blob/0c4519871c9b69f7e05fe90f59d224d5f9ab3e3e/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Server/ValueUtilsSmi.cs#L2920
I suspect that json to binary might be the only conversion but someone needs to make that decision.

_Originally posted by @Wraith2 in https://github.com/dotnet/SqlClient/issues/2722#issuecomment-2253665811_

**Comment by cheenamalhotra** [comment]
Given the plan to remove Context Connection and SMI related codebase in https://github.com/dotnet/SqlClient/issues/2838#issuecomment-2465838258, I believe this may no longer be applicable. Please reopen if needed.
