### ISSUE TITLE
Support config.json for SqlClientX test suite

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#2736]
As our test suites are advancing and require server setup for testing, we need to ensure server credentials can be passed to tests via config.json file.

Recommended approach: 
Take dependency on the same common project "TestUtilities" to fetch configuration that is also used by Manual Tests.

**Comment by saurabh500** [comment]
We also need an issue to enhance the Client X CI to deploy/or point to some SQL server that we can leverage for E2E
