### ISSUE TITLE
Add a NuGet package README to distinguish and inform consumers on each SQLClient package

### ISSUE THREAD

**Issue by JonDouglas** [dotnet/SqlClient#2764]
I was reading through this tweet in which consumers weren't aware of the differences of System/Microsoft packages:

https://x.com/terrajobst/status/1821683056115376129

https://github.com/dotnet/SqlClient/issues/1963

We recently have added README functionality to NuGet.org and soon you will be able to view these READMEs in your favorite IDE/editor experience as well like Visual Studio & VS Code.

It may be worth adding package READMEs to both packages for their next update to describe these packages further and what scenarios one should use them with. Here's a blog with more information on this:

https://devblogs.microsoft.com/nuget/write-a-high-quality-readme-for-nuget-packages/

**Comment by arellegue** [comment]
Thank you for raising the issue that consumers of Microsoft.Data.SqlClient package might not be aware of the differences of System/Microsoft packages.

The [porting-cheat-sheet](https://github.com/dotnet/SqlClient/blob/main/porting-cheat-sheet.md) from System.Data.SqlClient to Microsoft.Data.SqlClient should help to introduce the difference between the two packages.  This cheat-sheet is already referenced in the README.

**Comment by JRahnama** [comment]
@JonDouglas I've been considering this. Thank you for bringing it up. I will test it to see how it works. I’m fairly certain that snupkg files (pdbs) do not include READMEs, but at least the nupkg package will have that feature.

**Comment by JRahnama** [comment]
@JonDouglas to add more we can only do this on Microsoft.Data.SqlClient

**Comment by JonDouglas** [comment]
You should be able to use the old README experience for the older package and use the new one for packages that are actively built!
