### ISSUE TITLE
Package Dependency Azure.Identity with Moderate Vulnerability

### ISSUE THREAD

**Issue by vermiceli** [dotnet/SqlClient#2787]
### Describe the bug
Similar to #2195, `Azure.Identity` version 1.11.3 has a "at least one vulnerability with moderate severity."  `Microsoft.Data.SqlClient` as of 5.2.1 [references 1.11.3](https://github.com/dotnet/SqlClient/blob/main/release-notes/5.2/5.2.1.md#changed).

### To reproduce
Create a project and reference `Microsoft.Data.SqlClient`.  You'll see errors in the error window

> Warning As Error: Package 'Azure.Identity' 1.11.3 has a known moderate severity vulnerability, https://github.com/advisories/GHSA-m5vv-6r4h-3vj9

### Expected behavior
No references to packages with moderate severity vulnerabilities.

### Further technical details
Microsoft.Data.SqlClient version: 5.2.1
.NET target: .NET 8
SQL Server version: N/A
Operating system: Windows

**Additional context**
N/A

**Comment by dauinsight** [comment]
@vermiceli there will be a new release before the end of the month to address this: https://github.com/dotnet/SqlClient/issues/2568
