### ISSUE TITLE
Azure SQL: Microsoft.Data.SqlClient - Invalid value for key 'authentication'

### ISSUE THREAD

**Issue by techsaau** [dotnet/SqlClient#2853]
### Describe the bug
I'm trying to connect to Azure SQL Database with "Active Directory Service Principal", It failed with below error:

But Same code works fine with "Active Directory Password" mode.

```
Error Message:
   Assembly Initialization method XXXX.UnitTest.SqlDatabaseSetup.InitializeAssembly threw exception. System.ArgumentException: System.ArgumentException: Invalid value for key 'authentication'.. Aborting test execution.
  Stack Trace:
      at System.Data.Common.DbConnectionStringBuilderUtil.ConvertToAuthenticationType(String keyword, Object value)
   at System.Data.SqlClient.SqlConnectionStringBuilder.ConvertToAuthenticationType(String keyword, Object value)
   at System.Data.SqlClient.SqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at System.Data.SqlClient.SqlConnectionStringBuilder..ctor(String connectionString)
   at Microsoft.Data.Tools.Schema.Sql.UnitTesting.Common.SqlConnectionStringSecurer.RestoreConnectionString(String partialConnection)
   at Microsoft.Data.Tools.Schema.Sql.UnitTesting.SqlDatabaseTestService.DecryptConnectionString(String connectionString)
   at Microsoft.Data.Tools.Schema.Sql.UnitTesting.SqlDatabaseTestService.SetupConnectionString(String connStr)
   at Microsoft.Data.Tools.Schema.Sql.UnitTesting.SqlDatabaseTestService.DeployDatabaseProject()
   at XXXX.UnitTest.SqlDatabaseSetup.InitializeAssembly(TestContext ctx) in C:\Data\Agent\_work\316\s\XXXX.UnitTest\SqlDatabaseSetup.cs:line 23
```

### To reproduce
Below is the app.config file:

```c#
<PrivilegedContext Provider="Microsoft.Data.SqlClient" ConnectionString="Server=.database.windows.net;Authentication=Active Directory Service Principal; Encrypt=True; Database=-dbname; User Id={appID}; Password={secret}" CommandTimeout="3000" />
```

### Further technical details
Microsoft.Data.SqlClient version: 5.2.2
.NET target: 4.7.2
SQL Server version: Azure SQL Server

**Additional context**

**Comment by ErikEJ** [comment]
The call stack is from System.Data.SqlClient so this is expected.

**Comment by cheenamalhotra** [comment]
Does your using include 'System.Data.SqlClient' namespace? Have you tried converting them to 'Microsoft.Data.SqlClient' instead?

**Comment by techsaau** [comment]
@cheenamalhotra yes, I have replaced all the references from 'System.Data.SqlClient' to 'Microsoft.Data.SqlClient'. That's why it's bothering me.

But in project, primarily I use it in app.config only:

<ExecutionContext Provider="Microsoft.Data.SqlClient" ConnectionString="" />
<PrivilegedContext Provider="Microsoft.Data.SqlClient" ConnectionString="" />

**Comment by cheenamalhotra** [comment]
The error you're receiving is due to `System.Data.SqlClient` being in use, so you need to figure out why is that happening.

**Comment by edwardneal** [comment]
To expand on the point above: the stack trace indicates that it's being called directly by the [SqlDatabaseTestService](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.tools.schema.sql.unittesting.sqldatabasetestservice) class, which is part of the [SQL Server unit testing](https://learn.microsoft.com/en-us/sql/ssdt/walkthrough-creating-and-running-a-sql-server-unit-test) functionality in MSBuild/Visual Studio. Perhaps this functionality still uses System.Data.SqlClient by default? If so, using the [second overload](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.tools.schema.sql.unittesting.sqldatabasetestservice.deploydatabaseproject?view=sql-datatools-unittest-16#microsoft-data-tools-schema-sql-unittesting-sqldatabasetestservice-deploydatabaseproject(system-string-system-string-system-string-system-string)) of DeployDatabaseProject and specifying Microsoft.Data.SqlClient's provider name might help.

**Comment by arellegue** [comment]
@techsaau Have you tried the suggestion to use the second overload of DeployDatabaseProject and specifying Microsoft.Data.SqlClient's provider name?

**Comment by techsaau** [comment]
My main question would be, has anyone did unit testing with AAD SPN auth, using Microsoft.Data.SqlClient?

**Comment by techsaau** [comment]
So this is the sequence, current package versions:


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/nitinkalra/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/nitinkalra/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">


Package   Name | Version
-- | --
Azure.Core | 1.43.0
Microsoft.Data.SqlClient | 5.2.0
Microsoft.Identity.Client | 4.64.1



</body>

</html>




After running unit test, below is the sequence of errors after fixing them:

Microsoft.Data.SqlClient.SqlException: Could not load file or assembly 'Azure.Core, Version=1.40.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies

Azure.Core updated from 1.43 -> 1.40

Next Error:
Could not load file or assembly 'Microsoft.Identity.Client, Version=4.61.3.0, Culture=neutral, PublicKeyToken=0a613f4dd989e8ae' or one of its dependencies

Azure.Core updated from 4.64.1 -> 4.61.3

Next Error:
Microsoft.Data.SqlClient.SqlException: Could not load file or assembly 'Azure.Core, Version=1.38.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies



So, has anyone conducted unit test with Microsoft.Data.SqlClient?

**Comment by arellegue** [comment]
To investigate this issue further, could you provide a repro, please?

**Comment by techsaau** [comment]
After spending hell lot of time, this version thing was the issue:

![image](https://github.com/user-attachments/assets/cc37c7ac-a0f1-4fec-95ab-8af22af53582)


I have no clue, why it was complaining. Maybe some dependancy they have internally and giving incorrect errors earlier.

Thanks all.
