### ISSUE TITLE
Different behavior for Routing in netcore and netfx

### ISSUE THREAD

**Issue by JRahnama** [dotnet/SqlClient#2872]
There are two different behavior for Routing in SqlClient

in .Net inside [SqlInternalConnectionTds](https://github.com/dotnet/SqlClient/blob/3416ad92b9107d2618bc7ffdf1d595a86cf0e7d0/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L1561) we have 
```C#
if (routingAttempts > 0)
                        {
                            throw SQL.ROR_RecursiveRoutingNotSupported(this);
                        }
```
Where as the same place in [.NetFramework](https://github.com/dotnet/SqlClient/blob/3416ad92b9107d2618bc7ffdf1d595a86cf0e7d0/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L1886) we have

```C#
if (routingAttempts > _maxNumberOfRedirectRoute)
                        {
                            throw SQL.ROR_RecursiveRoutingNotSupported(this);
                        }
```

`_maxNumberOfRedirectRout` is 10

**Comment by David-Engel** [comment]
@JRahnama 

I noticed this a little while ago and looked into the history a bit. The max routing attempts changes was included as part of the Azure read only routing support changes in SDS netfx. I saved a branch of what I thought were the relevant changes required from bring everything from the netfx to the netcore MDS code: https://github.com/dotnet/SqlClient/compare/main...David-Engel:SqlClient:port?expand=1

**Comment by JRahnama** [comment]
> @JRahnama
> 
> I noticed this a little while ago and looked into the history a bit. The max routing attempts changes was included as part of the Azure read only routing support changes in SDS netfx. I saved a branch of what I thought were the relevant changes required from bring everything from the netfx to the netcore MDS code: https://github.com/dotnet/SqlClient/compare/main...David-Engel:SqlClient:port?expand=1

Thanks David, I have updated the PR #2873  with some extra changes and addressed some issues in your changes.
