### ISSUE TITLE
External links in documentation are relative

### ISSUE THREAD

**Issue by benrr101** [dotnet/SqlClient#2883]
**Description**: There are a lot of links in the XML documentation that point to web pages. I'm calling these "external links". However, the vast majority of them are links that are relative to the root of the documentation website (eg `<see href="/dotnet/framework/data/adonet/asynchronous-programming">Asynchronous Programming</see>`). In the context of the IDE, these links become meaningless since the IDE doesn't know where they should go. In my case, the IDE simply ignores them. This leaves a lot of documentation in the IDE that ends with `For more information see .`

**Solution**: Although this will warrant a small bit of research, I think if we just add the documentation website root to these links, we should solve the issue. This unfortunately adds a dependency on the root domain not changing, but we already depend on web links not changing, so this doesn't make it much worse.

**Comment by MichelZ** [comment]
Are you also interested in a PR that fixes links everywhere in code from msdn to learn.microsoft.com?
https://github.com/dotnet/SqlClient/commit/d682c2b529e1ff49cd7e154a1f7e884f45c14eb0
