### ISSUE TITLE
Does CommandTimeout only restrict the execution time of ExecuteReader() or also limit the time of GetName() and GetValue() ?

### ISSUE THREAD

**Issue by ycymio** [dotnet/SqlClient#2902]
We use synchronized way to read from sql server but we found some successful requests' latency of ExecuteReader() and reading from reader (`AppendObject()`) in client side is **much longer than the timeout**. `AppendObject()` only has one loop to read all the field names and values)

I saw the note in this [CommandTimeout property](https://learn.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlcommand.commandtimeout?view=netframework-4.8.1&redirectedfrom=MSDN#System_Data_SqlClient_SqlCommand_CommandTimeout), and it says the Timeout include all network reads during command execution or processing of the results. Could I simply think **ExecuteReader() + SqlDataReader's `GetName()` + SqlDataReader's `GetValue()` should be less than CommandTimeout**, otherwise it should throw exception?

The code we use is like below. 

```
                SqlCommand complexCommand = new SqlCommand(commandText, connection, transaction);
                complexCommand.CommandTimeout = CommandTimeout;
                if (parameters != null)
                {
                    complexCommand.Parameters.AddRange(parameters);
                }

                response.SetSQLObjectQuery(complexCommand.CommandText);
                var objectQueryExecutionStopWatch = Stopwatch.StartNew();

                using (SqlDataReader complexReader = complexCommand.ExecuteReader())
                {
                    if (complexReader != null)
                    {
                        while (complexReader.Read())
                        {
                            response.AppendObject(complexReader);
                        }
                    }
                }

                // objectQueryExecutionStopWatch.ElapsedMilliseconds sometimes is much larger than the CommandTimeout. 
                objectQueryExecutionStopWatch.Stop(); 
```

**Comment by David-Engel** [comment]
CommandTimeout applies independently to SqlCommand.Execute* and SqlDataReader.Read(). So in your sample code, you might get a timeout at `complexCommand.ExecuteReader()` if it exceeds CommandTimeout or if `complexReader.Read()` exceeds CommandTimeout. The time is not cumulative. Meaning each method call gets its own 30 seconds to complete.

The "all network reads" might be confusing but it related to any/all network reads within each method call. The majority of the time spent waiting for ExecuteReader() to return is spent waiting for the server to respond with the first packet of data. But for rows that don't fit into a single packet, there might be multiple packets coming in to complete each method. Hence the text in the doc note: "(for all network packets that are read _**during the invocation of a method**_)"

**Comment by ycymio** [comment]
Thanks a lot David! Your comment made the issue much clearer. :)

**Comment by ycymio** [comment]
Thanks a lot David! Your comment made the issue much clearer. :)
