### ISSUE TITLE
There seems to be a difference in the way Microsoft.Data.SqlClient treats Decimal values when compared to System.Data.SqlClient

### ISSUE THREAD

**Issue by Joel-VT** [dotnet/SqlClient#2905]
I have a .Net framework solution that runs a Chi Square test on a sql table and creates another sql table with its values. The P value that this test creates are Decimal values and the table that the program creates contains a column for it with Decimal(20,13) as its datatype.
Sometimes, the program calculates P values that have more than 13 decimal places but the value never exceeds the precision of 20. 
When this happens and my program inserts these values into the sql table, the value is just truncated after the 13th decimal place. 

Now I ported my solution to .Net Core and I started using Microsoft.Data.SqlClient instead of System.Data.SqlClient. Nothing else has changed in terms of the queries that the program runs. But what I'm noticing here is that in cases where there are more than 13 decimal places, the values are round up/down. Why is there a difference in the way decimal values are treated between the two packages? I tried finding any information on this online. If anyone could explain this, I'd really appreciate it.

I do know the default behavior of SQL server is to round values. But if that's the case, why doesn't it round when I'm using System.Data.SqlClient?

**Comment by cheenamalhotra** [comment]
You can enable old behaviour by setting this App Context Switch: 

`AppContext.SetSwitch("Switch.Microsoft.Data.SqlClient.TruncateScaledDecimal", true);`

More info: https://learn.microsoft.com/en-us/sql/connect/ado-net/appcontext-switches?view=sql-server-ver16#enabling-decimal-truncation-behavior

**Comment by Joel-VT** [comment]
This is exactly what I was looking for. Thanks, @cheenamalhotra.

**Comment by cheenamalhotra** [comment]
Closing as answered.
