### ISSUE TITLE
XUnit does not support public async void in next version

### ISSUE THREAD

**Issue by MichelZ** [dotnet/SqlClient#2947]
The next version of XUnit does not support `public async void` in test methods.
This should be changed to `public async Task`

https://dotnet.social/@xunit/112265523775265162

More recent versions of XUnit 2.x also issue a Warning - which gets treated as an Error in this project.

**Comment by Wraith2** [comment]
If you're working on tests is there any way you can make them work in visual studio? currently the netcore tests all fail because of missing sni. 
It'd also be really nice if the test conditions evaluated and worked correctly. They haven't for as long as i've worked on this library.

**Comment by MichelZ** [comment]
At least with current main it seems that I can run unit tests from VS Test Explorer:
![Image](https://github.com/user-attachments/assets/3cecda9c-1532-409c-9cfb-fb532bc22606)
