### ISSUE TITLE
Project dependency System.Memory does not contain in inclusive lower bound

### ISSUE THREAD

**Issue by MichelZ** [dotnet/SqlClient#2950]
My Visual Studio complains about this:

Error (active)	NU1604	Warning As Error: Project dependency System.Memory does not contain an inclusive lower bound. Include a lower bound in the dependency version to ensure consistent restore results.	Microsoft.Data.SqlClient (net462), Microsoft.Data.SqlClient (net6.0), Microsoft.Data.SqlClient (net8.0)	

And sure enough, here is there reference to System.Memory:
https://github.com/dotnet/SqlClient/blob/9d5ca32e666b3da1cc27b4ab145367308998b147/src/Microsoft.Data.SqlClient/src/Microsoft.Data.SqlClient.csproj#L12

But there is no corresponding version variable in Versions.props:
https://github.com/dotnet/SqlClient/blob/main/tools/props/Versions.props

I'm not 100% sure if the reference is needed or not, but a reference without a version is just wrong.

**Comment by benrr101** [comment]
You are correct, however this project is not meant to be built, yet. My suspicion is that nuget restore runs regardless of whether the project is mean to build in the current configuration. For the most part, this was a bit of leftover junk from a handful of PRs ago.
