### ISSUE TITLE
C++ Runtime Required

### ISSUE THREAD

**Issue by wjvii** [dotnet/SqlClient#296]
### Describe the bug
When installing our .NET Framework application on a new Windows 2012 server we started running into the error below after updating from System.Data.SqlClient to Microsoft.Data.SqlClient. The error gave no indication that the C++ runtime was required, but with the only other change of installing the C++ runtime from here:  https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads it started working.

```
Exception message: System.TypeInitializationException: The type initializer for 'Microsoft.Data.SqlClient.TdsParser' threw an exception.
```

### Expected behavior
I would prefer not to have to have this is a pre-requisite at all but if I do I would like the error message to be clear that is what is required.

### Further technical details
Microsoft.Data.SqlClient version: 1.0.19269.1
.NET target: (e.g. Framework 4.7.1
SQL Server version: (SQL Azure)
Operating system: (e.g. Windows 2012)

**Additional context**

**Comment by David-Engel** [comment]
@wjvii Thanks for filing the issue. We'll try and improve documentation about this requirement and perhaps update our NuGet package description to call this out.

**Comment by cheenamalhotra** [comment]
Closing as documentation added to be part of notes/specs.
