### ISSUE TITLE
Question: Is `Microsoft.Data.SqlClient` not souce code open source and is there some docs?

### ISSUE THREAD

**Issue by WeihanLi** [dotnet/SqlClient#3]
Is `Microsoft.Data.SqlClient` not souce code open source and is there some docs?

**Comment by WeihanLi** [comment]
find the answer in the wiki [here](https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions), sorry for this issue

**Comment by divega** [comment]
> sorry for this issue

No need to apologize. The fact that you care that is open source is good feedback!
