### ISSUE TITLE
Deploy machine: at runtime got System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.

### ISSUE THREAD

**Issue by starnutoditopo** [dotnet/SqlClient#302]
### Describe the bug
In an ASP.NET Core 3.0 project referencing the nuget package System.Data.SqlClient 4.7.0 I get an exception at runtime:

```
Exception message: System.Data.SqlClient is not supported on this platform.
Stack trace:
System.PlatformNotSupportedException: System.Data.SqlClient is not supported on this platform.
   at System.Data.SqlClient.SqlConnection..ctor(String connectionString)
   at ...
```

### To reproduce
```c#
SqlConnection connection = new SqlConnection(connectionString);
```

### Expected behavior
A connection to be created

### Further technical details
Microsoft.Data.SqlClient version: 4.7.0, from nuget
.NET target: Core 3.0
SQL Server version: SQL Server 10.0.1600
Operating system: Windows Server 2016

**Additional context**
Code runs fine from within Visual studio 2019 on development machine. Exception occurs on deployment machine.

**Comment by yukiwongky** [comment]
@starnutoditopo does your development machine have a different OS from the deployment machine? What are the OSes for the 2 machines?

**Comment by starnutoditopo** [comment]
I realized that the problem has a different nature and deals with the deployment process of .net core applications.
Basically, the situation is this:
The solution has two projects: Main and Dal.

- Main contains the application's entry point and an interface (let's say IDataService) defining the functionalities to retrieve and save data. It has NO reference to System.Data.SqlClient.
- Dal contains an implementation of IDataService. It DOES reference System.Data.SqlClient.

At build time, a post-build event copies the binaries of Dal into the folder of Main's binaries.

At runtime, Main loads all dlls containing implementations of services. In particular, it loads Dal.
So far, so good. The problem arises when Main attempts to invoke any method of the Dal implementation involving System.Data.SqlClient: here the System.PlatformNotSupportedException exception occurs.

So, it looks like some component of System.Data.SqlClient is missing at runtime.

That said, I explicitly added a reference to System.Data.SqlClient to the Main project and everything started to work properly.

So, definitely, I would like to avoid to reference the System.Data.SqlClient from the Main project (it should be unnecessary!). I'd like all runtime components of System.Data.SqlClient to be copied in the post-build event of Dal, instead.

Any suggestion to do the job?

thanks!

**Comment by starnutoditopo** [comment]
Digging some more, it turned out that the problem resides in the .deps.json file.
In practice, the Main's .deps.json file is missing probing information about System.Data.SqlClient dependencies.

**Comment by starnutoditopo** [comment]
I asked a question on Stackoverflow: see https://stackoverflow.com/q/58823302/1288109

**Comment by cheenamalhotra** [comment]
Hi @starnutoditopo 

Could you try this example in your environment and confirm?
I was able to run Main.dll that loads SqlClient from Dal.

[MainDalExample.zip](https://github.com/dotnet/SqlClient/files/3843709/MainDalExample.zip)

(Tested both System.Data.SqlClient and Microsoft.Data.SqlClient)

**Comment by starnutoditopo** [comment]
Hi!, @cheenamalhotra 

My situation is slightly different. Here I updated your code to reproduce the problem:
[MainDalExample.zip](https://github.com/dotnet/SqlClient/files/3845172/MainDalExample.zip)

I made the following changes:
 - removed the reference to System.Data.SqlClient from Main. Now only Dal contains that reference
 - removed the reference to Dal from Main
 - Defined the interface IDataService in Main
 - Added a Reference to Main in Dal
 - Added a propertygroup with `<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>` in Dal's project file (this outputs its dependencies to the output folder when building)
 - Added a post-build event in Dal, so that it's output is copied to the Main.
 - Changed code in Main

The idea is: Main defines an interface (IDataService) and, at runtime, it scans all available assemblies, looking for a type that implements IDataService. In this example, it instantiate the first type it finds that implements IDataService: DataService in assembly Dal. The idea is that the implementation should come from a pluggable dll (in this case, the data should come from SQL server, but in other implementation could come form a text file or something else).

If you run the code, you see that the DataService instance is correctly created.

When calling .GetData(), though, the "System.Data.SqlClient is not supported on this platform." exception occurs.

After some digging, I realized that the problem is not in the component itself, but in the way main.deps.json file is managed.

Adding a reference to System.Data.SqlClient in Main, produces a different main.deps.json file, with directives about how to load System.Data.SqlClient. Now you can perform this little experiment: keep the deps.json file just produced and remove the reference to System.Data.SqlClient from Main, compile and replace the deps.json file with the one you backed-up. Now run the code: it works!

Here are a working (.yes) and a non-working (.no) examples of those files for the Main project:
[netcoreapp2.1.zip](https://github.com/dotnet/SqlClient/files/3845314/netcoreapp2.1.zip)

So, as I reported in https://stackoverflow.com/q/58823302/1288109 , the workaround is to update the Main's deps.json file with a merge of all .deps.json of all dependencies.

**Comment by starnutoditopo** [comment]
Hi!

Looks the solution is here:

https://stackoverflow.com/a/58917235/1288109

**Comment by cheenamalhotra** [comment]
Sounds good. We’ll close the issue then!
