### ISSUE TITLE
update package with vulnerability

### ISSUE THREAD

**Issue by AmBplus** [dotnet/SqlClient#3053]
as show in bellow image , the version 5.2.0 has vulnerability , please update the packages to solve this problem

![Image](https://github.com/user-attachments/assets/68264333-b2f4-45d6-aa12-e5b51d177162)

**Comment by ErikEJ** [comment]
@AmBplus why are you nor using 5.2.2, where some vulnerable packages might have been updated?

**Comment by AmBplus** [comment]
@ErikEJ Updated To 5.2.2 and fixed , tnx
