### ISSUE TITLE
Distributed Transaction issue.

### ISSUE THREAD

**Issue by ksmith97** [dotnet/SqlClient#3064]
### Describe the bug
While using TransactionScope in an async context we are sporadically seeing this exception being thrown.  I have been unable to reproduce it running locally and am unsure how to track it down further.

It is running two queries across two databases on the same database server by using their qualified names.

```
System.PlatformNotSupportedException: This platform does not support distributed transactions.\n   at System.Transactions.Oletx.OletxTransactionManager.GetOletxTransactionFromTransmitterPropagationToken(Byte[] propagationToken)\n   at System.Transactions.TransactionInterop.GetOletxTransactionFromTransmitterPropagationToken(Byte[] propagationToken)\n   at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)\n   at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)\n   at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)\n   at System.Transactions.Transaction.Promote()\n   at System.Transactions.TransactionInterop.ConvertToOletxTransaction(Transaction transaction)\n   at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)\n   at Microsoft.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)\n   at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)\n   at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)\n   at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)\n   at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()\n--- End of stack trace from previous location ---\n   at Dapper.SqlMapper.QueryRowAsync[T](IDbConnection cnn, Row row, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 488\n   at InternalApiApp.Repository.Scorecard.HistoryRepository.InsertHistory(History obj) in /src/InternalApiApp/Repository/Scorecard/HistoryRepository.cs:line 38\n   at InternalApiApp.Services.Payment.ScorecardPaymentService.CreatePaymentOptionsRecord(PaymentOptions options) in /src/InternalApiApp/Services/Payment/ScorecardPaymentService.cs:line 33\n   at InternalApiApp.Controller.PaymentController.DispatchContext(CallbackParams callbackParams) in /src/InternalApiApp/Controller/PaymentController.cs:line 69\n   at InternalApiApp.Controller.PaymentController.Process(CallbackParams callbackParams) in /src/InternalApiApp/Controller/PaymentController.cs:line 60\n   at lambda_method10(Closure, Object)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)\n   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)\n   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)\n   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|10_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
```

### To reproduce
Unfortunately, I have not been able to reproduce this issue. When I run the container locally it does not occur and it happens seemingly at random in our production environment.

### Expected behavior
I expect it to work consistently

### Further technical details
Linux Container mcr.microsoft.com/dotnet/aspnet:8.0
Dotnet 8
Microsoft.Data.SqlClient 5.2.1
Dapper 2.1.35

SQL Server 2016

Sample pseudo code that mimics the code involved. Its not complicated.
```
using var txScope = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);

await repo.InsertObj1(obj);
await repo2.InsertObj2(obj2)

function async Task InsertObj1/2(obj)
       using var connection = new SqlConnection(connString);
       return await connection.QuerySingleAsync<int>(query, obj);

```

**Comment by roji** [comment]
.NET only supports distributed transactions on Linux, since it requires the MSDTC. See https://github.com/dotnet/runtime/issues/71769 for the issue tracking cross-platform distributed transactions on the .NET runtime side.

**Comment by roji** [comment]
If your intention is not to start a distributed transaction, you must make sure that you never have more than one connection open concurrently inside a TransactionScope; you likel have some case where you're (possibly accidentally) having two open connections.

**Comment by ksmith97** [comment]
Both of these queries are using the same connection string. The documentation claims that means since they are both in the same Transaction they should be the same connection.  Are you suggesting that hitting two different logical databases on the same server means it needs to be promoted to distributed? Even if thats true why does it work most of the time and only sporadically fail?

**Comment by roji** [comment]
> Are you suggesting that hitting two different logical databases on the same server means it needs to be promoted to distributed?

You haven't included much info above, so I can't be sure. But if you're connecting to two logical databases (in the sense that the connection string has two different databases), then absolultely - a distributed transaction is 100% expected; a regular (non-distributed) transaction can only be scoped to a single connection to a single database.

> Even if thats true why does it work most of the time and only sporadically fail? 

I have no idea because you haven't provided a minimal repro - just a partial code snippet - but I suspect you have some sort of issue there causing one of the connections to not be made, or for it to not be enlisted something. If you have two connection strings - each with a different database - within the same TransactionScope, then you should be seeing a 100% deterministic escalation to a distributed transaction.

**Comment by ksmith97** [comment]
@roji In my particular case I am not specifying the database in the connection string. My queries have the explicit database name involved in order for them to share the same connection string, which does allow them to share the same transaction. I don't believe that this transaction should have been elevated to a distributed one. The only reason for it to have done so is if the connection pool malfunctioned and returned a non transaction participating connection or if there is some other caveat to configuring things here that I missed. Since I can't produce it locally but am getting errors in our AWS logs it almost seems like it might be a runtime issue with the AWS environment the container runs in.

**Comment by roji** [comment]
> In my particular case I am not specifying the database in the connection string. My queries have the explicit database name involved in order for them to share the same connection string, which does allow them to share the same transaction.

I see. I'm not 100% sure about the SQL Server situation here - you may be right that it's possible for a local, non-distributed transaction to span multiple databases on the same server; that would explain why the problem doesn't reproduce reliably. But in that case it's very likely that at some point in your code you have two connections open somehow within the same TransactionScope... I'd recommend auditing your usage of connections very carefully - the stack trace for the PlatformNotSupportedException should provide some assistance for finding the problematic call site(s).
