### ISSUE TITLE
HTTP Proxy 

### ISSUE THREAD

**Issue by fowl2** [dotnet/SqlClient#315]
### Is your feature request related to a problem? Please describe.
Corporate network requires all outgoing network traffic to run through a HTTP proxy. Therefore accessing eg. Azure SQL from inside the corporate network is impossible. 

Primarily a concern for DBAs trying to do admin/migration tasks, but can also see how it would help thick client applications trying to move to the cloud.

### Describe the solution you'd like
`SqlClient` to be able to connect to SQL Server via a HTTP proxy.

Strawman connection strings: 
* `HttpProxy=http://user:pass@proxy:port/` - same format as `HTTP_PROXY` environment variable
* `HttpProxy=System` - read environment variable/registry etc.
* `HttpProxy=SystemWithDefaultCredentials` - same as above but authenticate as current user

Could be separated into multiple keys, not sure what the "done thing" is.

I think just automatically using the system proxy settings would be too invasive. 

### Describe alternatives you've considered
* `hosts` file trickery and local proxy software. (eg. WinGate)
* There are a few products on the market the use code injection to redirect connections.  (eg. 'ProxyCap')
* Changing corporate network design (ahahah)
* Moving clients off corporate network (not always possible)

**Comment by Wraith2** [comment]
> Corporate network requires all outgoing network traffic to run through a HTTP proxy.

That seems like a policy problem and not something that needs a technical solution. Adding tunnelling would be added complexity in the library and the only purpose would be to evade an annoying security practice.

**Comment by saurabh500** [comment]
HTTP is a stateless protocol and Sql server supports TDS protocol which is a completely stateful protocol. 
If this is done on the client side, keeping all the APIs the same and not changing the existing protocol, there will be a lot of caching needed on the client side to convert stateless protocol requests into stateful protocol. Also the performance will be terrible.

I am closing this issue since this is not something we will attempt to do as it is fundamentally a change to the way SqlClient and TDS protocol has been designed. 

Azure SQL DB now supports VNets which can be utilized by the corporate networking team to isolate the Azure SQL DB network as well.

**Comment by fowl2** [comment]
HTTP proxies support the [CONNECT method](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/CONNECT), which is analogous to and almost functionally identical to a TCP connection. 

There are no protocol changes required. As I said, this works today through some inconvenient hacks.

**Comment by saurabh500** [comment]
> HTTP proxies support the CONNECT method, which is analogous to and almost functionally identical to a TCP connection.

I didn't realize this is what you were referring to. Thanks for the link.

This capability should not be implemented in a client driver. What you are asking here is a way to build in *ONE* of  possibly many mechanisms to bypass the network requirements. There could be someone else who wants to work around this by opening an SSH tunnel using the client driver itself which opens up possibilities of trying to solve problems in client driver which it was never intended to solve. These mechanisms shouldn't be built into the client driver itself. 

You use your tunneling mechanism and tunnel SQL payload through the tunneling mechanism you want to use. 

I am sorry to hear that your corporate network access is designed in a way that it makes it hard for a DBA to access the database they are expected to take care of. 
But if there is another system which needs to be accessed, which doesn't support HTTP protocol, then this problem multiplies at your organization's level. It is not feasible to change clients across the board to fix such policy related issues.
