### ISSUE TITLE
Table value parameters in Microsoft.Data.SqlClient

### ISSUE THREAD

**Issue by MarkPflug** [dotnet/SqlClient#323]
### Table value parameters 

I've historically used table valued parameter to bulk insert data into SqlServer databases. The approach that I've used doesn't seem to work against Microsoft.Data.SqlClient. The same code (different `using` statements) compiles against System.Data.SqlClient (SDS) and Microsoft.Data.SqlClient (MDS), but when run against MDS it throws an exception trying to invoke a command that uses a `SqlDbType.Structured` parameter with a value of `IEnumerable<Microsoft.SqlServer.Server.SqlDataRecord>`. 

```
Exception message:
   Failed to convert parameter value from a <GetDataRecords>d__1 to a IEnumerable`1.
Stack trace:
   at Microsoft.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   at Microsoft.Data.SqlClient.SqlParameter.GetCoercedValue()
   at Microsoft.Data.SqlClient.SqlParameter.Validate(Int32 index, Boolean isCommandProc)
   at Microsoft.Data.SqlClient.SqlCommand.SetUpRPCParameters(_SqlRPC rpc, Int32 startCount, Boolean inSchema, SqlParameterCollection parameters)
   at Microsoft.Data.SqlClient.SqlCommand.BuildRPC(Boolean inSchema, SqlParameterCollection parameters, _SqlRPC& rpc)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at Program.Main() in C:\Users\Mark\source\SqlTvpTest\SqlTvpTest\Program.cs:line 53
```

### To reproduce

Clone https://github.com/MarkPflug/SqlTvpTest

The solution has two configurations: one to run against SDS and one to run against MDS. The SDS configuration works, and the MDS configuration produces an exception.

Note, that the code will expect a running sql server instance on the local machine, and will create a new database in it to operate against.

### Expected behavior
I guess I don't know if this is expected to be supported or not. However, if this particular approach 
of using TVPs is *not* supported, I'd like to know if there is a supported workaround. Preferably one that would work against both SDS and MDS.

### Further technical details
Microsoft.Data.SqlClient version: nuget 1.1.0
.NET target: netcoreapp3.0
SQL Server version: 14.0.2027.2 (developer)
Operating system: Windows 10 (1903)

**Comment by cheenamalhotra** [comment]
Hi @MarkPflug 

You need to use below classes with **Microsoft.Data.SqlClient**:
- `Microsoft.Data.SqlClient.Server.SqlDataRecord`
- `Microsoft.Data.SqlClient.Server.SqlMetaData`

**Comment by cheenamalhotra** [comment]
Also to add, your comment in the repro provided also needs correction:

```xml
<!-- this reference is needed by both configurations, because SqlDataRecord is forwarded to it in the Microsoft.Data.SqlClient-->
<PackageReference Include="System.Data.SqlClient" Version="4.7.0" />
```

You can use `Microsoft.Data.SqlClient.Server.SqlDataRecord` from **Microsoft.Data.SqlClient** itself and need not need additional reference to **System.Data.SqlClient**.

**Comment by MarkPflug** [comment]
Thanks. That fixed it.

I think I was thrown off, because without the `using Microsoft.Data.SqlClient.Server;` statement, the MDS configuration will produce the following error:

```
The type name 'SqlDataRecord' could not be found in the namespace 'Microsoft.SqlServer.Server'. This type has been forwarded to assembly 'System.Data.SqlClient, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.
```

Where is this coming from? System.Data.dll in `ProgramFiles/dotnet/shared/Microsoft.NETCore.App/3.0.0` reports this type as forwarded:
`[assembly: TypeForwardedTo(typeof(SqlDataRecord))]`. I'm assuming it is forwarded to `System.Data.SqlClient`, to which `System.Data` has a reported reference (ilspy doesn't make that clear). However, there is no System.Data.SqlClient in the shared framework, so where is System.Data.SqlClient 4.6.0 supposed to come from? It seems *really* strange to me that the shared framework would forward a type to a nuget package. Is that what's happening here?

**Comment by cheenamalhotra** [comment]
Hi @MarkPflug 

Please check you might be having `using Microsoft.SqlServer.Server;` declared in imports. Removing that rightly suggests importing `SqlDataRecord` from `Microsoft.Data.SqlClient.Server`.

**Comment by MarkPflug** [comment]
Indeed, I have that `using` statement. This is because I was trying to port code from SDS to MDS, and there was no indication that the `Microsoft.SqlServer.Server` namespace was moved to `Microsoft.Data.SqlClient.Server`. Why was it necessary to move that ns, and if it was moved, why not dump everything into `Microsoft.Data.SqlClient` so that it would be more obvious that those types had moved. Honestly, the `Server` sub-ns doesn't really mean anything to me. What does "Server" have to do with SqlDataRecord? I understand at this point that nothing can be done about it, but I want you to understand how this ns choice makes it easy to fall into this error when porting code that uses these types.

Anyway, thanks for the help in figuring this out. Much appreciated.

**Comment by cheenamalhotra** [comment]
You're welcome!

In order to highlight the namespace changes better, we're considering to document the same in a guideline to port from System.Data.SqlClient to Microsoft.Data.SqlClient.

**Comment by jzabroski** [comment]
> Hi [@MarkPflug](https://github.com/MarkPflug)
> 
> You need to use below classes with **Microsoft.Data.SqlClient**:
> 
> * `Microsoft.Data.SqlClient.Server.SqlDataRecord`
> * `Microsoft.Data.SqlClient.Server.SqlMetaData`
> 
> The namespace `Microsoft.SqlServer.Server` also needs to change to `Microsoft.Data.SqlClient.Server`

System.Data.SqlClient tells us erroneously to use "Microsoft.SqlServer.Server.SqlDataRecord" in the obsolete warning.
