### ISSUE TITLE
Intellisense tooltip for SqlCommand's CommandTimeout doesn't describe units

### ISSUE THREAD

**Issue by netdragonboberb** [dotnet/SqlClient#33]
The Visual Studio tooltip for SqlCommand.CommandTimeout doesn't say whether units are seconds or milliseconds.The tooltip says "Gets or sets the wait time before terminating the attempt to execute a command and generating an error."

[MSDN](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqlcommand.commandtimeout(v=vs.110).aspx) has a bettter description: "The time in seconds to wait for the command to execute. The default is 30 seconds."

**Comment by cheenamalhotra** [comment]
Hi @netdragonboberb 

PR #243 shall update the tooltip and documentation as requested.
Just to let you know, starting with Microsoft.Data.SqlClient [1.1.0-preview1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.0-preview1.19275.1) we now support Intellisense for both .NET Framework and .NET Core for this driver.

**Comment by cheenamalhotra** [comment]
Closing issue as PR #243 has been merged and fix shall be available in 1.1.0-preview2 release.
