### ISSUE TITLE
SQLCommandBuilder.DeriveParameters() having trouble with StoredProc Parameters of Type XML

### ISSUE THREAD

**Issue by ChristianSchieder** [dotnet/SqlClient#342]
Hi there,

we recently moved from .Net-core 2.1 to 3.0 and have experienced and issue regarding the DeriveParameters-Method when the stored procedure contains a parameter of type XML.

Here the link to some small reproduction code:
https://github.com/ChristianSchieder/SqlDataClient_TestApp

**Comment by ChristianSchieder** [comment]
Any kind of update/feedback on this issue would be great.

**Comment by JRahnama** [comment]
Hi @ChristianSchieder ,

I was able to repro the problem using System.Data.SqlClient. The issue started on System.Data.SqlClient 4.7.0-preview4.19212.13 and it lasted up to 4.8.0-preview1.19504.10. If you update the package to any version greater or equal to 4.8.0-preview1.19504.10 you won't see the exception. I have also tested the repro on Microsoft.Data.SqlClient and it worked fine. Please test the suggested fix and inform us that we can close the issue.

**Comment by ChristianSchieder** [comment]
Hi @JRahnama ,

thank you for your awnser, i will test that by tomorrow and will let you know if it worked.

**Comment by cheenamalhotra** [comment]
I believe this PR https://github.com/dotnet/corefx/pull/41008 fixed the issue.

**Comment by Wraith2** [comment]
I went through the repro provided and turned it into a test. It doesn't fail on latest M.D.SqlClient, it's likely the issue that @cheenamalhotra pointed out. So if you have this problem please upgrade to one of the supported S.D.SqlClient versions with the fix which @JRahnama identifies as 4.8.0-preview1.19504.10 or later and it should resolve the issue.
