### ISSUE TITLE
Support for SQL CE 3.5

### ISSUE THREAD

**Issue by aaron-pedigo-eii** [dotnet/SqlClient#386]
When porting code to a .NET Core 3 project, VS suggested installing Microsoft.SqlServer.Compact to help resolve SqlCeConnection. When trying to load my CE 3.5 file, I got a message mentioning that it cannot find an ADO.NET provider of version 8876. Google searching has led me to believe that is CE 4. Is there any way to load CE 3.5 files in .NET Core 3?

**Comment by cheenamalhotra** [comment]
Hi @aaron-pedigo-eii 

Looks like the product you're looking for is no longer in support, the only support available is Extended Support for [SQL Server Compact 4.0](https://support.microsoft.com/en-us/lifecycle/search/16106), that applies to MS premium/paid customers.

However, this repository is for SqlClient drivers (Microsoft.Data.SqlClient and System.Data.SqlClient) support only. Please reach out to Microsoft support for more details.
