### ISSUE TITLE
MS SSAS and SSIS connectivity for netstandard (Adomd, Amo etc. netstandard libraries )

### ISSUE THREAD

**Issue by voltcode** [dotnet/SqlClient#387]
### Is your feature request related to a problem? Please describe.
Lack of netstandard / net core connectivity to MS SQL Analysis Services.

Original issue reported at https://github.com/dotnet/corefx/issues/37563
As per @danmosemsft - I'm reporting it here.

### Describe the solution you'd like
a xplatform net core version of Adomd and AMO libraries.

### Describe alternatives you've considered
There is no real alternative for connecting to SSAS. 

### Additional context
You can find much more about the context in https://github.com/dotnet/corefx/issues/37563

**Comment by cheenamalhotra** [comment]
Hi @voltcode 

This repository is for SqlClient driver support and we take care of SQL Server connectivity only, not SSAS or SSIS. The original issue in CoreFx shall be the best place to discuss further on the same.

**Comment by danmosemsft** [comment]
sorry @voltcode I sent you to the wrong place. now I know 😄
