### ISSUE TITLE
NET Core 3 Always Encrypted

### ISSUE THREAD

**Issue by OnamChilwan** [dotnet/SqlClient#390]
I am getting the following error when using .NET Core 3.1 and SQL Always Encrypted. Is this supported in 3.1? Perhaps I am missing something here..

Keyword not supported: 'column encryption setting'.
Currently have the following packages installed

    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.12.0" />
    <PackageReference Include="Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include="Dapper" Version="2.0.30" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Design" Version="2.2.0" PrivateAssets="All" />
    <PackageReference Include="Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider" Version="1.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureKeyVault" Version="3.1.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="3.2.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />

**Comment by cheenamalhotra** [comment]
Hi @OnamChilwan 

I don't see a reference of "Microsoft.Data.SqlClient" in your list of packages, please add the same:
`<PackageReference Include="Microsoft.Data.SqlClient" Version="1.1.0" />`

and ensure you're using "Microsoft.Data.SqlClient" namespace and not "System.Data.SqlClient".

**Comment by OnamChilwan** [comment]
@cheenamalhotra thank you I'll give it a try and report back

**Comment by OnamChilwan** [comment]
@cheenamalhotra that works a treat thank you. The namespace stung me, was using `System.Data.SqlClient` and I didn't have that package installed.

Thanks.
