### ISSUE TITLE
GenerateResourceStringsSource.targets fails with project folders containing spaces

### ISSUE THREAD

**Issue by MrAnderson69UK** [dotnet/SqlClient#402]
### Describe the bug
After cloning the repo and setting my VS 2019 env. as per buildguide.md, starting VS to restore NuGet packages, I can't build due to creating the repo folder with a space char. 

**src/Microsoft.Data.SqlClient/netfx/tools/targets/GenerateResourceStringsSource.targets** needs single Quotes encapsulation of the command being invoked by powershell.exe ($(NetFxSource)tools\scripts\GenerateResourceStringsSource.ps1).

' < Exec Command="powershell.exe -NonInteractive -executionpolicy Unrestricted ^
-command &quot;&amp; **'$(NetFxSource)tools\scripts\GenerateResourceStringsSource.ps1'** -ResxFileDir '$(NetFxResources)' -ResxFileName '$(ResxFileName)' -OutputPath '$(IntermediateOutputPath)' -GeneratedSourceFileName '$(GeneratedSourceFileName)' &quot;" />'

Output excerpt from point at which 'msbuild' failed and not the summary at the end of build. 'msbuild' was run from the solution folder as per instructions.

```
GenerateResourceStringsSource:
  powershell.exe -NonInteractive -executionpolicy Unrestricted ^
        -command "& C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\tools\scripts\GenerateResourceStringsSource.ps1 -ResxFileDir 'C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\src\Resources\' -ResxFileName 'Strings' -OutputPath 'C:\Code\OurCompanyName .NET
  Microsoft.Data.SqlClient\src\..\obj\Debug.AnyCPU\Microsoft.Data.SqlClient\netfx\' -GeneratedSourceFileName 'Strings.ResourceNames.cs' "
  & : The term 'C:\Code\OurCompanyName' is not recognized as the name of a cmdlet, function, script file, or operable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  At line:1 char:3
  + & C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.Sql ...
  +   ~~~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (C:\Code\OurCompanyName:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException

C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\tools\targets\GenerateResourceStringsSource.targets(4,7): error MSB3073: The command "powershell.exe -NonInteractive -executionpolicy Unrestricted ^ [C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\src\M
icrosoft.Data.SqlClient.csproj]
C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\tools\targets\GenerateResourceStringsSource.targets(4,7): error MSB3073:       -command "& C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\tools\scripts\GenerateResourceStringsSource.ps1 -ResxFileDir 'C:
\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\src\Resources\' -ResxFileName 'Strings' -OutputPath 'C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\obj\Debug.AnyCPU\Microsoft.Data.SqlClient\netfx\' -GeneratedSourceFileName 'Strings.ResourceNames.cs' "" exited with code 1. [C:\Cod
e\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\src\Microsoft.Data.SqlClient.csproj]
Done Building Project "C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\Microsoft.Data.SqlClient\netfx\src\Microsoft.Data.SqlClient.csproj" (default targets) -- FAILED.

```

### To reproduce
Simply download/clone repo to a folder containing a space character, configure VS with 2017 or 2019 as per BUILDGUIDE.md and build default

### Expected behavior
Build to succeed and create Strings.ResourceName.cs in C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\obj\Debug.AnyCPU\Microsoft.Data.SqlClient\netfx

### Further technical details
Microsoft.Data.SqlClient version: 2.0.0-preview1 (27-01-2020 #398 was the last update to the branch)

**Comment by cheenamalhotra** [comment]
Closing - as cannot be fully supported, refer comments in related issue #403
