### ISSUE TITLE
GenerateNugetPackage.targets errors with project folders containing spaces

### ISSUE THREAD

**Issue by MrAnderson69UK** [dotnet/SqlClient#403]
### Describe the bug
Continuing work after raising bug #402, I set the project to generate the NuGet package. This failed also - it would seem as it invoked command downloadLatestNuget.ps1, it failed due to the project path containing spaces. The actual NuGet package was created but not from using the latest NuGet application.

Output excerpt from point at which 'msbuild' failed and not the summary at the end of build. 'msbuild' was run from the solution folder as per instructions.

```
GenerateNugetPackage:
  Setting NugetPackageVersion to 2.0.0-dev
  powershell.exe -NonInteractive -executionpolicy Unrestricted ^
        -command "&C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\tools\scripts\downloadLatestNuget.ps1 -nugetDestPath 'C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\.nuget\'"
  & : The term 'C:\Code\OurCompanyName .NET' is not recognized as the name of a cmdlet, function, script file, or operable program.
  Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
  At line:1 char:2
  + &C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\tools\scripts\downloadL ...
  +  ~~~~~~~~~~~~
      + CategoryInfo          : ObjectNotFound: (C:\Code\OurCompanyName:String) [], CommandNotFoundException
      + FullyQualifiedErrorId : CommandNotFoundException

C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\tools\targets\GenerateNugetPackage.targets(8,5): error MSB3073: The command "powershell.exe -NonInteractive -executionpolicy Unrestricted ^ [C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\build.proj]
C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\tools\targets\GenerateNugetPackage.targets(8,5): error MSB3073:       -command "&C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\tools\scripts\downloadLatestNuget.ps1 -nugetDestPath 'C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\src\..\.nuget\'"" exited with code 1. [C:\Code\OurCompanyName .NET Microso
ft.Data.SqlClient\build.proj]
Done Building Project "C:\Code\OurCompanyName .NET Microsoft.Data.SqlClient\build.proj" (default targets) -- FAILED.
```

### To reproduce
Simply download/clone repo to a folder containing a space character, configure VS with 2017 or 2019 as per BUILDGUIDE.md, enable the Microsoft.Data.SqlClient project to generate the package in VS proj settings and build default

### Expected behavior
Build to succeed without error

### Further technical details
Microsoft.Data.SqlClient version: 2.0.0-preview1 (27-01-2020 #398 was the last update to the branch)
A local fix for #402 has no effect as it's a different script, but maybe all .target files should be checked to ensure they support project folders with spaces.

**Comment by cheenamalhotra** [comment]
@MrAnderson69UK 

We could fix both issues but in the end NuGet.exe doesn't support space in paths, when we pack with nuspec. Turns out this issue was opened with NuGet team, but they didn't fix it yet.

Refer: https://github.com/NuGet/Home/issues/1818

**Comment by MrAnderson69UK** [comment]
Thanks for the quick reply, it probably explains why the fix for encapsulating the powershell command in the .target file only fixed the first call of getting the latest nuget! The actual call to nuget to generate the package also failed - for the reason you mentioned.

Don't worry too much with an alternative, I'll rename my project base folder as everything is relative from there. I seem to remember having to do this for a nuget package I created for an API I was using in multiple projects. I just did the rename as a quick change to fix another script and didn't realise it also fixed the package gen.!

Thanks again, feel free to close the issue, but if NuGet do fix #1818 then these will need fixing at some point, depends on the demand, but probably good practice to avoid spaces in the first place!!! ;)

**Comment by MrAnderson69UK** [comment]
...having said that, the followon errors I was seeing and skim-read as I'd seen your reply, were network/permission related - our IT have given us an administrative user account to do elevated permission changes and I was running msbuild from an Admin Cmd and so the user profile wasn't my dev account and the shared profile area wasn't used - not sure if thats a windows thing or something out IT created - I don't recall creating the shared profile!
All good though with normal user and spaceless folder name! Thanks

**Comment by cheenamalhotra** [comment]
Thanks @MrAnderson69UK 

I tried and would like to fix it if I could, but Nuget.exe doesn't load files from Nuspec as well if their path contains spaces, seems like another issue there.

Closing this as an external limitation.
