### ISSUE TITLE
Bug: Are Spatial Types like Geometry and Geography supported?

### ISSUE THREAD

**Issue by mikependon** [dotnet/SqlClient#415]
I tried to fully switch from System.Data.SqlClient to Microsoft.Data.SqlClient and I am getting a NULL response when calling the DbDataReader.GetFieldType(ordinal) method.

Where, the ordinal corresponds to the index of any of the columns with Data Types (Geography or Spatial) from the database.

To the extent, my tests are failing with the following information below.

**The weird thing is, why the *System.Data.SqlClient* is in the picture of the exception?**

I only referenced the *Microsoft.Data.SqlClient* and have no references at *System.Data.SqlClient*.

Please advise and thanks.

**Stack Trace:**

```
 TestBaseRepositorySpatialsCrud
   Source: BaseRepositorySpatialsTest.cs line 39
   Duration: 959 ms

  Message: 
    Test method RepoDb.IntegrationTests.Types.Spatials.BaseRepositorySpatialsTest.TestBaseRepositorySpatialsCrud threw exception: 
    System.IO.FileNotFoundException: Could not load file or assembly '_System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a_'. The system cannot find the file specified.
  Stack Trace: 
    RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
    RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
    TypeNameParser.ResolveType(Assembly assembly, String[] names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
    SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow) line 1870
    SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData) line 2778
    SqlDataReader.GetValue(Int32 i) line 2668
    lambda_method(Closure , DbDataReader )
    DataReader.ToEnumerable[TEntity](DbDataReader reader, IDbConnection connection, IDbTransaction transaction)+MoveNext() line 36
    List`1.AddEnumerable(IEnumerable`1 enumerable)
    Enumerable.ToList[TSource](IEnumerable`1 source)
    EnumerableExtension.AsList[T](IEnumerable`1 value) line 71
    DbConnectionExtension.ExecuteQueryInternal[TEntity](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction, Boolean skipCommandArrayParametersCheck) line 324
    DbConnectionExtension.QueryInternalBase[TEntity](IDbConnection connection, IEnumerable`1 fields, QueryGroup where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Int32 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder) line 1220
    DbConnectionExtension.QueryInternal[TEntity](IDbConnection connection, QueryGroup where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Int32 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder) line 294
    DbConnectionExtension.Query[TEntity](IDbConnection connection, QueryGroup where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Int32 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder) line 246
    DbConnectionExtension.Query[TEntity](IDbConnection connection, Expression`1 where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Int32 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder) line 198
    DbRepository`1.Query[TEntity](Expression`1 where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, IDbTransaction transaction) line 97
    BaseRepository`2.Query(Expression`1 where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, IDbTransaction transaction) line 64
    BaseRepositorySpatialsTest.TestBaseRepositorySpatialsCrud() line 55
```

**Comment by cheenamalhotra** [comment]
Hi @mikependon 

Please explain the nature of your application, is it .NET Framework?
Also confirm did you cover all namespace changes when transitioning, as documented here: [porting-cheat-sheet](https://github.com/dotnet/SqlClient/blob/master/porting-cheat-sheet.md)

**Comment by mikependon** [comment]
Hi, I have revisited the cheat sheet and it seems all necessary changes for the namespaces were covered by my changes. The version is on .NET Standard 2.0. Basically, the existing working Integration Tests of my ORM library is not working when I completely changed all the references from *System.Data.SqlClient* and to *Microsoft.Data.SqlClient*.

I have give up debugging it due to its weird loading of *System.Data.SqlClient*.

**Comment by cheenamalhotra** [comment]
Could you verify your tests don't reference any old NuGet packages related to System.Data.SqlClient as well?

Maybe you can list your test dependencies loaded in test runtime that we can look into?

**Comment by mikependon** [comment]
Here is my current solution that is failing.

Btw, when I tried to reference back the *System.Data.SqlClient*, the exception has changed to a conversion problem (Convertible Exception) (ie: _SqlHeirarchyId to IBinarySerializer_ and _SqlGeography to IBinarySerializer_ etc).

![image](https://user-images.githubusercontent.com/591015/74191968-e586c500-4c54-11ea-9d01-d5151996a670.png)

**Comment by mikependon** [comment]
The exception is:

```csharp
 TestSqlConnectionOthersCrudAsync
   Source: SqlConnectionOthersTest.cs line 149
   Duration: 17 ms

  Message: 
    Test method RepoDb.IntegrationTests.Types.Others.SqlConnectionOthersTest.TestSqlConnectionOthersCrudAsync threw exception: 
    System.AggregateException: One or more errors occurred. (Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.) ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
  Stack Trace: 
    RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive)
    RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
    TypeNameParser.ResolveType(Assembly assembly, String[] names, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    TypeNameParser.ConstructType(Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    TypeNameParser.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
    Type.GetType(String typeName, Func`2 assemblyResolver, Func`4 typeResolver, Boolean throwOnError)
    SqlConnection.CheckGetExtendedUDTInfo(SqlMetaDataPriv metaData, Boolean fThrow) line 1870
    SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData) line 2778
    SqlDataReader.GetValue(Int32 i) line 2668
    lambda_method(Closure , DbDataReader )
    DataReader.ToEnumerableAsync[TEntity](DbDataReader reader, IDbConnection connection, IDbTransaction transaction) line 66
    DbConnectionExtension.ExecuteQueryAsyncInternal[TEntity](IDbConnection connection, String commandText, Object param, Nullable`1 commandType, Nullable`1 commandTimeout, IDbTransaction transaction, Boolean skipCommandArrayParametersCheck) line 408
    DbConnectionExtension.QueryAsyncInternalBase[TEntity](IDbConnection connection, IEnumerable`1 fields, QueryGroup where, IEnumerable`1 orderBy, Nullable`1 top, String hints, String cacheKey, Int32 cacheItemExpiration, Nullable`1 commandTimeout, IDbTransaction transaction, ICache cache, ITrace trace, IStatementBuilder statementBuilder) line 1336
    --- End of inner exception stack trace ---
    Task`1.GetResultCore(Boolean waitCompletionNotification)
    SqlConnectionOthersTest.TestSqlConnectionOthersCrudAsync() line 169
```

**Comment by cheenamalhotra** [comment]
Interesting!

That does lead to a possibility of your tests referencing System.Data.SqlClient or related types. 
Mostly I would expect problems when your tests reference classes from **Microsoft.SqlServer.Server** namespace as we changed ours to **Microsoft.Data.SqlClient.Server** namespace to avoid clash, as also mentioned to _porting-cheat-sheet_ attached above.

I see you're working on RepoDb, could you provide me link me to your branch where you have your app changes and some basic scripts to reproduce the problem, if you may allow me to review those?

**Comment by mikependon** [comment]
You are welcome to do so examining RepoDb branches, however just last night I have resumed the support to *System.Data.SqlClient*. So my *Core* library is now again referencing that librart.

After doing that, my tests are still using *Microsoft.Data.SqlClient* and the exception has changed to *Conversion* problem. The problem only occurs to Spatials type.

Please allow me to reproduce it in a very few lines of codes so you guys can debug it. Thanks for the attention on this.

**Comment by cheenamalhotra** [comment]
A clean standalone repro would be ideal :)

**Comment by cheenamalhotra** [comment]
Hi @mikependon 

Just checking in, do you still need support on this issue?

**Comment by mikependon** [comment]
Please have a look at [here](https://github.com/mikependon/SqlClient/tree/master/Issue415). My first issue was actually replicated here.

**Comment by mikependon** [comment]
Now, without doing anything, just create a DB which is also attached on the solution. Then maybe fix the ConnectionString and simply run the solution.

**I am targeting 3 problems here.**

You will encounter this problem.

![image](https://user-images.githubusercontent.com/591015/74583061-6a5e3f80-4fc3-11ea-84e1-e5dd17b56a85.png)

Then, install the Microsoft.SqlServer.Types and re-run again. You will encounter the issue below.

![image](https://user-images.githubusercontent.com/591015/74583114-f53f3a00-4fc3-11ea-8071-2434905f6329.png)

Lastly, install the System.Data.SqlClient. You will encounter the issue below.

![image](https://user-images.githubusercontent.com/591015/74583098-cd4fd680-4fc3-11ea-838c-101d71d201db.png)

**Comment by mikependon** [comment]
RepoDb completely mimic this problem on my own compiler. Please advise.

**Comment by cheenamalhotra** [comment]
@mikependon 

I see you're using .NET Core as target framework where the driver doesn't support Geometry, Geography and HierarchyId types yet. We have issues open for the same: https://github.com/dotnet/SqlClient/issues/30 and https://github.com/dotnet/SqlClient/issues/322

But when targeting .NET framework, you should have no issues.. and I also tested with your repro, it seems to works well!

**Comment by mikependon** [comment]
When are you supporting such Data Types?

**Comment by ajcvickers** [comment]
@mikependon In case it helps, EF Core supports SQL Server spatial columns on .NET Core by mapping them to types from the [community NTS project](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite/)

These aren't the same native SQL Server types exposed on .NET Framework, but a lot of the same functionality is supported. Docs: https://docs.microsoft.com/en-us/ef/core/modeling/spatial

**Comment by ajcvickers** [comment]
@mikependon Just to clarify again before I start digging, there is SQL to generate a schema in the code you posted. Is this a fixed schema? That is, you're trying to map EF to this schema without changing the schema?

**Comment by mikependon** [comment]
> Is this a fixed schema? 

Yes.

Please remove EF in the picture, it is a plain ADO.NET actually. Though I caught the exceptions from the Integration Tests of my own ORM when I started to support MDS.

**Comment by mikependon** [comment]
> In case it helps, EF Core supports SQL Server spatial columns on .NET Core by mapping them to types from the community NTS project

I am planning to use the plain  Microsoft.SqlServer.Types here. It has been acknowledge that it is not yet supported in Core framework (ie: NetStandard?). Though I will look at this.

**Comment by ajcvickers** [comment]
@mikependon Sorry, my last comment about the schema was intended for a different issue. I posted it here by mistake.

**Comment by mikependon** [comment]
@ajcvickers no worries. Thanks

**Comment by cheenamalhotra** [comment]
@mikependon 

These types currently do not exist in .NET Core in the same namespace hence they are not supported by the driver. SMO Package exposes them only for .NET Framework and not .NET Core.

Our issues are kept open to probably implement them internally in a different namespace, which is not prioritized yet.

**Comment by mikependon** [comment]
Right. This is noted. I will revisit this issue moving forward once the type is present in .Net Core. Maybe, just leave this one open.

**Comment by cheenamalhotra** [comment]
Hi @mikependon 

We have issues #30 and #322 open for the missing types requirement. You may track the same in future.

**Comment by MaceWindu** [comment]
You cannot use those types with `Microsoft.Data.SqlClient`, because they build against `System.Data.SqlClient` and use types declared here.
Only solution is to manually build [dotMorten.Microsoft.SqlServer.Types](https://github.com/dotMorten/Microsoft.SqlServer.Types) against  `Microsoft.Data.SqlClient`

Ideally Microsoft could fix it by providing more flexible mechanims to load UDT types
