### ISSUE TITLE
System.Data.SqlClient.SqlConnection.PermissionDemand() method name doesn't match what it does

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/SqlClient#42]
There's `System.Data.SqlClient.SqlConnection.PermissionDemand()` method which actually checks whether the connection strings are proper set. That doesn't sound like "permission demand" at all.

**Comment by David-Engel** [comment]
To me, it looks like PermissionDemand is just part of the Common Db interfaces and SqlClient is using it to validate the connection string since actual permissions are validate when we try to connect. It doesn't seem like something that needs to be changed.
