### ISSUE TITLE
Exception StackTrace shows a method not in code!

### ISSUE THREAD

**Issue by cnayan** [dotnet/SqlClient#432]
Hi,

I see an exception and I try to relate the exception stack trace with the code, but as per the code, the top method in stack is not there in code! What am I not able to see here?

```
[Error] System.AggregateException: One or more errors occurred. (One or more errors occurred. (Access is denied) (Access is denied)) ---> System.AggregateException: One or more errors occurred. (Access is denied) (Access is denied) ---> System.Security.SecurityException: Access is denied
   at System.Security.Principal.WindowsIdentity.GetCurrentInternal(TokenAccessLevels desiredAccess, Boolean threadOnly)
   at Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()
   at Microsoft.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at Microsoft.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
```

As per the source code https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.Windows.cs, there is no call made to "WindowsIdentity.GetCurrentInternal".
Then why is the stack trace showing it?

I get this exception when I try to impersonate another person on my machine (which succeeds) but SQL Client is unable to open a connection.

Can anyone help?

TIA!

Nayan

**Comment by cheenamalhotra** [comment]
We call `Windows.GetCurrent()`

https://github.com/dotnet/SqlClient/blob/a9dfe480eff5dd344518eab5198654eff969fb6e/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/ProviderBase/DbConnectionPoolIdentity.Windows.cs#L23

which calls `GetCurrentInternal()` by making a [Sibling/Tail call](https://en.wikipedia.org/wiki/Tail_call), which is not captured by Stack Trace.

Reference source: [windowsidentity.cs#L263-L267](https://github.com/microsoft/referencesource/blob/17b97365645da62cf8a49444d979f94a59bbb155/mscorlib/system/security/principal/windowsidentity.cs#L263). 

Regarding the exception, you might wanna try giving Security permission to the impersonated user account.

**Comment by cnayan** [comment]
> Regarding the exception, you might wanna try giving Security permission to the impersonated user account.

Thank you for responding.

From the call flow, it seems to me that the original account is being retrieved : Microsoft.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()

Is my assumption correct?
If yes, then would impersonation really work?

Regarding security permission, can you please share any sample or test code link? I need to learn.

Thanks again!

Regards,
Nayan

**Comment by Wraith2** [comment]
the GetCurrentNative call uses the windows api to request the SecurityIdentifier for the current user and that will respond based on the user that the thread token has a handle to so that it will respect impersonation. This behaviour is checked in the tests in System.Security.Principal.Windows in the dotnet/runtime repo.

**Comment by cnayan** [comment]
Do you have a working example?
I've an example on how it doesn't work.

**Comment by Wraith2** [comment]
I'm looking for an example of something that doesn't work but that you want to. Can you show how you'd use this feature if it existed.

**Comment by cheenamalhotra** [comment]
@cnayan 

Can you list down the steps you took so far that I can try and help solve?

**Comment by cheenamalhotra** [comment]
Closing this issue as answered, if you need support on more topics from SqlClient, please open a new issue with repro attached.
