### ISSUE TITLE
Change in handling of Date/DateTime values after migration from v1.0.19269.1 to v1.1.1.

### ISSUE THREAD

**Issue by dev-ska** [dotnet/SqlClient#434]
On v1.0: the DbType.Date parameter, which has a DateTime value, is saved as a DateTime in the database.
On v1.1: the DbType.Date parameter, which has a DateTime value, is saved as a Date in the database (a time part is truncated).
The database column is of type datetime2.

Table declaration:
```
CREATE TABLE SqlClientTest
(
	DateTimeColumn datetime2 NOT NULL
)
GO
```

Code:
```
using (var connection = new SqlConnection(connectionString))
{
	var command = new SqlCommand($"insert into SqlClientTest (DateTimeColumn) values (@value)", connection);
	var parameter = command.CreateParameter();

	parameter.ParameterName = "@value";
	parameter.Value = DateTime.Now;
	parameter.DbType = DbType.Date;

	command.Parameters.Add(parameter);

	connection.Open();
	command.ExecuteNonQuery(); // running on v1.1, DateTimeColumn has no time part
	connection.Close();
}
```

Was this a functional change?

**Comment by ErikEJ** [comment]
Yes, I believe so: https://github.com/dotnet/SqlClient/pull/269

**Comment by dev-ska** [comment]
@ErikEJ Thanks!

**Comment by cheenamalhotra** [comment]
@dev-ska 

Since you're specifying "parameter.DbType = DbType.Date;"  you're seeing this difference.
You need to specify "parameter.DbType = DbType.DateTime" in order to receive the time part.

**Comment by dev-ska** [comment]
Thanks, it's understandable. The question was raised when the code (with an old history) successfully storing datetime's using SqlType.Date started to fail after switching to the new package version.

**Comment by ErikEJ** [comment]
Hmm.. So a breaking change caused by a wrong mapping (bug) in your code.

**Comment by dev-ska** [comment]
Yes, I'm unsure about the original reason for mapping date times to DbType.Date. Might be something related to that the code should support SQL and Oracle databases. I've switched to the DbType.DateTime mapping and it works as it used to with SQL. But this is a subject for further investigation on how the oracle provider behaves with the mapping update. The eventual goal is to keep the previous behaviour on both database types.
