### ISSUE TITLE
Persist Security Info=false isn't respected

### ISSUE THREAD

**Issue by roji** [dotnet/SqlClient#448]
With Microsoft.Data.SqlClient on netcoreapp3.1, the password is present in SqlConnection.ConnectionString after Open has been called. [As per the docs](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqlconnection.connectionstring?view=netframework-4.8#remarks), once Open is called, all security info is supposed to be stripped from the user-exposed connection string. System.Data.SqlClient behaves correctly. This can be seen with MS.Data.SqlClient versions 1.1.1 and 2.0.0-preview1.20021.1.

```c#
using System;
//using System.Data.SqlClient;
using Microsoft.Data.SqlClient;

namespace Test
{
    class Program
    {
        static void Main(string[] args)
        {
            var conn = new SqlConnection(@"Server=localhost;Database=test;User=SA;Password=Abcd5678;Persist Security Info=false");
            conn.Open();
            Console.WriteLine("Connection string: " + conn.ConnectionString);
            // With Microsoft.Data.SqlClient, outputs Server=localhost;Database=test;User=SA;Password=Abcd5678;Persist Security Info=false
            // With System.Data.SqlClient, outputs Server=localhost;Database=test;User=SA;Persist Security Info=false
        }
    }
}
```

**Comment by cheenamalhotra** [comment]
I confirm issue is reproducible in .NET Core with **Microsoft.Data.SqlClient**, while .NET Framework seems to be fine.
