### ISSUE TITLE
Suspicious error object creation in System.Data.SqlClient.TdsParserStateObject.OnTimeout() 

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/SqlClient#45]
`System.Data.SqlClient.TdsParserStateObject.OnTimeout()` goes like this:

```
   _internalTimeout = true;
     // lock protects against Close and Cancel
     lock (this)
     {
         if (!_attentionSent)
        {
             AddError(new SqlError( WHATEVER ));
```

If you look through usage of `_internalTimeout` elsewhere in the same class you may notice that `ReadSniError()` also checks `_internalTimeout` and optionally sets `fail` local variable. It's unclear whether this may cause `ThrowExceptionAndWarning()` being called with empty "errors" collection which would cause https://github.com/dotnet/corefx/issues/6119 I guess that `OnTimeout()` should add a new `SqlError()` no matter if `_attentionSent` is set.

**Comment by Wraith2** [comment]
We recently reworked how timeouts and attention interact to make them more reliable. As part of that work i dug into how exceptions are being handled and propagated in the driver. The errors that the function picks up are present in TLS and put there by various places in managed and native driver implementations, this check looks nonsensical but is really the only place that picks up the TLS stored values. It would be nice to change how it behaves but it is currently correct even though it's confusing and not the best way to implement the functionality.

@cheenamalhotra I'd recommend closing this if you agree with my analysis.

**Comment by cheenamalhotra** [comment]
Closed based on @Wraith2 's explanation above.
