### ISSUE TITLE
Sql Client XML Help file has bad HTML that breaks Sandcastle

### ISSUE THREAD

**Issue by MCFHTAGENTS** [dotnet/SqlClient#450]
The System.Data.SqlClient.xml file has bad XML reported in Sandcastle as:

 Reason: The 'p' start tag on line 506 position 2 does not match the end tag of 'th'. Line 506, position 96.

This relates to the following:
 ```
<table><thead><tr><th> Value  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="4" sourceendlinenumber="4"> </th><th> Description  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="6" sourceendlinenumber="6"> </th></tr></thead><tbody><tr><td> SQL Server 2005  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="8" sourceendlinenumber="8"> </td><td> Uses the SQL Server 2005 type system. No conversions are made for the current version of ADO.NET.  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="10" sourceendlinenumber="10"> </td></tr><tr><td> SQL Server 2008  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="12" sourceendlinenumber="12"> </td><td> Uses the SQL Server 2008 type system.  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="14" sourceendlinenumber="14"> </td></tr><tr><td> Latest  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="16" sourceendlinenumber="16"> </td><td> Use the latest version than this client-server pair can handle. This will automatically move forward as the client and server components are upgraded.  <p>
<p sourcefile="System.Data.SqlClient.yml" sourcestartlinenumber="18" sourceendlinenumber="18"> </td></tr></tbody></table>
```

where you can see the lack of closures of the P tags etc.

**Comment by David-Engel** [comment]
@MCFHTAGENTS Can you provide some more information, please?

1. What version of System.Data.SqlClient are you using?
2. What target platform and version are you referring to? (Ex: .NET Framework 4.7, .NET Core 2.1)
3. Which System.Data.SqlClient.xml file are you referring to? (NuGet package? Path in the package?)
4. How does this impact you?

**Comment by MCFHTAGENTS** [comment]
Sure:
1: Version 1.1.1
2: .Net Core 3.1
3: Nuget Package (not exactly sure how to answer the question 'which one' - it is the one that Sandcastle pulls in to build the help file using reflection)
4: It prevents Sandcastle from reading the <summary> tags across my entire solution and therefore stops the generation of a useful compiled help file. You could argue that Sandcastle shouldn't be this brittle but that is another issue....

Thanks
Mark

**Comment by cheenamalhotra** [comment]
Are you talking about Microsoft.Data.SqlClient or System.Data.SqlClient?

1. [v1.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.1.1) corresponds to **Microsoft.Data.SqlClient** while your logs say "**System.Data.SqlClient**".
2. XML for M.D.S (.NET Core) v1.1.1 does not have any `<p>` or `<th>` tags.

Please link to the correct NuGet package you're using.

**Comment by David-Engel** [comment]
@MCFHTAGENTS I'm going to assume you are actually referring to _Microsoft.Data.SqlClient_ since you specified version 1.1.1.

> 3: Nuget Package (not exactly sure how to answer the question 'which one' - it is the one that Sandcastle pulls in to build the help file using reflection)
> 4: It prevents Sandcastle from reading the summary tags across my entire solution and therefore stops the generation of a useful compiled help file. You could argue that Sandcastle shouldn't be this brittle but that is another issue....

I'm not familiar with SandCastle. Are you referring to this project? https://github.com/EWSoftware/SHFB

I opened every Microsoft.Data.SqlClient.xml file in the 1.1.1 NuGet package and none of them contain `<p>`. The XML files do contain the other text, but it looks like this:
```
<list type="table"><listheader><term> Value  
  
 </term><description> Description  
  
 </description></listheader><item><term> SQL Server 2005  
  
 </term><description> Uses the SQL Server 2005 type system. No conversions are made for the current version of ADO.NET.  
  
 </description></item><item><term> SQL Server 2008  
  
 </term><description> Uses the SQL Server 2008 type system.  
  
 </description></item><item><term> Latest  
  
 </term><description> Use the latest version than this client-server pair can handle. This will automatically move forward as the client and server components are upgraded.  
  
 </description></item></list>
```
Which appears to be valid XML to me.

I suspect this is a problem in SandCastle.

**Comment by MCFHTAGENTS** [comment]
Thanks all

I have raised an issue here [https://github.com/EWSoftware/SHFB/issues/787](https://github.com/EWSoftware/SHFB/issues/787) - yes I was talking about that project.

I had moved my code over to the Microsoft.Data.SqlClient namespace but the old System one must be being referenced by one of my components as it appears in reflection and yes it is that one that appears in the logs! I will try and find out how this file is being created (verbose logging isn't telling me! - Sandcastle caches some of these but not, on the face of it, this one) and report back.

Thanks
Mark

**Comment by MCFHTAGENTS** [comment]
Just an update here. The XML file in `C:\Users\MarkHeaton\.nuget\packages\system.data.sqlclient\4.4.0\ref\netstandard2.0`
contain bad HTML and I assume the same is true of the other platforms for this version. Obviously this is also an old version of the library but the assembly resolver is picking it up somewhere in my dependency chain (need to work out where)

**Comment by cheenamalhotra** [comment]
Hi @MCFHTAGENTS 

I'll close the issue at our end, as the issue does not persist in newer driver versions that we maintain.
