### ISSUE TITLE
SqlConnection.Open hangs when connecting to SQL Server 2012SP4

### ISSUE THREAD

**Issue by joozek78** [dotnet/SqlClient#451]
The following code hangs, when trying to connect to SQL Server 2012 SP4

```
var connection = new SqlConnection(connectionString);
connection.Open();
```
.NET Core Version: **3.1** (from  mcr.microsoft.com/dotnet/core/sdk:3.1 docker image)
System.Data.SqlClient Version: **4.3.0**
OS: **Linux** (inside a container)
SQL Server version: **2012 (SP4-GDR)**

This code works on Mac and Windows though, connecting to exactly the same SQL Server.

According to [Microsoft](https://support.microsoft.com/en-us/lifecycle/search?alpha=SQL%20Server%202012%20Service%20Pack%204) Extended Support doesn't end until 2022, so I would expect that I could connect to it from .NET Core

Reproduction project: [gist.github.com](https://gist.github.com/joozek78/ea28a3968f4ee38dd9bc357e7f63e32d)

SQL Server version details:
```
> SELECT @@VERSION AS 'SQL Server Version';
> Microsoft SQL Server 2012 (SP4-GDR) (KB4057116) - 11.0.7462.6 (X64) 
	Jan  5 2018 22:11:56 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1)
```

Related issue: dotnet/runtime#26759 - similar, but actually recommends upgrading to 2012

**Comment by cheenamalhotra** [comment]
Hi @joozek78 

We have similar issue reported here: https://github.com/dotnet/SqlClient/issues/201, please ensure TLS 1.2 protocol is enabled on your server machine as TLS 1.0 and 1.1 are no longer supported by some linux images and driver cannot connect to server if server only supports these 2 protocols.

**Comment by joozek78** [comment]
@cheenamalhotra Thanks for the reference, I verified that lowering client requirements to TLS 1.0 lets me connect. I currently have no way to update the server, but the workaround at least gives me way to go on with project development.
Should I close this issue as a duplicate then?

**Comment by cheenamalhotra** [comment]
@joozek78 Glad you've resolved it.

Please remember TLS 1.0 and TLS 1.1 are deprecated and not recommended protocols, so you must try to move to TLS 1.2 by upgrading server machines.

I will close the issue at our end.

**Comment by nayanishdamania** [comment]
Please try to change Connection Timeout from 0 to 30, If you have given Connection Timeout is 0

Thanks
