### ISSUE TITLE
SqlConnection.GetSchema() Throws Exception in Release Build

### ISSUE THREAD

**Issue by tuggernuts** [dotnet/SqlClient#46]
In a UWP app, SqlConnection.GetSchema(string, string[] args) will throw an "ArgumentNull" exception in a release build, with or without code optimization. Same exact GetSchema() call works fine in debug builds. I can also otherwise successfully connect and query the server (a remote machine). Tried SQL Server versions 2012 & 2017.

Specific Exception is a System.AggregateException, with an Inner Exception of ArgumentNull: "value cannot be null. Parameter name: xmlStream."

Sample app is [here](https://github.com/tuggernuts/GetSchema)

Using Visual Studio 15.5.7, targeting build 16299.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by tuggernuts** [comment]
I am circling back to this issue and decided to try 1.1.0-preview1.19275.1,  VS2019. I'm not sure exactly where your team is with this, but I still have exceptions with the sample app I linked to above - though a little different. Passing along, hoping this will help.

 GetSchema(string, string[]) will throw an ArgumentException: 'Column requires a valid DataType'. **This only happens when 'compile with .net native tool chain' is enabled.**

<img width="449" alt="Annotation 2019-10-08 185536" src="https://user-images.githubusercontent.com/36776999/66439323-3e232880-e9fd-11e9-955e-b1edc23c48a3.png">

Call Stack
[Managed to Native Transition]	
 	System.Data.Common.dll!System.Data.DataColumn.DataType.set(System.Type value)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.SetProperties(object instance, System.Xml.XmlAttribute[] attrs)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.HandleElementColumn(System.Xml.Schema.XmlSchemaElement elem, System.Data.DataTable table, bool isBase)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.HandleParticle(System.Xml.Schema.XmlSchemaParticle pt, System.Data.DataTable table, System.Collections.ArrayList tableChildren, bool isBase)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.HandleComplexType(System.Xml.Schema.XmlSchemaComplexType ct, System.Data.DataTable table, System.Collections.ArrayList tableChildren, bool isNillable)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.InstantiateTable(System.Xml.Schema.XmlSchemaElement node, System.Xml.Schema.XmlSchemaComplexType typeNode, bool isRef)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.HandleTable(System.Xml.Schema.XmlSchemaElement node)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.HandleDataSet(System.Xml.Schema.XmlSchemaElement node, bool isNewDataSet)	Unknown
 	System.Data.Common.dll!System.Data.XSDSchema.LoadSchema(System.Xml.Schema.XmlSchemaSet schemaSet, System.Data.DataSet ds)	Unknown
 	System.Data.Common.dll!System.Data.DataSet.ReadXSDSchema(System.Xml.XmlReader reader, bool denyResolving)	Unknown
 	System.Data.Common.dll!System.Data.DataSet.ReadXml(System.Xml.XmlReader reader, bool denyResolving)	Unknown
 	System.Data.Common.dll!System.Data.DataSet.ReadXml(System.IO.Stream stream)	Unknown
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.ProviderBase.DbMetaDataFactory.LoadDataSetFromXml(System.IO.Stream XmlStream) Line 512	C#
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.ProviderBase.DbMetaDataFactory.DbMetaDataFactory(System.IO.Stream xmlStream, string serverVersion, string normalizedServerVersion) Line 48	C#
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlConnectionFactory.CreateMetaDataFactory(Microsoft.Data.ProviderBase.DbConnectionInternal internalConnection, out bool cacheMetaDataFactory) Line 281	C#
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.ProviderBase.DbConnectionFactory.GetMetaDataFactory(Microsoft.Data.ProviderBase.DbConnectionPoolGroup connectionPoolGroup, Microsoft.Data.ProviderBase.DbConnectionInternal internalConnection) Line 392	C#
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.ProviderBase.DbConnectionInternal.GetSchema(Microsoft.Data.ProviderBase.DbConnectionFactory factory, Microsoft.Data.ProviderBase.DbConnectionPoolGroup poolGroup, System.Data.Common.DbConnection outerConnection, string collectionName, string[] restrictions) Line 265	C#
 	Microsoft.Data.SqlClient.dll!Microsoft.Data.SqlClient.SqlConnection.GetSchema(string collectionName, string[] restrictionValues) Line 1316	C#
	ClassLibrary.dll!ClassLibrary.SomeClass.GetSchema() Line 31	C#
 	GetSchemaTestApp.exe!GetSchemaTestApp.MainPage.MainPage() Line 29	C#
 	GetSchemaTestApp.exe!GetSchemaTestApp.GetSchemaTestApp_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_MainPage() Line 226	C#
 	GetSchemaTestApp.exe!GetSchemaTestApp.GetSchemaTestApp_XamlTypeInfo.XamlUserType.ActivateInstance() Line 382	C#
 	GetSchemaTestApp.McgInterop.dll!__Interop.ReverseComStubs.Stub_12(object __this, void** unsafe_instance__retval, System.IntPtr __methodPtr)	C#
 	GetSchemaTestApp.McgInterop.dll!Windows.UI.Xaml.Markup.IXamlType__Impl.Vtbl.ActivateInstance__n(System.IntPtr pComThis, void** unsafe_instance__retval)	C#
 	[Native to Managed Transition]	
 	[Managed to Native Transition]	
 	GetSchemaTestApp.McgInterop.dll!__Interop.ComCallHelpers.Call(System.__ComObject __this, System.RuntimeTypeHandle __typeHnd, int __targetIndex, System.Type__Impl.UnsafeType arg0, void* arg1, void* arg2)	C#
 	GetSchemaTestApp.McgInterop.dll!Windows.UI.Xaml.Controls.IFrame__Impl.Stubs.Navigate(System.__ComObject __this, System.Type sourcePageType, object parameter)	C#
 	GetSchemaTestApp.exe!GetSchemaTestApp.App.OnLaunched(Windows.ApplicationModel.Activation.LaunchActivatedEventArgs e) Line 64	C#
 	System.Diagnostics.DiagnosticSource.dll!System.Diagnostics.DiagnosticSource.IsEnabled(string name, object arg1, object arg2)	Unknown
 	GetSchemaTestApp.McgInterop.dll!__Interop.ReverseComStubs.Stub_3<System.__Canon>(object __this, void* unsafe_p, System.IntPtr __methodPtr)	C#
 	GetSchemaTestApp.McgInterop.dll!Windows.UI.Xaml.IApplicationOverrides__Impl.Vtbl.OnLaunched__n(System.IntPtr pComThis, void* unsafe_args)	C#
 	[Native to Managed Transition]

**Comment by cheenamalhotra** [comment]
Thanks @tuggernuts 

We will take a look and update you soon!

**Comment by cheenamalhotra** [comment]
Closing as stale, please open new issue with repro if problem reoccurs.
