### ISSUE TITLE
SslOverTdsStream functionality

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#475]
I've been looking at the code for a few hours now and I'm not sure if I'm missing something important or if it's broken. The file in question is here: https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SslOverTdsStream.cs 
and the main point that's puzzling me is in the ReadInternal (and WriteInternal but that should just be an inverse operation so if I understand one of them I should understand the other).

https://github.com/dotnet/SqlClient/blob/520f4ebd0dcec734d488542f6e44480153c8b4b7/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SslOverTdsStream.cs#L91-L136

This class sits between the network stream and an ssl stream. It's purpose seem to be to handle packet construction/deconstruction at login. To do that I think it intercepts operations when encapsulate is set and then removes packet headers and recombines the data from multiple receive operations into a single packet wherever possible. It does this without storing any remaining buffers so it is careful to only request information from the base stream that it needs to reconstruct a single packet. Is this description correct? Because it doesn't seem to actually do this.

I extracted the class into a new project. Forced the max packet size to a manageable size and then called it in a trivial fashion with 4 input pieces of data. I then attempted to read back the data and hoped to get the same as the input. I didn't. Gist is here: https://gist.github.com/Wraith2/792da77e7e7b9004dae55197935def8c

Can anyone comment on whether I've missed the point of the class or am making invalid assumptions? 

/cc @saurabh500 @cheenamalhotra for technical internals knowledge

**Comment by saurabh500** [comment]
I took a look at the code, and it is something that @corivera wrote for encrypted data transfer and I changed it to optimize it later. 
I do agree with what you are saying (though I never really tried to interpret the code the way you have mentioned i.e. the read should return the same thing as write).

Where is the comparision of the read and write buffer happening in your console app ? 

Are you seeing differences only in header comparison ? Or data as well? I will try out your code to figure out what the change is.

**Comment by Wraith2** [comment]
I'm just manually checking the data in the debugger at the moment. There's an infinite loop bug which is fixable but I'm wondering if input and output should be identical. should 4 input packets yield 8 output packets or 4?

**Comment by saurabh500** [comment]
You are sending 4 byte[] each of size 32. 
The packet size is set to 32. Hence each byte[] is split into two chunks Header + data, 8 + (32 - 8)
Hence 32 bytes of data is split into two packets of size 32 and 16, since each packet size is the size including header. 

Hence you are reading 8 packets for four chunks of data of length 32 bytes.  
I can verify that the input and output is correct in your application.

**Comment by saurabh500** [comment]
packet Size = HEADER + data size 
HEADER = 8 bytes
Max Data size = max packet size - HEADER size.

**Comment by saurabh500** [comment]
Each line depicts a packet

Sending packets 
18 0 0 32 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
18 1 0 16 0 0 0 0 1 1 1 1 1 1 1 1 
18 0 0 32 0 0 0 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
18 1 0 16 0 0 0 0 2 2 2 2 2 2 2 2
18 0 0 32 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
18 1 0 16 0 0 0 0 3 3 3 3 3 3 3 3 18 0 0 32 0 0 0 0 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 
18 1 0 16 0 0 0 0 4 4 4 4 4 4 4 4

Reading packets
First packet with 24 bytes of data : 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0
Left over 8 bytes: 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
The trend follows:
2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0
2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 0 0 0 0 0 0 0 0
3 3 3 3 3 3 3 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0
4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

**Comment by saurabh500** [comment]
I changed the `Main` function in your gist to the following to print the data
```C#
static void Main(string[] args)
        {
            byte[] buffer = null;

            int printOffset = 0;
            using (MemoryStream stream = new MemoryStream())
            {
                using (SslOverTdsStream tdsStream = new SslOverTdsStream(stream))
                {
                    for (int index = 0; index < 4; index++)
                    {
                        byte[] bytes = new byte[TdsEnums.DEFAULT_LOGIN_PACKET_SIZE];
                        Array.Fill<byte>(bytes, (byte)(index + 1));
                        tdsStream.Write(bytes);
                        buffer = stream.ToArray();

                        for(; printOffset < buffer.Length; printOffset++)
                        {
                            Console.Write(buffer[printOffset] + " ");
                        }
                        Console.WriteLine();
                    }
                }
            }


            Console.WriteLine("Printing read packets");
            List<byte[]> packets = new List<byte[]>();
            using (MemoryStream stream = new MemoryStream(buffer))
            {
                using (SslOverTdsStream tdsStream = new SslOverTdsStream(stream))
                {

                    int readCount = 0;
                    do
                    {
                        byte[] bytes = new byte[TdsEnums.DEFAULT_LOGIN_PACKET_SIZE];
                        readCount = tdsStream.Read(bytes, 0, bytes.Length);
                        if (readCount > 0)
                        {
                            packets.Add(bytes);
                        }

                        foreach (byte b in bytes)
                        {
                            Console.Write(b + " ");
                        }
                        Console.WriteLine();
                    }
                    while (readCount > 0);
                }
            }
        }
```

**Comment by saurabh500** [comment]
Hey @Wraith2  i closed this, since I think I answered the question. Please reopen if you need more discussions.

**Comment by Wraith2** [comment]
So returning a single split packet in multiple chunks to the reader isn't a problem. That clears up one thing. As I see it currently it will only ever work if a packet contains less or equal the amount of data that is requested. If you request 200 bytes and the packet contains 400 it will strip off the first 8 bytes, copy the (200-8) bytes to buffer parameter and then lose the other (400 - (200-8)) bytes.
So perhaps the problem is that I'm treating as a symmetric demultiplexor and it's really just a constrained use packetizer.
