### ISSUE TITLE
SqlParameterCollection.Insert() fails with InvalidCastException

### ISSUE THREAD

**Issue by KristianWedberg** [dotnet/SqlClient#478]
### Describe the bug
`Microsoft.Data.SqlClient.SqlParameterCollection.Insert()` fails with `System.InvalidCastException : Unable to cast object of type 'Microsoft.Data.SqlClient.SqlParameter' to type 'Microsoft.Data.SqlClient.SqlParameterCollection'.`, even though it works in `System.Data.SqlClient`.

StackTrace:
```
at Microsoft.Data.SqlClient.SqlParameterCollection.Insert(Int32 index, Object value) in E:\SqlClientInternal\agent-1\_work\5\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\ProviderBase\SqlParameterCollectionHelper.cs:line 238
   at XTest.ParameterCollectionTest.ParameterCollection_Insert() in ParameterCollectionTest.cs:line 125
```

### To reproduce

```c#
            using (var conn = new SqlConnection(connectionString))
            {
                conn.Open();
                var command = conn.CreateCommand();

                var paramA = new SqlParameter("@A", SqlDbType.Int);
                paramA.Value = 1;
                command.Parameters.Add(paramA);

                var paramB = new SqlParameter("@B", SqlDbType.Int);
                paramB.Value = 2;
                command.Parameters.Insert(0, paramB); //  THROWS!
            }
```

### Expected behavior

No exception thrown.

### Further technical details
- Microsoft.Data.SqlClient version: 1.1.1 and 2.0.0-preview1.20021.1
- .NET target: .NET Framework 4.6.1
- Operating system: Windows 10

**Comment by cheenamalhotra** [comment]
Hi @KristianWedberg 

We'll investigate and get back to you soon!

**Comment by KristianWedberg** [comment]
Verified as fixed, thanks!
