### ISSUE TITLE
Add TestCommandBuilder() and TestInitialCatalogStandardValues() in SqlSchemaInfoTest

### ISSUE THREAD

**Issue by geleems** [dotnet/SqlClient#48]
TestCommandBuilder() and TestInitialCatalogStandardValues() need to be filled out after CommandBuilder and PropertyDescriptor become supported in .NET Core.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
I wonder if this issue can be closed. Branch 'master' > [SqlSchemaInfoTest.cs](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/SqlSchemaInfoTest/SqlSchemaInfoTest.cs )

@geleems Please confirm, in case I'm missing something!
