### ISSUE TITLE
Microsoft.Data.SqlClient.SNI v1.1.1: Still Azure Cloud Service (classic) with EF Core 3.1 => sni.dll not found

### ISSUE THREAD

**Issue by VeselovAndrey** [dotnet/SqlClient#485]
Hi,
Even with Microsoft.Data.SqlClient.SNI v1.1.1 I still have same issue with Azure Cloud Service as it was described in https://github.com/dotnet/SqlClient/issues/407

Example update to Microsoft.Data.SqlClient.SNI v1.1.1:
https://github.com/VeselovAndrey/SniBugDemo (branch master-1-1-1)

But it still doesn't copy required files into cloud role folder. All similar to https://github.com/dotnet/SqlClient/issues/407

Any suggestions?

**Comment by cheenamalhotra** [comment]
Please provide your repro to investigate.

**Comment by VeselovAndrey** [comment]
https://github.com/VeselovAndrey/SniBugDemo
branch:  master-1-1-1

or direct link https://github.com/VeselovAndrey/SniBugDemo/tree/master-1-1-1

**Comment by VeselovAndrey** [comment]
@cheenamalhotra Any news? Are you able to reproduce problem using repo above?

**Comment by VeselovAndrey** [comment]
Hi @cheenamalhotra ! Any progress on this bug?

**Comment by cheenamalhotra** [comment]
Hi @VeselovAndrey 

You need to import SNI targets file in [Azure.cproj](https://github.com/VeselovAndrey/SniBugDemo/blob/03f82ef219c346715b8be8cfd86b6473b2cc0637/EFCore31Demo.Azure/EFCore31Demo.Azure.ccproj#L60) file.

**Comment by acbaile** [comment]
Hi! I have the same issue. I described it here: [Failed to load SNI.dll](https://github.com/NuGet/docs.microsoft.com-nuget/issues/2049)

Solution from [sni.dll not found](https://github.com/dotnet/SqlClient/issues/407) does not work in my case too.

Now, I have to run special JScript that puts `x86` and `x64` folders to `approot` during starting emulation. I run this script manually. It is not convinient, and I don't know what will happen when I will publish it to Azure. Has to be, it will not copy SNI folders too.

So, how to resolve this issue? Have I to look for make some script to do this task? It's time and energy spent. Please, resolve this issue.

**Comment by cheenamalhotra** [comment]
@acbaile 

Could you try with v2.0.0 of Microsoft.Data.SqlClient and let us know?
If it still doesn't fix, please upload a small repro app to reproduce issue in a new issue so we can take a deeper look.

**Comment by acbaile** [comment]
> Could you try with v2.0.0 of Microsoft.Data.SqlClient and let us know?

I tried to update to v2.0.0. It does not resolve. I see the same error message in project file and folders `x86`, `x64` are not copied when emulation starts.

**Comment by acbaile5** [comment]
> If it still doesn't fix, please upload a small repro app to reproduce issue in a new issue so we can take a deeper look.

I published it here: https://github.com/acbaile5/VirginEFCore

**Comment by acbaile** [comment]
When will it be resolved?

**Comment by acbaile** [comment]
I found solution. To resolve problem you have to downgrade EF Core to branch `2.2`. Latest version is `2.2.6` at this moment.

`2.2.6` uses `System.Data.SqlClient` and this package does not need to copy folders `x86`, `x64` to `approot`. Everything works without SNI.

`3.0.0` uses `Microsoft.Data.SqlClient`, that has this issue.

Until this issue will be resolved, we have to use previous version of EF Core.

**Comment by zatuliveter** [comment]
I had issue with copying SNI* files into cloud role folder in case Azure Cloud Service has multipe worker roles. For some reason it copies files only for one worker role. To fix it I modified  Azure Cloud Service .ccproj project file by adding the following lines:
```xml
<Import Project="..\..\packages\Microsoft.Data.SqlClient.SNI.2.0.0\build\net46\Microsoft.Data.SqlClient.SNI.targets" Condition="Exists('..\..\packages\Microsoft.Data.SqlClient.SNI.2.0.0\build\net46\Microsoft.Data.SqlClient.SNI.targets')" />

<Target Name="CopySNIRoleFiles" Condition="'@(WorkerRoleReferences)' != ''" >
  <Copy SourceFiles="@(SNIFiles)" DestinationFolder = "%(WorkerRoleReferences.OutputDir)" />
</Target>

<PropertyGroup>
  <CopyRoleFilesDependsOn>
    $(CopyRoleFilesDependsOn)
    CopySNIRoleFiles;
  </CopyRoleFilesDependsOn>
</PropertyGroup>
```
Pay attention on `Copy` command, I used `DestinationFolder` instead of `DestinationFiles` param.
```xml
<Copy SourceFiles="@(SNIFiles)" DestinationFolder = "%(WorkerRoleReferences.OutputDir)" />
```

**Comment by David-Engel** [comment]
This can be addressed with workarounds in previous MDS versions. I believe current versions of MDS/MDS SNI have addressed this issue for the type of project specified. Closing.
