### ISSUE TITLE
Tried to implement repository pattern and unit of work using. Net core but it's giving errors

### ISSUE THREAD

**Issue by sameersayani** [dotnet/SqlClient#491]
I used Microsoft. Data
Sql Client but things like IDbconnection, IConnectionFactory does not work.

**Comment by cheenamalhotra** [comment]
Hi @sameersayani

Could you also link your repro application here that we can validate?

**Comment by sameersayani** [comment]
Hi @cheenamalhotra ,

Please find link of repo application.

**Comment by DavoudEshtehari** [comment]
Hi @sameersayani,
Did you try to set `DBProviderFactories` configuration in the config file.

**Comment by cheenamalhotra** [comment]
Closed due to inactivity and no-op for SqlClient.
