### ISSUE TITLE
System.Data.SqlClient hangs on Linux (Docker) with SQL Server 2005

### ISSUE THREAD

**Issue by giannoug** [dotnet/SqlClient#50]
We are observing a wierd behaviour with System.Data.SqlClient and Linux (Debian Jessie / Docker with microsoft/aspnetcore:1.1.0). When connecting to an SQL Server 2016 instance everything works fine. When connecting to SQL Server 2005, our application hangs indefinitely. Sometimes, an InvalidOperationException occurs stating: "The timeout period elapsed prior to obtaining a connection from the pool.". Everything works as expected on Windows.

Maybe a similar issue to #15287?

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.
