### ISSUE TITLE
EF Core SqlClient and App Insights

### ISSUE THREAD

**Issue by MaximBalaganskiy** [dotnet/SqlClient#52]
What can be the reason for not seeing raw SQL in EF app insights in net core project? Not locally nor in Azure. 

I remember at some point with one of the RCs I saw SQL logged but not anymore.
Originally, I posted the question here https://github.com/aspnet/EntityFramework/issues/5510 but was referred to this repo.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
Can anyone confirm that this is fixed in .NET Core 2.2?

**Comment by cijothomas** [comment]
https://github.com/dotnet/SqlClient/issues/52#issuecomment-342860520 This is fixed.
