### ISSUE TITLE
Full CPU load on Ubuntu 20.04

### ISSUE THREAD

**Issue by DenSmoke** [dotnet/SqlClient#538]
Any SQL operation causes 100% CPU load on Ubuntu 20.04 when using Microsoft.Data.SqlClient with ASP.NET Core 3.1 project

**Comment by cheenamalhotra** [comment]
Hi @DenSmoke 

Could you upload your repro app here to investigate?

**Comment by DenSmoke** [comment]
[Test.zip](https://github.com/dotnet/SqlClient/files/4531242/Test.zip)
I made project for repro and I found that it happens at SqlConnection.OpenAsync and only with our production instance of SQL Server 2016. We have another instance with SQL Server 2017 and almost same configuration and this problem doesn't occur when connecting to it.

**Comment by DenSmoke** [comment]
Any ideas why is this happening or how can I help you to investigate this?

**Comment by cheenamalhotra** [comment]
Hi @DenSmoke 

Thanks for your repro. It seems to be related to other Docker Unix image issues we have in the repository where protocols supported by client don't match server and driver cannot connect.

Hanging on SQL 2016 only suggests you probably don't have TLS 1.2 enabled on this server, please try enabling it and let us know!

**Comment by DenSmoke** [comment]
I changed certificate of SQL Server 2016 instance to SHA256 encrypted (https://github.com/dotnet/SqlClient/issues/201#issuecomment-570755094) and problem is gone. But I think this `SqlConnection.OpenAsync` behavior should be fixed anyway.

**Comment by cheenamalhotra** [comment]
Since we have other issues to track that improvement, I'll close this issue.
