### ISSUE TITLE
Backport Mars cleanup fix PR #22709 to release/2.0.0

### ISSUE THREAD

**Issue by corivera** [dotnet/SqlClient#55]
This change should be backported to 2.0.0, if possible.

PR: https://github.com/dotnet/corefx/pull/22709
Original issue: https://github.com/dotnet/corefx/issues/22661

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.
