### ISSUE TITLE
Using AAD Access Token to login to a SQL Server - how to handle expiration of token

### ISSUE THREAD

**Issue by aaomidi** [dotnet/SqlClient#552]
Hi!

If I'm using AAD access token to authenticate with a SQL server/database, how should the expiration of the token be handled?

For example, if the connection has been a long lasting connection and has been left open for 1 hour, what is the mechanism of rehydrating a new authentication token without disruption to the user?

Reference: https://github.com/microsoft/azuredatastudio/issues/9174

**Comment by Wraith2** [comment]
If the tcp connection is maintained do you even need to re-auth? the connection is stateful so i wouldn't think you'd need to provide any form of credential again unless it closed down. If that's the case then it's down to the person managing the connection lifetime how to make another connection.

**Comment by aaomidi** [comment]
Ah I see, so I won't be "kicked off" of a connection if I keep it alive?

**Comment by Wraith2** [comment]
That's something that the server could do but it isn't something this driver does as far as I'm aware. The token you give in the connection string is passed to the server which uses it to authenticate you and if it also decides to add a timer then that's internal detail from this library's perspective. This library doesn't introspect the token and limit the connection time from what I know.

You might want to just try it in a small test console project. open a connection with a token for auth and see if it stays open.
