### ISSUE TITLE
Improve code coverage for System.Data.SqlClient (18.1%)

### ISSUE THREAD

**Issue by danmosemsft** [dotnet/SqlClient#56]
[Report here](https://dotnetcoverage.blob.core.windows.net/cov1/report/index.htm)

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
Hi @danmosemsft 

The current code coverage for Microsoft.Data.SqlClient is currently ~55% ([Internal pipeline report](https://sqlclientdrivers.visualstudio.com/ADO.Net/_build/results?buildId=16625&view=results)).

![image](https://user-images.githubusercontent.com/13396919/66171618-accb4500-e5fd-11e9-914e-ed0142bd6bef.png)


If you agree, we'd like to close the issue and keep working on code coverage improvement as we move forward.

Let us know what you think!

**Comment by danmosemsft** [comment]
That's a big improvement, I think it can be closed now 😸
