### ISSUE TITLE
PlatformNotSupported using Mac OS X and .NET Core 3.1

### ISSUE THREAD

**Issue by marco-bue** [dotnet/SqlClient#561]
The README.md is not very clear about whether .NET Core 3.x and Mac OS X should work, or not. 
I always get a PlatformNotSupportedException:

Unhandled exception. System.PlatformNotSupportedException: Microsoft.Data.SqlClient is not supported on this platform.
   at Microsoft.Data.SqlClient.SqlConnection..ctor(String connectionString)

The FAQ is not really helpful in fixing the problem. It is good to know that there is a fallback DLL that throws a more pretty exception, but is there also any documentation on how to fix this problem?

I am using Microsoft.Data.SqlClient v2.0.0-preview3.20122.2, installed via NuGet.
I am NOT using Azure. It is a simple ASP.NET Core App on a Mac Desktop.

Thank you in advance.

**Comment by Wraith2** [comment]
The nuget restore process should cause the correct binary to be located. Make sure you're building with a target runtime not just a generic build.

**Comment by DavoudEshtehari** [comment]
Hi @marco-bue,

We are preparing to investigate. And we will leave the new updates here.

**Comment by cheenamalhotra** [comment]
Hi @marco-bue 

I tested Microsoft.Data.SqlClient ([v2.0.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.0.0)) on macOS Catalina (version 10.15.1 Beta (19B68f)), and I'm able to connect to SQL Server (in the same network) as well as Azure DB without any issues.

I only tested with console app, but if you can verify your application is using the right DLL from NuGet Package (runtimes\unix\lib\netcoreapp3.1\Microsoft.Data.SqlClient.dll), there should be no problem.

**Comment by cheenamalhotra** [comment]
Closing this issue as not reproducible.
Connectivity works as expected.
