### ISSUE TITLE
Give a way to specify server supplied values using a TVP

### ISSUE THREAD

**Issue by mburbea** [dotnet/SqlClient#57]
Consider a TVP defined like so:
```sql
create type p_tvp as table
(
    id int identity not null,
    value float not null
)
```

Currently, if you have a query using a table value parameter, if the source is a `DataTable` or a `DbDataReader` there seems to be no actual way to use them as parameters for queries using thsi TVP as you either get an error about missing a column if your source only has a double column, or this error `INSERT into an identity column not allowed on table variables.` if you try to pass a value for Id.

There should be a way to specify the mapping. for a TVP in `SqlParameter`.
I propose adding a new method on SqlParameter
```cs
public void AddMetaData(SqlMetaData[] columnMapping)
```
Which would allow you to send in a metadata record for the missing the column(s).

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by benrr101** [comment]
After some digging and testing, it looks like this answer is a suitable workaround for the issue of using TVPs with identity columns as a SqlCommand parameter https://stackoverflow.com/a/10193608

This could be cleaned up a bit if multiple records are needed
```C#
using (var command = connection.CreateCommand())
    {
        command.CommandType = CommandType.StoredProcedure;
        command.CommandText = "dbo.sp_tvpTest";

        // Setup metadata for TVP, indicating useServerDefault
        var sqlMetaData = new[]
        {
            new SqlMetaData("ID", SqlDbType.Int, true, false, SortOrder.Unspecified, -1),
            new SqlMetaData("VALUE", SqlDbType.Float),
        };
        
        // Create record(s) for TVP
        var tvpRecords = new HashSet<SqlDataRecord>();
        var record1 = new SqlDataRecord(sqlMetaData);
        record1.SetDouble(1, 2.34);
        tvpRecords.Add(record1);

        // Assign TVP value to parameter
        var tvpParam = command.CreateParameter();
        tvpParam.ParameterName = "@tvp";
        tvpParam.SqlDbType = SqlDbType.Structured;
        tvpParam.SqlValue = tvpRecords;
        command.Parameters.Add(tvpParam);

        using (var reader = command.ExecuteReader())
        {
            while (reader.Read())
            {
                Console.WriteLine($"Row: {reader.GetInt32(0)}, {reader.GetDouble(1)}");
            }
        }
    }
```

**Comment by David-Engel** [comment]
Closing as not planned.
