### ISSUE TITLE
SqlConnection.GetSchema cannot get procedure parameters with predefined metadata collection name

### ISSUE THREAD

**Issue by mizulily** [dotnet/SqlClient#575]
### Description
I tried to get parameters of sql server procedure, so I used GetSchema method as follow:
`DataTable dt = connection.GetSchema(SqlClientMetaDataCollectionNames.Parameters);`
Then I got an exception telling me the requested collection(Parameters) is not defined.
I am confused because I have already tried collections like Databases/Tables/Procedures/Columns and the collection name is predefined by SqlClientMetaDataCollectionNames class. 

### Configuration
I am using System.Data.SqlClient 4.8.1 from nuget with project configured as .Net Framework 4.7.

### Other information
I reviewed some codes in System.Data and found that this collection name string is both 'ProcedureParameters'  in OLEDB and ODBC connection.
So I tried to type 'ProcedureParameters' string straight as parameter of GetSchema and it worked.
`DataTable dt = connection.GetSchema("ProcedureParameters");`
I think it's a minor bug that you can fix it by updating string mapping in SqlClientMetaDataCollectionNames.cs

**Comment by karinazhou** [comment]
HI @mizulily, 
Can you try Microsoft.Data.SqlClient to see whether this issue can still be reproduced? And also, do you have a standalone app so I can test it locally?

Thanks,

**Comment by mizulily** [comment]
HI @karinazhou ,
Yes, I think "ProcedureParameters" is missing in SqlClientMetaDataCollectionNames.cs
Furthermore, the predefined string "Parameters" is invalid since it will cause exception.

**Comment by karinazhou** [comment]
@mizulily  , I also test it with some old SQL Servers such as 2008, 2012, and 2016. All of them give me the same exception to this `SqlClientMetaDataCollectionNames.Parameters`. 
This will be fixed soon for sure.

**Comment by cheenamalhotra** [comment]
Closing as #580 got merged.
