### ISSUE TITLE
Failed to load SNI.dll (when path contains a #)

### ISSUE THREAD

**Issue by bkohlmaier** [dotnet/SqlClient#589]
When the project path contains a character, which is not a valid URI (in my case a subfolder called "/c#/..."), am Exception will be raised: 
Win32Exception: Failed to load C:\projects\MsSQLSample\x86\SNI.dll

The search path for the SNI.DLL is truncated at the # sign - resulting in a wrong search path.

**Comment by cheenamalhotra** [comment]
Hi @bkohlmaier

Please try the latest preview version (**2.0.0-preview4**) of the driver and let us know if you still face issues. We removed relative path `LoadLibrary()` calls from the driver recently.

**Comment by cheenamalhotra** [comment]
Closing as the issue has been fixed with SNI modifications and does not need additional changes in driver/SNI
