### ISSUE TITLE
Timestamp missing from SqlClientDiagnosticListenerExtensions.WriteCommandBefore telemetry publisher

### ISSUE THREAD

**Issue by anpete** [dotnet/SqlClient#59]
The SqlBeforeExecuteCommand telemetry event is missing the timestamp making it more difficult to compute the duration of executed commands. 

cc @saurabh500

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
This seems like it should be an easy 1-line fix.

**Comment by cheenamalhotra** [comment]
Duplicate of #101 
Closing as issue is fixed and change will be available in next preview release.
