### ISSUE TITLE
Unable to load DLL Microsoft.Data.SqlClient.x86.dll (Exception From HRESULT: 0x800707E)

### ISSUE THREAD

**Issue by qwertybba** [dotnet/SqlClient#592]
### Describe the bug
I am trying to edit connection string on my report using DevExpress winform report wizard 
![EditConnectionString](https://user-images.githubusercontent.com/20028775/83882979-ca2b5280-a73a-11ea-850b-709d99fe51ea.png)
when I click on next button I get this error
![Unable to load DLL](https://user-images.githubusercontent.com/20028775/83883182-0bbbfd80-a73b-11ea-8555-2628a5e99b8b.png)
When I try to install latest stable version of Microsoft.Data.SqlClient 1.1.3 I get two different error
01-With Windows authentication 
![SNINative](https://user-images.githubusercontent.com/20028775/83884636-0fe91a80-a73d-11ea-8de8-01dcd6cdd8ab.png)

02-With Server authentication 
![TdsParser](https://user-images.githubusercontent.com/20028775/83884676-242d1780-a73d-11ea-9c0b-89ca143de8a2.png)

Note: 
-When running the app, all report works fine without any problems.

### Further technical details
Microsoft.Data.SqlClient version: 2.0.0-preview4.20142.4
Microsoft.Data.SqlClient.SNI version: 2.0.0-preview1.20141.10
System.Configuration.ConfigurationManager version: 5.0.0-preview.4.20251.6
.NET target: Framework 4.7.2
SQL Server version: SQL Server 2019
Operating system: Windows 10 Version 2004
DevExpress 20.1.3
Microsoft Visual Studio Enterprise 2019 Preview Version 16.7.0 Preview 2.0

Update:
It is seems to be related to DevExpress version ,I downgrade to version 19.2.8 and all problems are gone.

**Comment by DavoudEshtehari** [comment]
Hi @qwertybba,

I installed the DevExpress(trial) v20.1.4 and Visual Studio community 2019 v16.6.1, but the DevExpress components are not added to the Toolbox and it was not in the component window to add. Can you prepare your repo app here for more investigations?

**Comment by qwertybba** [comment]
> Hi @qwertybba,
> 
> I installed the DevExpress(trial) v20.1.4 and Visual Studio community 2019 v16.6.1, but the DevExpress components are not added to the Toolbox and it was not in the component window to add. Can you prepare your repo app here for more investigations?
Sorry for the delay.
https://github.com/qwertybba/DXApplication1

**Comment by DavoudEshtehari** [comment]
@qwertybba, I am not able to run the sample application. I have an issue with `licenses.licx`. I need a repro app to investigate more.
According to the library you are using is not open source, can I ask you do you follow your issue with the DevExpress support team?

**Comment by qwertybba** [comment]
After contacting the DevExpress support team, advise me to do the following
"I have managed to reproduce this error and found the following workaround:

Open the bin\Debug folder in your project, and copy all files starting with "Microsoft.Data.SqlClient" the "C:\Program Files (x86)\Microsoft Visual Studio\2019[YOUR EDITION NAME]\Common7\IDE\PrivateAssemblies" folder.
Restart Visual Studio."

So I copied these files and the problem was solved
Microsoft.Data.SqlClient.dll
Microsoft.Data.SqlClient.pdb
Microsoft.Data.SqlClient.SNI.x64.dll
Microsoft.Data.SqlClient.SNI.x64.pdb
Microsoft.Data.SqlClient.SNI.x86.dll
Microsoft.Data.SqlClient.SNI.x86.pdb
Microsoft.Data.SqlClient.xml

Big Thanks to DevExpress support team

**Comment by DavoudEshtehari** [comment]
Thank you for the update. So, I am closing this issue.
