### ISSUE TITLE
DbConnectionPool.CleanupCallback with short lived windows impersonation tokens causes kestrel process to crash

### ISSUE THREAD

**Issue by lakeman** [dotnet/SqlClient#60]
Add the following reproducer to an empty dotnet core 2 project and wait for the timer DbConnectionPool.CleanupCallback to fire.
Since the WindowsIdentity token that was being impersonated has now been closed, an ObjectDisposedException will be thrown while attempting to run the timer in the captured execution context.
This causes ExecutionContext.OnContextChanged to call FailFast and crash the process.

```c#
    public class Startup
    {
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddEntityFrameworkSqlServer();
            services.AddDbContextPool<DbContext>(o => {
                var server = "localhost";
                var database = "master";
                o.UseSqlServer($"Server={server};Database={database};integrated security=True;Trusted_Connection=true", options => { } );
            });
        }

        private async Task WhoAmI(HttpContext context)
        {
            var dbContext = context.RequestServices.GetRequiredService<DbContext>();
            var parm = new SqlParameter("name", SqlDbType.VarChar, 50);
            parm.Value = "";
            parm.Direction = ParameterDirection.InputOutput;
            await dbContext.Database.ExecuteSqlCommandAsync("select @name = loginame from master.sys.sysprocesses where spid = @@SPID", parm);
            var name = (parm.Value as string).Trim();
            await context.Response.WriteAsync($"Hello {name}!");
        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            app.Run(context => {
                WindowsIdentity.RunImpersonated(
                    ((WindowsIdentity)context.User.Identity).AccessToken,
                    () => WhoAmI(context).Wait());
                return Task.CompletedTask;
            });
        }
    }
```
Is there an easy way to run this (and any other) timer to avoid capturing the execution context?

[EDIT] Add C# syntax highlighting by @karelz

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
Closing as no longer repro.
