### ISSUE TITLE
Microsoft.Data.SqlClient 2.0.0 A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - )

### ISSUE THREAD

**Issue by hovek** [dotnet/SqlClient#609]
After a NuGet update of Microsoft.Data.SqlClient from 1.1.3 to 2.0.0 I am no longer able to connect to SQL Server 2017 14.0.3294.2 (latest update).
I get an error:  A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - )

Code:

   
```
using (var cnn = new SqlConnection(CreateConnectionString(server, port, LoginDatabaseName, Username, Password)))
            {
                var cmd = new SqlCommand("uspGetDatabasesByLogin", cnn);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.Add(new SqlParameter("@LoginName", login));

                try
                {
                    cnn.Open();
                }
                catch (SqlException ex)
                {
                    //it goes here
                    greska = ex;
                    return ret;
                }
...
```

**Comment by ErikEJ** [comment]
What OS are you using?
Maybe this is relevant: https://github.com/dotnet/SqlClient/issues/567#issuecomment-634390841 ?

**Comment by hovek** [comment]
I am using Windows. When I downgrade to 1.1.3 it all Works fine, so it has to do with the Microsoft.Data.SqlClient 2.0.0.

Poslano iz programa Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> za Windows 10

Pošiljatelj: Erik Ejlskov Jensen<mailto:notifications@github.com>
Poslano:17. lipnja 2020. 14:27
Primatelj: dotnet/SqlClient<mailto:SqlClient@noreply.github.com>
Kopija: hovek<mailto:hove1982@hotmail.com>; Author<mailto:author@noreply.github.com>
Predmet: Re: [dotnet/SqlClient] Microsoft.Data.SqlClient 2.0.0 A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - ) (#609)


What OS are you using?
Maybe this is relevant: #567 (comment)<https://github.com/dotnet/SqlClient/issues/567#issuecomment-634390841> ?

**Comment by cheenamalhotra** [comment]
Hi @hovek 

Please verify if your SQL Server forces encryption:

![image](https://user-images.githubusercontent.com/13396919/84909864-0cbe2a80-b06b-11ea-817e-16e34d4dee25.png)

If **yes**, the driver now will validate server certificate on client systems.

You can try below options:
- Set `Trust Server Certificate = true` on connection string.
- Export SSL Certificate used by SQL Server and install it on Client machine.

This change has been introduced with [v2.0.0-preview2](https://github.com/dotnet/SqlClient/releases/tag/v2.0.0-preview2) as mentioned in release notes (breaking changes).

**Comment by hovek** [comment]
Yes, I set it up to force euncription, years ago and I do not wat to force user machines to trust it, I want it simple and practical and I don't want to pay for expensive trusted certs so, I'll try setting that option in conn str.

lp,
Hrvoje Batrnek
________________________________

**Comment by ErikEJ** [comment]
Maybe it would be helpful to have all breaking changes listed in on place?

**Comment by cheenamalhotra** [comment]
That's been worked upon and will be published on Microsoft Docs soon.

**Comment by ErikEJ** [comment]
I did a PR in the meantime!

**Comment by hovek** [comment]
Maybe exception descriptions should be more accurate,descriptive and maybe give you some pointers. 😉

Poslano iz programa Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> za Windows 10

Pošiljatelj: Erik Ejlskov Jensen<mailto:notifications@github.com>
Poslano:17. lipnja 2020. 19:59
Primatelj: dotnet/SqlClient<mailto:SqlClient@noreply.github.com>
Kopija: hovek<mailto:hove1982@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Predmet: Re: [dotnet/SqlClient] Microsoft.Data.SqlClient 2.0.0 A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - ) (#609)


Maybe it would be helpful to have all breaking changes listed in on place?

**Comment by cheenamalhotra** [comment]
Hi @hovek 

SSL Handshake/Pre-Login errors can occur due to many reasons and if trust was established, we'd receive error code from SQL Server, which is provided in error message. If Error code is 0, that would mean we did not receive response from server as trust could not be established.

**Comment by hovek** [comment]
I know that, I was thinking in general.

Poslano iz programa Pošta<https://go.microsoft.com/fwlink/?LinkId=550986> za Windows 10

Pošiljatelj: Cheena Malhotra<mailto:notifications@github.com>
Poslano:18. lipnja 2020. 1:41
Primatelj: dotnet/SqlClient<mailto:SqlClient@noreply.github.com>
Kopija: hovek<mailto:hove1982@hotmail.com>; Mention<mailto:mention@noreply.github.com>
Predmet: Re: [dotnet/SqlClient] Microsoft.Data.SqlClient 2.0.0 A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: HTTP Provider, error: 0 - ) (#609)


Hi @hovek<https://github.com/hovek>

SSL Handshake/Pre-Login errors can occur due to many reasons and if trust was established, we'd receive error code from SQL Server, which is provided in error message. If Error code is 0, that would mean we did not receive response from server as trust could not be established.

**Comment by cheenamalhotra** [comment]
Could you confirm if the above options worked for you and we are good to close this issue?

**Comment by hovek** [comment]
This works: Set Trust Server Certificate = true on connection string.

lp,
Hrvoje Batrnek
________________________________

**Comment by CumpsD** [comment]
I am having the same issue with `Microsoft.Data.SqlClient 2.0.0` using `AspNetCore.HealthChecks.SqlServer`. 

Our application is running in `mcr.microsoft.com/dotnet/core/runtime-deps:3.1.5` and connects to a standard Azure Sql Server.

It stopped working after upgrading SqClient.

**Comment by ErikEJ** [comment]
@CumpsD your connection string?

**Comment by CumpsD** [comment]
@ErikEJ it was `Server=Xxxx.database.windows.net;Database=Xxxx;User=Xxx@xxx.database.windows.net;Password=Xxxx;`

By adding `Server=Xxxx.database.windows.net;Database=Xxxx;User=Xxx@xxx.database.windows.net;Password=Xxxx;Trust Server Certificate=true;` it works.

**Comment by ErikEJ** [comment]
Thanks, missed your update to your original post

**Comment by cheenamalhotra** [comment]
> `Trust Server Certificate = true;` solved it too for us. Maybe add it to the release notes?

This breaking change is mentioned in release notes, please view them in [2.0.0.md](https://github.com/dotnet/SqlClient/blob/master/release-notes/2.0/2.0.0.md#breaking-changes-1). Since the solution to server certificate validation is respective to customer application requirements, it's in the applications hands which option they would like to choose.

However the solutions are not new when connecting with forced encryption on server, and are same as documented here: [Microsoft Docs: Using Encryption without validation](https://docs.microsoft.com/en-us/sql/relational-databases/native-client/features/using-encryption-without-validation?view=sql-server-ver15)), it was an incorrect driver behavior to not validate server certificate which has been fixed in this release.

We will close the issue as resolved.

**Comment by shaojun** [comment]
could you guys help to take look at this similar issue: https://github.com/microsoft/azuredatastudio/issues/11249#issuecomment-1455376523

**Comment by ErikEJ** [comment]
@shaojun That is not similar, this repo is not for the no longer supported System.Data.SqlClient but for Microsoft.Data.SqlClient

**Comment by shaojun** [comment]
@ErikEJ I've updated to use `Microsoft.Data.SqlClient` and still got the issue for connecting to MS sql server 2008, the details are in the post, could you help to take a look
