### ISSUE TITLE
Investigate if lock statements are necessary in SqlClient.SNITcpHandle's EnableSsl & DisableSsl methods

### ISSUE THREAD

**Issue by corivera** [dotnet/SqlClient#61]
Whenever reads and writes are called on the _stream variable in SNITcpHandle, a lock(this) statement is used. EnableSsl & DisableSsl set the value of _stream without using any lock statements.

CC @saurabh500

**Comment by David-Engel** [comment]
@Wraith2 Did you ever look into this? If so, what did you find? If not, I'll drop this into Future for later.

**Comment by Wraith2** [comment]
I looked but wasn't satisfied that I could prove that a change was desirable. It might be something that is clearer with some of the other managed implementation work in place. I'd recommend marking it as future.

**Comment by David-Engel** [comment]
No issues with current implementation.
