### ISSUE TITLE
Is it possible to add keyword "Command Timeout" to the connection string

### ISSUE THREAD

**Issue by Georgy-Losenkov** [dotnet/SqlClient#614]
Right now the only way to override default value of SqlCommand.CommandTimeout is to do this in code.
It would be nice to do this through connection string/ConnectionStringBuilder/Connection.

**Comment by cheenamalhotra** [comment]
Hi @Georgy-Losenkov 

I believe it should be possible, we'll keep that noted for future enhancements.

**Comment by roji** [comment]
For reference, [Npgsql has this](http://www.npgsql.org/doc/connection-string-parameters.html#timeouts-and-keepalive).

**Comment by ErikEJ** [comment]
Would you consider a community PR for this?

**Comment by ErikEJ** [comment]
Had a quick look, needs design in terns of conflicting values and order of settings values on SqlConnection  and SqlCommand.

**Comment by ErikEJ** [comment]
@roji Can you point me to how you are prioritizing CommandTimeout set via the Connection string vs CommanTimeout set in code?

**Comment by roji** [comment]
In Npgsql, the programmatic NpgsqlCommand.CommandTimeout [takes precedence](https://github.com/npgsql/npgsql/blob/6740134173fe7281f9b03c715eee8a4b6cea454d/src/Npgsql/NpgsqlCommand.cs#L147) over the connection string parameter - as a general rule, programmatic access always overrides connection string parameters (as they can be more specific).

**Comment by ErikEJ** [comment]
@roji Thanks! Will try the same with SqlCommand. Nice #regions 😁

**Comment by ErikEJ** [comment]
API proposal:

   SqlConnectionStringBuilder: public int CommandTimeout { get; set; }

   SqlConnection: public int CommandTimeout { get; }

SqlCommand will use same precedence logic as [here](https://github.com/npgsql/npgsql/blob/6740134173fe7281f9b03c715eee8a4b6cea454d/src/Npgsql/NpgsqlCommand.cs#L147)

**Comment by cheenamalhotra** [comment]
> Would you consider a community PR for this?

That would be great!
As for us, it isn't in the top priority list as of now.

**Comment by ErikEJ** [comment]
I will look into it, I think it would be a very welcome addition, in particular if you are using some library on top of ADO.NET, where it may not be possible for you as a library consumer to modify the command timeout.
