### ISSUE TITLE
No async overload for SqlConnection.Open with SqlConnectionOverrides

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/SqlClient#615]
I'm currently working on consuming the new `Open(SqlConnectionOverrides overrides)` method in EF Core. However, there is no OpenAsync equivalent.

See #29 and https://github.com/dotnet/efcore/issues/7283

**Comment by cheenamalhotra** [comment]
Hi @ajcvickers 

We noticed that the delay of 10 seconds due to transient fault handling did not apply to `OpenAsync()`, hence this option was not introduced to `OpenAsync()` Ref https://github.com/dotnet/SqlClient/pull/463#issue-385867075

**Comment by ajcvickers** [comment]
@cheenamalhotra Missed that--sounds good.
