### ISSUE TITLE
Partial reads in TryReadInt32 query

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#621]
Perhaps I've been staring at the code too long but looking at how the input buffer is accessed in various placed I ended up looking at this part of TdsStateParserObject.TryReadInt32

```csharp
        internal bool TryReadInt32(out int value)
        {
            Debug.Assert(_syncOverAsync || !_asyncReadWithoutSnapshot, "This method is not safe to call when doing sync over async");
            if (((_inBytesUsed + 4) > _inBytesRead) || (_inBytesPacket < 4))
            {
                // If the int isn't fully in the buffer, or if it isn't fully in the packet,
                // then use ReadByteArray since the logic is there to take care of that.

                if (!TryReadByteArray(_bTmp, 4))
                {
                    value = 0;
                    return false;
                }

                AssertValidState();
                value = BitConverter.ToInt32(_bTmp, 0);
                return true;
            }
```

Imagine that we have 2 bytes of an int32 in the end of a packet. The call will find there aren't enough bytes and try to read up to 4 bytes from the buffer with the `TryReadByteArray` call, but it doesn't keep track of how many bytes were read into the buffer or update `_bTmpRead` with that value so the next call when there is another packet available will read start at offset 0 into the array again and overwrite the buffered bytes.

The equivalent segment in TryReadUInt32 is this:

```csharp
            if ((_bTmpRead > 0) || (((_inBytesUsed + 4) > _inBytesRead) || (_inBytesPacket < 4)))
            {
                // If the int isn't fully in the buffer, or if it isn't fully in the packet,
                // then use ReadByteArray since the logic is there to take care of that.

                int bytesRead = 0;
                if (!TryReadByteArray(_bTmp.AsSpan(_bTmpRead), 4 - _bTmpRead, out bytesRead))
                {
                    Debug.Assert(_bTmpRead + bytesRead <= 4, "Read more data than required");
                    _bTmpRead += bytesRead;
                    value = 0;
                    return false;
                }
                else
                {
                    Debug.Assert(_bTmpRead + bytesRead == 4, "TryReadByteArray returned true without reading all data required");
                    _bTmpRead = 0;
                    AssertValidState();
                    value = BitConverter.ToUInt32(_bTmp, 0);
                    return true;
                }
            }
```
which you can see tracks how many bytes were read and takes account of how many were already in the buffer.

Being this intrinsic to the functionality of the driver it seems that this really can't be a bug but I don't understand how it can be made safe. Can anyone explain?

**Comment by cheenamalhotra** [comment]
Hi @Wraith2 

`TryReadByteArray()` takes care of it. If you look at the `while (len > 0)` loop, it continues to fill buffer by calling `TryPrepareBuffer()` as soon as `inBytesPacket` becomes **0** till desired data length is received before sending data to caller to continue data conversion.

```csharp
        // loop through and read up to array length
        while (len > 0)
        {
            if ((_inBytesPacket == 0) || (_inBytesUsed == _inBytesRead))
            {
                if (!TryPrepareBuffer()) // Fills buffer again before getting out of the loop.
                {
                    return false;
                }
            }

            int bytesToRead = Math.Min(len, Math.Min(_inBytesPacket, _inBytesRead - _inBytesUsed));
            Debug.Assert(bytesToRead > 0, "0 byte read in TryReadByteArray");
            if (!buff.IsEmpty)
            {
                var copyFrom = new ReadOnlySpan<byte>(_inBuff, _inBytesUsed, bytesToRead);
                Span<byte> copyTo = buff.Slice(totalRead, bytesToRead);
                copyFrom.CopyTo(copyTo);
            }
            ...
```

The other cases where offsets are maintained is possibly an overhead since `TryReadByteArray()` is supposed to read full data length by itself continuing to fill buffer.

**Comment by Wraith2** [comment]
Sure, but if you've already got 2 bytes in `_bTmp` from a previous partial read TryReadInt32 is going to try to read 4 bytes the next time it's called which will overwrite the two bytes you've already got. 
Rather than `if (!TryReadByteArray(_bTmp, 4))` it should be `if (!TryReadByteArray(_bTmp.AsSpan(_bTmpRead), 4 - _bTmpRead, out bytesRead)))` shouldn't it? Otherwise you ignore the bytes from the previous packet. 

I know that we aren't concatenating packets together so there's no way a partial payload can become a full payload without reconstruction in this temp buffer.

**Comment by cheenamalhotra** [comment]
> if you've already got 2 bytes in _bTmp from a previous partial read ..
> Otherwise you ignore the bytes from the previous packet.

I don't think both statements are true or are even possible since all "TryRead" functions call `TryReadByteArray()` to read data, which won't let the control out until complete read is done by fetching next packet in queue if needed. So there's no way a partial read is let out and offset is needed outside the scope of `TryReadByteArray()`.

To put it simple `_bTmp` would never contain partial bytes from any read operation.

**Comment by Wraith2** [comment]
Ok. Well that answers the question. This code is very confusing.
