### ISSUE TITLE
Microsoft.Data.SqlClient.SNI not deployed along with Teamcity octopack

### ISSUE THREAD

**Issue by knopa** [dotnet/SqlClient#624]
Libraries are in bin folder during build. When prepare to pack it's not included to nuget package.

It use msbuild to build project as I see it start to copy to outputdirectory
![image](https://user-images.githubusercontent.com/1783681/85406649-c8e78b80-b56a-11ea-92ad-9f4b011138c4.png)
than after OctoPack skip it
![image](https://user-images.githubusercontent.com/1783681/85407007-4b704b00-b56b-11ea-9d70-963a1056b76a.png)
![image](https://user-images.githubusercontent.com/1783681/85407062-604cde80-b56b-11ea-9ecc-d51a6bfbe722.png)

P.S I also have reference to System.Data.SqlClient could that affect?

### Further technical details
Microsoft.Data.SqlClient version: 2.0.0
.NET target: Framework 4.8
SQL Server version: SQL Server 2019
Operating system: Windows 2019

**Comment by cheenamalhotra** [comment]
Hi @knopa 

The `Microsoft.Data.SqlClient.SNI.xxx` dlls are Native DLLs that need to copied over explicitly. Commonly needed targets are defined in `Microsoft.Data.SqlClient.SNI.targets` file (included in NuGet), but for other missing cases, you can create targets to copy these native DLLs where needed.

If you can provide us a repro of your app, we can investigate and see if that's something useful to be added to our targets as well.

**Comment by knopa** [comment]
@cheenamalhotra it's not public repo. 
But the issue in another I don't see clear way what kind of target I really need.

**Comment by knopa** [comment]
Workaround - add to msbuild /p:OctoPackEnforceAddingFiles=true
Create in target project nuspec file
`<?xml version="1.0"?>  
<package >  
  <metadata>
    <id>Project</id>
    <version>$version$</version>
    <authors>Project</authors>
    <description>Project deplopyment package</description>
  </metadata>
  <files>
   <file src="bin\*.*" target="bin"></file>
  </files>
</package>  `

**Comment by cheenamalhotra** [comment]
@knopa 

I think that's a valid solution in this case, as documented here: [OctoPack to include buildevent files](https://octopus.com/docs/packaging-applications/create-packages/octopack/octopack-to-include-buildevent-files)

**Comment by cheenamalhotra** [comment]
Closing issue as external, no-op for SqlClient.

**Comment by TrymBeast** [comment]
After having the same issue I've fixed it by setting this property in the csproj:
```xml
<PropertyGroup>
  <ContentSNIFiles>true</ContentSNIFiles>
</PropertyGroup>
```

**Comment by wearerock** [comment]
> After having the same issue I've fixed it by setting this property in the csproj:
> 
> <PropertyGroup>
>   <ContentSNIFiles>true</ContentSNIFiles>
> </PropertyGroup>

I spent one day to find this answer. Thanks a lot.
