### ISSUE TITLE
Not a problem/bug: How does Application Insights plugs in here to report "Dependency"?

### ISSUE THREAD

**Issue by Leonardo-Ferreira** [dotnet/SqlClient#631]
I would like to have my data provider to report "Dependency" as seamlessly as this Data provider does, so I would like to find out how the internals works here so I can replicate over there... can anyone point me a direction?

**Comment by cheenamalhotra** [comment]
Hi @Leonardo-Ferreira 

We put our dependencies in [nuspec file](https://github.com/dotnet/SqlClient/blob/master/tools/specs/Microsoft.Data.SqlClient.nuspec) that's used for creating NuGet package using `nuget pack`.

**Comment by Leonardo-Ferreira** [comment]
@cheenamalhotra thanks for the answer but I must confess I was expecting something completely different... I was expecting something like `take a look at this file on line 188 we use method XYZ to checkout if the domain has the AppInsights dll loaded and if it does we call ABC`

**Comment by cheenamalhotra** [comment]
That job is left to NuGet 😄 

Did that answer your question?

**Comment by Leonardo-Ferreira** [comment]
Actually no... I see nugget as a mean to obtain the APPInsights dll, not a mean to actually write telemetry... where is the "DependencyTelemetry" object instantiated for example?

**Comment by cheenamalhotra** [comment]
Do you have a repro to study your usecase?

**Comment by ErikEJ** [comment]
@Leonardo-Ferreira Is this what you are looking for? https://github.com/microsoft/ApplicationInsights-dotnet/blob/master/WEB/Src/DependencyCollector/DependencyCollector/Implementation/SqlClientDiagnostics/SqlClientDiagnosticSourceListener.cs

**Comment by Leonardo-Ferreira** [comment]
@ErikEJ It does look like it... but it's in a place completely different that I've been looking!

**Comment by ErikEJ** [comment]
Guess you have been looking in the wrong place, then 😊

**Comment by Leonardo-Ferreira** [comment]
yeah, but this placement is very strange... to have the code that handles this on the insights dll is very odd... this means that if every driver wants to be able to be auto-collected by app insights, they would have to alter application insights... very strange...

**Comment by ErikEJ** [comment]
I think App Insights has some extensibility APIs that you can use.

**Comment by cheenamalhotra** [comment]
@Leonardo-Ferreira 

Do you have any further questions, or else we can close this issue?

**Comment by cheenamalhotra** [comment]
Closing this ticket as external.
