### ISSUE TITLE
Use Microsoft.Data.SqlClient with Entity.Framework on NETFX instead of System.Data.SqlClient

### ISSUE THREAD

**Issue by collinstevens** [dotnet/SqlClient#632]
Is there documentation on how to configure Microsoft.Data.SqlClient for Entity.Framework on NETFX instead of using System.Data.SqlClient? I'm attempting to get SQL dependency tracking with Application Insights as documented on https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies#advanced-sql-tracking-to-get-full-sql-query.

**Comment by ajcvickers** [comment]
@collinstevens Vote for https://github.com/dotnet/ef6/issues/823

**Comment by collinstevens** [comment]
> 
> 
> @collinstevens Vote for [dotnet/ef6#823](https://github.com/dotnet/ef6/issues/823)

Ahh great, my Google-fu failed me, thank you.
