### ISSUE TITLE
Documentation on how to use SqlAuthenticationProvider

### ISSUE THREAD

**Issue by aaomidi** [dotnet/SqlClient#640]
How do I register my own AuthenticationProvider? What changes do I need to make to the connection string to call my custom AcquireTokenAsync method?

**Comment by cheenamalhotra** [comment]
Hi @aaomidi 

You'd need to just set provider as I did in example here: [Custom Auth Provider Example](https://github.com/dotnet/SqlClient/blob/f1be61f0debfb8586ea0126d2fa53795b6ffeac9/doc/samples/CustomDeviceCodeFlowAzureAuthenticationProvider.cs).
This example is part of PR #597 so will be published later, but you can refer usecase from here.

Also to mention, we're making "ActiveDirectoryAuthenticationProvider" public soon (with PR #597) so users can override specific properties and let driver take care of the rest.

Please feel free to test and review the PR if it solves the purpose of your overriding and let us know if we can improvise it further :)

Thanks!

**Comment by cheenamalhotra** [comment]
Hi @aaomidi 

Feel free to close the issue, if you like.
We will take care of documentation with the PR #597 :)

**Comment by cheenamalhotra** [comment]
FYI - Documentation Updates follow in this file:
https://github.com/dotnet/SqlClient/pull/597/files#diff-40729a3831f0d4cce99828d5f5f80fb3

**Comment by aaomidi** [comment]
Thank you so much!
