### ISSUE TITLE
Unable to connect to sql database using System.Data.SqlClient 4.4.3 and hostname but ip works 4.4.2 also works

### ISSUE THREAD

**Issue by endasil** [dotnet/SqlClient#651]
I'm running a .net core 3.1 app inside a docker container based on mcr.microsoft.com/dotnet/core/sdk:3.1-bionic (Ubuntu 18.04).   but also tried with mcr.microsoft.com/dotnet/core/sdk:3.1-buster. 

I'm trying to connect to a database with the following code: 
using var connection = new SqlConnection(connectionString);
connection.Open();

If i use If using **System.Data.SqlClient 4.4.3** or higher and use a hostname this will fail with the following error:

    "Microsoft.Data.SqlClient.SqlException (0x80131904): A network-related or in stance-specific error 
    occurred while establishing a connection to SQL Server. The server was not found or was not 
    accessible. Verify that the instance name is correct and that SQL Server is configured to allow 
    remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)" 

if i use an ip adress it works fine.  If i run this outside of a docker container it works fine. My first though was that it was an issue with DNS resolution so i tried `Dns.GetHostAddresses("myhostname");` but it is able to resolve the correct IP from it, 
so that does not seem to be the issue. If i downgrade to **System.Data.SqlClient 4.4.2** my application has no issue connecting to the sql server with hostname. So what change was made in 4.4.3 that could make me have these issues? I can also mention that i tried with Microsoft.Data.SqlClient v2.0.0,  System.Data.SqlClient 4.8.1 and entityFramework with Microsoft.EntityFameworkCore.SqlServer. Same issue. I tried using sqlCmd inside the docker container and it has no problem connecting.

I tried this with two different databases hosted in different places and get it working with one but not the other. I suspect that it is something else than the actual hosting machine that is the issue but posting info anyway for completeness.

```
l Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64) 
Dec 31 2019 22:39:35 
Copyright (c) Microsoft Corporation
Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> 
(Build 14393: ) (Hypervisor)

```

Works with hostname  regardless of SqlCLient version 

```
Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64)
        Dec 31 2019 22:39:35
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64>
 (Build 9600: ) (Hypervisor)

```

Even if some network configuration on the sever side could be a contributing factor to me having this issue, The one factor that remains is that it works with System.Data.SqlClient 4.4.2 but fails with anything above that version. I would really like to understand what is happening. Here is a minimal project that can reproduce the issue. Very basic, so i don't think it is anything in my code that is directly an issue. 
[sql-test.zip](https://github.com/dotnet/SqlClient/files/4930568/sql-test.zip)

**Comment by karinazhou** [comment]
Hi @endasil ,

I am confused by your error message. You are saying that your application uses System.Data.SqlClient but your error message gives a Microsoft.Data.SqlClient.SqlException. These are two different libraries. Have you tried with Microsoft.Data.SqlClient v2.0.0 to see whether you still get the connection error or not? 

The same container works on Windows but failed on Linux. 
-->  this looks strange to me too. Have you tried other docker images instead of this mcr.microsoft.com/dotnet/core/sdk:3.1-bionic ?

And also, it would be helpful if you can provide the repro app.

**Comment by endasil** [comment]
It seems like i can reproduce this on my windows machine too, if just forgot that i had visual studio configured to run my app in IIS mode and not in a container.  Sorry about the confusing error message, I have tried this with  Microsoft.Data.SqlClient v2.0.0 and System.Data.SqlClient is 4.8.1 as well as using entityFramework with Microsoft.EntityFameworkCore.SqlServer.  If i try to use sqltools from within the container i can establish a connection with that. If i try to use a buster image same error.

The reason for talking more specific about  System.Data.SqlClient is that i had one application running that uses it and is able to connec to that database. I compared the projects to find what was different and found that it was the version of System.Data.SqlClient .  It breaks if i try to use  4.4.3 and  works if i use 4.4.2. Is there a way to find out what happened there that could give a hint at what is different? I tried this on another database hosted in the following environment and it works, but i suspect that it has more to do with the network than the machine and database. Just can't figure out why.

Failing with hostname  and SqlClient > 4.4.2

```
l Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64) 
Dec 31 2019 22:39:35 
Copyright (c) Microsoft Corporation
Enterprise Edition (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> 
(Build 14393: ) (Hypervisor)

```

Works with hostname  regardless of SqlCLient version 

```
Microsoft SQL Server 2016 (SP2-GDR) (KB4532097) - 13.0.5102.14 (X64)
        Dec 31 2019 22:39:35
        Copyright (c) Microsoft Corporation
        Standard Edition (64-bit) on Windows Server 2012 R2 Datacenter 6.3 <X64>
 (Build 9600: ) (Hypervisor)

```



 The one factor that remains is that it works with System.Data.SqlClient 4.4.2 but fails with anything above. I would really like to understand what happened there.

**Comment by cheenamalhotra** [comment]
@endasil 

Can you paste full stack trace here?

**Comment by cheenamalhotra** [comment]
Please also explain what is the difference in these 2 hosted SQL Server environments you are connecting to that 1 works and other does not. That might give us some clue what's going on.

Please check below things:
- Are they both hosted on default SQL Server instance?
- You said IP address works, have you tried to connect with "tcp:" appended to hostname or with Port/Instance name specified?
- Are both servers in the same active directory as your client?

**Comment by karinazhou** [comment]
@endasil   
I tested a standalone .NET Core console app with docker support to narrow down the driver issue you have described. The test app simply opens a SqlConnection using server hostname. From my local environment, the connection is always successful when using server hostname with System.Data.SqlClient v4.4.2, v4.4.3, and Microsoft.Data.SqlClient v2.0.0. My server is located in the same domain of my client machine.

I have attached my test app and enabled EventSource tracing so you can test it with your server and collect the tracing information from the console. The tracing could give some hints about what has happened with your server. Please feel free to give it a try.

[netcoreMDS.zip](https://github.com/dotnet/SqlClient/files/4950544/netcoreMDS.zip)

**Comment by karinazhou** [comment]
@endasil  We are closing this issue now due to no activities on this. Please feel free to reopen it if you have any updates.
