### ISSUE TITLE
Microsoft.Data.SqlClient.SNI.pdb not found with V2.0.0

### ISSUE THREAD

**Issue by genifycom** [dotnet/SqlClient#652]
# Issue Title

Just published a console app using Microsoft.Data.SqlClient V2.0.0 and runtime fails to run when: `<PublishSingleFile>true</PublishSingleFile>`

# General

I have tried with and without `<IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile>`

The error is
 An assembly specified in the application dependencies manifest (MyApp.deps.json) was not found:
    package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.0.0'
    path: 'runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.pdb'

For some issues, you will get a quicker and better response if you file it at a more specific [.NET repo](https://github.com/dotnet/core/blob/master/Documentation/core-repos.md). For example, if the problem is with ASP.NET Core, you are encouraged to use the [aspnet/home repo](https://github.com/aspnet/home/issues).

**Comment by cheenamalhotra** [comment]
@genifycom 

Do you still face this issue?
Could you provide us a small repro to demo the error?

**Comment by genifycom** [comment]
The <PublishSingleFile>true</PublishSingleFile> must be placed between the <PropertyGroup> tags and not the <ItemGroup> tags.

Thank you

**Comment by alfeg** [comment]
@cheenamalhotra 
Hi, we have similiar issue with 3rd party libary that started use of `Microsoft.Data.SqlClient v2.0.0`
Here is a issue in corresponding Quartz library with stemp to reproduce https://github.com/quartz-scheduler/quartz/issues/617

**Comment by jjxtra** [comment]
Issue exists in .net 5 rtm release as well, any ideas how to fix?

**Comment by cheenamalhotra** [comment]
Please check your application DOES NOT reference any other custom version of **Microsoft.Data.SqlClient.SNI.runtime** Nuget package. Your dependency hierarchy should be as under with **Microsoft.Data.SqlClient v2.1.0**.

**> Note: Microsoft.Data.SqlClient.SNI.runtime version should be 2.1.1**

![image](https://user-images.githubusercontent.com/13396919/99868411-1ba78c80-2b77-11eb-9b96-8b2a5f5313ff.png)

**Comment by jjxtra** [comment]
I am using ef core 5. Once I manually added the 2.1.1 runtime package, 2.1.0 sqli client package and removed Microsoft.Web.Management nuget package and brought it's source code manually, this error went away.

**Comment by jjxtra** [comment]
Microsoft.EntityFrameworkCore.SqlServer is referecing the wrong Microsoft.Data.SqlClient - 2.0.1, this is where the problem is. Please add that to your project and remove the Microsoft.Data.SqlClient package and you should get the error.

**Comment by mstoicescu** [comment]
Work for me too

**Comment by alejandrorangel-assurant** [comment]
> Microsoft.EntityFrameworkCore.SqlServer 5.0.0 is referecing the wrong Microsoft.Data.SqlClient - 2.0.1, this is where the problem is. Please add that to your project and remove the Microsoft.Data.SqlClient 2.1.0 package and you should get the error.
> 
> Adding both Microsoft.Data.SqlClient 2.1.0 and Microsoft.EntityFrameworkCore.SqlServer 5.0.0 works as well, but it took me several days of troubleshooting to realize this.
> 
> Most people diving into entity framework may only add the entity framework packages and then have headaches with self contained builds. Hopefully next version of sql server entity framework can reference the newer Microsoft.Data.SqlClient 2.1.0.

Thanks for sharing, it worked for me. This is still happening in version 5.0.3 of Microsoft.EntityFrameworkCore.SqlServer, the moment I added the direct reference to Microsoft.Data.SqlClient to my project it automatically refreshed the version inside EF package.

![image](https://user-images.githubusercontent.com/51138640/107695358-789a7680-6c7e-11eb-8ff8-c03b53986062.png)

**Comment by gabrielionita** [comment]
Still happening in Microsoft.EntityFrameworkCore.SqlServer 5.0.5. Added the direct reference to Microsoft.Data.SqlClient 2.1.2 and it worked

**Comment by PylotLight** [comment]
Still an issue on 5.0.8.
Referencing Microsoft.Data.SqlClient 3.0.0 seems to have fixed it as others have suggested though.

**Comment by mihailsidoroff** [comment]
came across on this bug  with <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.9" />
Adding <PackageReference Include="Microsoft.Data.SqlClient" Version="3.0.1" /> fixed it
Thanks, @jjxtra.
