### ISSUE TITLE
Add a method to dump connection pool information

### ISSUE THREAD

**Issue by breakpoint7** [dotnet/SqlClient#655]
In many performance scenarios, it would be extremely helpful to have a simple way to get information on the state of connection pools.  For instance, I want how many connections are pooled and what destinations they represent.  Today, it's difficult to get information on the state of the pools.  Perf counters aren't details enough to be useful and dumping a process isn't always a practical way get this data.  It would be great to have an API that allowed us to query the pool info so we could build telemetry into our apps that quickly and easily showed this information (example - app service extension or profiling library).  
Connection pooling is a really important part of building highly performant apps.  We need to easily see that it's working, whether pools are too big or too small, etc.  Please consider adding a way to get to this info easily.

**Comment by cheenamalhotra** [comment]
HI @breakpoint7 

Microsoft.Data.SqlClient supports [DB Performance Pool counters](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/performance-counters) for .NET Framework (inherited from System.Data.SqlClient).
We also have a story open for supporting EventSource counters in future for .NET Core (#523)

**Comment by breakpoint7** [comment]
Pool counters are helpful, but you can't see detail on the individual pools (e.g. - which connections are getting pooled and which are not).  It would great for perf tuning if there was a way to get a breakdown of the pools.  For example, if you have 40K backend databases and you are trying to tune your pool size - some may need to be bigger than others-- it's nice to know where all the activity is going.

**Comment by cheenamalhotra** [comment]
Hi @breakpoint7 

Since these are counters, they don't really reveal more than numeric data. So even if we scaled counters to reveal info on multiple pools, I wonder how would you match pools to your connection strings to identify which pool corresponds to which database of yours as there can be many variables to pool key (it's a combination of connection string + access token + credentials).

Do you have a proposition to how you'd like to read them so we can review it's feasibility?

**Comment by breakpoint7** [comment]
Ideally, an API that dumped the connection pool info would be perfect.  I'd love to get a dictionary or list of some time that gave me a breakdown of pools with the connection string that is cached, along with the number of connections active.  That way, I could see what pools were actually being at any given time.

**Comment by joymon** [comment]
+1

**Comment by David-Engel** [comment]
Closing this issue in favor of OpenTelemetry #2211.
