### ISSUE TITLE
Expose transaction state on SqlConnection object to avoid server round trip

### ISSUE THREAD

**Issue by shueybubbles** [dotnet/SqlClient#656]
### Is your feature request related to a problem? Please describe.
Today, when the user closes an SSMS query window, SSMS has to query @@trancount to determine if the user has an open transactions. If it returns > 0, SSMS asks the user if they want to commit the transaction before closing the window.
This process can cause SSMS to take a long time to exit, as the connection could fail or timeout and take minutes to do so.
### Describe the solution you'd like
 IIUC, TDS already provides the transaction state to the SqlConnection each time a command completes, so can you expose this state as a public property on the object?

**Comment by JRahnama** [comment]
@shueybubbles,Thanks for reaching out about the request. We will discuss your request and get back to you soon.

**Comment by cheenamalhotra** [comment]
@shueybubbles 

The most relevant token I found was "**[OutstandingRequestCount](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/9f10990a-9c74-4a39-89da-2a3b05effacb)**" which is sent from Client to Server as part of Sql Batch/RPC/Transaction manager request and applies only to **MARS**.

Ref: [MS-TDS Documentation: Transaction Descriptor Header](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-tds/4257dd95-ef6c-4621-b75d-270738487d68)

I don't see any response from Server that corresponds to this information for SQL Batch/RPC/transaction manager response.
Could you point me to right token if I'm missing something?

**Comment by shueybubbles** [comment]
I don't know if it's available, I'm just being hopeful! I may have misunderstood an old email about it.
If it's not available, perhaps you could work with the engine folks to see if a future version of SQL could add it.

**Comment by cheenamalhotra** [comment]
I'm waiting for response internally from SQL side, will update when I get any updates.

**Comment by cheenamalhotra** [comment]
Hi @shueybubbles 

Closing this issue as currently there's no support available from SQL Server.
We'll continue internal conversations and can re-activate this when a possible solution is available.
