### ISSUE TITLE
Changing from System.Data.SqlClient to Microsoft.Data.SqlClient - .NET Framework Connection Strings providerName Attribute

### ISSUE THREAD

**Issue by schmidlkofer** [dotnet/SqlClient#661]
Hello,

Currently when using System.Data.SqlClient, any connection strings I have look like the following:

<add name="name" connectionString="connection string value" providerName="**System.Data.SqlClient**"/>

After changing to Microsoft.Data.SqlClient, does the providerName attribute change?  If so, what should it change to?

Thanks.

**Comment by schmidlkofer** [comment]
Sorry, the sample connection string was lost.  Here it is:

`<add name="name" connectionString="connection string" providerName="**System.Data.SqlClient**"/>`

**Comment by ErikEJ** [comment]
It looks like you are trying to use microsoft.data.sqlclient with Entity Framework "classic" - this is not supported.

**Comment by cheenamalhotra** [comment]
If you own and want to update _app.config_ configurations, then Yes, the provider attribute would need to be changed to "**Microsoft.Data.SqlClient**" and it shall work.

It's tested for both .NET Core and .NET Framework, also discussed in https://github.com/dotnet/SqlClient/issues/239

**Comment by schmidlkofer** [comment]
Hi Cheena,

I made the change.  When testing it out, I got the following error:

System.ArgumentException: Unable to find the requested .Net Framework Data Provider.  It may not be installed.

I presume that means that I also need to add the following to the config file?

```
<system.data>  
  <DbProviderFactories>  
    <add name="SqlClient Data Provider"  
     invariant="Microsoft.Data.SqlClient"   
     description=".Net Framework Data Provider for SqlServer"   
     type="Microsoft.Data.SqlClient.SqlClientFactory, Microsoft.Data.SqlClient,   
     Version=1.0.19269.1, Culture=neutral, PublicKeyToken=****"  
    />  
  </DbProviderFactories>  
</system.data>
```

Note:  I am using .NET Framework

**Comment by cheenamalhotra** [comment]
Yes that entry is needed.
The correct solution is here: https://github.com/dotnet/SqlClient/issues/239#issuecomment-537770942

**Comment by cheenamalhotra** [comment]
Hi @schmidlkofer 

I hope your query is resolved? Feel free to close issue when you get it working.

**Comment by cheenamalhotra** [comment]
Closing as inactive.
