### ISSUE TITLE
Does Microsoft.Data.SqlClient support web.config-based SqlAuthenticationProviders when installed in a .NET Framework app?

### ISSUE THREAD

**Issue by madelson** [dotnet/SqlClient#663]
We're trying to migrate applications to .NET Core and along the way we're looking to switch over to Microsoft.Data.SqlClient.

Some of our apps use this method to set up azure access tokens: https://azure.microsoft.com/en-us/blog/securing-azure-sql-databases-with-managed-identities-just-got-easier/

From looking at the MDSC code, it seems like this will continue to work in a .NET Core app: (https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.NetCoreApp.cs) but may not work if MDSC is installed in a .NET Framework app (https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.NetStandard.cs).

Am I interpreting this correctly? If so, would you recommend that NuGet packages aiming to support both .NET Framework and .NET Core apps use multi-targeting to switch between MDSC and System.Data.SqlClient?

**Comment by cheenamalhotra** [comment]
Hi @madelson 

For .NET Framework, the correct class is here: 
https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlAuthenticationProviderManager.cs

It would work as expected.

However, we are also going to introduce "Azure Managed Identity" authentication support in Microsoft.Data.SqlClient (#616) and it's planned for next release cycle (v2.1.0).

**Comment by cheenamalhotra** [comment]
@madelson 

Waiting for your reply, I hope your query is resolved?

**Comment by cheenamalhotra** [comment]
Closed as inactive.

**Comment by madelson** [comment]
@cheenamalhotra when you say:

> However, we are also going to introduce "Azure Managed Identity" authentication support in Microsoft.Data.SqlClient (#616) and it's planned for next release cycle (v2.1.0).

What will this look like for apps that today use the web.config based approach that want to switch over to .NET core?

**Comment by cheenamalhotra** [comment]
For apps that currently provide web.config as of now in .NET Core, will no longer need to do that.

With #616 being addressed, it will be implemented in the driver and no custom configuration would be needed.
Managed Identity based authentication will work directly with a new Connection String "Authentication" property.

**Comment by madelson** [comment]
Sounds great. Thanks for the additional details!
