### ISSUE TITLE
When targeting Azure, default connection timeout to 30 seconds

### ISSUE THREAD

**Issue by cpujuice** [dotnet/SqlClient#664]
### Is your feature request related to a problem? Please describe.
Connection timeout defaults to 15s right now, but on most documentation it is recommended that it be set to 30s when targeting Azure. We have actually overrode this in SSMS to be 30s, and I'm doing the same thing right now to SqlPackage. It would be great if this was handled natively by SqlClient.

### Describe the solution you'd like
Connection timeout set to 30s when targeting Azure and no timeout was specified

### Describe alternatives you've considered
We can override it but other services might be starting to do the same workaround

### Additional context
None

**Comment by karinazhou** [comment]
Hi @cpujuice ,
We can change the default connection timeout as requested to keep consistent with SSMS and SqlPackage. If I understand it correctly, for the local SQL Server, the default connection time remains 15s. Is the case for SSMS and SqlPackage too?

**Comment by karinazhou** [comment]
And one thing we notice is that we have retry logic in the driver's code when AD interactive mode is used ([AttemptRetryADAuthWithTimeoutError](https://github.com/David-Engel/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlInternalConnectionTds.cs#L1601-L1603)). It looks like less necessary to increase the default connection timeout for AD interactive mode. What do you think?

**Comment by cpujuice** [comment]
Hi @karinazhou 

Actually it seems that SSMS defaults all connections to 30s so my initial statement was not entirely correct. However I still believe it would be a good idea if SqlClient could default Azure connection timeouts to 30s, just because that's the recommended approach on all the docs.

If there's retry logic for AD interactive mode then I agree we won't need to increase the timeout.

**Comment by David-Engel** [comment]
We cannot reliably detect that a connection is trying to connect to an Azure SQL endpoint before we have actually connected. I would be very hesitant to change the default behavior anyway, as that would be a back-compat breaking change in the driver. Given the above info, I don't think it is likely we would ever implement this change.

**Comment by cheenamalhotra** [comment]
Closing feature request.
