### ISSUE TITLE
Request hangup (Task hangup)

### ISSUE THREAD

**Issue by yunfandev** [dotnet/SqlClient#673]
### Describe the bug
We write a web application with AspNetCore 3.1 run on Linux Docker. We found that the client's request occasionally timed out, and the request has reached the backend. The request timed out due to Task hangup

This is a normal request log:
![image](https://user-images.githubusercontent.com/8027453/88670244-63f9f500-d117-11ea-9bee-887c4a53c667.png)

This is a timeout request log:
![image](https://user-images.githubusercontent.com/8027453/88670647-e682b480-d117-11ea-9211-510fd5093b4a.png)

Last line message:

```text
Route matched with {action = "AccountList", controller = "Merchant"}. Executing controller action with signature System.Threading.Tasks.Task`1[WebApi.Core.ResponseResult.DataResponseResult`1[System.Collections.Generic.List`1[WebApi.Services.Merchant.Models.MerchantLightModel]]] AccountList(WebApi.Areas.Merchant.ViewModels.ListAccountViewModel) on controller WebApi.Areas.Merchant.Controllers.MerchantController (WebApi).
```

It seems that the Task has been created, but it is not executed, and no errors are reported.😢😢😢😢

### Exceptions (if any)

Can't find any expection

### Further technical details
- ASP.NET Core version 
  3.1.6
- Include the output of `dotnet --info`

  ```
  Host (useful for support):
    Version: 3.1.6
    Commit:  3acd9b0cd1

  .NET Core SDKs installed:
    No SDKs were found.

  .NET Core runtimes installed:
    Microsoft.AspNetCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
    Microsoft.NETCore.App 3.1.6 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  ```

- The IDE (VS / VS Code/ VS4Mac) you're running on, and it's version
  VS 2019 (16.6.5)

**Comment by roji** [comment]
I've transferred this to the SqlClient repo. @yunfandev definitely try with SqlClient 2.0.0 (or at least with the latest 1.1 if it gives you any issues).

**Comment by yunfandev** [comment]
@roji 

I upgraded to version 1.1.3 and ran it for several hours without any problems.

```bash
> syncblk
Index         SyncBlock MonitorHeld Recursion Owning Thread Info          SyncBlock Owner
-----------------------------
Total           231
Free            163
```

It seems the package Microsoft.Data.SqlClient that the packages that [Microsoft.EntityFrameworkCore.SqlServer](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/3.1.6) depends on need to be upgraded. 😂😂😂

**Comment by ErikEJ** [comment]
Is an update not planned for EF, Core 3.1.7?

**Comment by roji** [comment]
@yunfandev this has been considered (see https://github.com/dotnet/efcore/issues/19962). As a general rule, we don't update dependency versions (e.g. Microsoft.Data.SqlClient) in patch releases, since that may destabilize things (EF Core 5.0 already depends on SqlClient 2.0.0). However, users can always take an explicit dependency on a newer dependency as you've done.

In any case, thanks for confirming that everything works - I'll go ahead and close this.

**Comment by ajcvickers** [comment]
@roji @ErikEJ @yunfandev EF Core 3.1.7 (the next patch release) has been updated to pull in SqlClient 1.1.3. See https://github.com/dotnet/efcore/pull/20377

**Comment by roji** [comment]
@ErikEJ is more up to date than I am...

**Comment by ErikEJ** [comment]
@roji one of my key issues 😄
