### ISSUE TITLE
Microsoft.Data.SqlClient.SNI.pdb gets generated after the update to Microsoft.Data.SqlClient 2.0.0

### ISSUE THREAD

**Issue by kljuco** [dotnet/SqlClient#674]
Our CI pipeline removes all .pdb-s from the publish folder before packaging. After updating `Microsoft.Data.SqlClient 2.0.0` our ASP.net core app stopped working and we figure out that `Microsoft.Data.SqlClient.SNI.pdb` is required in `Release\netcoreapp3.1\runtimes\win-x64\native` in `.deps.json`. 
Is this .pdb really necessary, or is there a workaround for not requiring it?

**Comment by cheenamalhotra** [comment]
Hi @kljuco 

Based on discussions here: https://github.com/dotnet/SqlClient/issues/644#issuecomment-659064214, we're planning to remove symbols in .NET Core native (SNI) NuGet. It's not required by driver, they're linked in deps.json from where without them publish doesn't happen. It's different how dotnet sdk handles PDBs for native-runtime v/s .net runtime packages.

**Comment by kljuco** [comment]
Great. Thank you :)
