### ISSUE TITLE
No Application Insights telemetry in 2.0.0 when using EF Core & net48

### ISSUE THREAD

**Issue by Rans4ckeR** [dotnet/SqlClient#678]
### Description
Microsoft.Data.SqlClient 2.0.0 does not generate SQL telemetry when using EF Core where Microsoft.Data.SqlClient 1.1.3 is working fine using the same packages and configuration. To be clear I'm not talking about SQL queries, just the basic SQL telemetry.
-When using ADO.NET instead of EF Core telemetry is generated as expected.
-All other Application Insights telemetry is working fine in all scenarios.

### Non working scenarios
The following scenarios are not working for me unless I switch to Microsoft.Data.SqlClient 1.1.3:

1) WCF service
-net48
-Microsoft.Data.SqlClient 2.0.0
-Microsoft.ApplicationInsights.Wcf 0.28.0-build06820
-Microsoft.ApplicationInsights.WindowsServer 2.14.0
-Microsoft.EntityFrameworkCore.SqlServer 3.1.6
2) Windows service
-net48
-Microsoft.Data.SqlClient 2.0.0
-Microsoft.ApplicationInsights.WorkerService 2.14.0
-Microsoft.EntityFrameworkCore.SqlServer 3.1.6

### Working scenarios (same configuration and package versions)
-Microsoft.Data.SqlClient 2.0.0 is working when using ADO.NET instead of EF Core.
-Microsoft.Data.SqlClient 2.0.0 is working in netcoreapp2.2 applications using Microsoft.ApplicationInsights.AspNetCore 2.14.0.
-Microsoft.Data.SqlClient 1.1.3 is working with EF Core.

### ApplicationInsights.config for WCF service:
`<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <InstrumentationKey></InstrumentationKey>
  <TelemetryInitializers>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureWebAppRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.OperationNameTelemetryInitializer, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.OperationCorrelationTelemetryInitializer, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.UserTelemetryInitializer, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.UserAgentTelemetryInitializer, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.ClientIpTelemetryInitializer, Microsoft.AI.Wcf"/>
    <Add Type="Bel.Common.Infrastructure.Telemetry.CloudRoleNameTelemetryInitializer, Bel.Common.Infrastructure.Telemetry"/>
  </TelemetryInitializers>
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <ExcludeComponentCorrelationHttpHeadersOnDomains>
        <Add>core.windows.net</Add>
        <Add>core.chinacloudapi.cn</Add>
        <Add>core.cloudapi.de</Add>
        <Add>core.usgovcloudapi.net</Add>
      </ExcludeComponentCorrelationHttpHeadersOnDomains>
      <IncludeDiagnosticSourceActivities>
        <Add>Microsoft.Azure.EventHubs</Add>
        <Add>Microsoft.Azure.ServiceBus</Add>
      </IncludeDiagnosticSourceActivities>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AppServicesHeartbeatTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureInstanceMetadataTelemetryModule, Microsoft.AI.WindowsServer">
    </Add>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DeveloperModeWithDebuggerAttachedTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnhandledExceptionTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnobservedExceptionTelemetryModule, Microsoft.AI.WindowsServer">
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Wcf.RequestTrackingTelemetryModule, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.ExceptionTrackingTelemetryModule, Microsoft.AI.Wcf"/>
    <Add Type="Microsoft.ApplicationInsights.Wcf.WcfDependencyTrackingTelemetryModule, Microsoft.AI.Wcf"/>
  </TelemetryModules>
  <ApplicationIdProvider Type="Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider, Microsoft.ApplicationInsights"/>
  <TelemetrySinks>
    <Add Name="default">
      <TelemetryProcessors>
        <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
        <Add Type="Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor, Microsoft.ApplicationInsights"/>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
          <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
          <ExcludedTypes>Event</ExcludedTypes>
        </Add>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
          <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
          <IncludedTypes>Event</IncludedTypes>
        </Add>
      </TelemetryProcessors>
      <TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
    </Add>
  </TelemetrySinks>
</ApplicationInsights>`

### ApplicationInsights.config for Windows service:
`<?xml version="1.0" encoding="utf-8"?>
<ApplicationInsights xmlns="http://schemas.microsoft.com/ApplicationInsights/2013/Settings">
  <InstrumentationKey></InstrumentationKey>
  <TelemetryInitializers>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.HttpDependenciesParsingTelemetryInitializer, Microsoft.AI.DependencyCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureWebAppRoleEnvironmentTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.BuildInfoConfigComponentVersionTelemetryInitializer, Microsoft.AI.WindowsServer"/>
    <Add Type="Bel.Common.Infrastructure.Telemetry.CloudRoleNameTelemetryInitializer, Bel.Common.Infrastructure.Telemetry"/>
  </TelemetryInitializers>
  <TelemetryModules>
    <Add Type="Microsoft.ApplicationInsights.DependencyCollector.DependencyTrackingTelemetryModule, Microsoft.AI.DependencyCollector">
      <ExcludeComponentCorrelationHttpHeadersOnDomains>
        <Add>core.windows.net</Add>
        <Add>core.chinacloudapi.cn</Add>
        <Add>core.cloudapi.de</Add>
        <Add>core.usgovcloudapi.net</Add>
      </ExcludeComponentCorrelationHttpHeadersOnDomains>
      <IncludeDiagnosticSourceActivities>
        <Add>Microsoft.Azure.EventHubs</Add>
        <Add>Microsoft.Azure.ServiceBus</Add>
      </IncludeDiagnosticSourceActivities>
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.PerformanceCollectorModule, Microsoft.AI.PerfCounterCollector">
    </Add>
    <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryModule, Microsoft.AI.PerfCounterCollector"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AppServicesHeartbeatTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.AzureInstanceMetadataTelemetryModule, Microsoft.AI.WindowsServer">
    </Add>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.DeveloperModeWithDebuggerAttachedTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnhandledExceptionTelemetryModule, Microsoft.AI.WindowsServer"/>
    <Add Type="Microsoft.ApplicationInsights.WindowsServer.UnobservedExceptionTelemetryModule, Microsoft.AI.WindowsServer">
    </Add>
  </TelemetryModules>
  <ApplicationIdProvider Type="Microsoft.ApplicationInsights.Extensibility.Implementation.ApplicationId.ApplicationInsightsApplicationIdProvider, Microsoft.ApplicationInsights"/>
  <TelemetrySinks>
    <Add Name="default">
      <TelemetryProcessors>
        <Add Type="Microsoft.ApplicationInsights.Extensibility.PerfCounterCollector.QuickPulse.QuickPulseTelemetryProcessor, Microsoft.AI.PerfCounterCollector"/>
        <Add Type="Microsoft.ApplicationInsights.Extensibility.AutocollectedMetricsExtractor, Microsoft.ApplicationInsights"/>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
          <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
          <ExcludedTypes>Event</ExcludedTypes>
        </Add>
        <Add Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.AdaptiveSamplingTelemetryProcessor, Microsoft.AI.ServerTelemetryChannel">
          <MaxTelemetryItemsPerSecond>5</MaxTelemetryItemsPerSecond>
          <IncludedTypes>Event</IncludedTypes>
        </Add>
      </TelemetryProcessors>
      <TelemetryChannel Type="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel.ServerTelemetryChannel, Microsoft.AI.ServerTelemetryChannel"/>
    </Add>
  </TelemetrySinks>
</ApplicationInsights>`

### Expected behavior
Application Insights AppDependencies telemetry for type SQL are generated in all scenarios.

### Further technical details
Microsoft.Data.SqlClient version: 2.0.0
.NET target: Framework 4.8
SQL Server version: SQL Server 2012
Operating system: Windows 10, Windows Server 2012R2

**Comment by JRahnama** [comment]
@Rans4ckeR, Thanks for reaching out to us regarding this issue. We will look into the problem and get back to you soon.

**Comment by karinazhou** [comment]
Hi @Rans4ckeR , do you have the repro application for both working and non-working scenarios? It will be very helpful to investigate this issue locally.

**Comment by Rans4ckeR** [comment]
Hi @karinazhou, see attachment.

It contains a WCF service with a simple EF Core 3.1.6 model & Microsoft.Data.SqlClient 2.0.0 where SQL telemetry is not being sent.

To make SQL telemetry work change the Microsoft.Data.SqlClient PackageReference version to 1.1.3 in the project file and also replace the binding redirect in Web.config. I added both of these already as comments into said files for your convenience.

Observe the output window for SQL telemetry when making a request to confirm the findings.

[WcfService2.zip](https://github.com/dotnet/SqlClient/files/5044087/WcfService2.zip)

**Comment by karinazhou** [comment]
Hi @Rans4ckeR ,

Sorry for the late reply. I finally got a chance to test your repo app. However, I cannot run it from the WCF test client due to the following error message:

`This operation is not supported in the WCF Test Client because it uses type System.Threading.Tasks.Task`

Do you have the client application to test with?

**Comment by Rans4ckeR** [comment]
@karinazhou this is the case for all WCF services. You cannot call operations with the Async suffix in the WCF Test Client (They technically also are no part of the soap contract). Instead you should just invoke the same operation without the Async suffix from the WCF Test Client. This will cause the operation with or without the Async suffix, whichever is implemented in the service, to be invoked in the service.

**Comment by karinazhou** [comment]
@Rans4ckeR  Thank you for the explanation. As you suggested, I invoke the GetData() operation but I get the following error:

![image](https://user-images.githubusercontent.com/27743156/91236829-e3b2b980-e6ed-11ea-9cfb-7eace351c680.png)

I am new to this area so I would like to check it with you whether this is expected?

Though I get the error from the WCF test client, I look at the output window from the service project and find something related to the SQL Telemetry you mentioned at the beginning. 

When using MDS v1.1.3, I can see such information:
```
Application Insights Telemetry (unconfigured): {"name":"AppDependencies", ... , ,"resultCode":"208","success":false,"type":"SQL","target":"localhost | MyTest","properties":{"DeveloperMode":"true","_MS.ProcessedByMetricExtractors":"(Name:'Dependencies', Ver:'1.1')"}}}}
```

However, no such Application Insights Telemetry is seen after I switch to MDS v2.0.0. Is this the entry you are looking for?

I go through your issue description and find this line:
> Microsoft.Data.SqlClient 2.0.0 is working when using ADO.NET instead of EF Core.

Do you also have the repo for this scenario?

**Comment by Rans4ckeR** [comment]
Hi @karinazhou,

> As you suggested, I invoke the GetData() operation but I get the following error:

The error is expected since the physical database does not exist on your local machine. The database is not actually needed while testing this issue. You can expose the error to the client by updating the config:
`<serviceDebug includeExceptionDetailInFaults="true"/>`

If you want to have the db, this should create it:
CREATE DATABASE [DB1]
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

> However, no such Application Insights Telemetry is seen after I switch to MDS v2.0.0. Is this the entry you are looking for?

You have indeed successfully reproduced it.

> Do you also have the repo for this scenario?

I attached a working scenario using net48, ADO.NET & MDS v2.0.0.
[WcfService2.zip](https://github.com/dotnet/SqlClient/files/5128607/WcfService2.zip)

**Comment by karinazhou** [comment]
@Rans4ckeR    Thank you! I will try the working scenario.

So far, I have tested different driver versions with EF Core v3.1.6 and find the last working driver version is 
`2.0.0-preview1.20021.1`.
Starting from `2.0.0-preview2.20084.1`, I can not see `AppDependencies` info anymore. This makes me suspect that any commits in-between may cause this change.

**Comment by Rans4ckeR** [comment]
> I tried your working scenario. In fact, you are using System.Data.SqlClient instead of Microsoft.Data.SqlClient in your project. After I changed it to MDS, I couldn't see the AppDependencies from output.

@karinazhou indeed I missed the fact that it was using the wrong namespace, my bad.

**Comment by karinazhou** [comment]
@Rans4ckeR 
After some investigation, we find that the `AppDependencies` starts disappearing after we added EventSource support in .NET Framework:
https://github.com/dotnet/SqlClient/commit/791258132fa4782ef3f0f378ab5d4780b3d945c1

As what you have mentioned in the description, it generates the `AppDependencies` when using MDS v2.0.0 with .netcoreapp application:
> -Microsoft.Data.SqlClient 2.0.0 is working in netcoreapp2.2 applications using Microsoft.ApplicationInsights.AspNetCore 2.14.0.

We also have EventSource support on .NET Core. It is still a mystery to us why EventSource causes Application Insight doesn't catch SQL Telemetry in .NET Framework.

**Comment by karinazhou** [comment]
@Rans4ckeR 
After digging mote into this, I find the reason for this missing `AppDependencies` issue. 

While adding EventSource support in MDS, we changed the EventSource name from `Microsoft-AdoNet-SystemData` to `Microsoft.Data.SqlClient.EventSource`. The purpose is to distinguish MDS from System.Data.SqlClient. 

![image](https://user-images.githubusercontent.com/27743156/92276736-700b6c00-eea6-11ea-82b4-bd2a5dcb1b35.png)

https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlClientEventSource.cs#L10

However, from the ApplicationInsight.DependencyCollector, there is a hard-coded name `Microsoft-AdoNet-SystemData` for `AdoNetEventSourceName`:

https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/DependencyCollector/DependencyCollector/Implementation/FrameworkSqlEventListener.cs#L24

I am afraid that `AppDependencies` entry won't be captured unless ApplicationInsights changes their way to capture this EventSource with a new name.

**Comment by ErikEJ** [comment]
Is this only a .NET FX issue, or .NET Core also?

**Comment by Rans4ckeR** [comment]
@ErikEJ .NET FX only. Using .NET Core everything works fine.
@karinazhou Thanks for investigating.

**Comment by karinazhou** [comment]
No problem. I will open an issue to ApplicationInsights regarding this.

**Comment by karinazhou** [comment]
@Rans4ckeR  Since we now have another ticket to track this issue, we are closing this one. Please feel free to reopen it if you want.
