### ISSUE TITLE
System.Data.SqlClient clarify SqlDataReader get char

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#68]
Sql Server doesn't have an individual char datatype and in desktop .net the [`SqlDataReader.GetChar`](https://referencesource.microsoft.com/#System.Data/System/Data/SqlClient/SqlDataReader.cs,1930) is marked as not browsable and implemented as a `NotSupportedException`. The version in this repository lacks the browsable attribute (in src and ref) and I think it should be re-added.

The documentation for [`SqlDataReader.GetFieldValue<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.data.sqlclient.sqldatareader.getchar?view=netcore-2.2) lists char as one of the permitted types but it will not work, there is no metadata support or way to get a char from the database. This means it will always throw an `InvalidCastException` and I believe it should throw `NotSupportedException` where T is char to align with `GetChar`. This would be a behaviour change and need adding to the documentation.

@saurabh500 @AfsanehR @tarikulsabbir

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by initram** [comment]
It seems that part of this issue has been resolved already, as `GetChar` has already been marked as not editor browsable in #180 .
see https://github.com/dotnet/SqlClient/blame/master/src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.cs#L935
The changes to the exception behaviors, do not seem to have been accepted. So what part of this issue is "up for grabs"?
Does the attribute need to be added in other files?

**Comment by Wraith2** [comment]
If you've checked and I hid it but didn't close this issue then it's closable now.

**Comment by cheenamalhotra** [comment]
Thanks @Wraith2 for confirming, we'll close this thread then.
