### ISSUE TITLE
CacheConnectionStringProperties is called twice when initializing SqlConnection.

### ISSUE THREAD

**Issue by TrayanZapryanov** [dotnet/SqlClient#680]
When calling any constructor of **SqlConnection** - there is an explicit call of **CacheConnectionStringProperties**.
This looks redundant as both ctor's are setting property **ConnectionString** and there is a call in it's set method.
I hope that I've read correctly the code, if not please excuse me and close the issue.

**Comment by JRahnama** [comment]
@TrayanZapryanov by saying any constructor you mean I can see the issue on ` new SqlConnection(sourceString.ConnectionString)` for example?
If the answer is no, can you kindly provide the repro/cpde sample that you were looking at while facing the issue?

And second is it happening at netcore or dotnet framework?

**Comment by TrayanZapryanov** [comment]
I've mean both public constructors in netcore:
[https://github.com/dotnet/SqlClient/blob/dbbcde899c646df362ac8369f2d1edd82437759f/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L117](url)

and

[https://github.com/dotnet/SqlClient/blob/dbbcde899c646df362ac8369f2d1edd82437759f/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L160](url)

Although same is valid and for dotnet framework.

**Comment by karinazhou** [comment]
Hi @TrayanZapryanov ,

Thank you for pointing this out. I agree that there are additional calls of CacheConnectionStringProperties in some SqlConnection constructors after setting ConnectionString property.
