### ISSUE TITLE
SqlClient: Command execution failures when using Packet Size = 16388 with Encryption

### ISSUE THREAD

**Issue by corivera** [dotnet/SqlClient#69]
When setting the packet size to 16388 or higher while using encryption, command execution fails. This issue is present with both managed and native SNI, and with TCP & NP. Failures also happen with sync & async command execution.

With native SNI:
System.Data.SqlClient.SqlException : A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 0 - The specified network name is no longer available.)
        ---- System.ComponentModel.Win32Exception : The specified network name is no longer available

With managed SNI:
System.Data.SqlClient.SqlException : A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught)
        ---- System.IO.IOException : Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.
        -------- System.Net.Sockets.SocketException : An existing connection was forcibly closed by the remote host

CC @saurabh500 @geleems

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
@corivera #69 with the same issue information. Would that work in your case?

**Comment by corivera** [comment]
@cheenamalhotra No idea, I didn't investigate this issue very much.

**Comment by David-Engel** [comment]
Closing as there is nothing to do here.
