### ISSUE TITLE
Investigate Quartz library issue with Microsoft.Data.SqlClient v2.0.0

### ISSUE THREAD

**Issue by cheenamalhotra** [dotnet/SqlClient#691]
_Originally posted by @alfeg in https://github.com/dotnet/SqlClient/issues/652#issuecomment-672950367_

Hi, we have similar issue with 3rd party library that started use of `Microsoft.Data.SqlClient v2.0.0`
Here is a issue in corresponding Quartz library with steps to reproduce https://github.com/quartz-scheduler/quartz/issues/617

cc @JRahnama @karinazhou

**Comment by karinazhou** [comment]
Hi @alfeg ,

I tested your repo steps in https://github.com/quartz-scheduler/quartz/issues/617 . If I use the following commands to create the web app and publish the executable, I can see the Assembly error as described. 

```
Error:
  An assembly specified in the application dependencies manifest (GH691.deps.json) was not found:
    package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.0.0'
    path: 'runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.pdb'
```

I checked the csproj file and there is no `<PublishSingleFile>` tag added inside the `PropertyGroup`. After I added the `PublishSingleFile`, I didn't see the assembly error any more:

```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <PublishSingleFile>True</PublishSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Quartz" Version="3.1.0" />
  </ItemGroup>

</Project>
```

Instead, I get the following message:

```
Failure processing application bundle.
Bundle header version compatibility check failed
A fatal error was encountered. Could not extract contents of the bundle
```

If I set `<PublishSingleFile>False</PublishSingleFile>` , I get the web app running without issue.

FYI We are going to remove pdb files from the native runtime SNI nuget package in the future so it should be able to solve any issues caused by the pdb.

**Comment by mwmccallum** [comment]
> Hi @alfeg ,
> 
> I tested your repo steps in [quartz-scheduler/quartz#617](https://github.com/quartz-scheduler/quartz/issues/617) . If I use the following commands to create the web app and publish the executable, I can see the Assembly error as described.
> 
> ```
> dotnet new web
> dotnet add package Quartz
> dotnet publish -c Release -r win-x64 /p:PublishSingleFile=True -o dist
> .\dist\GH691.exe
> ```
> 
> ```
> Error:
>   An assembly specified in the application dependencies manifest (GH691.deps.json) was not found:
>     package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.0.0'
>     path: 'runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.pdb'
> ```
> 
> I checked the csproj file and there is no `<PublishSingleFile>` tag added inside the `PropertyGroup`. After I added the `PublishSingleFile`, I didn't see the assembly error any more:
> 
> ```
> <Project Sdk="Microsoft.NET.Sdk.Web">
> 
>   <PropertyGroup>
>     <TargetFramework>netcoreapp3.1</TargetFramework>
>     <PublishSingleFile>True</PublishSingleFile>
>   </PropertyGroup>
> 
>   <ItemGroup>
>     <PackageReference Include="Quartz" Version="3.1.0" />
>   </ItemGroup>
> 
> </Project>
> ```
> 
> Instead, I get the following message:
> 
> ```
> Failure processing application bundle.
> Bundle header version compatibility check failed
> A fatal error was encountered. Could not extract contents of the bundle
> ```
> 
> If I set `<PublishSingleFile>False</PublishSingleFile>` , I get the web app running without issue.
> 
> FYI We are going to remove pdb files from the native runtime SNI nuget package in the future so it should be able to solve any issues caused by the pdb.

When is this change (removing pdb dependency) going to be implemented/deployed? This prevents MSIX projects from working properly because the pdb is not deployed in MSIX. So client throws dependency error when executed.

Thanks, Mike

**Comment by cheenamalhotra** [comment]
Hi @mwmccallum 

We're planning to address this change with next preview release of Microsoft.Data.SqlClient **v2.1.0-preview2**.

**Comment by cheenamalhotra** [comment]
Closing this issue as pdbs have been removed from [Microsoft.Data.SqlClient.SNI.runtime v2.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI.runtime/2.1.1) to be picked by [Microsoft.Data.SqlClient v2.1.0-preview2](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0-preview2.20297.7) onwards.

**Comment by jjxtra** [comment]
Rolling back to 3.1.8 version of entity framework nugets fixed the error for me in .NET 5 rtm release.
