### ISSUE TITLE
Including Microsoft.Data.SqlClient.SNI dll files in MS Installer project

### ISSUE THREAD

**Issue by SuliemanMansouri** [dotnet/SqlClient#694]
I am building a winform application and used nuget package Microsoft.SqlServer.SqlManagementObjects Which depends on Microsoft.Data.SqlClient.
When creating setup files for my project the files Microsoft.Data.SqlClient.SNI are not included in the detected dependencies. I have to add them manually as files to my setup package.

I am using VS2019 CE 16.7.1
SQL EE 2019
MS Visual Studio Installer Project Ver: 0.9.8
Microsoft.SqlServer.SqlManagementObjects Ver: 161.41011.9
.Net Framework 4.7.1

I am not sure if this is the appropriate repository to submit the issue to. But I had to start somewhere, so I decided to start from the bottom up.

Cheers

**Comment by JRahnama** [comment]
Hi @SuliemanMansouri can you try with Microsoft.SqlServer.SqlManagementObjects version: 161.41981.14-msdata? I tested with this and it worked fine. I will test with the older version to see if the problem comes up or no.

**Comment by SuliemanMansouri** [comment]
Hi @JRahnama, tried that still no luck. The files are present in my build folder but will not be included in the detected dependencies.

**Comment by JRahnama** [comment]
@SuliemanMansouri can you walk me through your application? How can I start the app the way you did or if you can make me a repro to see the steps?

**Comment by SuliemanMansouri** [comment]
@JRahnama 
I noticed that when installing Microsoft.SqlServer.SqlManagementObjects, I can see that sqlClient.SNI is successfully added to my packages but doesn't show up in my reference tree.
Opening the packages folder the files are there but are not included in my project references.
To reproduce the problem :
Create WinForms Application .NET 4.7.2
Install  Microsoft.SqlServer.SqlManagementObjects.161.42121.15-msdata.
You can see in the Output screen for Package Manager that SNI is added

"Added package 'Microsoft.Data.SqlClient.SNI.2.0.0' to 'packages.config'
Successfully installed 'Microsoft.Data.SqlClient.SNI 2.0.0' to WindowsFormsApp2"

Check the References node in your project the files are not listed.
Trying to add the files to the references by browsing to either one of the package folder \build or \buildTransitive and selecting the files will result in the following error:
![image](https://user-images.githubusercontent.com/12877044/90705432-337b2600-e293-11ea-949b-5c22e012c139.png)

Since the files are not listed in the references they won't be added to my Install project when detecting dependencies for my assembly. 
Fro now I am adding them manually to my setup project from my build folder

**Comment by cheenamalhotra** [comment]
@SuliemanMansouri 

SNI DLLs are Native C++ DLLs, so they need to be treated that way. Unfortunately dotnet sdk doesn't work nicely with native C++ DLLs when referencing .NET Framework, so we provide targets files (included in NuGets) and copy DLLs to target locations.
Since they're not .NET libraries hence not provided in "lib" folder but in "build" and "buildTransitive" folders.

We will look more into issues when SMO is referenced in WebForms, but just wanted to mention that to clear any doubts.

**Comment by SuliemanMansouri** [comment]
@cheenamalhotra 
Thanks for the clarification. I guess that my solution for now is my only option.
