### ISSUE TITLE
v2.1.0 preview on Nuget as release?

### ISSUE THREAD

**Issue by snekbaev** [dotnet/SqlClient#709]
Hi,

noticed the 2.1.0 version on Nuget in VS offered as an update for 2.0.0 ("Include prelease" checkbox is unchecked), thought it was a release and decided to read what's new, however, it seems to be a preview version?

Thank you!

**Comment by JRahnama** [comment]
@snekbaev, you are right. Version 2.1.0-preview1.20235.1 as the name indicates is a preview release.  You can follow our releases in [Nuger.org](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0-preview1.20235.1). 

I tried the following steps:

- created a new app

- Added Microsoft.Data.SqlClient v2.0.0.0 as a dependency.

- tried to update nugets without including the prerelease versions(checkbox):

![image](https://user-images.githubusercontent.com/32077152/91066827-04dcb280-e5e7-11ea-8064-37af3d6ee170.png)

- When I marked the checkbox, as expected, I got the following updates:

![image](https://user-images.githubusercontent.com/32077152/91067015-3f464f80-e5e7-11ea-9f7b-d2a566ed2f1c.png)

Am I following you correct? If not, can you provide me a repro that I can see your steps and the application to understand better please?

All preview and stable driver release notes are available under [release-notes](https://github.com/dotnet/SqlClient/tree/master/release-notes).

**Comment by snekbaev** [comment]
@JRahnama well, that's interesting as my VS (16.7.2) is showing me this view:

![image](https://user-images.githubusercontent.com/6025502/91069367-fbcb0000-e63d-11ea-9b1c-d9d9c9001f5d.png)

Curious why though...

**Comment by JRahnama** [comment]
Microsoft.Data.Sqlclient.SNI is a separate dependency package for M.D.S. and its latest version is indeed 2.1.0. that is different than Microsoft.Data.Sqlclient. Basically SNI contains Native C++ DLLs which are consumed by M.D.S. You can see them [here](https://github.com/dotnet/SqlClient#sni-package-references).

**Comment by snekbaev** [comment]
@JRahnama I see, thought those dependencies go hand in hand, also it being 2.1 and current SqlClient being 2.1-preview added to the confusion. All is good then, will update it. Thanks!
