### ISSUE TITLE
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning() silently swallows error conditions

### ISSUE THREAD

**Issue by Dmitry-Me** [dotnet/SqlClient#71]
`System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning()` has a Debug.Assert check that the errors connection is not empty and also this excellent `if`:

```
 SqlConnection exception = null;
 //later...
 if (temp != null && temp.Count > 0)
      //craft exception
 }

 //later ...
 if (exception != null ) {
     //do a lot of cool stuff
 } // else do nothing
```

which means that allowing to have this function called when there're no elements in `temp` leads to a logical error - no error indication is given and the connection is just silently closed.

Those `Debug.Assert`s should instead throw something like `InvalidOperationException`.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
Closing as not planned.
