### ISSUE TITLE
Microsoft.Data.SqlClient.SNI.pdb is now included in nuget microsoft.data.sqlclient.sni.runtime and it's causing problem when packaging MSIX

### ISSUE THREAD

**Issue by dandesro71** [dotnet/SqlClient#711]
Since Microsoft.Data.SqlClient 2.0, Microsoft.Data.SqlClient.SNI.pdb is included in nuget package microsoft.data.sqlclient.sni.runtime. 

When packaging (MSIX or AppBundle) my application (.NET Core 3.1), Visual Studio is removing all the .pdb files from the installation package, but the "*.deps.json" still contains a reference to the Microsoft.Data.SqlClient.SNI.pdb.

After the installation of the MSIX package, the application doesn't start because there is a missing file that is referenced in its *.deps.json.

In the Event Viewer, we have the following error:

Description: A .NET Core application failed.
Application: Composer.exe
Path: C:\Program Files\WindowsApps\Composer_20.0.28.0_neutral__10zv4tmbkprx6\Composer-Core\Composer.exe
Message: Error:
  An assembly specified in the application dependencies manifest (Composer.deps.json) was not found:
    package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.1.0'
    path: 'runtimes/win-x86/native/Microsoft.Data.SqlClient.SNI.pdb'

Is it possible to remove the .pdb files in future release? For now, I need to use Microsoft.Data.SqlClient 2.0.0-preview4.20142.4, that was the last version that worked.

**Comment by cheenamalhotra** [comment]
Hi @dandesro71 

Yes, that's in plan and as also discussed in https://github.com/dotnet/SqlClient/issues/644#issuecomment-659064214

**Comment by dandesro71** [comment]
Ok, I'll stop searching for a solution or workaround and I'll wait for a future correction

Thanks for you quick answer.

**Comment by cheenamalhotra** [comment]
@dandesro71 

As we're tracking #644 for the same, I'll close this issue.
