### ISSUE TITLE
Does this package Microsoft.Data.SqlClient work with Entity Framework?

### ISSUE THREAD

**Issue by surajpatil9211** [dotnet/SqlClient#725]
My application runs on .NET framework 4.7 and I'm using Entity Framework 6.1.3. Currently, my code uses some classes from the namespace System.Data.SqlClient such as SqlParameter. I want to switch to Microsoft.Data.SqlClient. However, I'm not sure if EF6 is compatible with Microsoft.Data.SqlClient. 

Everything has been working well with System.Data.SqlClient for the below code

```
public async Task<ICollection<int>> GetChildCustomerIdsAsync(int customerId)
{
   var sqlParameters = new List<SqlParameter>()
   {
      new SqlParameter("@CustomerId", customerId)
   };

   return await DbContext.Database.SqlQuery<int>("dbo.sp_GetChildCustomerIds @CustomerId=@CustomerId",
                sqlParameters.ToArray()).ToListAsync().ConfigureAwait(false);
}
```

However, when I am switching to Microsoft.Data.SqlClient, I'm getting this error:

> System.InvalidCastException: The SqlParameterCollection only accepts non-null SqlParameter type objects, not SqlParameter objects.
> at System.Data.SqlClient.SqlParameterCollection.ValidateType(Object value)
> at System.Data.SqlClient.SqlParameterCollection.AddRange(Array values)
> at System.Data.Entity.Core.Objects.ObjectContext.CreateStoreCommand(String commandText, Object[] parameters)
> at System.Data.Entity.Core.Objects.ObjectContext.ExecuteStoreQueryInternalAsync.d__6f`1.MoveNext()

**Comment by ErikEJ** [comment]
EF 6 is not compatible with Microsoft.Data.SqlClient - one of the issues is that EF6 targets net40, and M.D.S lowest target is netstandrad2.0

**Comment by surajpatil9211** [comment]
Thank you @ErikEJ for the clarification. Could you please also tell me if there is any workaround to make the above code work or what would be the recommended approach to switch to Microsoft.Data.SqlClient in my application.

**Comment by karinazhou** [comment]
@surajpatil9211  EntityFramework Core internally uses Microsoft.Data.SqlClient so maybe you can switch to that if possible.

**Comment by ErikEJ** [comment]
EF Core, raw ADO.NET, Dapper...

**Comment by JRahnama** [comment]
@ErikEJ Thanks for clarification and support.

**Comment by surajpatil9211** [comment]
@ErikEJ @karinazhou Thank you for the clarification.

**Comment by Jehoel** [comment]
For the benefit of others looking into this too, this issue in the EF6 repo is the one to follow: https://github.com/dotnet/ef6/issues/823

**Comment by ErikEJ** [comment]
FYI, I just published a preview package: https://github.com/ErikEJ/EntityFramework6PowerTools/blob/community/README.md#preview-of-ef6-sql-server-provider-based-on-microsoftdatasqlclient
