### ISSUE TITLE
SqlConnectionStringBuilder - several keywords are not supported

### ISSUE THREAD

**Issue by EgorBo** [dotnet/SqlClient#73]
I am wondering why [these keywords](https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlConnectionStringBuilder.cs#L873-L887) are marked as "not supported" in SqlConnectionStringBuilder? Is it by design or just is not yet implemented? Especially:
- 'Network Library'
- 'asynchronous processing'
- 'connection reset'

I tried to run mono System.Data tests using corefx sources (Passed: 2347, Failures: 36) and the most popular failure is 
`The keyword 'XX' is not supported on this platform.`

For example, the following code works in .NET 4.6 but fails with NIE in .NET Core:

`var builder = new SqlConnectionStringBuilder("SERVER=localhost;Network=DBMSSOCN");`

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
@EgorBo 

Closing the issue since the above discussed keywords are not planned to be supported in .NET Core, due to below reasons:
1. 'asynchronous processing' - _Deprecated in .Net Framework._
2. 'connection reset' _- Deprecated in .Net Framework._
3. 'context connection' - _No plans_
4. 'Network Library' - _No plans_
