### ISSUE TITLE
Allow Stream and TextReader to be retrieved by GetFieldValue and GetFieldValueAsync

### ISSUE THREAD

**Issue by roji** [dotnet/SqlClient#732]
As per discussion in https://github.com/dotnet/runtime/issues/28596#issuecomment-484462213, there are currently no async counterparts to DbDataReader.Get{Stream,TextReader}. Rather than adding new methods, it seems better to just allow these types to be returned from DbDataReader.GetFieldValue (and Async).

Added tests to @bgrainger's AdoNetApiTest for Stream: https://github.com/mysql-net/AdoNetApiTest/pull/145

/cc @Wraith2

**Comment by cheenamalhotra** [comment]
Acknowledged for future.

**Comment by David-Engel** [comment]
Seems like this was covered/completed by the implementation in #1019
