### ISSUE TITLE
Remote certificate is invalid according to the validation procedure when using Authentication=Active Directory Service Principal and TrustServerCertificate=True

### ISSUE THREAD

**Issue by liquidcowgithub** [dotnet/SqlClient#738]
With the release of 2.0.0, we're looking to switch over a few services to use AD service principal based authentication to Azure SQLDB instances.

However, when adding the properties to the connection string, "Authentication=Active Directory Service Principal;TrustServerCertificate=True" an error occurs:

```
System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
```

The error is correct, in that a corporate issued self-signed certificate is in use, however this is not the behaviour that's observed when SQL authentication is used, with the same self-signed certificate and the "TrustServerCertificate=True" property in the connection string. With SQL authentication it connects fine.
Additionally, running ef core migrations with "Authentication=Active Directory Service Principal;" works fine (via Azure DevOps)

Is this the expected behaviour?

For some context the environment is .net core 3.1.8 on mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic images on AKS. Microsoft.Data.SqlClient 2.0.1

**Comment by cheenamalhotra** [comment]
@liquidcowgithub 

Could you paste full stack trace of this error?

I'm wondering if this is thrown by Microsoft.Identity.Client (MSAL) library when it tries to acquire token. As in SQL Authentication no access token is fetched and credentials are passed as-is.

**Comment by liquidcowgithub** [comment]
@cheenamalhotra I suspect you're right about it being thrown via MSAL. Stack trace attached.

[stack trace.txt](https://github.com/dotnet/SqlClient/files/5271805/stack.trace.txt)

**Comment by liquidcowgithub** [comment]
Does the AD service principal use in the connection string need to have the self-signed certificate registered against it?

Something along the lines of [Register your certificate with Microsoft identity platform](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-certificate-credentials#register-your-certificate-with-microsoft-identity-platform)?

**Comment by cheenamalhotra** [comment]
I think this might be an issue for MSAL team to investigate further.
I'm not sure how Certificates are validated by Microsoft.Identity.Client as it's out of our driver scope.

Could you reach out to https://github.com/AzureAD/microsoft-authentication-library-for-dotnet and let them know your usecase?

**Comment by liquidcowgithub** [comment]
Thanks @cheenamalhotra will do, just to confirm, is Microsoft.Data.Sqlclient 2.0.1 on Microsoft.Identity.Client >= 4.14.0? 
As listed on [nuget](https://www.nuget.org/packages/Microsoft.Data.SqlClient/) dependencies for .NETCoreApp 3.1.

**Comment by liquidcowgithub** [comment]
Exploring the documentation for Microsoft.Identity.Client, is there a way to potentially supply a customised HttpClient for the token acquisition step?

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/httpclient

**Comment by liquidcowgithub** [comment]
Created an issue on [microsoft-authentication-library-for-dotnet](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet) ->  [2054](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/issues/2054)

**Comment by cheenamalhotra** [comment]
Just FYI, this is how we fetch access token from MSAL library for Service Principal mode:

https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L84-L92

We don't maintain the HttpClient in this case.

**Comment by cheenamalhotra** [comment]
@liquidcowgithub 

Can you try to run this standalone app that acquires token to validate MSAL functionality:
https://gist.github.com/cheenamalhotra/8398e61f8c50388382c6dd0e84609720

**Comment by cheenamalhotra** [comment]
Closing issue as external as HttpClient is not managed by SqlClient in this case.
