### ISSUE TITLE
"Specified type is not registered on the target server.Microsoft.SqlServer.Types.SqlGeography” Exception while working with SQLGeography data type

### ISSUE THREAD

**Issue by shailendrarampal** [dotnet/SqlClient#747]
> When trying to use SqlGeometry (SqlGeograpy or HiearchyId) with the new Microsoft.Data.SqlClient i get the following error:
> 
> ```
> Unhandled Exception: System.ArgumentException: Specified type is not registered on the target server.Microsoft.SqlServer.Types.SqlGeography, Microsoft.SqlServer.Types, Version=14.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91.
> ```
> 
> even if I can see that I have that library in my SQL Server assemblies (select * from sys.assemblies)

Have anyone found the solution of this issue ? I am facing the same exception while adding SQLGeography type as command.parameter
` command.Parameters.Add(new SqlParameter("@deviceGeolocation", SqlDbType.Udt)
                    {
                        UdtTypeName = "Geography",
                        Value = geo,
                    });`

_Originally posted by @shailendrarampal in https://github.com/dotnet/SqlClient/issues/30#issuecomment-703454176_

**Comment by cheenamalhotra** [comment]
Hi @shailendrarampal 

As mentioned by @karinazhou , this is an existing limitation in .NET Core.
Since we have existing issues for the same query, I will close this issue.

**Comment by shailendrarampal** [comment]
But I was able to read SQLGeolocation column data through SqlDataReader.GetSqlBytes though !!

**Comment by cheenamalhotra** [comment]
Spatial column data could be retrieved if you map them to SqlVarBinary or fetch data as Bytes, the missing support is for SqlGeometry and SqlGeography types whose implementations are not available in .NET Core yet.
