### ISSUE TITLE
Issue connecting to MS SQL Server running on non default port 1433

### ISSUE THREAD

**Issue by Petermarcu** [dotnet/SqlClient#75]
@mahesji commented on [Fri Feb 09 2018](https://github.com/dotnet/core/issues/1264)

# Issue Title

Issue connecting to MS SQL Server running on non default port 1433 from Linux environment 

**OS Version**
Linux 4.4.0-109-generic #132~14.04.1-Ubuntu SMP Tue Jan 9 21:46:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

dotnet core project settings 
```
<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <RuntimeFrameworkVersion>2.0.5</RuntimeFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.0.5" />
    <PackageReference Include="System.Data.SqlClient" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Tools" Version="2.0.2" />
  </ItemGroup>

</Project>

```
# General
Using System.Data.SqlClient to connect to Sql server database. Following the sample in this post https://blogs.msdn.microsoft.com/dotnet/2016/11/09/net-core-data-access/

It works fine if the sql server is listening on port 1433 but fails when connecting to sql servers listening on port 1434. Confirmed that there is no network / firewall issues that that is blocking the ports. Able to connect to the same sql server on port 1434 using java code.
This connection string works >
Server=myhostname,1433;Database=mydatabase;User Id=myuser;Password=mypassword;
This connection string does not work in above linux environment.  Works fine on windows
Server=myhostname,1434;Database=mydatabase;User Id=myuser;Password=mypassword;

Both connect strings work fine in Windows environment.

Record Fetch Error: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)

---

@usergiga commented on [Fri Feb 09 2018](https://github.com/dotnet/core/issues/1264#issuecomment-364605423)

If an instance of SQL Server is listening on any other port, than 1433. You have to specify a server-alias or change the standard port globally. 
You can have SQL Server listening on multiple ports. 

---

@mahesji commented on [Mon Feb 12 2018](https://github.com/dotnet/core/issues/1264#issuecomment-364967845)

@usergiga , Thank you for the reply.  I have the alias created and that doesn't seem to help. The connection works fine in Windows runtime.  Have this issue only in the Linux (Ubuntu) runtime.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by ztane** [comment]
The problem is in **documentation**. The correct address string for connecting to a database at `1.2.3.4` port `666` is `1.2.3.4,666`, **not `1.2.3.4:666` like in every other program**.

**Comment by GSPP** [comment]
Can we support the `1.2.3.4:666` syntax, *like in every other program*? :smile:

Over time the ecosystem can move away from the comma style.

**Comment by cheenamalhotra** [comment]
Hi @Petermarcu @GSPP 

Just wanted to get confirmation on current status of the issue, can you confirm if connection to custom port works fine with Microsoft.Data.SqlClient ([latest version](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19269.1)) when specified with comma (server, port) in connection string?

Supporting colon (:) can be treated as a separate request.

@arthurvaverko 

Please test and confirm the same issue with Microsoft.Data.SqlClient ([latest version](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19269.1)) in your environment and open a new ticket if that occurs.

**Comment by Petermarcu** [comment]
@mahesji opened this issue. I just moved it to this repo.

**Comment by arthurvaverko** [comment]
Looks like latest nuget package works fine.
Now we have some issues under load tests.
Seems like linux libs are handling connections less efficiently than windows.

We get tcp connection establishment timeouts after a certain load has been achieved.

The affect does not end with sql .. same issues starts with any other outbound network communications like rabbit mq and basic http requests...

Still investigating root cause.

**Comment by cheenamalhotra** [comment]
Hi @arthurvaverko 

Please share your details for any networking issues with dotnet/corefx team for further investigations.
We can investigate any SqlClient specific use-case, please provide a repro for the same in that case and create a new issue.

Closing this issue.
