### ISSUE TITLE
SqlConnectionStringBuilder uses wrong value for ApplicationIntent

### ISSUE THREAD

**Issue by Coder3333** [dotnet/SqlClient#754]
### Describe the bug
When I use Microsoft.Data.SqlClient.SqlConnectionStringBuilder and set the ApplicationIntent property, the ConnectionString produced includes the phrase "Application Intent=ReadWrite", which is invalid.  Using System.Data.SqlClient.SqlConnectionStringBuilder produces the correct "ApplicationIntent=ReadWrite".

This is the exception thrown by the SqlConnection constructor when I try to use the ConnectionString produced by SqlConnectionStringBuilder.

```
System.ArgumentException : Keyword not supported: 'application intent'
```

### To reproduce

```c#
var builder = new SqlConnectionStringBuilder(ConnectionString);
builder.ApplicationIntent = ApplicationIntent.ReadOnly;
return new Microsoft.Data.SqlClient.SqlConnection(builder.ConnectionString);
```

### Expected behavior
I expect the correct ConnectionString to be produced with "ApplicationIntent=ReadWrite", not "Application Intent=ReadWrite".

### Further technical details
Microsoft.Data.SqlClient version: 2.0.1
.NET target: Core 3.1
SQL Server version: SQL Server 2019
Operating system: Windows 10

**Comment by cheenamalhotra** [comment]
Hi @Coder3333 

"application intent" (with space) only applies to Microsoft.Data.SqlClient, from v2.0.0. Mixing drivers like that is not recommended as they're different products and they may not be cross compatible like that. Just like you cannot create connection from 1 driver and pass on to another. 

If you want to provide connection string to System.Data.SqlClient, you should fetch it from the same driver.

**Comment by Coder3333** [comment]
@cheenamalhotra 

I did not think I was mixing drivers, but upon further inspection, the particular line of code that broke actually was mixing drivers.  I can clear that up from my end.  Thank you for getting back to me so quickly.
