### ISSUE TITLE
Question: How to log Datareader or result value via sqlclient diagnostics

### ISSUE THREAD

**Issue by hueifeng** [dotnet/SqlClient#758]
code from SqlClientDiagnosticListenerExtensions: [SqlClientDiagnosticListenerExtensions](https://github.com/dotnet/SqlClient/blob/a536885e4e6ccf2a98a86657609b6b72003c890c/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlClientDiagnosticListenerExtensions.cs#L65)

As in the code snippet below, we can use the `Diagnostics` to intercept the information accordingly. The `Diagnostics` is a good practice, but as in the code below, Through the `Diagnostics`, I want to abstract an `APM` from the database connection pool. Now I have an idea, whether we can write `DataReader` in the following event writing, I want to try to listen to it, so that I can monitor the response result set in `APM` and also do response monitoring.

```csharp
  public static void WriteCommandAfter(this SqlDiagnosticListener @this, Guid operationId, SqlCommand sqlCommand, SqlTransaction transaction, [CallerMemberName] string operation = "")
        {
            if (@this.IsEnabled(SqlAfterExecuteCommand))
            {
                @this.Write(
                    SqlAfterExecuteCommand,
                    new
                    {
                        OperationId = operationId,
                        Operation = operation,
                        ConnectionId = sqlCommand.Connection?.ClientConnectionId,
                        Command = sqlCommand,
                        transaction?.InternalTransaction?.TransactionId,
                        Statistics = sqlCommand.Statistics?.GetDictionary(),
                        Timestamp = Stopwatch.GetTimestamp()
                    });
            }
        }
```

### Implement

As in the description, I want to call `DataReader` here by subscribing to the Diagnostics.

```csharp
 [DiagnosticName(DiagnosticNames.SqlAfterExecuteCommand)]
  public void OnCommandAfter(Guid operationId, string operation, Guid connectionId, DbCommand command)
   {
            var stopwatch = _stopwatch.Value;
            stopwatch.Stop();
            #if DEBUG
            Console.WriteLine($"CommandText: {command.CommandText}");
            Console.WriteLine($"Elapsed: {stopwatch.Elapsed}");
            #endif
            //Here i want to get DataReader
            AsyncContext.Run(() => _storageProcessor.WriteAsync(command, stopwatch.Elapsed));
}
```

**Comment by Wraith2** [comment]
Executing a command does not require that a reader exist. Internally it often does but for ExecuteNonQuery and ExecuteScalar the readers are never exposed to the user. 

Readers are also stateful so using one from a diagnostics callback could mutate it and cause errors in the calling program that it wasn't designed to handle, imagine for example a user uses Sequential mode on a reader and the diagnostics callback advances past a field that the program hasn't read yet.

**Comment by cheenamalhotra** [comment]
@hueifeng 

We'll need to understand what information from SqlDataReader is being requested in diagnostics.
Could you elaborate by what you mean by `APM` ? I'm not familiar with this acronym.

We can look into it's feasibility, but as Wraith mentioned above, it will not be always applicable, but only on `SqlCommand` Execute APIs that expose a `SqlDataReader` on execution. What is that you're interested to capture here? 

```cs
//Here i want to get DataReader
AsyncContext.Run(() => _storageProcessor.WriteAsync(command, stopwatch.Elapsed));
```

@Wraith2 
I think the `SqlDiagnosticListener` only raises events/notifications, and there are no callbacks. We can only provide reader's current state information on public APIs in diagnostics which shouldn't lead to conflict.

But yes, it is not possible to read data/stream requested by user application, for diagnostics.

**Comment by Wraith2** [comment]
I meant the call into the listener, the way the observables are used it feels like a callback when you use it. When you get the call in the listener you can mutate the references because they're full objects not serialized or readonly versions. It's entirely possible to mutate things badly from diagnostic listeners. User can abuse it as an extension point which isn't possible with EventListeners.

**Comment by hueifeng** [comment]
For the needs, I only need to obtain the monitoring of the result set, one is the result set, the other is to get the number of affected rows. 

Even without a datareader, Can we pass the result of a stateless object.

**Comment by hueifeng** [comment]
@Wraith2 Just like efcore, you can pass an `object result`.

efcore code [CommandExecutedEventData](https://github.com/dotnet/efcore/blob/b970bf29a46521f40862a01db9e276e6448d3cb0/src/EFCore.Relational/Diagnostics/CommandExecutedEventData.cs#L32)


## Implement

In efcore, we can get our data in this way. Like efcore, we can achieve what I want in the following ways.

```csharp
[DiagnosticName("Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted")]
public void OnCommandExecuted(object result, bool async)
 {

            if (async == false)
            {
                if (result.GetType() == typeof(int))
                {
                    // ExecuteNonQuery
                    var data = (int) result;
                }
                else if (result.GetType() == typeof(RelationalDataReader))
                {
                    // RelationalDataReader
                    RelationalDataReader rdr = (RelationalDataReader)result;
                }
                else
                {
                    // ExecuteScalar data=1
                    
                }
            }
 }
```

**Comment by David-Engel** [comment]
Request is for a new diagnostics event listener that enables access to DataReader or related data. Good points that exposing DataReader could lead to mutation of reader state; stateless object could be passed, But it's unclear what properties are required. Closing as it's unlikely we will do this.
