### ISSUE TITLE
Could not load type 'Microsoft.SqlServer.Server.SqlContext' from assembly 'System.Data, Version=4.0.0.0

### ISSUE THREAD

**Issue by PraisyA** [dotnet/SqlClient#76]
I am getting this exception when  i tried to restore the Data base using **c# , .Net core2 and VS2017 preview2 ,**
 here is the sample code 
SqlConnection sqlConnection = new SqlConnection(ConnectionString);
    // Error on the line below
    Microsoft.SqlServer.Management.Common.ServerConnection conn = new Microsoft.SqlServer.Management.Common.ServerConnection(sqlConnection);

but this is working in console application .  Did i miss anything ...

Thanks
Victor.A

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
This is a SMO issue and there is already a .NET Standard version (https://github.com/dotnet/SqlClient/issues/76#issuecomment-402709831). Closing this issue.

**Comment by dude0001** [comment]
@shueybubbles & @David-Engel. I hear what you are saying that SMO already has a .NET Standard version. I'm not clear how to use Microsoft.Data.SqlClient with the SMO .NET Standard package. I'm still getting similar errors with my application that targets .NET Core 3.0.

**Comment by shueybubbles** [comment]
We're not quite ready to push a public SMO package that changes its dependency from System.Data.SqlClient to Microsoft.Data.SqlClient. Once the kinks get worked out between SMO and M.D.S to fully support key apps like Azure Data Studio we'll make that version of NetStandard SMO available on nuget.org.
