### ISSUE TITLE
Assembly loading - PlatformNotSupportedException

### ISSUE THREAD

**Issue by Benjiinator** [dotnet/SqlClient#761]
I am in the middle of migrating a large project from .net framework -> .net core 3.1 and during the process i am encountering "Microsoft.Data.SqlClient is not supported on this platform".

My project solution consists of the following:
- .Net core 3.1 program that can load and run plugin modules through assembly.
- .Net standard 2.0 plugin modules with dependecies (1 of which has a dependency on Microsoft.Data.SqlClient)

I have read the [FAQ](https://github.com/dotnet/SqlClient/wiki/Frequently-Asked-Questions) point 11 which refers to what sounds like my problem - however, i am still oblivious as to how i am to solve the problem.

**Comment by cheenamalhotra** [comment]
Hi @Benjiinator 

Is it possible to wrap a repro application and upload it here to take a closer look?
It does look like what is mentioned in point 11 may apply to your case.

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

I will attempt creating one and get back to you.

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 
I have created a [repro application](https://github.com/Benjiinator/AssemblyLoading) and the issue still persists.
I have set it up to build the needed librarys to the path "C:/AssemblyLoading".

When publishing the exe itself i used the following settings:
- Deployment mode: self contained
- Target Runtime: win-x64
- Produce single file: true

**Comment by cheenamalhotra** [comment]
Hi @Benjiinator 

If you specify "RuntimeIdentifier" in your `PluginShared.csproj`, that seems to resolve the issue:

![image](https://user-images.githubusercontent.com/13396919/96501604-6bf09f00-1205-11eb-97eb-a1d8cc90ec9d.png)

I now see correct DLL being referenced in `*.deps.json` files:

![image](https://user-images.githubusercontent.com/13396919/96501537-54191b00-1205-11eb-92e2-8e03876a8c88.png)

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

After setting the "RuntimeIdentifier", cleaning, rebuilding and publishing the application the issue is still present.

**Comment by cheenamalhotra** [comment]
Could you also specify the same in `DemoPlugin.csproj` and try again?

It seems that project also needs a RuntimeIdentifier to yield this:

![image](https://user-images.githubusercontent.com/13396919/96618217-82583280-12b9-11eb-9ea0-bc5f97ccd87d.png)

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

This resolved my issue.

Many thanks for the help - it is much appreciated.

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

After implementing your solution i now am getting the following error: "Unable to load DLL 'Microsoft.Data.SqlClient.SNI.dll' or one of its dependencies: The specified module could not be found. (0x8007007E)" when i attempt running it on my production environment.

**Comment by cheenamalhotra** [comment]
Hi @Benjiinator 

We depend on native runtime library "Microsoft.Data.SqlClient.SNI.dll" which could usually be found on runtimes directly from where all runtime DLLs are loaded. If you haven't provided Execute permissions there (common possibility in Production env), it might be the reason your application will have issues. Please take a look at https://github.com/dotnet/SqlClient/issues/385#issuecomment-696376185 and related discussion for more details.

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

I'm not quite sure how to proceed with this issue, my application is not running on iis - it is a windows service running on an administrator account.
The directory of the application does have Read & Execute permissions for the administrator account - I think i'm missing something though.

**Comment by cheenamalhotra** [comment]
Runtime native DLLs are fetched from NuGet Cache location in .NET Core, so you will need to verify permissions to that folder too.

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

A NuGet cache is not present on my production environment - i looked for it under "%localappdata%" + "/NuGet/Cache" but the NuGet folder is not present.

**Comment by cheenamalhotra** [comment]
Hi @Benjiinator 

You may find your NuGet cache location by running this tool and verify if you have required permissions:
`dotnet nuget locals` ([details](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-locals))

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

After running the tool i got found out the following:
- http-cache: C:\Users\Administrator\AppData\Local\NuGet\v3-cache - path does not exist
- global-packages: C:\Users\Administrator\.nuget\packages\ - path does not exist
- temp: C:\Users\Administrator\AppData\Local\Temp\2\NuGetScratch - administrator account has all permissions
- plugins-cache: C:\Users\Administrator\AppData\Local\NuGet\plugins-cache - path does not exist

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

Any ideas what else could be wrong when the paths either don't exist or has the proper permissions?

**Comment by Benjiinator** [comment]
Hi @cheenamalhotra 

Any updates on this issue? - it is the last thing keeping us from fully migrating to .Net Core.

**Comment by Benjiinator** [comment]
@cheenamalhotra After upgrading from .Net Core 3.1 to .Net 5.0 the issue disappeared.
Thanks for your help though - it is greatly appreciated
