### ISSUE TITLE
.Net Standard 2.1 support with UWP

### ISSUE THREAD

**Issue by amitagrawalhyd** [dotnet/SqlClient#769]
We have a UWP application where we are planning to use Microsoft.Data.SqlClient with "Column Encryption Setting=enabled" option. But unfortunately in .Net Standard 2.0 "Column Encryption Setting=enabled" option is not supported and .Net Standard 2.1 which works fine with "Column Encryption Setting=enabled" option is not supported to any of the UWP version.

**Comment by ErikEJ** [comment]
I think this will be fixed in 2.1.0-preview2 (due any time now)

**Comment by cheenamalhotra** [comment]
Yes, we're going to release this support in next preview release, stay tuned!

**Comment by amitagrawalhyd** [comment]
Thanks for the quick response, Can you guys let me know which version of Windows 10 SDK (19H2, 20H1 or FallCreator etc...) is targeted for .Net Standard 2.1.0 - preview2?

**Comment by cheenamalhotra** [comment]
Hi @amitagrawalhyd I'm afraid that's out of our domain, please reach out to dotnet/sdk group for the same. 

Closing issue as **v2.1.0-preview2** has been released that contains the requested changes.
