### ISSUE TITLE
Always Encrypted on Serverless functions

### ISSUE THREAD

**Issue by tyler-shuhnicki** [dotnet/SqlClient#775]
Hello,

I've got an interesting (and challenging) use case. Currently, our .NET app is hosted on a windows server and accesses a SQL server that uses Always Encrypted. We are migrating, and transitioning our app to .NET Core and using AWS Lambda.

Obviously, this makes it impossible to install the certificate required. We _could_ re-encrypt the database using an Azure Key Vault provider, but this is a bit of a challenge seeing as we'd like to 1.) keep our application from making too many hops between cloud providers, and 2.) avoid impacting the current production application *at all*, since we will have a small overlap during these transitions.

So, that brings me here - I'm trying to think of different ways to decrypt our columns.  I've been scouring the internet with no luck, and ultimately my question is this: is there _any_ way that I can manually load our certificate into the application to use it? Or potentially just use the private key inside of the certificate itself?

I've been playing around with trying to make a custom key store provider to override the standard MSSQL_CERTIFICATE_STORE, that returns the decrypted column encryption key, but I'm not sure if it's the correct path to go down.

Do you have any thoughts? If this is not possible, is this a reasonable feature request?

Thank you much for your time.
Tyler

**Comment by cheenamalhotra** [comment]
Hi @tyler-shuhnicki 

> ultimately my question is this: is there any way that I can manually load our certificate into the application to use it.

That's an interesting question, but I believe it is possible.

You can implement a custom provider by extending the [SqlColumnEncryptionKeyStoreProvider](https://docs.microsoft.com/dotnet/api/microsoft.data.sqlclient.sqlcolumnencryptionkeystoreprovider) (abstract) Class and registering the provider using the [SqlConnection.RegisterColumnEncryptionKeyStoreProviders](https://docs.microsoft.com/dotnet/api/microsoft.data.sqlclient.sqlconnection.registercolumnencryptionkeystoreproviders) method.

```
public class MyCustomKeyStoreProvider : SqlColumnEncryptionKeyStoreProvider
{
    public const string ProviderName = @"MY_CUSTOM_STORE";
    public override byte[] EncryptColumnEncryptionKey(string masterKeyPath, string encryptionAlgorithm, byte[] columnEncryptionKey)
    {
        // Logic for encrypting a column encrypted key.
    }
    public override byte[] DecryptColumnEncryptionKey(string masterKeyPath, string encryptionAlgorithm, byte[] EncryptedColumnEncryptionKey)
    {
        // Logic for decrypting a column encrypted key.
    }
}  
class Program
{
    static void Main(string[] args)
    {
        Dictionary<string, SqlColumnEncryptionKeyStoreProvider> providers =
            new Dictionary<string, SqlColumnEncryptionKeyStoreProvider>();
        providers.Add("MY_CUSTOM_STORE", customProvider);
        SqlConnection.RegisterColumnEncryptionKeyStoreProviders(providers);
        // Continue to use this provider to create Column Master Key
    }
}
```

You may refer existing Key Store providers source to implement yours. e.g. [SqlColumnEncryptionCngProvider](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlColumnEncryptionCngProvider.cs)

Please Note:
_The names of custom key store providers can't start with 'MSSQL\_', which is a prefix reserved for Microsoft key store providers._

**Comment by tyler-shuhnicki** [comment]
Hi Cheena,

Thanks for the response! I had actually been trying out something exactly similar as above.
I got stuck, ultimately, at the point that a new provider can't start with "MSSQL_". Unless I'm mistaken, the certificate on the database is pointing to the MSSQL_CERTIFICATE_STORE, and the key will attempt to retrieve it from that location. I can register a new store, but it won't matter unless I re-create the key with this store name (which would require a change to our soon-to-be-legacy code).

Is there any way around the "MSSQL_" limitation that would allow me to overwrite that store? Or, am I actually totally wrong, and I can just create a new store and the key will be found as expected?

Thanks!
Tyler

**Comment by cheenamalhotra** [comment]
Yes, as per SQL Docs ([Creating COLUMN MASTER KEY](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-column-master-key-transact-sql?view=sql-server-ver15#arguments)), you cannot start your custom provider name with "MSSQL_" prefix as they're reserved for system provider names. 

But you can try to override implementation of **MSSQL_CERTIFICATE_STORE** like this:
```cs
public class MyCustomKeyStoreProvider : SqlColumnEncryptionKeyStoreProvider
{
    // ************ Note the change below **************
    public const string ProviderName = SqlColumnEncryptionCertificateStoreProvider.ProviderName;
    public override byte[] EncryptColumnEncryptionKey(string masterKeyPath, string encryptionAlgorithm, byte[] columnEncryptionKey)
    {
        // Logic for encrypting a column encrypted key.
    }
    public override byte[] DecryptColumnEncryptionKey(string masterKeyPath, string encryptionAlgorithm, byte[] EncryptedColumnEncryptionKey)
    {
        // Logic for decrypting a column encrypted key.
    }
}  
class Program
{
    static void Main(string[] args)
    {
        Dictionary<string, SqlColumnEncryptionKeyStoreProvider> providers =
            new Dictionary<string, SqlColumnEncryptionKeyStoreProvider>();

        // ************ Note the change below **************
        providers.Add(SqlColumnEncryptionCertificateStoreProvider.ProviderName, customProvider);
        SqlConnection.RegisterColumnEncryptionKeyStoreProviders(providers);
        // Continue to use MSSQL_CERTIFICATE_STORE provider to create Column Master Key
    }
}
```

**Comment by tyler-shuhnicki** [comment]
Thanks for the correspondence!

As it turns out, using the above code still gets upset with me. I think SqlColumnEncryptionCertificateStoreProvider.ProviderName evaluates to MSSQL_CERTIFICATE_STORE, which ultimately causes the same error.

**Comment by cheenamalhotra** [comment]
@tyler-shuhnicki Right I see now it's not accepted in driver, so you'll have to go for a different prefix.

https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlConnection.cs#L273-L276

Is there a problem you're facing without "MSSQL_" ?

**Comment by tyler-shuhnicki** [comment]
@cheenamalhotra  Not particularly - the reason I was hoping to overwrite MSSQL is to avoid creating another encryption key store. Having to make a custom key store would require an edit on our existing application.

It looks like we'll have to just change our encryption strategy. No worries!

Thanks.

**Comment by cheenamalhotra** [comment]
Closing issue as queries answered.

**Comment by tyler-shuhnicki** [comment]
@ekjuanrejon Unfortunately, we never found a solution that worked for us. Instead, our databases are now using TDE.

**Comment by ekjuanrejon** [comment]
I got it working for integration test using docker where i had the issue

I'm using a pfx file and created an implementation of SqlColumnEncryptionKeyStoreProvider
