### ISSUE TITLE
.NET Core and .NET 5 - focal Docker images Won't Connect to SQL Server

### ISSUE THREAD

**Issue by zs-dima** [dotnet/SqlClient#776]
Issue appear as TLS protocol version 1.0 had been disabled by default since Ubuntu 20.04

The solution for now is update /etc/ssl/openssl.cnf file to enable TLSv1:

```
openssl_conf = openssl_init

[openssl_init]
ssl_conf = ssl_sect

[ssl_sect]
system_default = system_default_sect

[system_default_sect]
MinProtocol = TLSv1
CipherString = DEFAULT@SECLEVEL=1
```

for example:
```
FROM mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.2-focal AS base
* * *
RUN wget -O /etc/ssl/openssl.cnf https://raw.githubusercontent.com/zs-dima/view/master/openssl.cnf
RUN wget -O /usr/lib/ssl/openssl.cnf https://raw.githubusercontent.com/zs-dima/view/master/openssl.cnf
```

Reproduced on .NET Core 3+ and .NET 5 focal images:
```
mcr.microsoft.com/dotnet/core/aspnet:3.1-focal
mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.1-focal
mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.2-focal
***
```

Microsoft SQL Server 2008 R2 (SP2)

```
Exception message:
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
Stack trace:
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
|  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
|  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
|  ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
|    --- End of inner exception stack trace ---
|    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
|    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
|    --- End of inner exception stack trace ---

```

similar issue with bionic images:
https://github.com/dotnet/SqlClient/issues/222

**Comment by cheenamalhotra** [comment]
Hi @zs-dima 

The correct solution to this issue is to ensure target SQL Server supports TLS 1.2 protocol by installing all latest updates. This Microsoft Article: [TLS 1.2 support for Microsoft SQL Server](https://support.microsoft.com/en-ca/help/3135244/tls-1-2-support-for-microsoft-sql-server) can be used to figure out whether target SQL Server supports TLS 1.2 or not.

**The workaround to bring back TLS 1.0 support in client machine, is not Microsoft recommendation.**
Microsoft has declared TLS 1.0 and TLS 1.1 protocols as insecure with known vulnerabilities and all customers must move towards TLS 1.2 protocol.

More information: [Enable TLS 1.2 on Servers](https://docs.microsoft.com/en-us/configmgr/core/plan-design/security/enable-tls-1-2)

**Comment by zs-dima** [comment]
@cheenamalhotra thanks for details, for sure if it is possible it is better to update SQL Server to supports TLS 1.2
however it is some cases when SQL Server could not be updated, then workaround could be helpful

**Comment by LGinC** [comment]
`RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo -e "\n[ default_conf ]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT:@SECLEVEL=1" >> /etc/ssl/openssl.cnf`

it's work  for SQLServer 2014

**Comment by danilobreda** [comment]
[system_default_sect]
MinProtocol = **TLSv1.0** does not work, need to be TLSv1, that can be the problem here?
CipherString = DEFAULT@SECLEVEL=1

**Comment by marekstachura** [comment]
Yeah, @cheenamalhotra enabling TLS1.2 on SQL Server is not helping unfortunately.
We had to change the `openssl.cnf` to get this working, only change was:

From
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=2
```
To:
```
[system_default_sect]
MinProtocol = TLSv1.2
CipherString = DEFAULT@SECLEVEL=1
```

https://github.com/microsoft/azuredatastudio/issues/11249
https://wiki.debian.org/ContinuousIntegration/TriagingTips/openssl-1.1.1

**Comment by cheenamalhotra** [comment]
@marekstachura 
Could you paste output of [Get-TlsCipherSuite](https://docs.microsoft.com/en-us/powershell/module/tls/get-tlsciphersuite?view=win10-ps) from both server and client OS ?

**Comment by marekstachura** [comment]
@cheenamalhotra I'm afraid I can't. The Windows Server we are using is `Win server 2012 r2` and this command is not available there.
Is there any alternative command we could use or alternative way of getting you the information you need?

And for the client - what would be the linux alternative? Would the output from 
```
/usr/bin/openssl ciphers -v
```
work?

Thanks!

**Comment by cheenamalhotra** [comment]
Hi @marekstachura 

Below post sounds familiar, could you try the recommendation:
https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux
(original issue https://github.com/dotnet/runtime/issues/45244)

**Comment by krzysztofmajewski** [comment]
I have this SSL handshake problem connecting from a dotnet 5.0 app running on Ubuntu 20.04.2 LTS to an Aurora db in AWS. Tried the /etc/ssl/openssl.cnf edits various people suggest without success. I see there is also [CipherSuitesPolicy](https://docs.microsoft.com/en-us/dotnet/api/system.net.security.ciphersuitespolicy?view=net-5.0), but not sure how to use it, especially (but not only) because my development environment is Windows. I am able to connect using mysql client, I can see (via SHOW SESSION STATUS) that the connection is using a cipher that is listed in my /etc/ssl/openssl.cnf.

**Comment by cheenamalhotra** [comment]
Hi @krzysztofmajewski 

Did you try suggested links above: https://github.com/dotnet/SqlClient/issues/776#issuecomment-762999879 ?

**Comment by thyago-ribeiro** [comment]
> Hi @marekstachura
> 
> Below post sounds familiar, could you try the recommendation:
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux
> (original issue [dotnet/runtime#45244](https://github.com/dotnet/runtime/issues/45244))
> 
> Also please take a look at [SqlClient Troubleshooting Guide - Login Phase solutions](https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver15#possible-reasons-and-solutions) to verify your environment is configured correctly.

My solution to connect to a SQL SERVER 2012 (from alpine mcr.microsoft.com/dotnet/aspnet:5.0-alpine) was the following: testing many configurations, between of them the instructions of the commented link. Just after appending the legacy configuration from [Mozilla SSL Configuration Generator](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=old&openssl=1.1.1d&hsts=false&ocsp=false&guideline=5.6) I have achieved the connection to the SQL Instance. 

My fix was the following:

```
RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo -e "\n\n[default_conf]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA" >> /etc/ssl/openssl.cnf
```

**Comment by krzysztofmajewski** [comment]
> Hi @krzysztofmajewski
> 
> Did you try suggested links above: [#776 (comment)](https://github.com/dotnet/SqlClient/issues/776#issuecomment-762999879) ?

Yes, I did. Not sure what to try next.

**Comment by krzysztofmajewski** [comment]
Is anybody here running a dotnet5 project on Linux, and able to connect to an Aurora or MySQL db from that project? If yes, which Linux distribution are you using?

**Comment by thyago-ribeiro** [comment]
@krzysztofmajewski , I'm using net 5 and connecting from Alpine (mcr.microsoft.com/dotnet/aspnet:5.0-alpine). You just need to add the solution that I have shared just before the entry-point.

**Comment by krzysztofmajewski** [comment]
Thanks @thyago-ribeiro . Looks like you are running a Docker (?) image of Alpine Linux packaged my Microsoft. I could try that as well. However, looking at your sed command, it looks you like had to modify `/etc/ssl/openssl.cnf` in that container. I have also tried that (following the instructions in this thread), and it did not work for me (on Ubuntu). Could it be that Microsoft's image includes some additional magic that is required for dotnet to connect to Aurora? I was hoping that "dotnet works on Linux" means "works on any Linux" and not just "works on Linux images packaged by Microsoft". 

I'm attaching my openssl.conf, in case you (or someone else) sees a bug in it. Note that I am able to connect to Aurora using the mysql client on my Linux box. I can see that the cipher being used appears in the list of ciphers in my openssl.cnf:

```

mysql> SHOW SESSION STATUS LIKE 'Ssl_cipher';
+---------------+---------------------------+
| Variable_name | Value                     |
+---------------+---------------------------+
| Ssl_cipher    | DHE-RSA-AES128-GCM-SHA256 |
+---------------+---------------------------+
1 row in set (0.00 sec)
```

Here's my [openssl.cnf](https://github.com/dotnet/SqlClient/files/6306284/openssl.cnf.txt)

**Comment by krzysztofmajewski** [comment]
Update on this: I used @thyago-ribeiro 's sed expression to hack my openssl.cnf, and now the problem is resolved. Thanks again @thyago-ribeiro .

**Comment by thyago-ribeiro** [comment]
Just for your consideration, @krzysztofmajewski. This solution isn't the best, because you're downgrading the minimum TLS configuration. Please, use it with caution.

**Comment by krzysztofmajewski** [comment]
Just checked and it turns out TLSv1.2 works fine. So the problem was with my CipherString and not the MinProtocol.

**Comment by KarlKl** [comment]
Just had this problem. After a half day of debugging, I found this thread. Then it took another few hours to find out that on **Ubuntu you must remove the `-e` flag** from the `echo` command.. 😑

So the command that I used is a slightly modified version of @LGinC (removed the `-e` and set the MinProtocol to TLSv1.2):
```
RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo "\n[ default_conf ]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1.2\nCipherString = DEFAULT:@SECLEVEL=1" >> /etc/ssl/openssl.cnf
```

I hope this helps someone not to waste a whole day in debugging like me. 😄

**Comment by GregBalajewicz** [comment]
does anyone have a sample docker file with this fixed? running into the same issue

**Comment by KarlKl** [comment]
> 
> @GregBalajewicz 
> does anyone have a sample docker file with this fixed? running into the same issue

Add the `RUN sed ...` command just before the `ENTRYPOINT` in your Dockerfile. For Ubuntu 20.04(focal), you can use my command I've posted last week, for the other distros there are slightly other commands above.

I have added the Command to the base image(line 4 on default Dockerfile) right after the `EXPOSE 80` in my setup, so that it also works in debugging mode. 😉

**Comment by h0wXD** [comment]
Just want to add here that in case your sql server certificate is expired, the same error (with a different stack trace) will be shown regardless of updating the /etc/ssl/openssl.cnf file. In that case you could use ;TrustServerCertificate=True if it's a development environment, or setup a new set of certificates.

Error from expired cert:
`Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)`

**Comment by FabriDamazio** [comment]
The solution that worked for me:

1 - Enable TLS1.2 support on SQL Server
2 - Add @KarlKl suggested command above (without TLS1.2 enabled do not worked)

**Comment by KoakiMiku** [comment]
> Hi @marekstachura
> 
> Below post sounds familiar, could you try the recommendation:
> https://docs.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux
> (original issue [dotnet/runtime#45244](https://github.com/dotnet/runtime/issues/45244))
> 
> Also please take a look at [SqlClient Troubleshooting Guide - Login Phase solutions](https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-troubleshooting-guide?view=sql-server-ver15#possible-reasons-and-solutions) to verify your environment is configured correctly.

It's worked, Thanks!

**Comment by cralberto** [comment]
> Just had this problem. After a half day of debugging, I found this thread. Then it took another few hours to find out that on **Ubuntu you must remove the `-e` flag** from the `echo` command.. 😑
> 
> So the command that I used is a slightly modified version of @LGinC (removed the `-e` and set the MinProtocol to TLSv1.2):
> 
> ```
> RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo "\n[ default_conf ]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1.2\nCipherString = DEFAULT:@SECLEVEL=1" >> /etc/ssl/openssl.cnf
> ```
> 
> I hope this helps someone not to waste a whole day in debugging like me. 😄

@KarlKl, faced the same problem when deploying a _codefirst_ database model from .netcore 5.0 into RDS using AWS's CodeBuild feature (which is using Ubuntu). Placing your version of the command fixed for Ubuntu just saved my day.

Thanks all!

**Comment by mkris2003** [comment]
It is working for me on .net 5.0 , AKS , docker 
Please try below code in docker file 

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf


FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

------------

**Comment by mkris2003** [comment]
It is working for me on .net 5.0 , AKS , docker 
Please try below code in docker file 

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf


FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src

------------

**Comment by yorknguyen** [comment]
> It is working for me on .net 5.0 , AKS , docker
> Please try below code in docker file
> 
> FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
> WORKDIR /app
> EXPOSE 80
> EXPOSE 443
> 
> RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
> RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
> RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
> RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf
> 
> FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
> WORKDIR /src
> 
> reference: vcsjones
> #222

Thanks so much , it work for me , you was help my life

**Comment by alperenoz14** [comment]
> It is working for me on .net 5.0 , AKS , docker
> Please try below code in docker file
> 
> FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
> WORKDIR /app
> EXPOSE 80
> EXPOSE 443
> 
> RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /etc/ssl/openssl.cnf
> RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /etc/ssl/openssl.cnf
> RUN sed -i 's/DEFAULT@SECLEVEL=2/DEFAULT@SECLEVEL=1/g' /usr/lib/ssl/openssl.cnf
> RUN sed -i 's/MinProtocol = TLSv1.2/MinProtocol = TLSv1/g' /usr/lib/ssl/openssl.cnf
> 
> FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
> WORKDIR /src
> 
> reference: vcsjones
> #222

Works successfully in Docker and SQL Server 2014 connection via .NET Core 5.0 API project. My connection string like        **"Data Source=Your_IP_adress,1433;Initial Catalog=YourDB;User ID=sa;Password=*****;TrustServerCertificate=False"**              
 So appreciated to @mkris2003 for the solution. Saved my day mate!

**Comment by ajaysuwalka** [comment]
Changing FROM `mcr.microsoft.com/dotnet/aspnet:5.0.10-focal` to `FROM mcr.microsoft.com/dotnet/aspnet:5.0` Helped me

Basically focal images have this issue hence use non focal images

**Comment by GothicSecret** [comment]
> Issue appear as TLS protocol version 1.0 had been disabled by default since Ubuntu 20.04
> 
> The solution for now is update /etc/ssl/openssl.cnf file to enable TLSv1:
> 
> ```
> openssl_conf = openssl_init
> 
> [openssl_init]
> ssl_conf = ssl_sect
> 
> [ssl_sect]
> system_default = system_default_sect
> 
> [system_default_sect]
> MinProtocol = TLSv1
> CipherString = DEFAULT@SECLEVEL=1
> ```
> 
> for example:
> 
> ```
> FROM mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.2-focal AS base
> * * *
> RUN wget -O /etc/ssl/openssl.cnf https://raw.githubusercontent.com/zs-dima/view/master/openssl.cnf
> RUN wget -O /usr/lib/ssl/openssl.cnf https://raw.githubusercontent.com/zs-dima/view/master/openssl.cnf
> ```
> 
> Reproduced on .NET Core 3+ and .NET 5 focal images:
> 
> ```
> mcr.microsoft.com/dotnet/core/aspnet:3.1-focal
> mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.1-focal
> mcr.microsoft.com/dotnet/aspnet:5.0.0-rc.2-focal
> ***
> ```
> 
> Microsoft SQL Server 2008 R2 (SP2)
> 
> ```
> Exception message:
> A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
> Stack trace:
> Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
> |  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
> |  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
> |  ---> Interop+Crypto+OpenSslCryptographicException: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
> |    --- End of inner exception stack trace ---
> |    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, Byte[] recvBuf, Int32 recvOffset, Int32 recvCount, Byte[]& sendBuf, Int32& sendCount)
> |    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteContext& context, ArraySegment`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
> |    --- End of inner exception stack trace ---
> ```
> 
> similar issue with bionic images: #222

Works with SQL 2012 and ASPNET 6.0.10, 6.0 images

**Comment by JRahnama** [comment]
Closing the issue as this not SqlClient. Feel free to comment here or open a new issue,

**Comment by gaoconggit** [comment]
I modified dotnet core runtime has fixed this problem

**Comment by Mehranh** [comment]
I've tried all solutions , but still it's not working for me,
docker image :mcr.microsoft.com/dotnet/aspnet:8.0
