### ISSUE TITLE
Use last versions of Microsoft.Identity.Client and Microsoft.IdentityModel.*

### ISSUE THREAD

**Issue by mojtabakaviani** [dotnet/SqlClient#788]
Please update references identity projects with last version that use System.Text.Json

**Comment by cheenamalhotra** [comment]
Hi @mojtabakaviani 

Could you explain more about your requirement?

**Comment by mojtabakaviani** [comment]
After update efcore to version 5.0, see Newtonsoft.Json in bin folder. because Microsoft.Data.SqlClient use version 5.6, if update to version 6.8 remove this dependency. other than this Azure Authentication not use in many projects, it's better move to separated library (Microsoft.Data.SqlClient.Azure) so remove Microsoft.Identity.* and  Newtonsoft.Json from Microsoft.Data.SqlClient dependencies
