### ISSUE TITLE
SqlClient UDT support needs an assembly-plugin model

### ISSUE THREAD

**Issue by dotMorten** [dotnet/SqlClient#79]
I built a .NET Standard implementation of the `Microsoft.SqlServer.Types` classes. This works great for insertion, but when deserializing I'll get an exception like this:
![image](https://user-images.githubusercontent.com/1378165/38794079-b34e7df2-4108-11e8-9ca1-7631c9c50840.png)

Instead I have to write something like:

```cs
var binvalue = reader.GetSqlBytes(rowid);
var g = SqlGeometry.Deserialize(binvalue);
```

This makes sense, because SqlClient has no idea I provided an implementation it could use. Assembly redirect only works for assemblies with the same name and public key, so that's not really an option.
How do we across all the different platforms allow us to use UDT in assemblies defined on each platform, and get the SqlClient to import the types?

The issue is somewhat called out in the doc:
> SqlClient may fail to load a UDT in the event of mismatched UDT versions or other problems. [(1)](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/accessing-user-defined-types-retrieving-udt-data?view=sql-server-2017)

> A local copy of the UDT assembly must be available to the client project. [(2)](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/accessing-user-defined-types-retrieving-udt-data?view=sql-server-2017#using-udts-in-query-parameters)

> The assembly loaded in SQL Server and the assembly on the client must be compatible in order for the UDT to be created on the client. For UDTs defined with the Native serialization format, the assemblies must be structurally compatible. For assemblies defined with the UserDefined format, the assembly must be available on the client.
> You do not need a copy of the UDT assembly on the client in order to retrieve the raw data from a UDT column in a table. [(3)](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/accessing-user-defined-types-retrieving-udt-data?view=sql-server-2017#requirements-for-using-udts-in-adonet)

> In some situations, you may want to retrieve the raw data from the UDT column. Perhaps the type is not available locally [(4)](https://docs.microsoft.com/en-us/sql/relational-databases/clr-integration-database-objects-user-defined-types/accessing-user-defined-types-retrieving-udt-data?view=sql-server-2017#binding-udts-as-bytes)

> [Warning about client side usage of GEOMETRY, GEOGRAPHY and HIERARCHYID](https://msdn.microsoft.com/en-us/library/dn236441(v=sql.120).aspx)

A .NET Standard Implementation of the geometry types for reference which can be used as an example (just tweak unit tests to call `GetValue` instead of `GetSqlBytes` on the data reader): 
https://github.com/dotMorten/Microsoft.SqlServer.Types/blob/89c5e6158867d9603d93fde6286a0f32f01fa96d/src/Microsoft.SqlServer.Types.Tests/DBTests.cs#L81

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
Since we have open issues for supporting missing SqlTypes in .NET Core, closing this issue.
- Spatial types (SqlGeometry and SqlGeography) #30 
- SqlHierarchyId #322
