### ISSUE TITLE
Embedding native SNI dlls with Costura

### ISSUE THREAD

**Issue by 0xced** [dotnet/SqlClient#793]
Would it be worth including the following information in the README under the *SNI Package References* section? If it's worth it, I'll create a pull request. If not, people can now find this information just by searching for *Costura* in the issues of this repository (future me included!). 😉

<hr>

If you are using [Costura](https://github.com/Fody/Costura) to package a .NET Framework application as a single exe, you need to add the following elements in your project file. The `CopySNIFiles` must be set to `false` so that the native dll files (`Microsoft.Data.SqlClient.SNI.x64.dll` and `Microsoft.Data.SqlClient.SNI.x86.dll`) are not copied into the build output directory. The native dll files are instead embedded in special `costura32` and `costura64` directories so that they are automatically loaded by Costura as documented in [Native Libraries and PreloadOrder](https://github.com/Fody/Costura#native-libraries-and-preloadorder).

```xml
<PropertyGroup Label="SqlClientNativeLibraries">
  <CopySNIFiles>false</CopySNIFiles>
</PropertyGroup>

<Target Name="EmbedSqlClientNativeLibraries" BeforeTargets="ResolveReferences">
  <ItemGroup>
    <EmbeddedResource Include="@(SNIDllFiles)">
      <Link Condition="$([MSBuild]::ValueOrDefault('%(Identity)', '').Contains('x86'))">costura32\%(Filename)%(Extension)</Link>
      <Link Condition="$([MSBuild]::ValueOrDefault('%(Identity)', '').Contains('x64'))">costura64\%(Filename)%(Extension)</Link>
    </EmbeddedResource>
  </ItemGroup>
</Target>
```

**Comment by cheenamalhotra** [comment]
Hi @0xced 

This desired behavior looks very specific to Costura product, I think this should go in product documentation for Costura customers as they take dependency on Microsoft.Data.SqlClient. This issue would be helpful for anyone seeking immediate support here, thanks for letting us know!

**Comment by 0xced** [comment]
Thanks for your reply, Cheena. I'm closing the issue. Now with the *Native SNI* label, it's even easier to find.

**Comment by danielmeza** [comment]
> Thanks for your reply, Cheena. I'm closing the issue. Now with the _Native SNI_ label, it's even easier to find.

Yup! I dit it!
