### ISSUE TITLE
.NET 5 single file fails to execute

### ISSUE THREAD

**Issue by jjxtra** [dotnet/SqlClient#812]
### Describe the bug

This error is output upon referencing Microsoft.Data.SqlClient v. 2.1.0 and trying to open a sql connection in a .net 5 single file app with embedded binaries. Issue also exists when not embedding the binaries.

```
Error:

  An assembly specified in the application dependencies manifest (DigitalRuby.IPBanProWebAdmin.deps.json) was not found:

    package: 'Microsoft.Data.SqlClient.SNI.runtime', version: '2.0.1'

    path: 'runtimes/win-x64/native/Microsoft.Data.SqlClient.SNI.pdb'

```

### To reproduce
```c#
using SqlConnection conn = new SqlConnection("...");
conn.Open();
```

### Expected behavior
Shouldn't need a pdb to run regardless of single file or not

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET 5 nuget of Microsoft.Data.SqlClient 2.1.0
Windows Server 2019 x64

The latest nuget packages for Microsoft.Data.SqlClient are fouled up. They onlly have .net framework resources in them.

I copied the pdb manually to the root of my single file publish folder and then things started working.

**Comment by cheenamalhotra** [comment]
Please confirm you're referencing v2.1.0 of Microsoft.Data.SqlClient and not confusing with v2.0.1.
I'm able to connect without any issue.

![image](https://user-images.githubusercontent.com/13396919/99868322-65dc3e00-2b76-11eb-8d3e-f1a55046c08c.png)

**Comment by cheenamalhotra** [comment]
Your dependency hierarchy should be as under:

**[Microsoft.Data.SqlClient v2.1.0](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.0)**
    -- **[Microsoft.Data.SqlClient.SNI.runtime v2.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient.SNI.runtime/2.1.1)** (does not contains any PDB)


![image](https://user-images.githubusercontent.com/13396919/99868450-6de8ad80-2b77-11eb-859d-db751d0a2cb7.png)

**Comment by ErikEJ** [comment]
@jjxtra Please share your csproj

**Comment by jjxtra** [comment]
I'm using entity framework, I suspect that is the culprit, I will try to get a minimal csproj for you

**Comment by cheenamalhotra** [comment]
Hi @jjxtra 

I've opened this request to EF Core team: https://github.com/dotnet/efcore/issues/23453
Closing issue from our side, as you confirmed fix here: https://github.com/dotnet/SqlClient/issues/652#issuecomment-731615294

**Comment by jjxtra** [comment]
@cheenamalhotra Thank you! I will look forward to a fix from the ef core package :) but at least right now there is a work-around.
