### ISSUE TITLE
Return Value from Stored Procedure with ExecuteReader

### ISSUE THREAD

**Issue by MaxAkbar** [dotnet/SqlClient#813]
I am trying to get the return value from the stored procedure but when calling ExecuteReader I get a null value but when calling ExecuteNonQuery I get the value expected. 

Is this a bug or not supported?

Thanks,
-Max

**Comment by ErikEJ** [comment]
What do you mean by "value" ??

Resultset, return value or output parameter?

**Comment by MaxAkbar** [comment]
In my code I have the following:
`            SqlParameter returnParam = new SqlParameter("@RETURN_VALUE", SqlDbType.Int);
            returnParam.Direction = ParameterDirection.ReturnValue;`

In sql SP I have the following:
`return 1;`

**Comment by ErikEJ** [comment]
It doubt this work with Reader, but you need to share your sproc and stored procedure call as well.

**Comment by MaxAkbar** [comment]
SQL Stored Procedure:
`CREATE PROCEDURE [dbo].[TEST_RETURN_PARAM] 

AS
BEGIN
	select @@VERSION

	return 1;
END`

c# code:
`SqlConnectionStringBuilder sqlConnStringBuilder = new SqlConnectionStringBuilder 
{
    ApplicationName = "Sql Example",
    DataSource = "localhost",
    UserID = "sa",
    Password = "password",
    InitialCatalog = "SqlExamples"
};

using SqlConnection sqlConn = new SqlConnection(sqlConnStringBuilder.ConnectionString);

sqlConn.Open();

using SqlCommand sqlCmd = new SqlCommand
{
    Connection = sqlConn,
    CommandType = CommandType.StoredProcedure,
    CommandText = "TEST_RETURN_PARAM"
};

SqlParameter returnParam = new SqlParameter("@RETURN_VALUE", SqlDbType.Int);

returnParam.Direction = ParameterDirection.ReturnValue;

sqlCmd.Parameters.Add(returnParam);

//sqlCmd.ExecuteNonQuery();

SqlDataReader sqlRdr = sqlCmd.ExecuteReader(CommandBehavior.CloseConnection);

Console.WriteLine(sqlCmd.Parameters["@RETURN_VALUE"].Value);`

After debugging the SQLClient code this is what I see:
![Untitled](https://user-images.githubusercontent.com/13856299/99885655-82668d80-2beb-11eb-81dc-879680285ee9.png)

The ExecuteNonQuery takes the 1. path which calls _stateObj.Parser.TryRun and in TryRun the return value is set.
The ExecuteReader takes the 2. path which does not call _stateObj.Parser.TryRun and does not set the return value.

I am pretty sure this is a bug.

-Max

**Comment by MaxAkbar** [comment]
Looks like if I add the following code it fixes the issue. Hope this helps.

![Microsoft Data](https://user-images.githubusercontent.com/13856299/99887759-ff99fe80-2bfb-11eb-8dde-47c9bc35de84.png)

**Comment by MaxAkbar** [comment]
After testing some more output parameter with ExeceuteReader has the same issues :(.

**Comment by MaxAkbar** [comment]
After searching it turns out that I was wrong. The way this works is that the reader has to be read first then I can access the return and out put params.
