### ISSUE TITLE
.NET 5 compatibility and onboarding

### ISSUE THREAD

**Issue by someguysi** [dotnet/SqlClient#828]
Hi,

Is SqlClient supported on .NET 5?

**Comment by JRahnama** [comment]
@someguysi our driver is compatible with .NET5, but we are yet to declare full support.

**Comment by willibrandon** [comment]
I have the same question. @JRahnama Are you saying that I can take the current release and use it in a .NET 5 project? I have tried that with no luck so far.

**Comment by JRahnama** [comment]
I am closing this issue as Net 5 will be out of support  on May 8, 2022. Support/build for net 6 will be added soon.
