### ISSUE TITLE
Add tests for DataContractSerializer serializing SqlTypes types

### ISSUE THREAD

**Issue by huanwu** [dotnet/SqlClient#83]
We need have tests covering DataContractSerializer serializing the following types.
Refer https://github.com/dotnet/corefx/blob/master/src/System.Runtime.Serialization.Xml/tests/DataContractSerializer.cs on how to add the DCS tests using the common helper method.
#20329

- [x] System.Data.SqlTypes.SqlBoolean
- [x] System.Data.SqlTypes.SqlByte
- [x] System.Data.SqlTypes.SqlDateTime
- [x] System.Data.SqlTypes.SqlDouble
- [x] System.Data.SqlTypes.SqlInt16
- [x] System.Data.SqlTypes.SqlInt32
- [x] System.Data.SqlTypes.SqlInt64
- [x] System.Data.SqlTypes.SqlString

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
Hi @huanwu 

Please take a look at PR #251 by @v-kaywon and let us know if there's anything more needed.
Thanks!

**Comment by huanwu** [comment]
@HongGit Could you take a look?

**Comment by v-kaywon** [comment]
Closing since PR #251 is merged.
