### ISSUE TITLE
Could not load file or assembly 'Microsoft.Data.SqlClient, Version=1.13.20136.2

### ISSUE THREAD

**Issue by wjvii** [dotnet/SqlClient#833]
### Describe the bug
When making a database call with Microsoft.Data.SqlClient it is looking for the wrong version.

This application uses a combination of EntityFramework Core 3.1.9 and Microsoft.Data.SqlClient 2.0.1 calls.

```
Error Msg:Could not load file or assembly 'Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040).

Stack Trace:(no main stack trace available)
```

### Expected behavior
I expected it to use the 2.0.1 version that is used and distributed with the application.

### Further technical details
Microsoft.Data.SqlClient version: (found on the nuget or Microsoft.Data.SqlClient.dll)
.NET target: (e.g. Framework 4.8)
SQL Server version: (e.g. Azure SQL)
Operating system: (e.g. Windows 10)

**Additional context**
I have checked the entire solution and the only references I see are to Microsoft.Data.SqlClient 2.0.1 so I am not sure where it is getting this 1.13.20136.2 from. I have tried binding redirects with the following, which appears to be working but may be wrong (what is the best way to get the version needed here?). 

`            <dependentAssembly>
                <assemblyIdentity name="Microsoft.Data.SqlClient" publicKeyToken="23ec7fc2d6eaa4a5" culture="neutral" />
                <bindingRedirect oldVersion="0.0.0.0-2.0.1.0" newVersion="2.0.0.0" />
            </dependentAssembly>
`
Not sure what to try next so hoping someone can put me on the path to understanding why it thinks it needs this old version. We use directory.build.targets for our nuget packages in this solution and in searching the solution there is no reference to any earlier version of Microsoft.Data.SqlClient.

Thank you in advance for any insight or suggestions.

**Comment by JRahnama** [comment]
@wjvii Can you provide a sample repro?

**Comment by wjvii** [comment]
Let me give it a try.

**Comment by JRahnama** [comment]
@wjvii you can directly reference and overwrite Microsoft.Data.SqlClient version in your csproj as below:
`<ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="2.1.0" />
  </ItemGroup>`

or use NuGet Package Manager to add any different version of M.D.S to your application.

**Comment by wjvii** [comment]
@JRahnama So do you think I should try 2.1.0? I am using EF Core 3.1.9 which appears to use 2.0.1 and it does appear that the 2.0.1 dll gets into the build folder. I am all for trying the later version if it should still work with EF Core 3.1.9. Should I add a binding redirect for 2.10 to my app.config?

**Comment by JRahnama** [comment]
for net48 and EFCore please see [this document](https://docs.microsoft.com/en-us/ef/core/miscellaneous/platforms#net-framework) as well.

**Comment by wjvii** [comment]
I have the redirects but no matter what I do I still get the error. I tried Microsoft.Data.SqlClient 2.1.0. I did manage to make a change that shows more of a stack trace.

`Error Msg:Could not load file or assembly 'Microsoft.Data.SqlClient, Version=1.13.20136.2, Culture=neutral, PublicKeyToken=23ec7fc2d6eaa4a5' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Stack Trace:   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerConnection.CreateDbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.get_DbConnection()
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.CreateCommand(RelationalCommandParameterObject parameterObject, Guid commandId, DbCommandMethod commandMethod)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.<ExecuteReaderAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<InitializeReaderAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.AsyncEnumerator.<MoveNextAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.<SingleAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HWC.Repositories.ActivityRepository.<SelectAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HWC.Patient.HTML.Summary.<GetVisitSummaryAsync>d__3.MoveNext() in E:\Git\HWC\HWC.Patient.HTML.Summary\Summary.cs:line 62
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HWC.Patient.HTML.Summary.<GetVisitSummaryHtmlAsync>d__4.MoveNext() in E:\Git\HWC\HWC.Patient.HTML.Summary\Summary.cs:line 89
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at HWC.Patient.HTML.Helper.<CreatePatEMRDocRec>d__4.MoveNext() in E:\Git\HWC\HWC.Patient.HTML.Summary.Helper\Helper.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at HWC.ActivityOverview.dcActivityOverview.VB$StateMachine_8_OverrideGrid_ClickCellButton_ForAsync.MoveNext() in E:\Git\HWC\ActivityOverview\dcActivityOverview.vb:line 509
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)`

I created a small .NET 4.8 console app trying to replicate but it runs fine so I am trying to see what I can create that will reproduce this error with less code.

**Comment by JRahnama** [comment]
@wjvii I just made an application with net48 and EFCore 3.1.9 and it works fine. What I think you need to add manually is `Microsoft.EntityFrameworkCore.SqlServer 3.1.9` and `Microsoft.EntityFrameworkCore.Tools 3.1.9` this will add Microsoft.Data.SqlClient 1.1.3 as default. I manually changed the Version number in `packages.config` to 2.1.0 and did not have any effect on the application. You can read more [here](https://www.entityframeworktutorial.net/efcore/entity-framework-core-console-application.aspx).

Here is all the packages added to my application:
```
<packages>
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.1.1" targetFramework="net48" />
  <package id="Microsoft.Bcl.HashCode" version="1.1.0" targetFramework="net48" />
  <package id="Microsoft.CSharp" version="4.7.0" targetFramework="net48" />
  <package id="Microsoft.Data.SqlClient" version="2.1.0" targetFramework="net48" />
  <package id="Microsoft.Data.SqlClient.SNI" version="1.1.0" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore.Abstractions" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore.Analyzers" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore.Design" version="3.1.9" targetFramework="net48" developmentDependency="true" />
  <package id="Microsoft.EntityFrameworkCore.Relational" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore.SqlServer" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.EntityFrameworkCore.Tools" version="3.1.9" targetFramework="net48" developmentDependency="true" />
  <package id="Microsoft.Extensions.Caching.Abstractions" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Caching.Memory" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Configuration" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.DependencyInjection" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Logging" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Options" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Extensions.Primitives" version="3.1.9" targetFramework="net48" />
  <package id="Microsoft.Identity.Client" version="3.0.8" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.JsonWebTokens" version="5.5.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Logging" version="5.5.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Protocols" version="5.5.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Protocols.OpenIdConnect" version="5.5.0" targetFramework="net48" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.5.0" targetFramework="net48" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="net48" />
  <package id="System.Buffers" version="4.5.1" targetFramework="net48" />
  <package id="System.Collections.Immutable" version="1.7.1" targetFramework="net48" />
  <package id="System.ComponentModel.Annotations" version="4.7.0" targetFramework="net48" />
  <package id="System.Data.Common" version="4.3.0" targetFramework="net48" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.7.1" targetFramework="net48" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.5.0" targetFramework="net48" />
  <package id="System.Memory" version="4.5.4" targetFramework="net48" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net48" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.7.1" targetFramework="net48" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.4" targetFramework="net48" />
</packages>
```

**Comment by wjvii** [comment]
@JRahnama finally got it. I think the trick is the syntax of the redirect and finding the right version values to use. I built a sample app and let it create the redirects and then saw that what I needed was:

```
      <dependentAssembly>
        <assemblyIdentity name="Microsoft.Data.SqlClient" publicKeyToken="23ec7fc2d6eaa4a5" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.0.20168.4" newVersion="2.0.20168.4" />
      </dependentAssembly>
```
I also found out you can also get this version information using ildasm and looking at the manifest.

Thank you for all assistance today, it definitely put me on the right path.

**Comment by JRahnama** [comment]
@wjvii, happy that we could help you in this case. If the problem is resolved feel free to close the this issue.

**Comment by wjvii** [comment]
@JRahnama I will close it and thank you again.

I would like to suggest that the assembly redirects or the actual assembly version be documented with each version of a nuget package. In working on this issue for myself I saw numerous posts on stackoverflow, blog posts, etc where the redirect values were not working because they were wrong. I think the fact that the nuget and the assembly versions are sometimes the same but sometimes not helps cause confusion along with the fact that the assemblies have file versions and product versions which are not necessary the same as the assembly version. For example, I never would have guessed the assembly version of the Nuget 2.1.0 Microsoft.Data.SqlClient was 2.0.20168.4 and that is the value that I needed to resolve the issue. The auto AutoGenerateBindingRedirects certainly helps but in some cases when you need to do it manually it would save time if you could just look at the nuget or project documention or something and get the actual assembly version value.

On a similar note, is there a tool, besides ildasm, that can give you the assembly version needed for an assembly redirect?

**Comment by JRahnama** [comment]
Besides` ildasm` or `ilspy` added in your visual studio you can use powershell. Basically what you need to do is, install the package by 
`Install-Package -Name "Microsoft.Data.SqlClient" -Destination ".\temp" -Force -Source MyNuget -SkipDependencies`
This will isntall the package in a folder named temp created in the same directory.
`MyNuget` can be defined as name variable for your provider or source. you can get list of your providers by running Get-PackageProvider after installing package provider you can run:
`Get-ChildItem *.dll -Path .\temp -Recurse | ForEach-Object versioninfo`

That will provide you a list like this:

![image](https://user-images.githubusercontent.com/32077152/101066548-68ae3a00-354b-11eb-8626-883f10b0442e.png)

in the FileVersion section you can find assembly versions.
