### ISSUE TITLE
Need help getting AzureKeyVaultProvider to work with MSI

### ISSUE THREAD

**Issue by alvipeo** [dotnet/SqlClient#847]
I've spent about 8 hours reading docs and trying to read encrypted data!
Please see [https://stackoverflow.com/q/65245840/2896495](https://stackoverflow.com/q/65245840/2896495).

**Comment by ErikEJ** [comment]
I don't think this library claims to support .net 5 yet.

**Comment by JRahnama** [comment]
@alvipeo As @ErikEJ mentioned we are yet to claim full support for .NET 5. Have you tested your code with `netcoareapp` 3.1?

**Comment by karinazhou** [comment]
Hi @alvipeo ,

I find that you have created the same issue in multiple places. Please see my reply here:
https://github.com/MicrosoftDocs/sql-docs/issues/5799#issuecomment-743659934

And have you tested it with netcoreapp 3.1? Does it work with your application? 

Thanks,

**Comment by alvipeo** [comment]
I'm downgrading to 3.1 tomorrow. Let's see if it works.

**Comment by cheenamalhotra** [comment]
@alvipeo 

I've tested the same with .NET 5.0 and do not see any issues.
Please find working example here: [sqlclient-akv-example](https://github.com/cheenamalhotra/sqlclient-akv-example/tree/main)

**Comment by alvipeo** [comment]
@cheenamalhotra Thank you! I will try it very soon!

**Comment by alvipeo** [comment]
ok, the problem is still there. Your code uses Service Principal, not the MSI.

I have the following code to register encryption key store provider:
```
                SqlColumnEncryptionAzureKeyVaultProvider sqlColumnEncryptionAzureKeyVaultProvider = new(AzureActiveDirectoryAuthenticationCallback);

                // Register AKV provider
                SqlConnection.RegisterColumnEncryptionKeyStoreProviders(
                    new Dictionary<string, SqlColumnEncryptionKeyStoreProvider>(1, StringComparer.OrdinalIgnoreCase)
                    {
                        {SqlColumnEncryptionAzureKeyVaultProvider.ProviderName, sqlColumnEncryptionAzureKeyVaultProvider}
                    });
```
and here's the `AzureActiveDirectoryAuthenticationCallback`:

```
        private static async Task<string> AzureActiveDirectoryAuthenticationCallback(string authority, string resource, string scope)
        {
            return await new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/");
        }
```

The connection string has `Authentication=Active Directory MSI` in place.

With all of this I get the error:
> No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId

**Comment by alvipeo** [comment]
ok, putting `Authentication=Active Directory MSI` was a mistake. It's used when it's user-defined identity.
 Without this all queries to db work except when encrypted fields are used.

With encrypted fields I get:
> Failed to decrypt a column encryption key using key store provider: 'AZURE_KEY_VAULT'. Verify the properties of the column encryption key and its column master key in your database. The last 10 bytes of the encrypted column encryption key are: '....'

**Comment by alvipeo** [comment]
Using `Authentication=Active Directory Managed Identity;` in connection string brings the error:
> No UserAssigned Managed Identity found for specified ClientId/ResourceId/PrincipalId.

What else should I try? I'm running out of ideas :(

**Comment by alvipeo** [comment]
If I use the following code:
```
sqlConn.AccessToken = await new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/");
```
with `Authentication=Active Directory MSI` in the connection string, I get:
> Failed to load Campaigns Cannot set the AccessToken property if 'Authentication' has been specified in the connection string.

The only other idea I have is to use Service Principal which is my only hope but this makes MSI useless.

**Comment by cheenamalhotra** [comment]
Hi @alvipeo 

The connection string property: "Authentication=Active Directory MSI" or "Authentication=Active Directory Managed Identity" are same (synonyms) and they apply to SqlConnection instance to connect to SQL Server.

Could you please try with [v2.1.1](https://www.nuget.org/packages/Microsoft.Data.SqlClient/2.1.1) as a recent patch was released to fix empty User Id being passed that led to those errors.

**Comment by alvipeo** [comment]
I updated to 2.1.1 and removed this line:
```
sqlConn.AccessToken = await new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/");
```
Now the error related to MSI auth with sql azure is gone but the problem with encrypted data access is still there.

**Comment by cheenamalhotra** [comment]
Did you enable encryption by setting `Column Encrypted Setting=Enabled` property in connection string?
You'll find that in in-line comments in samples and [documentation](https://docs.microsoft.com/en-us/sql/connect/ado-net/sql/sqlclient-support-always-encrypted?view=sql-server-ver15#enabling-always-encrypted-for-application-queries).

**Comment by alvipeo** [comment]
Yes, I did.

One thing I noticed that my App Service is Linux and I don't see .NET Core 5.0 setting in the configuration. But the app works, all other pages that do not require encrypted data work.

**Comment by alvipeo** [comment]
Here it is:
```
Server=tcp:myserver.database.windows.net,1433;Database=mydb;Authentication=Active Directory Managed Identity;Column Encryption Setting=Enabled;
```

**Comment by cheenamalhotra** [comment]
I see your resource ID might be wrong to authenticate to Azure Key Vault: 

```
        private static async Task<string> AzureActiveDirectoryAuthenticationCallback(string authority, string resource, string scope)
        {
            return await new AzureServiceTokenProvider().GetAccessTokenAsync("https://database.windows.net/");
        }
```

Please change your callback to under and try again:

```
        private static async Task<string> AzureActiveDirectoryAuthenticationCallback(string authority, string resource, string scope)
        {
            return await new AzureServiceTokenProvider().GetAccessTokenAsync("https://vault.azure.net/");
        }
```
[Link to Microsoft Docs for Resource IDs](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-key-vault)

You must note that this callback only applies to Azure Key Vault authentication which is separate from Azure Database authentication that's handled by SqlConnection class.

**Comment by alvipeo** [comment]
I just tried - same error:

> Failed to decrypt a column encryption key using key store provider: 'AZURE_KEY_VAULT'. Verify the properties of the column encryption key and its column master key in your database. The last 10 bytes of the encrypted column encryption key are: '....'

**Comment by cheenamalhotra** [comment]
Can you confirm SSMS works for you using the same Key Vault URL and encrypting/decrypting same data to validate Keys have required permissions? [Connect with SSMS - Azure Key Vault](https://docs.microsoft.com/en-us/azure/azure-sql/database/always-encrypted-azure-key-vault-configure?tabs=azure-powershell#connect-with-ssms)

If not, please verify all permissions are granted as mentioned above on same documentation.

@Xtrimmer do you have additional thoughts about when AKV Provider would fail with above error?

**Comment by alvipeo** [comment]
Yes, SSMS works without any problem.

I'll try to use Service Principal. That's the only idea I have.

**Comment by cheenamalhotra** [comment]
Hi @alvipeo 

SSMS doesn't use Managed Identity to authenticate, you're probably using your own credentials to login to Key Vault, which have access. 

Please follow steps as shown here to provide access to App Service/VM where "Identity" is enabled and add a role assignment to be able to access Key Vault: [Assign Role](https://docs.microsoft.com/en-us/azure/key-vault/general/rbac-guide#assign-role)

Azure Key Vaults access policy should be set so that your Environment can access the vault's secrets (in this case, the Always Encrypted keys). The `create`, `get`, `list`, `sign`, `verify`, `wrapKey`, and `unwrapKey` permissions are required for creating a new column master key and for setting up encryption with SQL Server.

**Comment by alvipeo** [comment]
ok, trying to fix this again. No luck so far. All required permissions are granted for AppService.
I've done this before and had no problems. But this was about a year ago, so something has changed.
Let me work on this today and see if I can fix this.

**Comment by alvipeo** [comment]
btw, my key vault uses **Vault access police**, so those RBAC assignments are not relevant.

**Comment by alvipeo** [comment]
removing MSI and setting it up again did not help either :(

**Comment by alvipeo** [comment]
I create completely new App Service in another region - .NET Core 5, MSI enabled, created policy for key vault (get, list, sign, wrap, unwrap, verify) and ... same error!

Let me try now with SP... gr...!

**Comment by alvipeo** [comment]
And VOILA! It perfectly works with Service Principal!

Guys, you DEFINITELY have NOT created any apps to test your code with Always Encrypted and MSI! Please do this!

**Comment by cheenamalhotra** [comment]
Hi @alvipeo 

I've updated my example to also demo fetching access token from Managed Identity, and it works seamlessly.
Please find code here: https://github.com/cheenamalhotra/sqlclient-akv-example

Please follow steps from this tutorial to define "Access Policies", for both your Identity as well as Client VM/App Service/Function: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-windows-vm-access-nonaad

Output is as under:
![image](https://user-images.githubusercontent.com/13396919/106340166-c14d3b00-624d-11eb-8ad3-c6e9a019678b.png)

**Comment by alvipeo** [comment]
oh, that's new:

```
public static async Task<string> KeyVaultAuthenticationCallback(string authority, string resource, string scope)
        {
            return await Task.Run(() => new ManagedIdentityCredential().GetToken(new TokenRequestContext(new string [] {"https://vault.azure.net/.default"})).Token);
            /********************** Alternatively, to use User Assigned Managed Identity *********************/
            // var clientId = {clientId_of_UserAssigned_Identity};
            // return await Task.Run(() => new ManagedIdentityCredential(clientId).GetToken(new TokenRequestContext(new string [] {"https://vault.azure.net/.default"})).Token);
        }
```
This is the very first time I see `TokenRequestContext` ! Please update the docs for .Net 5 and KV access.

Thank you! I'll give it a go very soon!

**Comment by cheenamalhotra** [comment]
This is not special case for .NET 5 as same test is compatible with .NET Core 3.1 and .NET Framework 4.8.

There are a few Azure libraries available that can be used to acquire Access token, so it's just a matter of which library you want to use.

Using **Azure.Identity** to acquire Access Token is just another way to do it, you can the same with various other mechanisms: https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token 

And this callback allows not just use of Managed Identity but any Token Credential implementation that can authenticate Key Vault can be used in callback (e.g. InteractiveTokenCredential, DefaultAzureCredential are more examples of what also work here).

How customers use and implement this Key Vault Authentication Callback is a customer decision and therefore does not need specific documentation.

**Comment by cheenamalhotra** [comment]
Closing as solution provided.

**Comment by Mudit-Garg** [comment]
Hi, I am trying to acquire access token in my local setup using 

`            return await Task.Run(() => new ManagedIdentityCredential().GetToken(new TokenRequestContext(new string [] {"https://vault.azure.net/.default"})).Token);
`

But it is giving me the error

`ManagedIdentityCredential authentication unavailable. No Managed Identity endpoint found.`

From what I read, the code snippet above only works for deployed app service and not when running locally. 
Can someone help me with reading encrypted Columns value via using developer context in visual studio locally ?
