### ISSUE TITLE
[Question] FileStream Api - Windows usage

### ISSUE THREAD

**Issue by Shad0wlife** [dotnet/SqlClient#852]
Hello there!

I'm currently investigating which DB system to use for an application, and I require capability to store images and small documents in the DB. I found FileStream, and I really like the Idea of it, even more so since I will only have windows clients. Now, my application is currently written in UWP, just because I wanted to work with the platform (it seemed like a good Idea when the project started...) - so it really is as Windows-Based as it can get. Yet I cannot access the Microsoft.Data.SqlTypes namespace when installing the SqlClient Package - neither in my .NET Standard Library I use for the Model and Data access in the MVVM setup, nor in the actual UWP project.
Did I miss something I have to install, or did I just happen to find the one niche where FileStream is still not supported?

Thanks already for clearing this up!

**Comment by karinazhou** [comment]
Hi @Shad0wlife ,

We support Microsoft.Data.SqlTypes.SqlFileStream for both .NET Framework and .NET Core according to this:
https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqltypes.sqlfilestream?view=sqlclient-dotnet-core-2.1

Thanks,

**Comment by Shad0wlife** [comment]
Ok, so according to the page it's not available in .Net Standard 2.0, that was easy to find.

There's no selection for UWP though on that page though. I'm using min version of Win10 1809 if that helps. Is FileStream not available on UWP due to requiring the Win32 filesystem api? But I think that should be fine.

**Comment by Wraith2** [comment]
> Is FileStream not available on UWP due to requiring the Win32 filesystem api? But I think that should be fine.

Based on what I've seen in the code the filestream functions require pinvokes into win32 apis to maninpulate extended attributes, the only practical use i've ever seen them put to on windows. Those aren't likely to be on the approved uwp api whitelist so they can't be used in a uwp target.

**Comment by cheenamalhotra** [comment]
@Shad0wlife 

We don't build separate DLLs for UWP - .NET Standard DLLs are used for the same.

**Comment by Shad0wlife** [comment]
Alright, thank you. While I really like the features of UWP, it's restrictions have given me nothing but trouble in the last months... Maybe I just should've stuck with WPF and the corresponding winui libraries. Thank you for the clear answer!

**Comment by cheenamalhotra** [comment]
I don't think there's any plan in near future to support FileStream for UWP, or to even support UWP specifically.
I will proceed to close the issue.
