### ISSUE TITLE
How Do I Use Sql Server Spatial Data Types

### ISSUE THREAD

**Issue by marqdouj** [dotnet/SqlClient#858]
I am using .NET Core 5.0, Microsoft.Data.SqlClient Version 2.0.1

I have a table that contains a geography field. When I do a 'Select * From MyTable' I get this error:
DataReader.GetFieldType(24) returned null.

I found this nuget package but it won't install:
Microsoft.SqlServer.Types

So how do I read data that contains geography types?

**Comment by Wraith2** [comment]
I think the suggested option is to use https://github.com/NetTopologySuite

**Comment by marqdouj** [comment]
I the only package I found was for ER Core

________________________________

**Comment by marqdouj** [comment]
EF Core
________________________________

**Comment by Wraith2** [comment]
https://github.com/NetTopologySuite/NetTopologySuite.IO.SqlServerBytes ?

**Comment by marqdouj** [comment]
I will  try that, thanks.

**Comment by marqdouj** [comment]
I don't think that is what I need (or at least I can't figure out how to use it). I have used Microsoft.SqlServer.Types before in .NET 4.7.2 and it worked fine; it just won't install in .NET Standard or .NET Core.

**Comment by Wraith2** [comment]
`Microsoft.SqlServer.Types` relies on a windows only native dll which contains the implementation of those types' methods. It isn't portable so you can't use it on core of netstandard. You need a fully managed or at least cross platform capable library that provides the specific functionality you want.

Can you given a simple standalone example of what you're trying to do?

**Comment by Wraith2** [comment]
related old thread, may cover what you need: https://github.com/dotnet/SqlClient/issues/30

**Comment by marqdouj** [comment]
This is the code I use to fill a table. I want to be able to use sql like 'Select * From MyTable Where Id = 1'.
I'm not sure if the NetTopologySuite can be use here to make this work?

`public static int FillTable(this SqlConnection cn, SqlTransaction tn, DataTable table, string sql, Dictionary<string, object> parameters = null, LoadOption fillLoadOption = LoadOption.OverwriteChanges)
{
	using (var cmd = cn.CreateCommand(tn, sql, parameters))
	{
		using (var adapter = new SqlDataAdapter((SqlCommand) cmd))
		{
			adapter.MissingSchemaAction = MissingSchemaAction.AddWithKey;
			adapter.FillLoadOption = fillLoadOption;
			return adapter.Fill(table);
		}
	}
}`

**Comment by ErikEJ** [comment]
@marqdouj I doubt this will work on .net core - you have to use DataReader...

**Comment by cheenamalhotra** [comment]
Hi @marqdouj 

As @Wraith2 linked above too, there is an open issue #30 for the same.
There is no .NET Core/Standard support for SQL Spatial types (Microsoft.SqlServer.Types) as of now.

**Comment by marqdouj** [comment]
Thanks all for the help.
I've worked around the issue for now, as I don't really want to get the spatial data - it's just that I was getting errors.
I'm first getting a list of column info using INFORMATION_SCHEMA.COLUMNS and then building my column list using all the columns that are not spatial.

**Comment by cheenamalhotra** [comment]
Will close this issue, as we already are tracking missing spatial type support in #30.
