### ISSUE TITLE
Connection pool fragmentation by connection string variation (case, space..etc)

### ISSUE THREAD

**Issue by geleems** [dotnet/SqlClient#86]
Connection String A: `Server=tcp:.;User ID=testuser;Password=test1234;pooling=true`
Connection String B: `Server=tcp:.;User ID=testuser;Password=test1234; pooling=true` (notice a space where `pooling=true` starts)
Connection String C: `Server=tcp:.;User ID=testuser;Password=test1234;pooling=True`

Connection strings A, B, and C are indicating the same connection, but they creates separated connection pool for each of them  although only one connection pool is supposed to be created.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.
