### ISSUE TITLE
Is it compatible with Xamarin.Mac (Cocoa App created with Visual Studio for Mac) ?

### ISSUE THREAD

**Issue by zokid-be** [dotnet/SqlClient#865]
I just created a Cocoa App with Visual Studio for Mac and I don't have a lot of experience with that.
I'm on Mac OS Big Sur with .NET Core installed.
When I want to install nuget package **Microsoft.SqlServer.SqlManagementObjects** I have an error message with your package : 

`Could not install package 'Microsoft.Data.SqlClient.SNI.runtime 2.0.0'. You are trying to install this package into a project that targets 'Xamarin.Mac,Version=v2.0', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.`

I'm sad because I really appreciate your data provider and it works very well in .NET Core.
What's going on with **Microsoft.Data.SqlClient.SNI** for Cocoa App ? 
I installed 4 others nuget package without problem...

Is it compatible or not ?
Did I missed something ?

[Edited]
Yes I missed something... Target framework was in Xamarin.Mac Modern !
I solved this problem by using Xamarin.mac Full .Net Framework 4.8 + Retarget nuget package.
New Challenge succeeded for this new year.
Next challenge : Sleep more !!!

**Comment by cheenamalhotra** [comment]
Seems like issue got solved, closing.
