### ISSUE TITLE
SqlBulkCopy throws SqlNullValueException due to special SqlDataReader type tweak which does not check for NULL.

### ISSUE THREAD

**Issue by sergii-kryzh** [dotnet/SqlClient#87]
SqlBulkCopy throws SqlNullValueException due to special SqlDataReader type tweak which does not check for NULL.

Sample application: https://github.com/sergii-kryzh/netCore-SqlBulkCopy-Bug
Copy is attached: [netCore-SqlBulkCopy-Bug.zip](https://github.com/dotnet/corefx/files/3147838/netCore-SqlBulkCopy-Bug.zip)

When source cell is SqlDouble and cell is NULL then SqlDouble.Value will throw SqlNullValueException.
Source code (netCore): https://github.com/dotnet/corefx/blob/master/src/System.Data.SqlClient/src/System/Data/SqlClient/SqlBulkCopy.cs

Method: ` private object GetValueFromSourceRow(int destRowIndex, out bool isSqlType, out bool isDataFeed, out bool isNull)`
Line: `value = new SqlDecimal(_SqlDataReaderRowSource.GetSqlDouble(sourceOrdinal).Value);`

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
@Wraith2 's PR seems like a simple fix. We should port it to the current M.D.SqlClient code, too, after it is merged in corefx. @Gary-Zh

**Comment by cheenamalhotra** [comment]
PR merged in System.Data.SqlClient and has also been ported to Microsoft.Data.SqlClient. The fix will be available in next release. Closing issue.
