### ISSUE TITLE
Hitting SqlException, Error Number:40971

### ISSUE THREAD

**Issue by alerickson** [dotnet/SqlClient#873]
Our service started hitting a System.Data.SqlClient SQLException on December 4th (see full error below).
We use Azure databases and Azure cloud apps for our service and I initially thought there was an issue connecting to one of those components. But after talking to support folks from both the database and cloud service sides they were unable to find anything wrong.  I am also able to connect to the database manually, so the username/password used in the connection string is correct. 

Full trace:
> 
>   System.Data.SqlClient.SqlException (0x80131904): Cannot open Failover Group "dtlgalleryint.database.windows.net" requested by the login. The login failed.
>    at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
>    at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
>    at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Data.Entity.Infrastructure.DbExecutionStrategy.<>c__DisplayClass4.<<ExecuteAsync>b__3>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Data.Entity.Infrastructure.DbExecutionStrategy.<ProtectedExecuteAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Data.Entity.Core.EntityClient.EntityConnection.<OpenAsync>d__8.MoveNext()
> ClientConnectionId:717c97b6-7c28-44e3-8697-334a2be9d99d
> Error Number:40971,State:1,Class:20

Do you have any suggestions for debugging and addressing this error?

**Comment by cheenamalhotra** [comment]
Hi @alerickson 

Could you provide more info:
1. What does "dtlgalleryint.database.windows.net" imply, is it server for Azure SQL Managed Instance or Azure SQL DB or Synapse?
2. Where is your client application running? Are you able to connect to all the "dtlgalleryint.database.windows.net' server databases from the same client that is throwing this error?
3. What changed on December 4 that led to these issues? It certainly doesn't qualify for Client issue.
4. Is this server "dtlgalleryint.database.windows.net" configured as a "Failover Group" for another server that the client is not able to connect to?
5. Does this error happen everytime or randomly or is there a pattern to failures?

**Comment by ErikEJ** [comment]
Also, pls share your connection string

**Comment by cheenamalhotra** [comment]
Closed due to inactivity
