### ISSUE TITLE
Failed to Connect to Sql Server with MultiSubnetFailover .netCore 2.0

### ISSUE THREAD

**Issue by ezeasharma** [dotnet/SqlClient#88]
I'm running a .NET Core App 2.0 in a container against a SqlServer 12 database with MultiSubnetFailover.

My connection string looks like this...

Data Source=***.***.***.com;Initial Catalog=DATABASENAME;User ID=USER_ID;Password="USER_PASSWORD";Connect Timeout=60;MultiSubnetFailover=True

When i try to connect, it fails with the following error

Message="A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections.

Same issue is documented here for 1.1
https://github.com/dotnet/corefx/issues/14978

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
Hi @ezeasharma @epoyraz 

Please confirm if issue exists with Microsoft.Data.SqlClient ([latest version](https://www.nuget.org/packages/Microsoft.Data.SqlClient/1.0.19269.1))

**Comment by a-sharma11** [comment]
confirmed this is fixed. thanks!
