### ISSUE TITLE
System.IO.FileLoadException: 'Assembly with same name is already loaded'

### ISSUE THREAD

**Issue by hovek** [dotnet/SqlClient#891]
In .NET 5.0 on LocalReport.Render() for some reports, it throws System.IO.FileLoadException: 'Assembly with same name is already loaded'

**Comment by cheenamalhotra** [comment]
Please provide more details or a repro to reproduce the error.

**Comment by hovek** [comment]
> Please provide more details or a repro to reproduce the error.

Well, I can only provide you with the report, but the report itself is complicated and has several subreports and subreport processing. The source code is huge and error does not help in any way of pinpointing the problem. Maybe the problem is in multiple subreports, datasets per every subreport, and database fetches on subreport processing.

**Comment by cheenamalhotra** [comment]
If this is regarding Reporting Services, we are not the right team to help.
This is support group for SqlClient driver.

**Comment by hovek** [comment]
I clicked on the wrong NuGet package. Ah.

**Comment by hovek** [comment]
...
