### ISSUE TITLE
Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: 'There is no data for the field at position 2.'

### ISSUE THREAD

**Issue by hovek** [dotnet/SqlClient#892]
Microsoft.ReportingServices.ReportProcessing.ReportProcessingException: 'There is no data for the field at position 2.'

The previous version of the report viewer in .NET Framework tolerated that, now having this constraint really does not help in porting hundreds of reports to .NET 5.0. Make it tolerable for not provided dataset fields, make a property with which we can make it tolerable for such issues.

**Comment by cheenamalhotra** [comment]
Hi @hovek 

This project is for SqlClient and we do not handle ReportProcessingException.
Please reach out to Reporting Services support group.

**Comment by hovek** [comment]
But why does it get triggered when using this

**Comment by hovek** [comment]
...
