### ISSUE TITLE
Managed SNI Improvements

### ISSUE THREAD

**Issue by Wraith2** [dotnet/SqlClient#895]
Investigating the managed SNI (Sql Network IOnterface) implementation used in non-windows OS's for another thread there are a number of changes which would be beneficial to make. 

SNIProxy is used only by the managed SNI and is at best pointless and at worst possibly harmful. 

1) Consider:
https://github.com/dotnet/SqlClient/blob/9e3f0d625eb5ec15e069a1d8f118d3bac41b61f5/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs#L33-L36
https://github.com/dotnet/SqlClient/blob/9e3f0d625eb5ec15e069a1d8f118d3bac41b61f5/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs#L469-L472
Where we have a single instance which we use to access another single instance which holds an error code that is used by every physical handle in the process to report errors. It's surprising that this works under high load. Errors should be reported as exceptions or function returns not through this single instance.

2) An example of useless behaviour is 
https://github.com/dotnet/SqlClient/blob/9e3f0d625eb5ec15e069a1d8f118d3bac41b61f5/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SNI/SNIProxy.cs#L450-L453
A single instance is fetched by the caller and then the parameters passed in and used. This could be done directly in the caller, there is no virtual or polymorphic behaviour here.

The demuxing code in MarsConnection that deals with received mars packets is complicated and difficult to follow. It is an implicit state machine decoding the current state from multiple variables in a loop. It also has multiple exit points which makes packet lifetimes very difficult to track leading to cached packet leaks to the GC. This can be written as an explicit state machine make it far easier to debug and work with. It may also allow full demuxed packets to be forwarded rather than copied for a perf improvement.

Code based async is used throughout and has many opportunities for small improvements. ValueTask can be used in several areas for non netstandard2.0 builds to possibly avoid TCS and Task allocations on hot paths.

**Comment by cheenamalhotra** [comment]
@Wraith2 

Ack: I think we can try and gather more data to understand the impact of current v/s proposed changes.
Interesting would be to capture and validate issues with `GetLastError()` design and if exceptions do flow over and cause disruption.

**Comment by Wraith2** [comment]
I started working through how to remove the last error behaviour and it's a minefield. I got 30 files in and stopped because it was clearly too much work to do with other outstanding changes in progress. The singleton behaviour is actually worse than I originally thought because it's stored in a ThreadLocal and if there's any async/threadpool between it being set and fetch it'll be wrong. I'm assuming that at the moment there are none of those but it's not an easy thing to validate, it would be easy to break it without noticing.

It will also affect the native side because it'll change the TdsParser-StateObject interface so it may be best to wait until merging of netfx and netcore are further along.

**Comment by cheenamalhotra** [comment]
Ok.

I did see the same design on Native SNI, but hadn't thought of it's association with StateObject.
We might as well, close this topic for now then. We can come back to it, when we have moved over from Native SNI (as that's one of our goals too once we make it a lot stable).

**Comment by Wraith2** [comment]
Ok. The trivial methods I'll remove in a small easy PR and leave the error handling rework as a future large change.
