### ISSUE TITLE
Where is the ConnectionState?

### ISSUE THREAD

**Issue by halcwb** [dotnet/SqlClient#908]
I want to check the connection state, what namespace do I need to open? I do find this in System.Data. But is not the whole point that this lib can run on net5 without the need for local system specific assemblies?

**Comment by David-Engel** [comment]
The connection state is available directly on your active connection object:

Example:
```
using Microsoft.Data.SqlClient;
using System.Data;

namespace Example
{
    class Program
    {
        static void Main(string[] args)
        {
            using (SqlConnection conn = new SqlConnection("Server=localhost;Integrated Security=true;"))
            {
                if (conn.State = ConnectionState.Closed)
                {
                    conn.Open();
                }
            }
        }
    }
}
```

> But is not the whole point that this lib can run on net5 without the need for local system specific assemblies?

I'm not sure what you mean by "system specific assemblies". The Microsoft.Data.SqlClient package has a dependency on System.Data, just like all ADO.NET providers. System.Data is available with .NET 5.

**Comment by cheenamalhotra** [comment]
Hi @halcwb 

[ConnectionState](https://docs.microsoft.com/en-us/dotnet/api/system.data.connectionstate?view=net-5.0) comes from **System.Data.Common.dll** (that supports .NET 5) as explained above too by David.

**Comment by halcwb** [comment]
Thanks. I use F# which is a bit more difficult on opening namespaces.
