### ISSUE TITLE
CommandCancelTest.TimeoutCancel fails when using managed SNI with Encrypt=true

### ISSUE THREAD

**Issue by corivera** [dotnet/SqlClient#91]
Test results:
FAILURE: - unexpected non-open state after Execute!
Expected: True
Actual:   False

Stack Trace:
System.Data.SqlClient\tests\ManualTests\SQL\CommandCancelTest\CommandCancelTest.cs(198,0): at System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.VerifyConnection(SqlCommand cmd)
System.Data.SqlClient\tests\ManualTests\SQL\CommandCancelTest\CommandCancelTest.cs(154,0): at System.Data.SqlClient.ManualTesting.Tests.CommandCancelTest.TimeoutCancel(String constr)

CC @saurabh500

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by cheenamalhotra** [comment]
Closing the issue as Pipelines run tests with "Encrypt=true" and TImeoutCancel() test runs for TCP connection string without issues. Tested on Windows, Windows + Managed SNI, Unix.
