### ISSUE TITLE
Support Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider package for .Net 5

### ISSUE THREAD

**Issue by vd94** [dotnet/SqlClient#911]
Hi Team,

Package dependency is not resolved for .Net 5 project. I am getting error 'This package may not be fully compatible with your project.'
Is this supported for .Net 5?

**Comment by ErikEJ** [comment]
Not yet.

**Comment by vd94** [comment]
@ErikEJ Thanks! Is there any expected timeline for this? or any possible alternative till then?

**Comment by ErikEJ** [comment]
Are you having any runtime issues?

**Comment by vd94** [comment]
At compile time itself I am getting errors as the package dependency is not resolved.

**Comment by cheenamalhotra** [comment]
@vd94 

[Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider](https://www.nuget.org/packages/Microsoft.SqlServer.Management.AlwaysEncrypted.AzureKeyVaultProvider/) package applies to System.Data.SqlClient (.NET Framework) as also clearly mentioned on NuGet.org.

Please use [Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider](https://www.nuget.org/packages/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider) with [Microsoft.Data.SqlClient](https://www.nuget.org/packages/Microsoft.Data.SqlClient) for .NET 5 platform support.
