### ISSUE TITLE
Question: Using proxy with Active Directory Authentication to SQL Azure

### ISSUE THREAD

**Issue by Swellenator** [dotnet/SqlClient#914]
I am getting 407 proxy auth required when trying to connect to Azure SQL. I can see it does some HTTP calls to verify the realm of my user name. Eg. it is trying to access login.microsoft.com.

My connection string is like this:

```
Server=tcp:[redacted].database.windows.net,1433;Initial Catalog=[redacted];Persist Security Info=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Authentication=ActiveDirectoryIntegrated;ApplicationIntent=ReadOnly;Application Name=[redacted]
```
I can connect to the same database using SSMS with Azure Active Directory - Integrated as I believe we were able to set the proxy in it's config files. 

How can I set the proxy for SqlClient. Usually we would provide a custom HttpClient. Is that possible? I can see some details here:

https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/httpclient

How could I hook that up?

Thanks

**Comment by cheenamalhotra** [comment]
Hi @Swellenator 

We don't support accepting a custom HttpClient right now, so best possible option would be to implement this by yourself and pass on the access token to driver directly, as under:
```cs
SqlConnection sqlConnection = new SqlConnection("Data Source=<your-server>.database.windows.net; Database=Db1;");
sqlConnection.AccessToken = "<accessToken>"l
sqlConnection.Open();
```

**Comment by Swellenator** [comment]
Hi @cheenamalhotra 

Any tips on how to generate my own access token? 

Also I am actually using Entity Framework, so any ideas on how to pass EF the token??

Thanks

Stephen

**Comment by cheenamalhotra** [comment]
The above link you mentioned, that creates PCA (PublicClientApplication) instance, is what you all need!
You can use this [PublicClientApplication](https://docs.microsoft.com/en-us/dotnet/api/microsoft.identity.client.publicclientapplication?view=azure-dotnet) instance to acquire access token using it's APIs.

We use the same to [acquire token](https://github.com/dotnet/SqlClient/blob/master/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/ActiveDirectoryAuthenticationProvider.cs#L146), and it's supported with .NET Framework 4.6+

**Comment by cheenamalhotra** [comment]
Closing as resolved.
