### ISSUE TITLE
Why isn't the Activity API used to track diagnostic events?

### ISSUE THREAD

**Issue by eduard-bystrov** [dotnet/SqlClient#917]
like for example in [HttpHandlerDiagnosticListener](https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/HttpHandlerDiagnosticListener.cs#L594).

**Comment by roji** [comment]
Note that https://github.com/dotnet/runtime/issues/22336 is about revisiting what .NET database drivers do for diagnostics, we plan to take a good look during the 6.0 timeframe.

**Comment by cheenamalhotra** [comment]
We have been using Activity API to track Event Source traces, but not diagnostic traces specifically.
We can consider proposal as linked by @roji for further standardizations in .NET 6.

**Comment by cijothomas** [comment]
Can we close this issue, given there is another recent one https://github.com/dotnet/SqlClient/issues/2210?
