### ISSUE TITLE
Next LTS Release

### ISSUE THREAD

**Issue by bdschaap** [dotnet/SqlClient#932]
Can you tell me what the next LTS release will be?  Will 3.0 be an LTS release which is anticipated within a few months?

The following document lists only 1.1 as having LTS support.
https://docs.microsoft.com/en-us/sql/connect/ado-net/sqlclient-driver-support-lifecycle?view=sql-server-ver15

**Comment by cheenamalhotra** [comment]
Hi @bdschaap 

The next LTS version is decided to be **v2.1**, documentation will be updated this week.

**Comment by cheenamalhotra** [comment]
The above doc is updated for v2.1 as LTS, closing issue.
