### ISSUE TITLE
Possible memory leak in System.Data.SqlClient when using SqlCredential 

### ISSUE THREAD

**Issue by alphaleonis** [dotnet/SqlClient#94]
Tested on **.NET Core 2.1** with **System.Data.SqlClient v4.5.1**.
Also tested on **.NET Framework 4.7.2** with **System.Data.SqlClient v4.5.1**
____
When using `SqlCredential` to specify credentials for a `SqlConnection` there seems to ba a memory leak in some scenarios.  

Consider the following program that just repeatedly creates a new `SqlConnection`, opens it and then closes it:

```c#
using System;
using System.Data.SqlClient;
using System.Security;

namespace MemTest
{
   class Program
   {
      static void Main(string[] args)
      {
         SqlConnectionStringBuilder sb = new SqlConnectionStringBuilder();
         sb.DataSource = ".";
         sb.Pooling = false;
         string connectionString = sb.ConnectionString;
         string password = "XXXX";
         
         using (var securePassword = ToSecureString(password))
         {
            while (true)
            {
               SqlCredential cred = new SqlCredential("sa", securePassword);
               using (SqlConnection conn = new SqlConnection(connectionString, cred))
               {
                  conn.Open();
               }
            }
         }
      }

      static SecureString ToSecureString(string str)
      {
         SecureString s = new SecureString();
         foreach (var c in str)
            s.AppendChar(c);

         s.MakeReadOnly();
         return s;
      }
   }
}
```

This program does not use connection pooling, but does create a new `SqlCredential` instance for each call.  The memory usage seems to constantly increase, and using a memory profiler also indicates that memory consumption increases. It also appears that the program slows down over time.

The memory profiler we used seems to indicate among other things that there is a bunch of new instances of `SqlConnectionString` held by an `SqlConnectionFactory` constantly being allocated without being freed.

The documentation states that using a new *instance* of an `SqlCredential` will cause a new connection rather than using a pooled connection even if the user id and the passwords are the same.  So this will obviously cause problems when using pooled connections if a new `SqlCredential` instance is used for each connection, but in the case above connection pooling is turned off in the connection string, so why does memory usage seem to increase here?

In our real scenario, we need to use connection pooling, but we also need to be able to indicate that a specified connection/`SqlCredential` will no longer be used and should be freed. If we try to use connection pooling, the memory also seems to increase, even if we call `SqlConnection.ClearPool(conn)` in the inner loop.  How can we forefully remove a connection using a specific `SqlCredential` from the pool to avoid this problem?

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by David-Engel** [comment]
Do we know if SqlClient against .NET Framework exhibits the same memory usage?

**Comment by bachimanne** [comment]
We have same issue and **resolved it** by using single instance of SqlCredential object in every SqlConnection, instead of creating SqlCredential object every time.

**Comment by cheenamalhotra** [comment]
@alphaleonis 

I don't think this is an issue in the driver, you should be creating 1 single instance of `SqlCredential` object in order to pool the connection. The base hashcode of the every new object differs and the connection would not qualify for being pooled in this case, which is correct as per design.

On side note to answer @David-Engel 's question, the behavior is same in .NET Framework and .NET Core.

**Comment by cheenamalhotra** [comment]
Closing as not an issue.

**Comment by hancpavel** [comment]
Hi, I'm not sure it's right close this case as not an issue - the same problem is on .net core 5. With heavy usage SqlCredential runtime easily allocates up to gigabytes of RAM and causes huge slowdown (for example initial SQL call is 3ms, after thousands calls 40ms with the same query) - it's funny the critical value is approx 60 000 of new instances - after this new instances do not cause slowdown, but memory is still allocated... Solution with single instance of SqlCredential works well - thanks God :)
