### ISSUE TITLE
RunTests.sh fails on AArch64, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [dotnet/SqlClient#961]
[jw@cn05 sqlclient]$ sh ./RunTests.sh
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/netcore/ref/Microsoft.Data.SqlClient.csproj (in 3.67 sec).
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/netcore/src/Microsoft.Data.SqlClient.csproj (in 2.57 sec).
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release/Microsoft.Data.SqlClient/ref/netcoreapp3.1/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release/Microsoft.Data.SqlClient/ref/netstandard2.0/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release/Microsoft.Data.SqlClient/ref/netstandard2.1/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release/Microsoft.Data.SqlClient/ref/netcoreapp2.1/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient/netcore/netstandard2.0/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient/netcore/netcoreapp3.1/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient/netcore/netcoreapp2.1/Microsoft.Data.SqlClient.dll
  Microsoft.Data.SqlClient -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient/netcore/netstandard2.1/Microsoft.Data.SqlClient.dll
Building Add-Ons
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/add-ons/AzureKeyVaultProvider/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.csproj (in 1.44 sec).
  1 of 2 projects are up-to-date for restore.
  Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/AzureKeyVaultProvider/netcoreapp2.1/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.dll
Building tests
Microsoft (R) Build Engine version 16.8.3+39993bd9d for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UDTs/Address/Address.csproj (in 1.35 sec).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UDTs/Circle/Circle.csproj (in 773 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UDTs/Shapes/Shapes.csproj (in 672 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/SQL/UdtTest/UDTs/Utf8String/Utf8String.csproj (in 705 ms).
  1 of 2 projects are up-to-date for restore.
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/tools/Microsoft.DotNet.XUnitExtensions/Microsoft.DotNet.XUnitExtensions.csproj (in 2.18 sec).
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/tools/Microsoft.Data.SqlClient.TestUtilities/Microsoft.Data.SqlClient.TestUtilities.csproj (in 184 ms).
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS/TDS.csproj (in 55 ms).
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.EndPoint/TDS.EndPoint.csproj (in 69 ms).
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/tools/TDS/TDS.Servers/TDS.Servers.csproj (in 69 ms).
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj (in 2.82 sec).
  8 of 12 projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Determining projects to restore...
  Restored /home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj (in 1.6 sec).
  7 of 8 projects are up-to-date for restore.
  Determining projects to restore...
  All projects are up-to-date for restore.
  Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/AzureKeyVaultProvider/netcoreapp2.1/Microsoft.Data.SqlClient.AlwaysEncrypted.AzureKeyVaultProvider.dll
  TDS -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.SqlServer.TDS/netcoreapp2.1/Microsoft.SqlServer.TDS.dll
  TDS.EndPoint -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.SqlServer.TDS.EndPoint/netcoreapp2.1/Microsoft.SqlServer.TDS.EndPoint.dll
  TDS.Servers -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.SqlServer.TDS.Servers/netcoreapp2.1/Microsoft.SqlServer.TDS.Servers.dll
  Microsoft.DotNet.XUnitExtensions -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.DotNet.XUnitExtensions/netcoreapp2.1/Microsoft.DotNet.XUnitExtensions.dll
  Address -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Address/netcoreapp2.1/Address.dll
  Microsoft.Data.SqlClient.Tests -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU.FunctionalTests/netcoreapp2.1/FunctionalTests.dll
  Circle -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Circle/netcoreapp2.1/Circle.dll
  Shapes -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Shapes/netcoreapp2.1/Shapes.dll
  Utf8String -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Utf8String/netcoreapp2.1/Utf8String.dll
  Microsoft.Data.SqlClient.TestUtilities -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient.TestUtilities/net461/Microsoft.Data.SqlClient.TestUtilities.dll
  Microsoft.Data.SqlClient.TestUtilities -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU/Microsoft.Data.SqlClient.TestUtilities/netcoreapp2.1/Microsoft.Data.SqlClient.TestUtilities.dll
  Microsoft.Data.SqlClient.ManualTesting.Tests -> /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU.ManualTests/netcoreapp2.1/ManualTests.dll
Running SqlClient test suite
Build started 03/04/2021 14:29:23.
Test run for /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU.FunctionalTests/netcoreapp2.1/FunctionalTests.dll (.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3-dev+212656d7b384a506aa714999f678b3ace82d114e
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.12 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
      5.0.3 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=arm64&rid=fedora.33-arm64
. Please check the diagnostic logs for more information.

Test Run Aborted.
     1>Project "/home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj" on node 1 (VSTest target(s)).
     1>DispatchToInnerBuildsWithVSTestTarget:
         Build continuing because "ContinueOnError" on the task "MSBuild" is set to "ErrorAndContinue".
     1>Done Building Project "/home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.62
Build started 03/04/2021 14:29:27.
Test run for /home/jw/dotnet/sqlclient/artifacts/Project/bin/Unix/Release.AnyCPU.ManualTests/netcoreapp2.1/ManualTests.dll (.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 16.8.3-dev+212656d7b384a506aa714999f678b3ace82d114e
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.12 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
      5.0.3 at [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=arm64&rid=fedora.33-arm64
. Please check the diagnostic logs for more information.

Test Run Aborted.
     1>Project "/home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj" on node 1 (VSTest target(s)).
     1>DispatchToInnerBuildsWithVSTestTarget:
         Build continuing because "ContinueOnError" on the task "MSBuild" is set to "ErrorAndContinue".
     1>Done Building Project "/home/jw/dotnet/sqlclient/src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj" (VSTest target(s)) -- FAILED.

Build FAILED.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:02.72
[jw@cn05 sqlclient]$

**Comment by DavoudEshtehari** [comment]
Could you specify your environment settings, especially, the `dotnet --info` result here?

**Comment by Wraith2** [comment]
```
Testhost process exited with error: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
```
Seems pretty clearcut. You can either install it or use a custom Target Framework per the buildguide https://github.com/dotnet/SqlClient/blob/master/BUILDGUIDE.md#testing-with-custom-targetframework

**Comment by LutzWeischerFujitsu** [comment]
[jw@cn06 sqlclient]$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.103
 Commit:    72dec52dbd

Runtime Environment:
 OS Name:     fedora
 OS Version:  33
 OS Platform: Linux
 RID:         fedora.33-arm64
 Base Path:   /usr/lib64/dotnet/sdk/5.0.103/

Host (useful for support):
  Version: 5.0.3
  Commit:  c636bbdc8a

.NET SDKs installed:
  5.0.103 [/usr/lib64/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 5.0.3 [/usr/lib64/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 5.0.3 [/usr/lib64/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
[jw@cn06 sqlclient]$ 

msbuild is not available on Fedora 33 (yet?).

**Comment by cheenamalhotra** [comment]
@LutzWeischerFujitsu 

You need to install [.NET Core SDK v2.1](https://dotnet.microsoft.com/download/dotnet/2.1) in order to run scripts as needed.

**Comment by cheenamalhotra** [comment]
Yes, the SDK for respective .NET platform is always required to build and run with it.
In our case our tests use .NET Core 2.1 by default. If you want to change that to .NET Core 3.1, you can provide additional property when building and running tests:

`/p:TargetNetCoreVersion=netcoreapp3.1`

**Comment by LutzWeischerFujitsu** [comment]
So I should try 'sh ./RunTests.sh /p:TargetNetCoreVersion=netcoreapp3.1', correct?

**Comment by cheenamalhotra** [comment]
No, that property applies to MSBuild command.
You need to edit script and append that property to all commands, as under:

```
dotnet msbuild /p:Configuration="Release" /t:Clean,BuildAll /p:GenerateDocumentationFile=false /p:TargetNetCoreVersion=netcoreapp3.1
echo Building Add-Ons
dotnet msbuild /p:Configuration="Release" /t:BuildAKVNetCore /p:OSGroup=Unix /p:Platform=AnyCPU /p:TargetNetCoreVersion=netcoreapp3.1
echo Building tests
dotnet msbuild /p:Configuration="Release" /t:BuildTestsNetCore /p:OSGroup=Unix /p:Platform=AnyCPU /p:TargetNetCoreVersion=netcoreapp3.1
echo Running SqlClient test suite
dotnet test "src/Microsoft.Data.SqlClient/tests/FunctionalTests/Microsoft.Data.SqlClient.Tests.csproj" /p:Platform="AnyCPU" /p:Configuration="Release" /p:TestTargetOS="Unixnetcoreapp" --no-build -v n --filter "category!=nonnetcoreapptests&category!=failing&category!=nonlinuxtests&category!=nonuaptests" /p:TargetNetCoreVersion=netcoreapp3.1
dotnet test "src/Microsoft.Data.SqlClient/tests/ManualTests/Microsoft.Data.SqlClient.ManualTesting.Tests.csproj" /p:Platform="AnyCPU" /p:Configuration="Release" /p:TestTargetOS="Unixnetcoreapp" --no-build -v n --filter "category!=nonnetcoreapptests&category!=failing&category!=nonlinuxtests&category!=nonuaptests" /p:TargetNetCoreVersion=netcoreapp3.1
```

**Comment by cheenamalhotra** [comment]
Closing as information provided as requested.
