### ISSUE TITLE
Question: is using both Microsoft.Data.SqlClient and System.Data.SqlClient in the same process a bad idea?

### ISSUE THREAD

**Issue by mbakalov** [dotnet/SqlClient#968]
Hi,

I've an old ASP.NET web app that is using [`SQLMembershipProvider`](https://github.com/microsoft/referencesource/blob/master/System.Web/Security/SQLMembershipProvider.cs), which is tied to `System.Data.SqlClient`. The web app shares a library with another project, and that library is using `Microsoft.Data.SqlClient`. Both membership info and the data are in the same database.

Would there be any issues when using both SqlClient libraries in the same process talking to the same db? Something with connection pooling perhaps?

Thank you!

**Comment by mbakalov** [comment]
Not looking for a detailed answer, but maybe someone right away knows it is a "yeah, don't do that" or even a "there might be problems, not sure" type of thing :smile:

**Comment by cheenamalhotra** [comment]
It's an interesting question.

But if I understand correctly, it seems that both drivers are working in isolation and it's not like you're passing connection string from one driver to another or expect them to share anything. If that is true, you should not have any issues.

The drivers should be able to coexist in isolation in a single runtime as they don't share anything. They just cannot be expected to share any resources, meaning both drivers will occupy their own memory and caches and pool connections separately.

**Comment by mbakalov** [comment]
@cheenamalhotra - thanks again for the quick answer!

Yeah I was worried that maybe some shared native dependencies could possibly lead to some unexpected issues.

If you don't see any obvious issues with this, then I am happy to go down that path.

**Comment by cheenamalhotra** [comment]
Yes, the native libraries we use are different than those of System.Data.SqlClient. 
If you face any issues, let us know!
