### ISSUE TITLE
Incorrect copied log messages

### ISSUE THREAD

**Issue by nickljones** [dotnet/SqlClient#972]
### Describe the bug
`long scopeID = SqlClientEventSource.Log.TrySNIScopeEnterEvent("<sc.SNI.SNIMarsHandle.SendAsync |SNI|INFO|SCOPE>");`

is logged in the following methods:

- `SNIMarsHandle.SendAsync`
- `SNIMarsHandle.ReceiveAsync`
- `SNITcpHandle.SendAsync`

### Expected behavior
Each method should have a distinct message corresponding to the method name in which it is logged

### Further technical details
Microsoft.Data.SqlClient version: 2.1.2

**Comment by cheenamalhotra** [comment]
Hi @nickljones 

We're improving this design in future versions.
It's a huge effort so it's being done in parts. (ref: PR #897)

**Comment by JRahnama** [comment]
Closing this as PR #897 was merged. Feel free to open a new issue if the concern is not addressed yet.
