### ISSUE TITLE
Convert continuations in SqlClient managed SNI to async/await

### ISSUE THREAD

**Issue by saurabh500** [dotnet/SqlClient#98]
Based on the comment at https://github.com/dotnet/corefx/pull/27187#discussion_r168739991 the continuations in SqlClient SNI layer can be changed to use async await to prevent unnecessary allocations during network calls.

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.
