### ISSUE TITLE
SqlClient: Keyword not supported: 'TransparentNetworkIPResolution'

### ISSUE THREAD

**Issue by divega** [dotnet/SqlClient#99]
_From @msmolka on March 10, 2017 12:50_

I'm sharing connection string between net462 and core application.
connection string contains `TransparentNetworkIPResolution=False;'

When starting ASP NET Core app I have following error:
```
Exception message:  An exception occurred in the database while saving changes.
Stack trace:
Microsoft.EntityFrameworkCore.DbContext[1]
      An exception occurred in the database while saving changes.
      System.ArgumentException: Keyword not supported: 'transparentnetworkipresolution'.
         at System.Data.Common.DbConnectionOptions.ParseInternal(Dictionary`2 pa
```

I'm expecting `TransparentNetworkIPResolution` is proper keyword.

### Further technical details
EF Core version: 1.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows Server 2012
IDE: Visual Studio 2015

_Copied from original issue: aspnet/EntityFramework#7836_

**Comment by divega** [comment]
As recently [announced in the .NET Blog](https://devblogs.microsoft.com/dotnet/introducing-the-new-microsoftdatasqlclient/), focus on new SqlClient features an improvements is moving to the new [Microsoft.Data.SqlClient package](https://www.nuget.org/packages/Microsoft.Data.SqlClient/). For this reason, we are moving this issue to the new repo at https://github.com/dotnet/SqlClient. We will still use https://github.com/dotnet/corefx to track issues on other providers like System.Data.Odbc and System.Data.OleDB, and general ADO.NET and .NET data access issues.

**Comment by chrisjsmith** [comment]
+1 on this issue. We're getting 40,000 timeouts a day from .Net Core processes and latency spikes because this doesn't exist. Any chance of implementing it before the sun explodes?

**Comment by JRahnama** [comment]
@chrisjsmith any update if the issue still exists in M.D.SqlClient latest release?

**Comment by jrichardsz** [comment]
Any update?

**Comment by EbrahimMajdey** [comment]
Any update .. weird this has been sitting for years

**Comment by MichelZ** [comment]
Do I read this right that this feature will not get implemented?
If so, maybe it's time to close this issue out :)
