### ISSUE TITLE
Add Column/Field Name to Exception

### ISSUE THREAD

**Issue by chrispfarrell** [dotnet/SqlClient#990]
https://github.com/dotnet/SqlClient/blob/c37092a378a972c3799bdf79db6fa58f779ba9fd/src/Microsoft.Data.SqlClient/netfx/src/Microsoft/Data/SqlClient/SqlBuffer.cs#L209

On larger entities it can be tedious to figure out which column is the issue.  Can the fieldname be included in this error?  

Even better, if there was a way to validate the model as a whole to dump/list all issues.  Perhaps some kind of test harness/extension to validate mappings?

**Comment by JRahnama** [comment]
@chrispfarrell seems we have another #834 with same request. Please check the issue and if it is exact the same request close this one and follow the progress on that issue.

Thank you.

**Comment by chrispfarrell** [comment]
Not exactly the same but similar.  Thank you for the quick response!
