### ISSUE TITLE
Configurable retry - questions/clarifications

### ISSUE THREAD

**Issue by ErikEJ** [dotnet/SqlClient#993]
1: Is it possible to remove entries from the default list: https://github.com/dotnet/SqlClient/blob/c37092a378a972c3799bdf79db6fa58f779ba9fd/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/Reliability/SqlConfigurableRetryFactory.cs#L41 

2: Why is the default list different from  https://github.com/dotnet/efcore/blob/main/src/EFCore.SqlServer/Storage/Internal/SqlServerTransientExceptionDetector.cs#L24 (there may be good reasons...)

@DavidEshtehari

**Comment by roji** [comment]
Just a reminder about [implementing SqlException.IsTransient](https://github.com/dotnet/SqlClient/issues/649), which is related to this.

**Comment by scoriani** [comment]
@ErikEJ that list has been validated with multiple teams within AzureSQL team (e.g. Gateway, resource governance, etc.) and as of now represents the most accurate representation of most common transient errors for the service.  The list on EFCore seems a superset that includes also some transaction related errors that may be specific to their business logic, but we couldn't find a good use case to treat them as default. Of course users can still add those error codes in config file or in code if they will find them useful.

**Comment by ErikEJ** [comment]
Thanks for the info, @scoriani 

@AndriySvyryd  @ajcvickers  FYI!

**Comment by ErikEJ** [comment]
@scoriani So it is currently not possible to remove any?

**Comment by scoriani** [comment]
Not for now. To be completely honest, that feature was in my initial prototype 😀. I was using + and - signs after the error numbers in the list to indicate error codes to add or remove from the default list, but during internal reviews that was considered a bit too cumbersome.

**Comment by ErikEJ** [comment]
Also overkill, given the limited size of the list!
