### ISSUE TITLE
Wrong Schema Check in SqlParameter?

### ISSUE THREAD

**Issue by Tornhoof** [dotnet/SqlClient#995]
### Describe the bug
If you pass a DbDataReader into SqlParameter for a TVP parameter, it gets the schema to calculate the fields and checks the rows instead of the columns in the schema to produce the exception below.

https://github.com/dotnet/SqlClient/blob/9ebafbdf108214c2c5d43b9a0d58304006ccd0d8/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlParameter.cs#L1480-L1486

Either the check is wrong (which I believe) or the the exception is wrong.

if you pass a datatable the check is correct:

https://github.com/dotnet/SqlClient/blob/9ebafbdf108214c2c5d43b9a0d58304006ccd0d8/src/Microsoft.Data.SqlClient/netcore/src/Microsoft/Data/SqlClient/SqlParameter.cs#L1270-L1275

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.ArgumentException
  HResult=0x80070057
  Message=There are not enough fields in the Structured type.  Structured types must have at least one field.
  Source=Microsoft.Data.SqlClient
  StackTrace:
   at Microsoft.Data.SqlClient.SqlParameter.GetActualFieldsAndProperties(List`1& fields, SmiMetaDataPropertyCollection& props, ParameterPeekAheadValue& peekAhead)
   at Microsoft.Data.SqlClient.SqlParameter.MetaDataForSmi(ParameterPeekAheadValue& peekAhead)
   at Microsoft.Data.SqlClient.TdsParser.WriteSmiParameter(SqlParameter param, Int32 paramIndex, Boolean sendDefault, TdsParserStateObject stateObj, Boolean advancedTraceIsOn)
   at Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(SqlCommand cmd, _SqlRPC[] rpcArray, Int32 timeout, Boolean inSchema, SqlNotificationRequest notificationRequest, TdsParserStateObject stateObj, Boolean isCommandProc, Boolean sync, TaskCompletionSource`1 completion, Int32 startRpc, Int32 startParam)

  This exception was originally thrown at this call stack:
    Microsoft.Data.SqlClient.SqlParameter.GetActualFieldsAndProperties(out System.Collections.Generic.List<Microsoft.Data.SqlClient.Server.SmiExtendedMetaData>, out Microsoft.Data.SqlClient.Server.SmiMetaDataPropertyCollection, out Microsoft.Data.SqlClient.ParameterPeekAheadValue)
    Microsoft.Data.SqlClient.SqlParameter.MetaDataForSmi(out Microsoft.Data.SqlClient.ParameterPeekAheadValue)
    Microsoft.Data.SqlClient.TdsParser.WriteSmiParameter(Microsoft.Data.SqlClient.SqlParameter, int, bool, Microsoft.Data.SqlClient.TdsParserStateObject, bool)
    Microsoft.Data.SqlClient.TdsParser.TdsExecuteRPC(Microsoft.Data.SqlClient.SqlCommand, Microsoft.Data.SqlClient._SqlRPC[], int, bool, Microsoft.Data.Sql.SqlNotificationRequest, Microsoft.Data.SqlClient.TdsParserStateObject, bool, bool, System.Threading.Tasks.TaskCompletionSource<object>, int, int)
```

**Comment by Wraith2** [comment]
Do you have a canned repro I can use to investigate this?

**Comment by Tornhoof** [comment]
No not really, It showed up while trying to write a custom DbDataReader for TVP values, I went back to ``IEnumerable<SqlDataRecord>`` which was working before, so I didn't look to deeply into this.

**Comment by mburbea** [comment]
Schematable should have one row per column.  So this is by design.

**Comment by Tornhoof** [comment]
> Schematable should have one row per column. So this is by design.
Ah okay, thanks, then the exception is just confusing and we can close this.
